### ISSUE TITLE
Mensagem de Validação errada NFInfoReferenciada

### ISSUE THREAD

**Issue by daviarimateia93** [wmixvideo/nfe#100]
Boa tarde, estava observando a classe NFInfoReferenciada do pacote (com.fincatto.nfe310.classes.nota), e percebi que algumas mensagens de validações estão iguais, sendo que estão validando coisas diferentes. Exemplo abaixo, nos 3 casos, a mesma mensagem de validação é utilizada, sendo que apenas em um cenário está setando o Modelo 1 por 1 Referenciada.

"Nao pode setar modelo 1 por 1 referenciada caso chave de acesso esteja setado"

    public void setModelo1por1Referenciada(final NFInfoModelo1Por1AReferenciada modelo1por1Referenciada) {
        if (this.chaveAcesso != null || this.infoNFProdutorRuralReferenciada != null || this.chaveAcessoCTReferenciada != null || this.cupomFiscalReferenciado != null) {
            throw new IllegalStateException("Nao pode setar modelo 1 por 1 referenciada caso chave de acesso esteja setado");
        }
        this.modelo1por1Referenciada = modelo1por1Referenciada;
    }

    public void setChaveAcessoCTReferenciada(final String chaveAcessoCTReferenciada) {
        if (this.modelo1por1Referenciada != null || this.chaveAcesso != null || this.infoNFProdutorRuralReferenciada != null || this.cupomFiscalReferenciado != null) {
            throw new IllegalStateException("Nao pode setar modelo 1 por 1 referenciada caso chave de acesso esteja setado");
        }
        StringValidador.exatamente44N(chaveAcessoCTReferenciada);
        this.chaveAcessoCTReferenciada = chaveAcessoCTReferenciada;
    }

    public void setInfoNFProdutorRuralReferenciada(final NFInfoProdutorRuralReferenciada infoNFProdutorRuralReferenciada) {
        if (this.modelo1por1Referenciada != null || this.chaveAcesso != null || this.cupomFiscalReferenciado != null || this.chaveAcessoCTReferenciada != null) {
            throw new IllegalStateException("Nao pode setar modelo 1 por 1 referenciada caso chave de acesso esteja setado");
        }
        this.infoNFProdutorRuralReferenciada = infoNFProdutorRuralReferenciada;
    }

**Comment by fincatto** [comment]
Melhorado as mensagens, na versão: 1.1.6-SNAPSHOT
