### ISSUE TITLE
Atualizacao Nota Técnica 2015/003

### ISSUE THREAD

**Issue by daviarimateia93** [wmixvideo/nfe#101]
Implementação da atualização 2015/003.

Não fui muito a fundo nesta atualização, mas parece-me que ainda não implementamos.
Por exemplo na classe NFNotaInfoItemProduto, não há o atributo "CEST".

**Comment by fincatto** [comment]
Olá. 
No snapshot já foi implementado: item.setCodigoEspecificadorSituacaoTributaria();
Estamos providenciando a liberação como RELEASE, ainda esta manhã.

**Comment by daviarimateia93** [comment]
Opa, obrigado pela posição!

Davi de Sousa Arimateia

2016-01-06 10:43 GMT-02:00 Diego Fincatto <notifications@github.com>:

**Comment by jefperito** [comment]
Promovida versão para release.

<dependency>
  <groupId>com.github.wmixvideo</groupId>
  <artifactId>nfe</artifactId>
  <version>1.1.6</version>
</dependency>
