### ISSUE TITLE
Sistema com nota fiscal 

### ISSUE THREAD

**Issue by julianosts** [wmixvideo/nfe#103]
Pessoal...estava desenvolvendo um sistema com pdv(com emissao de nota fiscal), mas tenho um cliente que esta com certa urgencia e pelo jeito nao vai dar pra esperar terminar e fazer estes.
 Voces tem algum sistema para indicar com fontes para que eu possa analisar se vale a pena comprar? obrigado

**Comment by fincatto** [comment]
Bom dia Juliano.
Infelizmente não conheço nenhum sistema PDV pronto para indicar, mas sugiro que você pergunte no forum da NFe (veja na pagina inicial do projeto). Há muitos usuários que conhecem outros sistemas, vai ampliar o universo da sua pergunta.
Att,
Diego

**Comment by julianosts** [comment]
Bom dia Diego,

Obrigado pela informação.

Abraço
