### ISSUE TITLE
enum "inválido" em NFOrigem

### ISSUE THREAD

**Issue by daviarimateia93** [wmixvideo/nfe#104]
Conforme consta no manual, a opção 8, é superior a 70%, e não 80%.

"8 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70%; "

Na classe NFOrigem,
substituir enum NACIONAL_MERCADORIA_OU_BEM_COM_CONTEUDO_IMPORTACAO_SUPERIOR_80_P 
para NACIONAL_MERCADORIA_OU_BEM_COM_CONTEUDO_IMPORTACAO_SUPERIOR_70_P.

**Comment by jefperito** [comment]
Corrigido.

Obrigado.
