### ISSUE TITLE
Faltando atributos na classe NFNotaInfoItemImpostoICMS

### ISSUE THREAD

**Issue by daviarimateia93** [wmixvideo/nfe#106]
Na classe NFNotaInfoItemImpostoICMS, está faltando os seguintes atributos:

- icms41
- icms50
- icmssn103
- icmssn203
- icmssn300
- icmssn400

No manual, aparentam ser a mesma classe da icms40 (NFNotaInfoItemImpostoICMS40), icmssn102 (NFNotaInfoItemImpostoICMSSN102) e icmssn202 (NFNotaInfoItemImpostoICMSSN202),

Podendo ficar respectivamente: 

- private NFNotaInfoItemImpostoICMS40 icms41;
- private NFNotaInfoItemImpostoICMS40 icms50;
- private NFNotaInfoItemImpostoICMSSN102  icmssn103;
- private NFNotaInfoItemImpostoICMSSN202 icmssn203;
- private NFNotaInfoItemImpostoICMSSN102  icmssn300;
- private NFNotaInfoItemImpostoICMSSN102  icmssn400;

**Comment by jefperito** [comment]
Aonde isso?

No manual de orientação do contribuinte v6.00 não apresenta esses ICMS

**Comment by daviarimateia93** [comment]
No manual Versão 6.0 Maio 2015 

Página 208, titulo Grupo Tributação do ICMS= 40, 41. 50 .
 - 202 N06 ICMS40 Grupo Tributação ICMS = 40, 41, 50 CG N01  1-1  Tributação Isenta, Não tributada ou Suspensão

Página 217
 - 245.24 N10d ICMSSN102 Grupo CRT=1 – Simples Nacional e CSOSN=102, 103, 300 ou 400 
CG N01  1-1  Tributação ICMS pelo Simples Nacional, CSOSN=102, 103, 300 ou 400

Página 218
245.38 N10f ICMSSN202 Grupo CRT=1 – Simples Nacional e CSOSN=202 ou 203 
CG N01  1-1  Tributação ICMS pelo Simples Nacional, CSOSN=202 ou 203

**Comment by jefperito** [comment]
Mas isso é decidido quando voce seta o campo CST, exemplo...

o ICMS40 vc pode setar como 40/41/50 (se setar 50, será suspensão)

**Comment by jefperito** [comment]
ICMS40 é o grupo responsável pelo 40, 41 e 50

**Comment by daviarimateia93** [comment]
Entendi! Fez todo o sentido, desculpa a falta de atenção em achar que estava faltando ;(

É que estou fazendo a parte do front da nfe, e a gente acaba entrando num ciclo vicioso rs

**Comment by edudoda** [comment]
Tive a mesma dúvida do @daviarimateia93. Como existe praticamente uma classe de ICMS para cada CST da a entender que está faltando mesmo, inclusive até desenvolveram uma classe para [CSOSN400](https://github.com/wmixvideo/nfe/pull/545).  **Seria MUITO útil se essa informação estivesse documentada em algum lugar!** (se está não achei).
