### ISSUE TITLE
Download de NF-e

### ISSUE THREAD

**Issue by jefperito** [wmixvideo/nfe#107]
Verificar a possibilidade de usar o servico de download de NF-e.

Para mais informações ler a documentação do contribuinte v6.00, página 124 - 129

**Comment by fincatto** [comment]
Verificar possibilidade de consultar NFs emitidas para um determinado CNPJ. 
Será util para monitorarmos as entradas e fazermos os manifestos de recebimento.

**Comment by higomatos** [comment]
Diego,

Este projeto trabalha com Manifesto? Está implementado?

Cordialmente,

2016-06-17 17:20 GMT-03:00 Diego Fincatto <notifications@github.com>:

> Verificar possibilidade de consultar NFs emitidas para um determinado
> CNPJ.
> Será util para monitorarmos as entradas e fazermos os manifestos de
> recebimento.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/wmixvideo/nfe/issues/107#issuecomment-226871819>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AG74HXtCZRx6QqfSzyc-U2-9Cd-8NIrMks5qMwGUgaJpZM4HE4Vt>
> .
>



-- 
Higo Soares Matos
+55 86 99934-3237 - TIM
+55 86 98882-3796 - OI

**Comment by fincatto** [comment]
Olá @higomatos.
Ainda não está implementado, mas já está nos planos.
Creio que muito em breve teremos essa funcionalidade na biblioteca.
Att,
Diego

**Comment by fincatto** [comment]
Ola @higomatos.
O manifesto é um evento normal, não?
O sistema ja trabalha com eventos, se for isso mesmo.

**Comment by higomatos** [comment]
Sim, é um evento.

2016-06-26 12:09 GMT-03:00 Diego Fincatto <notifications@github.com>:

> Ola @higomatos <https://github.com/higomatos>.
> O manifesto é um evento normal, não?
> O sistema ja trabalha com eventos, se for isso mesmo.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wmixvideo/nfe/issues/107#issuecomment-228605828>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AG74HWP6Awx7I62qHJFn9Z3kWM155Fwxks5qPpYVgaJpZM4HE4Vt>
> .
>



-- 
Higo Soares Matos
Teresina - Piauí
86-9934-3237

**Comment by gilmario-kpslow** [comment]
Estou trabalhando nessa parte
consultar NFs emitidas para um determinado CNPJ
e Download de NF-e . Porem estou usando as informações contidas no manual, pois não encontrei os esquemas dessa funcionalidade.
Caso alguem tenha e queira me enviar agradeço.
Obrigado a todos.

**Comment by caiocteodoro** [comment]
@fincatto @jefperito @higomatos @gilmario-kpslow 
Vocês sabem me dizer como anda esta issue?
Tive que implementar esta funcionalidade, se não tiver em andamento faço um pull request.

**Comment by fincatto** [comment]
Manda!

**Comment by caiocteodoro** [comment]
@fincatto 
Não foi possível gerar os teste ainda, você quer criar uma nova branch ou pode fazer o pull request direto no master?

Ao testar o serviço obtive uma resposta positiva.

`[main] INFO com.fincatto.nfe310.webservices.WSDownladNF - <downloadNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="1.00"><tpAmb>1</tpAmb><xServ>DOWNLOAD NFE</xServ><CNPJ>09582757000105</CNPJ><chNFe>31161109482747000521550010000098371001427771</chNFe></downloadNFe>
[main] INFO com.fincatto.nfe310.webservices.WSDownladNF - <retDownloadNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="1.00"><tpAmb>1</tpAmb><verAplic>AN.DownNF_2.1.1</verAplic><cStat>139</cStat><xMotivo>Pedido de Download processado</xMotivo><dhResp>2016-11-11T09:55:12</dhResp><retNFe><chNFe>31161109482747000521550010000098371001427771</chNFe><cStat>140</cStat><xMotivo>Download disponibilizado</xMotivo><procNFe schema="procNFe_v3.10.xsd"><nfeProc versao="3.10"><NFe><infNFe versao="3.10" Id="NFe31161109482747000521550010000098371001427771"><ide><cUF>31</cUF><cNF>00142777</cNF><natOp>Vend Produc do Estabelecimento (6101)</natOp><indPag>1</indPag><mod>55</mod><serie>1</serie><nNF>9837</nNF><dhEmi>2016-11-03T10:53:03-02:00</dhEmi><dhSaiEnt>2016-11-03T10:53:03-02:00</dhSaiEnt><tpNF>1</tpNF><idDest>2</idDest><cMunFG>3164704</cMunFG><tpImp>1</tpImp><tpEmis>1</tpEmis><cDV>1</cDV><tpAmb>1</tpAmb><finNFe>1</finNFe><indFinal>0</indFinal><indPres>9</indPres><procEmi>0</procEmi><verProc>ZelusNFE 4.00</verProc></ide><emit><CNPJ>09482747000521</CNPJ><xNome>Zani e Zani Com.imp.exp.maquinas e Artigos do Vestuario Ltda</xNome><xFant>Zani e Zani - BojoForm</xFant><enderEmit><xLgr>RUA Deputado Humberto de Almeida</xLgr><nro>690</nro><xBairro>Jardim Europa</xBairro><cMun>3164704</cMun><xMun>Sao Sebastiao do Paraiso</xMun><UF>MG</UF><CEP>37950000</CEP><cPais>1058</cPais><xPais>Brasil</xPais><fone>03535316737</fone></enderEmit><IE>0013761350171</IE><CRT>3</CRT></emit><dest><CNPJ>09582757000105</CNPJ><xNome>L M Ferrarezi e Cia Ltda</xNome><enderDest><xLgr>Rua Castro Alves</xLgr><nro>1161</nro><xBairro>Vila Tolentino</xBairro><cMun>4104808</cMun><xMun>Cascavel</xMun><UF>PR</UF><CEP>85802110</CEP><cPais>1058</cPais><xPais>Brasil</xPais><fone>04532255208</fone></enderDest><indIEDest>1</indIEDest><IE>9044190521</IE></dest><det nItem="1"><prod><cProd>PAP7816.0/8</cProd><cEAN/><xProd>CHAVEIRO PERSONALIZADO - OUTUBRO ROSA 2016</xProd><NCM>63080000</NCM><CFOP>6101</CFOP><uCom>UN</uCom><qCom>1.0000</qCom><vUnCom>6.9300000000</vUnCom><vProd>6.93</vProd><cEANTrib/><uTrib>UN</uTrib><qTrib>1.0000</qTrib><vUnTrib>6.9300000000</vUnTrib><indTot>1</indTot></prod><imposto><vTotTrib>2.13</vTotTrib><ICMS><ICMS00><orig>0</orig><CST>00</CST><modBC>3</modBC><vBC>6.93</vBC><pICMS>12.00</pICMS><vICMS>0.83</vICMS></ICMS00></ICMS><IPI><cEnq>999</cEnq><IPINT><CST>51</CST></IPINT></IPI><PIS><PISAliq><CST>01</CST><vBC>6.93</vBC><pPIS>0.65</pPIS><vPIS>0.05</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>6.93</vBC><pCOFINS>3.00</pCOFINS><vCOFINS>0.21</vCOFINS></COFINSAliq></COFINS></imposto><infAdProd>Vl.Aprox.Tributos: R$2,13 (30,75%) Fonte: IBPT; IPI: IPI Reduzido a zero conforme Capitulo 62 - Anexo Unico do Decreto 7660 de 23/12/2011; PIS: Lei no. 10.833, de 2003, art. 1o., paragrafo 1o. e 2o.; COFINS: Lei no. 10.833, de 2003, art. 1o., paragrafo 1o. e 2o.</infAdProd></det><det nItem="2"><prod><cProd>PAP20.0/8</cProd><cEAN/><xProd>0 CONJUNTO LINGERIE - Duzani - Marca: Duzani</xProd><NCM>62081100</NCM><CFOP>6101</CFOP><uCom>CJ</uCom><qCom>7.0000</qCom><vUnCom>67.9900000000</vUnCom><vProd>475.93</vProd><cEANTrib/><uTrib>CJ</uTrib><qTrib>7.0000</qTrib><vUnTrib>67.9900000000</vUnTrib><indTot>1</indTot></prod><imposto><vTotTrib>146.35</vTotTrib><ICMS><ICMS00><orig>0</orig><CST>00</CST><modBC>3</modBC><vBC>475.93</vBC><pICMS>12.00</pICMS><vICMS>57.11</vICMS></ICMS00></ICMS><IPI><cEnq>999</cEnq><IPINT><CST>51</CST></IPINT></IPI><PIS><PISAliq><CST>01</CST><vBC>475.93</vBC><pPIS>0.65</pPIS><vPIS>3.09</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>475.93</vBC><pCOFINS>3.00</pCOFINS><vCOFINS>14.28</vCOFINS></COFINSAliq></COFINS></imposto><infAdProd>Vl.Aprox.Tributos: R$146,35 (30,75%) Fonte: IBPT; IPI: IPI Reduzido a zero conforme Capitulo 62 - Anexo Unico do Decreto 7660 de 23/12/2011; PIS: Lei no. 10.833, de 2003, art. 1o., paragrafo 1o. e 2o.; COFINS: Lei no. 10.833, de 2003, art. 1o., paragrafo 1o. e 2o.</infAdProd></det><det nItem="3"><prod><cProd>PAP7052.0/8</cProd><cEAN/><xProd>0 CONJUNTO - Cropped - Marca: Duzani</xProd><NCM>62081100</NCM><CFOP>6101</CFOP><uCom>CJ</uCom><qCom>2.0000</qCom><vUnCom>71.9500000000</vUnCom><vProd>143.90</vProd><cEANTrib/><uTrib>CJ</uTrib><qTrib>2.0000</qTrib><vUnTrib>71.9500000000</vUnTrib><indTot>1</indTot></prod><imposto><vTotTrib>44.25</vTotTrib><ICMS><ICMS00><orig>0</orig><CST>00</CST><modBC>3</modBC><vBC>143.90</vBC><pICMS>12.00</pICMS><vICMS>17.27</vICMS></ICMS00></ICMS><IPI><cEnq>999</cEnq><IPINT><CST>51</CST></IPINT></IPI><PIS><PISAliq><CST>01</CST><vBC>143.90</vBC><pPIS>0.65</pPIS><vPIS>0.94</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>143.90</vBC><pCOFINS>3.00</pCOFINS><vCOFINS>4.32</vCOFINS></COFINSAliq></COFINS></imposto><infAdProd>Vl.Aprox.Tributos: R$44,25 (30,75%) Fonte: IBPT; IPI: IPI Reduzido a zero conforme Capitulo 62 - Anexo Unico do Decreto 7660 de 23/12/2011; PIS: Lei no. 10.833, de 2003, art. 1o., paragrafo 1o. e 2o.; COFINS: Lei no. 10.833, de 2003, art. 1o., paragrafo 1o. e 2o.</infAdProd></det><det nItem="4"><prod><cProd>PAP53.0/8</cProd><cEAN/><xProd>0 SUTIA - Marca: Duzani</xProd><NCM>62081100</NCM><CFOP>6101</CFOP><uCom>PC</uCom><qCom>1.0000</qCom><vUnCom>42.4400000000</vUnCom><vProd>42.44</vProd><cEANTrib/><uTrib>PC</uTrib><qTrib>1.0000</qTrib><vUnTrib>42.4400000000</vUnTrib><indTot>1</indTot></prod><imposto><vTotTrib>13.05</vTotTrib><ICMS><ICMS00><orig>0</orig><CST>00</CST><modBC>3</modBC><vBC>42.44</vBC><pICMS>12.00</pICMS><vICMS>5.09</vICMS></ICMS00></ICMS><IPI><cEnq>999</cEnq><IPINT><CST>51</CST></IPINT></IPI><PIS><PISAliq><CST>01</CST><vBC>42.44</vBC><pPIS>0.65</pPIS><vPIS>0.28</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>42.44</vBC><pCOFINS>3.00</pCOFINS><vCOFINS>1.27</vCOFINS></COFINSAliq></COFINS></imposto><infAdProd>Vl.Aprox.Tributos: R$13,05 (30,75%) Fonte: IBPT; IPI: IPI Reduzido a zero conforme Capitulo 62 - Anexo Unico do Decreto 7660 de 23/12/2011; PIS: Lei no. 10.833, de 2003, art. 1o., paragrafo 1o. e 2o.; COFINS: Lei no. 10.833, de 2003, art. 1o., paragrafo 1o. e 2o.</infAdProd></det><det nItem="5"><prod><cProd>PAP53.0/8</cProd><cEAN/><xProd>0 SUTIA - Marca: Duzani</xProd><NCM>62081100</NCM><CFOP>6101</CFOP><uCom>PC</uCom><qCom>1.0000</qCom><vUnCom>37.5300000000</vUnCom><vProd>37.53</vProd><cEANTrib/><uTrib>PC</uTrib><qTrib>1.0000</qTrib><vUnTrib>37.5300000000</vUnTrib><indTot>1</indTot></prod><imposto><vTotTrib>11.54</vTotTrib><ICMS><ICMS00><orig>0</orig><CST>00</CST><modBC>3</modBC><vBC>37.53</vBC><pICMS>12.00</pICMS><vICMS>4.50</vICMS></ICMS00></ICMS><IPI><cEnq>999</cEnq><IPINT><CST>51</CST></IPINT></IPI><PIS><PISAliq><CST>01</CST><vBC>37.53</vBC><pPIS>0.65</pPIS><vPIS>0.24</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>37.53</vBC><pCOFINS>3.00</pCOFINS><vCOFINS>1.13</vCOFINS></COFINSAliq></COFINS></imposto><infAdProd>Vl.Aprox.Tributos: R$11,54 (30,75%) Fonte: IBPT; IPI: IPI Reduzido a zero conforme Capitulo 62 - Anexo Unico do Decreto 7660 de 23/12/2011; PIS: Lei no. 10.833, de 2003, art. 1o., paragrafo 1o. e 2o.; COFINS: Lei no. 10.833, de 2003, art. 1o., paragrafo 1o. e 2o.</infAdProd></det><total><ICMSTot><vBC>706.73</vBC><vICMS>84.80</vICMS><vICMSDeson>0.00</vICMSDeson><vBCST>0.00</vBCST><vST>0.00</vST><vProd>706.73</vProd><vFrete>0.00</vFrete><vSeg>0.00</vSeg><vDesc>0.00</vDesc><vII>0.00</vII><vIPI>0.00</vIPI><vPIS>4.60</vPIS><vCOFINS>21.21</vCOFINS><vOutro>0.00</vOutro><vNF>706.73</vNF><vTotTrib>217.32</vTotTrib></ICMSTot></total><transp><modFrete>1</modFrete><transporta><CNPJ>44914992000138</CNPJ><xNome>Rodonaves Transportes e Encomendas Ltda</xNome><xEnder>R General Augusto Soares dos Santos, 550</xEnder><xMun>Ribeirao Preto</xMun><UF>SP</UF></transporta><vol><qVol>1</qVol><esp>Volume</esp><marca>Duzani</marca><nVol>1</nVol><pesoL>3.000</pesoL><pesoB>3.000</pesoB></vol></transp><cobr><dup><nDup>98371/2</nDup><dVenc>2016-12-03</dVenc><vDup>353.37</vDup></dup><dup><nDup>98372/2</nDup><dVenc>2017-01-02</dVenc><vDup>353.36</vDup></dup></cobr><infAdic><infAdFisco>Informacoes de interesse do fisco constam do campo V03 (TAG Z03)</infAdFisco><infCpl>Valor Aprox. Tributos:R$217,32 (30,75%) Fonte: IBPT.ONU:Itens 1, 2, 3, 4 e 5: Produto sem classe de risco nao consta na lista de produtos perigosos emitida pela ONU.</infCpl></infAdic><compra/></infNFe><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI="#NFe31161109482747000521550010000098371001427771"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>bZGfr1YH+zxwy/FGjqyiHnxeH6w=</DigestValue></Reference></SignedInfo><SignatureValue>FKRwRVWLwrjT28t2CCkOt1CV8DRTLN/1kJoeVJSiI5fDL+zQCkfC7KfR2IUDOVvi8LBLTN69LY+B
r6n9vIdmNnEcLFCM+sCc4N0JL5RBVs1PReHALp7ZC/bZW1uHnS+KXqEaKw7d+zriSA6ehVT1+Mw0
M13f7yJUC8TzzVA0WH2zjJL5zcAD74SK8lZsyBaCUBCx2788nUz/OTLR5Nq5WplS5UDAPIG85gWr
lZ1TO11yBID0dzdtzY/pQ9FoeVk8HoWEU8BdCllf/oc9Y9povssAFAKwB6jeleWKkmx3A5pEbQTO
5hoD9lMHntfmDhq+g0XAufzTqEP5KrW0egBVEA==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIIETCCBfmgAwIBAgIIbbOI6/FIbrkwDQYJKoZIhvcNAQELBQAwdTELMAkGA1UEBhMCQlIxEzAR
BgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFs
IGRvIEJyYXNpbCAtIFJGQjEZMBcGA1UEAxMQQUMgU0VSQVNBIFJGQiB2MjAeFw0xNjA4MTAxNzM0
MDBaFw0xNzA4MTAxNzM0MDBaMIIBAjELMAkGA1UEBhMCQlIxCzAJBgNVBAgTAlNQMSEwHwYDVQQH
ExhTQU5UTyBBTlRPTklPIERBIEFMRUdSSUExEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsT
LVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEWMBQGA1UECxMN
UkZCIGUtQ05QSiBBMTETMBEGA1UECxMKQVIgQ0VSVE5FVDFJMEcGA1UEAxNAWkFOSSBFIFpBTkkg
Q09NRVJDSU8gSU1QT1JUQUNBTyBFIEVYUE9SVEFDQU8gREUgTTowOTQ4Mjc0NzAwMDEwNjCCASIw
DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKNmrQQkhSLcRdzwCZEVmc9f7+3lIVEQlC3QpfQ+
6mSnilkgRrnM9t/YhAJOYeLkbZCvu86je0OF1zyQNN14d3n9JSU6JYMrG3FfU/JQNxS4gDpFFLT7
V0At56xwrva1NU9+0B63oC7TSYP4N+/d+4kMBpjNY0Tnkc5NXp+KfC9ZRlOgnYZBg+2IR7H5ndw5
qfL8oHNAwSqeDCwfiKYhZQieajmZpb3CreVjfmYN+qcjuEwxIIkOpj+x9m0wYa+9rnyf+yQfb1VO
xvheu66OzQJFgLFUMx1tIUEPI8bAzUlUo1OTHOg5HRXVmN/LoJfY8DhrQcdrRAIPRkQX9tO5JjUC
AwEAAaOCAxQwggMQMIGZBggrBgEFBQcBAQSBjDCBiTBIBggrBgEFBQcwAoY8aHR0cDovL3d3dy5j
ZXJ0aWZpY2Fkb2RpZ2l0YWwuY29tLmJyL2NhZGVpYXMvc2VyYXNhcmZidjIucDdiMD0GCCsGAQUF
BzABhjFodHRwOi8vb2NzcC5jZXJ0aWZpY2Fkb2RpZ2l0YWwuY29tLmJyL3NlcmFzYXJmYnYyMAkG
A1UdEwQCMAAwHwYDVR0jBBgwFoAUsqDEPUaefMiFbAgeEDKUZUZwQXMwcQYDVR0gBGowaDBmBgZg
TAECAQ0wXDBaBggrBgEFBQcCARZOaHR0cDovL3B1YmxpY2FjYW8uY2VydGlmaWNhZG9kaWdpdGFs
LmNvbS5ici9yZXBvc2l0b3Jpby9kcGMvZGVjbGFyYWNhby1yZmIucGRmMIHzBgNVHR8Egeswgegw
SqBIoEaGRGh0dHA6Ly93d3cuY2VydGlmaWNhZG9kaWdpdGFsLmNvbS5ici9yZXBvc2l0b3Jpby9s
Y3Ivc2VyYXNhcmZidjIuY3JsMESgQqBAhj5odHRwOi8vbGNyLmNlcnRpZmljYWRvcy5jb20uYnIv
cmVwb3NpdG9yaW8vbGNyL3NlcmFzYXJmYnYyLmNybDBUoFKgUIZOaHR0cDovL3JlcG9zaXRvcmlv
LmljcGJyYXNpbC5nb3YuYnIvbGNyL1NlcmFzYS9yZXBvc2l0b3Jpby9sY3Ivc2VyYXNhcmZidjIu
Y3JsMA4GA1UdDwEB/wQEAwIF4DAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwQwga0GA1Ud
EQSBpTCBooEUU0lNT05FQERVWkFOSS5DT00uQlKgFwYFYEwBAwKgDhMMSkVPVkFOSSBaQU5JoBkG
BWBMAQMDoBATDjA5NDgyNzQ3MDAwMTA2oD0GBWBMAQMEoDQTMjMwMDYxOTY4NjIwODcyMzE2NzIw
MDAwMDAwMDAwMDAwMDAwMDBNNDk2MjkyMlNTUE1HoBcGBWBMAQMHoA4TDDAwMDAwMDAwMDAwMDAN
BgkqhkiG9w0BAQsFAAOCAgEAn1JRLMaIPkz0dR4K62MgtCP1buKikv5u63CdQQaYrgNqkxIRd3LK
oq46Su4axsy/t8FFFYVQGgo44mr9Vg3Ja5LBrKOlXHnRbTwoa9L/TRca9/cr26GowguG0ahWcYv+
DAdKJ2gXFzaoX+GPd4UfXBmwvXKeTaFhn1EyhVacZAWKS18fje3k6YKpimYdhWXsB7nNTcpC5aEK
s1MmY6cmon39fXQiX/f1SpWSpWgOhk/sBVUCRB34NcZ9BsVtTSNwZsbdcoeKcZq3hqipB9WQd8LW
r4mOWu4XlETNKfVgf0Pb84+KcKQC/7OKNdcjgtMTBPeVDSaP9bgwfyAp+P7wCr+SE/y00fQGWdTj
Y7EFkMtukOFn1XQZycOXmIPxwW/bKWpnPCWF5EtW1LTma77vLqCXakAKIFYIB4QWBlmQAuYGn1dc
0+AqvHBtcCr0AZ7Y24gs8kVHrMJ8WNRFSHoTxMVEK0nH5vmCoJzqEXzfPQwoM9CKxJebt+s5iZmc
m71zqkB5E3HN+Lx06W7yHRbfPWS6F1a5yXMYNmx1Bf3tXJN8Z8AJf7RUfKJTamNa0CmmXm41w6DL
3sIRmTnirGXVS5bV/y4iHGMUXNSMU8kB01G4mN18z5vHU5AlxHi6eoTUbCdYf7toY5+oHSnXWMjQ
de71vxiFu2dOB99ptc0WPTk=</X509Certificate></X509Data></KeyInfo></Signature></NFe><protNFe versao="3.10"><infProt Id="ID131162347151036">
  <tpAmb>1</tpAmb>
  <verAplic>14_0_8</verAplic>
  <chNFe>31161109482747000521550010000098371001427771</chNFe>
  <dhRecbto>2016-11-03T11:20:40-02:00</dhRecbto>
  <nProt>131162347151036</nProt>
  <digVal>bZGfr1YH+zxwy/FGjqyiHnxeH6w=</digVal>
  <cStat>100</cStat>
  <xMotivo>Autorizado o uso da NF-e</xMotivo>
</infProt></protNFe></nfeProc></procNFe></retNFe></retDownloadNFe>
`

**Comment by fincatto** [comment]
Adicionado ao projeto.

**Comment by lucasmbrito** [comment]
Tem algum exemplo da implementação do serviço de download da nota?
