### ISSUE TITLE
Erro na consulta do status de serviço para o estado da Bahia

### ISSUE THREAD

**Issue by cassiothadeu** [wmixvideo/nfe#112]
Realizando a consulta do status do serviço para o estado da Bahia recebi o seguinte erro:
org.apache.axis2.AxisFault: Unable to handle request. The action 'http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico2/nfeStatusServicoNF2' was not recognized.
    at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
    at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:37
    at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
    at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
    at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
    at com.fincatto.nfe310.webservices.statusservico.consulta.NfeStatusServico2Stub.nfeStatusServicoNF2(NfeStatusServico2Stub.java:106)
    at com.fincatto.nfe310.webservices.WSStatusConsulta.efetuaConsultaStatus(WSStatusConsulta.java:6
    at com.fincatto.nfe310.webservices.WSStatusConsulta.consultaStatus(WSStatusConsulta.java:34)
    at com.fincatto.nfe310.webservices.WSFacade.consultaStatus(WSFacade.java:63)

Aparentemente a classe Stub esta incorreta

**Comment by fincatto** [comment]
Corrigiu com seu PR?

**Comment by cassiothadeu** [comment]
Não, foi corrigido, primeiramente, achei que seria problema devido ao erro nas URL, mas mesmo após a correção, não funcionou, talvez será necessário gerar as classes stub novamente, estava dando uma olhada no forum do JavaC e encontrei esse post:
http://www.javac.com.br/jc/posts/list/2130-erro-ao-tentar-consultar-status-de-nfe-310-na-bahia.page

**Comment by jefperito** [comment]
Parece que serviços de varios estados estão em contigência.

http://www.nfe.fazenda.gov.br/portal/principal.aspx

Contingência Ativada
MG 
Desde 22/12/2015 11:50:57
RS 
Desde 4/2/2016 19:28:20
AC 
Desde 4/2/2016 19:28:54
AL 
Desde 4/2/2016 19:28:54
AP 
Desde 4/2/2016 19:28:54
DF 
Desde 4/2/2016 19:28:54
ES 
Desde 4/2/2016 19:28:54
PB 
Desde 4/2/2016 19:28:54
RJ 
Desde 4/2/2016 19:28:54
RN 
Desde 4/2/2016 19:28:54
RO 
Desde 4/2/2016 19:28:54
RR 
Desde 4/2/2016 19:28:54
SC 
Desde 4/2/2016 19:28:54
SE 
Desde 4/2/2016 19:28:54
TO 
Desde 4/2/2016 19:28:54

**Comment by cassiothadeu** [comment]
Entendo, mas o problema é referente ao consumo do WS do estado da Bahia, por este motivo acredito que possa ser alguma coisa nas classes stub

**Comment by jefperito** [comment]
Sim, portanto pode ter algo a ver...
caso tu acesse a url diretamente usando os certificados digitais, verás que tem um problema de status 404: https://nfe.sefaz.go.gov.br/nfe/services/v2/NfeStatusServico2?wsdl

**Comment by jefperito** [comment]
Esse post que tu postou de abril de 2015, provavelmente já teria sido pego nesses 8 meses

**Comment by jefperito** [comment]
Os endpoints não apresentam mais o status 404, portanto, fica concluido que era instabilidade do sefaz BA

**Comment by isaiastavares** [comment]
@jefperito tentei consultar o Web Service de Consulta Status da BA e ainda está ocorrendo esse problema.

Não entendi os comentários acima. O cara falou que está com problema na Bahia e vocês postaram falando que estava conseguindo acessar o de Goiás rsrsrs

Se possível, reabrir essa Issue, creio que o problema continua.
Pesquisando no Google, realmente parece ser algo relacionado ao stub

**Comment by isaiastavares** [comment]
Estava olhando aqui e pelo jeito a Sefaz BA desenvolveu o próprio SOAP.

No caso da BA, por exemplo, ao consultar o status do serviço, o método deveria terminar com 2, mas termina sem o 2, segue:

Outros estados:
statusServico.nfeStatusServicoNF2(...);

BA:
statusServico.nfeStatusServicoNF(...);

**Comment by isaiastavares** [comment]
@jefperito @fincatto Pessoal, quando puderem, favor reabrir essa atividade e passar para o meu nome que eu já resolvi o problema.

Infelizmente o único jeito de resolver foi criando Stub específico para a Sefaz Bahia.

**Comment by higomatos** [comment]
@isaiastavares, estou fazendo uma refatoração também e tenho pensado um pouco sobre esta questão de Stubs específicos. @fincatto acompanha esta ideia:

Por mais que a documentação seja única a implementação dos serviços não é (cada SEFAZ pode escrever seu código), logo, abre margem pra quem (Governo) não implementou fidedignamente ao que foi documentado ter provedores de serviços ligeiramente diferentes e este deve ser o motivo de termos que ficar fazendo alguns ajustes por estado, na verdade o servidor quer receber de outro jeito porém como o Stub foi gerado para o servidor A o correto seria enviar com um Stub especifico para o servidor B, hoje ao invés de termos Stubs por servidor, temos apenas a variação de endpoint. É algo a se refletir, podemos assumir que o Governo está errado e manter Stubs únicos ou assumir que por sempre estarem errados criar Stubs para cada WSDL provido por eles...

No caso da JAX-WS acho que poderíamos ter um meio termo pois o Axis gera uma "caralhada" de código com base no WSDL e depois não utiliza mais este arquivo, já na JAX-WS cada fez é instanciado um serviço ele faz com base no WSDL que está no endpoint, porém o endpoint (do WSDL) é estático com base no servidor que ele foi gerado, se tornarmos isto dinâmico ele poderia pegar WSDLs diferentes do servidor base que gerou o modelo, enfim, só abrindo ideias para possíveis alterações de estrutura do projeto.

**Comment by fincatto** [comment]
Se eu entendi bem a ideia, geraríamos toda a cadeia de codigo (stubs,
classes, etc) para cada endpoint?
Ou seria somente os stubs (classes poderiam ser reaproveitadas)?
Qual o nível de diferença entre implementações que os estados possuem?

2017-01-23 16:07 GMT-02:00 higomatos <notifications@github.com>:

**Comment by higomatos** [comment]
"Qual o nível de diferença entre implementações que os estados possuem?"

@fincatto, por enquanto só estou nas reflexões sobre o tema, não verifiquei de fato o nível de diferença mas pelos muitos fóruns que li há sim algumas divergências e alguns colocam que a solução para alguns problemas foi gerar Stubs com base no servidor que estão consumindo.

"geraríamos toda a cadeia de codigo (stubs, classes, etc) para cada endpoint?"

Não geraríamos tudo para cada endpoint pois os XSDs são liberados nacionalmente de acordo com os PLs, aí se a SEFAZ implementar diferente já vejo como um erro muito grosseiro, nestes casos, fazer ajustes seria a saída mesmo. Mas os WSDLs são liberados por estados, inclusive tem estados que tem servidores de homologação e produção separados onde eles podem ter um WSDL para homologação e outro diferente para produção e no momento do consumo o ideal era consumir de acordo com o servidor e não com o primeiro servidor que ocasionalmente tomamos como referência para gerar os Stubs (isto que fazemos hoje e torcemos pra funcionar nos outros servidores).

**Comment by fincatto** [comment]
Foram criados stubs diferenciados pra BA.
