### ISSUE TITLE
NFC-e

### ISSUE THREAD

**Issue by klutzer** [wmixvideo/nfe#117]
Gostaria de saber se este projeto serviria também para envio/emissão de NFC-e.

E parabéns pelo projeto!

**Comment by fincatto** [comment]
Bom dia Érico.
Como o layout é o mesmo, o projeto deve servir para a emissão de NFC-e
também.
Porém, como não temos a emissão de NFC-e aqui na empresa, nunca conseguimos
testar de forma apropriada.
Talvez alguém do nosso forum (vide página inicial do projeto) já tenha
utilizado o projeto e possa compartilhar mais experiências.
Mas seria interessante, se você decidir usar a lib no seu projeto, que nos
desse um feedback de como ele se comporta para o NFC-e.
Atenciosamente,
Diego Fincatto

**Comment by klutzer** [comment]
Obrigado pela resposta Diego.. Quanto ao fórum que você disse é este aqui? http://www.edsonmoretti.com.br/nfe/

Pois parece que está fora..

**Comment by fincatto** [comment]
Realmente.
Vou entrar em contato com o rapaz que está mantendo o Forum e comunicar.
Obrigado por avisar.

On Thu, Apr 7, 2016 at 1:44 PM, Érico Knapp Lutzer <notifications@github.com

**Comment by klutzer** [comment]
Beleza.. enquanto o fórum estiver fora, se alguém já usou este projeto para transmitir e imprimir NFC-e e puder compartilhar a sua experiência, vai ser de grande ajuda..

Abraço!

**Comment by klutzer** [comment]
Vi que na Issue #52 vocês estão comentando sobre a questão do envio de NFC-e, com as URLs para NFC-e e tal e esta Issue está fechada.. No final é informado de um possível PR mas que não foi feito, como que anda essa questão da NFC-e? É possível alguém que já tenha implementado fazer o PR?

Outro detalhe também seria verificar os campos que são obrigatórios pra NF-e mas que não são para a NFC-e, e não obrigá-los no momento do envio (verificando se o modelo é 65, no caso..)

**Comment by fincatto** [comment]
Seria uma boa mesmo.
Como não trabalhamos com o NFC-e, não o implementamos na biblioteca (até
por não ter como testá-lo direito).
Se alguém se habilitar e implementar, seria interessante ter isso na
biblioteca.
Atenciosamente,
Diego Fincatto

2016-04-22 11:32 GMT-03:00 Érico Knapp Lutzer <notifications@github.com>:

**Comment by klutzer** [comment]
Estou modificando o projeto para comportar também NFC-e. Aqui no RS é 
obrigatório então teremos um bom ambiente para testes.

Conforme vou implementando e testando vou criando/atualizando os PRs, ok?


Em 25-04-2016 08:17, Diego Fincatto escreveu:
