### ISSUE TITLE
Tornar xNome opcional

### ISSUE THREAD

**Issue by leonhardt** [wmixvideo/nfe#118]
Seria possível tornar opcional a propriedade NFNotaInfoDestinatario.razaoSocial :
`@Element(name` = "xNome", required = FALSE) private String razaoSocial;`
para ser compatível com a NFC-e?

Se for possível posso fazer um pull-request com a alteração.

**Comment by jefperito** [comment]
Olá,

Se isso fará compatível com a NFC-e, pode fazer um pull request, você poderia montar um pull request (quando estiver pronto) habilitando a NFC-e na biblioteca?

**Comment by fauker** [comment]
Segundo a nota técnica, o campo `xNome` é obrigatório para a NF-e e opcional para a NFC-e.

![captura de tela 2016-04-08 as 17 37 04](https://cloud.githubusercontent.com/assets/7989766/14396883/92cd1ae0-fdb0-11e5-9251-7ca7947d3d1a.png)

Não sei se seria a melhor solução. :smile_cat:

**Comment by jefperito** [comment]
Sim, mas caso mude apenas um campo, talvez possa ser verificado como adequar para ambos, torná-lo "não opcional" é a maneira mais fácil, porém, pode ser sugerido uma solução mais adequada.

**Comment by leonhardt** [comment]
Concordo, assim como o endereço já está opcional mesmo sendo obrigatório na nota técnica no caso da NF-e

**Comment by klutzer** [comment]
@leonhardt Você teve que modificar muita coisa para integrar com a NFC-e? A biblioteca já estaria adequada para o envio/emissão da NFC-e?
