### ISSUE TITLE
Links desatualizados

### ISSUE THREAD

**Issue by fauker** [wmixvideo/nfe#123]
Os seguintes links citados no README.md não estão desatualizados?

https://homologacao.nfe.sefaz.rs.gov.br/
https://nfe.sefaz.rs.gov.br/

Acho que foram trocados, respectivamente, por:

http://hom.nfe.fazenda.gov.br/portal/principal.aspx
https://www.sefaz.rs.gov.br/NFE/NFEindex.aspx?

Não faço um PR porque não tenho certeza.

**Comment by jefperito** [comment]
Talvez estejam... ainda não consegui verificar, talvez mudaram na época que atualizaram os endpoints do sefaz virtual

**Comment by fincatto** [comment]
Links atualizados, obrigado!
