### ISSUE TITLE
403 Forbidden ao acessar serviços [RESOLVIDO]

### ISSUE THREAD

**Issue by klutzer** [wmixvideo/nfe#124]
Olá pessoal..

Por acaso ninguém passou pelo erro "AxisFault2" retornando um Forbidden ao acessar os serviços da NF-e?

Eu fui atrás e resolvi com o código utilizado neste post:
http://www.javac.com.br/jc/posts/list/224-resolvendo-o-problema-4037-forbidden-para-certificado-a1-protocolsocketfactory.page

Achei estranho pois se não funcionasse mais gente estaria com esse problema. Talvez este código já exista no projeto e eu só não estou utilizando ele ainda (estou começando os trabalhos com este projeto).

**Comment by fincatto** [comment]
A Sefaz usa protocolos distintos, dependendo da UF.
Essa sua solução usa TLS, mas algumas outras UFs usam TLS1.1 ou TLS1.2.
Possivelmente tenhamos que mapear quais as UFs usam quais protocolos para
implementar uma solução para cada UF.
Qualquer ajuda nesse quesito será bem vinda!
Att,

2016-04-19 16:25 GMT-03:00 Érico Knapp Lutzer <notifications@github.com>:

**Comment by klutzer** [comment]
Certo.. Caso a gente mapeasse as UFs com seus devidos protocolos, o código que faria o registro `Protocol.registerProtocol("https", protocol);` teria que ficar no construtor da WSFacade, certo? Alguém já passou por este problema e fez algum tratamento neste sentido (levando em conta as UFs)?

**Comment by fincatto** [comment]
Imagino que o melhor lugar pra ele ficar seria na classe que
extende NFeConfig.
Vou fazer uma implementação de teste e posto em seguida pra vocês
validarem, ok?
Att,
Diego

**Comment by klutzer** [comment]
Beleza..

Inclusive daria pra incluir a classe que adaptei daquele post, que gera a cadeia de certificados para todos os serviços, já utilizando o NFAutorizador31.

Se quiser faço um PR

**Comment by fincatto** [comment]
Com certeza! Um PR seria mais do que bem vindo! :)
Estive dando uma olhada nos problemas do TLS:
https://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html#InstallationAndCustomization
Veja que ali tem os parametros para dizer qual SocketFactory deve ser
usado.
A SVRS usa 1.0 ainda (imagem em anexo).
Criei um branch chamado "protocolo_por_uf" para testarmos. Se puderem dar
uma olhada, vou testar aqui nos nossos sistemas em seguida.
[]s
[image: Inline image 1]

2016-04-19 17:20 GMT-03:00 Érico Knapp Lutzer <notifications@github.com>:

**Comment by klutzer** [comment]
Testei esse SocketFactoryDinamico utilizado no post e consegui consultar o status do serviço de quase todas as UFs (exceto BA, mas acredito q seja a URL).. Será que a versão do TLS/SSL faz realmente diferença?

O PR #122 está atualizado com a classe que gera a cadeia dos certificados..

**Comment by fincatto** [comment]
Acoplado codigo do SocketFactory dinamico na biblioteca.
Criado também no config um metodo para indicar qual protocolo usar.

**Comment by blennerSilva** [comment]
Pessoal estou tomando esse erro sera que poderiam me auxiliar em como usar o socket dinamico

**Comment by danielbohnrs** [comment]
Na sua clasase que extende a classe NFeConfig você tem o seguinte trecho?

    public String[] getSSLProtocolos() { // força a usar TLS1.2
		return new String[] { "TLSv1.2" }; 
	}

**Comment by blennerSilva** [comment]
onde chamar o getSSLProtocolos?

**Comment by blennerSilva** [comment]
HERE IS MY CODE

public class TesteNFE extends NFeConfig  {
    private static KeyStore keyStoreCertificado = null;
    private static KeyStore keyStoreCadeia = null;

    public static void main(String[] args) {
       TesteNFE testeNFE = new TesteNFE();
       testeNFE.testeStatus();
    }

    public void testeStatus(){
        try {
            NFStatusServicoConsultaRetorno retorno = null;
            retorno = new WSFacade(TesteNFE.this).consultaStatus(DFUnidadeFederativa.MG, DFModelo.NFE);
            System.out.println(retorno.getStatus());
            System.out.println(retorno.getMotivo());
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    @Override
    public DFUnidadeFederativa getCUF() {
        return DFUnidadeFederativa.MG;
    }

    @Override
    public KeyStore getCertificadoKeyStore() throws KeyStoreException {
        if (keyStoreCertificado == null) {
            keyStoreCertificado = KeyStore.getInstance("PKCS12");
            try (InputStream certificadoStream = new FileInputStream("C:\\ProjetosGrails\\testesmtp3\\certs\\******.pfx")) {
                keyStoreCertificado.load(certificadoStream, this.getCertificadoSenha().toCharArray());
            } catch (CertificateException | NoSuchAlgorithmException | IOException e) {
                keyStoreCadeia = null;
                throw new KeyStoreException("Nao foi possibel montar o KeyStore com a cadeia de certificados", e);
            }
        }
        return keyStoreCertificado;
    }

    @Override
    public String getCertificadoSenha() {
        return "********";
    }

    @Override
    public KeyStore getCadeiaCertificadosKeyStore() throws KeyStoreException {
        if (keyStoreCadeia == null) {
            keyStoreCadeia = KeyStore.getInstance("JKS");
            try (InputStream cadeia = new FileInputStream("C:\\ProjetosGrails\\testesmtp3\\certs\\******.jks")) {
                keyStoreCadeia.load(cadeia, this.getCadeiaCertificadosSenha().toCharArray());
            } catch (CertificateException | NoSuchAlgorithmException | IOException e) {
                keyStoreCadeia = null;
                throw new KeyStoreException("Nao foi possibel montar o KeyStore com o certificado", e);
            }
        }
        return keyStoreCadeia;
    }

    @Override
    public String getCadeiaCertificadosSenha() {
        return "******";
    }

    public String[] getSSLProtocolos() { // força a usar TLS1.2

        return new String[] { "TLSv1.2" };

    }

**Comment by RobertoTesteDeSoftware** [comment]
Comecei a implementar emissão de nota fiscal e estou usando o jar wmixvideo. Gostaria de tirar uma dúvida que pode parecer obvia, mas o projeto do wmixvideo/nfe serve para emissão de nfe e nfce?

**Comment by fincatto** [comment]
Boa tarde. Sim!
