### ISSUE TITLE
Front-END "XML Builder"

### ISSUE THREAD

**Issue by daviarimateia93** [wmixvideo/nfe#128]
Fala Pessoal,

Estou aqui para saber se alguem conhece/tem/ou desenvolveu algum XML Builder/Front end (Html/js/css) para a NFe.

Acredito que iria ajudar a muitos..

Valeu!

**Comment by fincatto** [comment]
A idéia é bem válida. Talvez pudesse ser criado um spinoff do projeto com um projetinho web fazendo essa comunicação.
