### ISSUE TITLE
Alterar nome atributo "valor" para "baseCalculoICMSST" (NFNotaInfoICMSTotal)

### ISSUE THREAD

**Issue by brunoguadagnini** [wmixvideo/nfe#135]
Alterar o nome do atributo "valor" para "baseCalculoICMSST"  existente nas classes:
```
com.fincatto.nfe200.classes.nota.NFNotaInfoICMSTotal.class
com.fincatto.nfe310.classes.nota.NFNotaInfoICMSTotal.class
```

Esta alteração irá quebrar o código de quem está fazendo uso da propriedade, mas é interessante manter o padrão de nomenclatura.

De:

```
@Element(name = "vBCST", required = true)
private String valor;

public void setValor(final BigDecimal valor) {
    this.valor = BigDecimalParser.tamanho15Com2CasasDecimais(valor);
}

public String getValor() {
    return this.valor;
}
```

Para: 

```
@Element(name = "vBCST", required = true)
private String baseCalculoICMSST;

public void setBaseCalculoICMSST(final BigDecimal valor) {
    this.valor = BigDecimalParser.tamanho15Com2CasasDecimais(baseCalculoICMSST);
}

public String getBaseCalculoICMSST() {
    return this.baseCalculoICMSST;
}
```

O que acham? posso realizar a alteração?

Obrigado.

**Comment by fincatto** [comment]
Boa tarde, Bruno.
Pode sim. Talvez o ideal não seria remover o getValor e setValor e sim
tornar eles Deprecated, mas já apontando para a nova propriedade, para que
possamos remover ele na proxima versão, sem quebrar o codigo de quem já usa.
PS: o pacote "com.fincatto.nfe200" já foi descontinuado e removido da
biblioteca.
Att,
Diego

2016-05-04 14:55 GMT-03:00 Bruno Guadagnini <notifications@github.com>:

**Comment by brunoguadagnini** [comment]
Tem razão Diego!
#137

Obrigado.

**Comment by fincatto** [comment]
Já foi adicionado ao projeto.
Obrigado Bruno!
