### ISSUE TITLE
O que acham de uma separação do projeto em módulos?

### ISSUE THREAD

**Issue by waldandrade** [wmixvideo/nfe#136]
O que acham de avaliar que se separe o projeto em módulos?
Por exemplo: 
Core, Assinatura, Envio, Validação ... 

Logicamente continuaria a versão Full.

No meu caso, eu fiz essa separação na marra. Meu Backend utiliza a parte de criação da Nota por meio dos modelos, e geram o XML. E criei um monitor que assina e envia arquivos que encontra em uma pasta específica.

Creio que isso agregaria valor a ferramenta.

**Comment by fincatto** [comment]
Bom dia @waldandrade.
Hoje a lib permite que seja enviado qualquer "arquivo" sem que ele "assine" o dito cujo.
Assim, está maleável para quem quiser assinar ou não antes de enviar.
Criei um branch chamado "assinatura" onde fiz algumas alterações para ficar independente do tipo de certificado também. Estamos em fase de homologação e liberaremos em breve como a versão 1.2.0.
Gostaria de saber como você imaginou essa separação, você pode falar um pouco sobre ela?

**Comment by waldandrade** [comment]
Bom dia...

A assinatura é um ótimo exemplo, pois qualquer documento pode ser assinado.
Então, teoticamente eu só precisaria da parte da lib de assinatura para
assinar. E hoje, dentro da biblioteca, as classes são interdependentes.

Penso que em um primeiro momento, a separação da assinatura do que é
referente a nota fiscal é o mais interessante. Eu posso criar um modelo de
nota fiscal não assinado, e eu posso assinar um documento que não
necessariamente é uma mota fiscal.

Com isso, penso que a biblioteca só tem a crescer. A questão é se é bem
visto ou não o crescimento da bilbioteca.
Em 09/05/2016 09:34, "Diego Fincatto" <notifications@github.com> escreveu:

**Comment by fincatto** [comment]
Neste caso, pelo que entendi, você sugere a separação da assinatura do resto da biblioteca.
Teríamos que criar um "core", que contenha apenas a classe NFConfig, uma "assinatura" que conterá apenas a classe AssinaturaDigital e dependerá do "core" para carregar o certificado e o resto da biblioteca, é isto?

**Comment by waldandrade** [comment]
Isso mesmo.
Em 09/05/2016 11:06, "Diego Fincatto" <notifications@github.com> escreveu:

**Comment by fincatto** [comment]
Acho que irá dificultar a vida dos desenvolvedores, que precisarão declarar 3 bibliotecas no maven pra poder usar as funcionalidade (Sendo que duas telas terão apenas uma classe, o que fica meio sem sentido). 
Isso vai meio que contra a filosofia da biblioteca, que é de facilitar a vida dos desenvolvedores, oferecendo uma estrutura robusta e bem testada para que eles precisem se preocupar apenas com as regras de negócio.
Mas a idéia ainda é válida. Estamos planejando adicionar outras funcionalidades na biblioteca, como o download das notas direto da SEFAZ e a geração de DANFE em PDF a partir de um determinado XML, e a separação por módulos passa a fazer todo o sentido (mas será analisado com cuidado, caso a caso).

**Comment by waldandrade** [comment]
Eu entendo perfeitamente! Apesar de considerar que seria possível
disponibilizar uma versão full, com todas as ferramentas juntas.

Bem, deixemos entâo esta discussâo para um outro momento.

Abraço
Em 09/05/2016 11:41, "Diego Fincatto" <notifications@github.com> escreveu:
