### ISSUE TITLE
Disponibilizar lista e link de dependências

### ISSUE THREAD

**Issue by waldandrade** [wmixvideo/nfe#138]
Acho interessante colocar duas coisas:

No doc inicial a lista das dependências (libs) necessárias para cada um dos processos (separado por processo, ou tudo junto, como quiserem). 

No código, alguma forma de testar se as bibliotecas estão adicionadas antes da utilização. Por que hoje, tudo compila e roda bonitinho ... mas quando a biblioteca é necessária o erro dispara.

**Comment by jefperito** [comment]
O projeto usa o maven q já resolve as dependencias:
http://mvnrepository.com/artifact/com.github.wmixvideo/nfe/1.1.12
