### ISSUE TITLE
NFC-E - Erro ao enviar NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO – SEM VALOR FISCAL

### ISSUE THREAD

**Issue by alyleite** [wmixvideo/nfe#140]
Baixei a versão 1.1.14-SNAPSHOT para testar o uso da nfc-e.
Rodando em homologação ao enviar um lote recebi o retorno da sefaz

> Descricao do primeiro item diferente de NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL [nItem:1]

Pesquisei e descobri que pra nfce em ambiente de homologação, deve-se inserir esta string
no primeiro item da nota:

> NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO – SEM VALOR FISCAL

Ao inserir recebi um erro falando que a string acima não era válida através do pattern:

> [!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}

Fui validar e verifiquei que ao transformar o lote em string antes da validação do xml, o mesmo está corrompendo-o.
http://regexr.com/3dc6s

Para uma solução momentânea (desespero rs) utilizei:
`final String loteNaoAssinado = lote.toString().replace(" – ", " - ");`

Alguma ideia de como corrigir isso?

**Comment by fincatto** [comment]
No primeiro item da nota?

Utilizamos o NFe aqui e só seto isso no destinatario:
info.getDestinatario().setRazaoSocial("NF-E EMITIDA EM AMBIENTE DE
HOMOLOGACAO - SEM VALOR FISCAL");

De qualquer forma, se vc setar o caractere "-" correto, não deve haver
probllemas (veja que o caractere do erro difere do que você colocou).

Podes testar e nos avisar se funcionou?

2016-05-06 16:44 GMT-03:00 Alyson Xavier Leite <notifications@github.com>:

**Comment by alyleite** [comment]
Então, no caso da NFe é diferente. 
Na NFCe não é obrigatório o destinatário (é necessário verificar isso tbm, pois no código o destinatário está como require=true), assim é necessário inserir na descrição do primeiro produto da nota (xprod).
http://www.newssystems.eti.br/blog/tag/nota-fiscal-emitida-em-ambiente-de-homologacao-sem-valor-fiscal/

Porém, logo após ver sua resposta, notei que meu caractere está diferente mesmo, pois copiei a frase direto do site acima. Provavelmente não percebi a diferença.
Vou fazer os testes novamente e aviso.

Muito obrigado

**Comment by fincatto** [comment]
Na ultima versão do repositorio, o destinatario nao esta como requerido.

**Comment by alyleite** [comment]
Realmente o problema era no hífen que copiei direto do site.

Obrigado. Problema resolvido
