### ISSUE TITLE
cEAN e cEANTrib na NFC-e

### ISSUE THREAD

**Issue by alyleite** [wmixvideo/nfe#143]
Pesquisei sobre a obrigatoriedade destes elementos na NFC-e, porém não achei nada conclusivo.
Alguém sabe se eles são necessários?

Vi que no código os dois estão como require = false. Entretanto, quando tento gerar a nfce recebo o erro:

> GRAVE: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1241; cvc-complex-type.2.4.a: Foi detectado um conteúdo inválido começando com o elemento 'xProd'. Era esperado um dos '{"http://www.portalfiscal.inf.br/nfe":cEAN}'.

> GRAVE: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1241; cvc-complex-type.2.4.a: Foi detectado um conteúdo inválido começando com o elemento 'uTrib'. Era esperado um dos '{"http://www.portalfiscal.inf.br/nfe":cEANTrib}'.

Alguma luz?

Att!

**Comment by fincatto** [comment]
Qual versão da biblioteca você está usando?
Tivemos esse erro e corrigimos criando um conversor para o campo.


2016-05-09 17:20 GMT-03:00 Alyson Xavier Leite <notifications@github.com>:

**Comment by alyleite** [comment]
Estou usando a versão 1.1.15-SNAPSHOT. Verifiquei e o código está atualizado.

**Comment by fincatto** [comment]
@alyleite faz um teste aí, por favor.
Seta esses campos como uma string vazia "" pra ver se vai, ok?
Se eles tiver sido transformados para obrigatório, alteramos a biblioteca pra isso.
Nos avise do resultado.

**Comment by alyleite** [comment]
Então, removi o XMLValidador.validaLote(loteNaoAssinado) da classe WSLoteEnvio para realizar os testes. E vi o retorno:

`<retEnviNFe versao="3.10" xmlns="http://www.portalfiscal.inf.br/nfe">
	<tpAmb>2</tpAmb>
	<verAplic>PR-v3_2_5</verAplic>
	<cStat>225</cStat>
	<xMotivo>Falha no Schema XML do lote de NFe. org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1057; cvc-complex-type.2.4.a: Invalid content was found starting with element &apos;xProd&apos;. One of &apos;{&quot;http://www.portalfiscal.inf.br/nfe&quot;:cEAN}&apos; is expected.</xMotivo>
	<cUF>41</cUF>
	<dhRecbto>2016-05-12T19:44:18-03:00</dhRecbto>
</retEnviNFe>`

Pesquisando mais, fiquei sabendo que se o produto não tiver um cEAN e/ou cEANTrib é necessário deixá-los em branco. Porém, quando informo os dados em branco

`
itemProduto.setCodigoDeBarras(""); 
itemProduto.setCodigoDeBarrasTributavel("");
`

A biblioteca remove esses componentes em branco. Assim causando o erro.

Não identifiquei o local da remoção. Será que é necessária esta implementação para quando os atributos estiverem em branco?

Att!
Alyson Xavier Leite
>

**Comment by jefperito** [comment]
Estranho esse comportamento, fiz um teste de unidade para cobrir essa particularidade dos ceans e passaram, geraram as tags vazias.

Até subi o teste de unidade para o master:

https://github.com/wmixvideo/nfe/commit/15107172fb5e4aa1ee74fd75bb6f897e9bfbbb84

**Comment by alyleite** [comment]
Então, estou utilizando a versão 1.1.15-SNAPSHOT.
olha o xml antes de enviar para a biblioteca

> http://pastebin.com/hX0hWEm3

e esse é quando a biblioteca vai enviar ao sefaz

> http://pastebin.com/Pb3Gnu1i

Notem que a primeira tem os atributos <cEAN/> e  <cEANTrib/> no item
já na segunda não está mais.

Tentei atualizar o projeto para ver seu commit dos testes mas não tinha nada para atualizar.
Tenho que fazer algo de diferente? Desculpe, sou novo no git. 

Att!

**Comment by fincatto** [comment]
@alyleite, boa noite.
Estou desconfiado que você esteja usando uma versão antiga, apesar de declarar a versão 1.1.15. 
Como o @jefperito disse, há até um teste garantindo que não seja gerado ou parseado esse atributo vazio.
De qualquer forma, alterei o branch "assinatura" para que o cEAN seja requerido.
Peço que teste com esse branch e nos informe se conseguiu corrigir.
Se o erro persistir, favor criar um teste que demonstre o erro com uma falha, para que possamos debugar e corrigir.
Att,
Diego.

**Comment by edivaldoms** [comment]
@fincatto 
O código de barra só deve ser informado SE o produto POSSUIR o código, caso contrário deve informar a tag fechada, dessa forma:
<cEAN/>
<cEANTrib/>

https://www.fazenda.sp.gov.br/nfe/perguntas_frequentes/respostas_X.asp

O Emissor gratuito da Sefaz quando não informado essas tags faz dessa forma:
```
<prod>
<cProd>14288</cProd>
<cEAN/>
<xProd>SCH80 TE CPVC 2 TIGRE</xProd>
<NCM>39174090</NCM>
<CEST>2803700</CEST>
<CFOP>5405</CFOP>
<uCom>UN</uCom>
<qCom>14.0000</qCom>
<vUnCom>21.5000000000</vUnCom>
<vProd>301.00</vProd>
<cEANTrib/>
<uTrib>UN</uTrib>
<qTrib>14.0000</qTrib>
<vUnTrib>21.5000000000</vUnTrib>
<indTot>1</indTot>
</prod>
```
