### ISSUE TITLE
Falta commitar a classe CertificadoUtils e adicionar a dependencia do commons-io

### ISSUE THREAD

**Issue by isaiastavares** [wmixvideo/nfe#146]
Pessoal, fiz um fork do projeto de vocês e implementei a classe NFeConfig conforme exemplo no README.md

Porém, acredito que está faltando vocês adicionarem a dependência do commons-io e falta commitar a classe CertificadoUtils, pois ela não existe no projeto atual e por isso está dando falha.

**Comment by fincatto** [comment]
Olá @isaiastavares.
A classe de config é um exemplo de como nós carregamos o certificado.
Você deve implementar a sua conforme a sua necessidade. 
Att,
Diego
