### ISSUE TITLE
Boas práticas: Tratamento de erros de validação, e no envio.

### ISSUE THREAD

**Issue by waldandrade** [wmixvideo/nfe#147]
Para uma melhor utilização da biblioteca, sugiro/solicito que de alguma forma alguém que tenha um entendimento mais avançado, oriente aqui os usuários a tratarem da maneira mais proveitosa os erros de validação e do envio.

Desde já obrigado

**Comment by waldandrade** [comment]
Um exemplo que me deparei agora é esse retorno que recebi:

org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1910; cvc-pattern-valid: O valor '0.00' não tem um aspecto válido em relação ao padrão '0\.[0-9]{1}[1-9]{1}|0\.[1-9]{1}[0-9]{1}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?' do tipo 'TDec_1302Opc'.

**Comment by jefperito** [comment]
Você recebeu um erro de validação do XSD, A expressão regular não permite o valor 0.00, permite valores de 0.01 em diante.

Seria em que sentido essa orientação?

**Comment by waldandrade** [comment]
A dúvida é basicamente a de não saber o que a biblioteca já trata, se, de repente, eu poderia estar tendo uma leitura melhor desses erros que surgem, por meio que algum meio que a ferramenta já disponibiliza.

**Comment by jefperito** [comment]
A biblioteca evita que qualquer valor inválido seja usado na nota e enviado para a Sefaz. Sem isso teria que corrigir os erros depois da nota ser processada pela Sefaz.

Para verificar os valores permitidos pelos campos, precisa acompanhar com a documentação disponibilizada pelo governo.

**Comment by fincatto** [comment]
Olá @waldandrade.
Tentamos dar o melhor feedback possível na biblioteca, por isso fazemos muitas das validações possíveis ainda quando o usuário está "montando" as notas.
Existem condicionais e/ou validações que são inerentes ao "conjunto da obra", e não a um campo específico, ou que, as vezes, o usuário nem chega a setar. Nesses casos, a validação com o XSD deve alertar o programador que algo que ele informou está inválido, e será rejeitado pela Sefaz.
Quanto a sua sugestão, você teria um exemplo mais palpável? Uns trechos de código, com uns testes validando, talvez?
Obrigado.

**Comment by waldandrade** [comment]
Vou ver isso direitinho. Por que vou ter que fazer esse tratamento para
minha ferramenta. Eu tenho um padrão no meu produto que é o de evitar ao
máximo a necessidade de suporte. E observei que da forma como os erros são
retornados hoje, o suporte seria muito requisitado.



Em 18 de maio de 2016 08:19, Diego Fincatto <notifications@github.com>
escreveu:

> Olá @waldandrade <https://github.com/waldandrade>.
> Tentamos dar o melhor feedback possível na biblioteca, por isso fazemos
> muitas das validações possíveis ainda quando o usuário está "montando" as
> notas.
> Existem condicionais e/ou validações que são inerentes ao "conjunto da
> obra", e não a um campo específico, ou que, as vezes, o usuário nem chega a
> setar. Nesses casos, a validação com o XSD deve alertar o programador que
> algo que ele informou está inválido, e será rejeitado pela Sefaz.
> Quanto a sua sugestão, você teria um exemplo mais palpável? Uns trechos de
> código, com uns testes validando, talvez?
> Obrigado.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/wmixvideo/nfe/issues/147#issuecomment-219997112>
>



-- 
*Waldney Souza de Andrade*
*compengi engenharia & sistemas*
*waldney.andrade@gmail.com <waldney.andrade@gmail.com>*

*+55(84)8894-3405*
*+55(84)9447-7354*

**Comment by felipedamiani** [comment]
O que voê está querendo dizer @waldandrade seria uma mensagem de erro mais amigável ao usuário? Por que para isso você deveria capturar no seu aplicativo e tratar da forma que mais lhe convém, se é que entendi a pergunta.

**Comment by waldandrade** [comment]
Exatamente Felipe

Só que, como as informações estão vindo em um texto, já "tratadas"
aparentemente. Eu não consigo tratar elas novamente para mostrar da minha
forma ao usuário.

Para quem usa Framework, no Grails por exemplo, tem posso definir

minhaClasse.minhaVariavel.invalid = "Aconteceu um erro X"
e quando o erro acontece eu defino que o erro e "invalid".

No caso, também é possível utilizar valores que são retornados junto com o
erro, o que me dá uma maior liberdade para trabalhar o erro como melhor
convém.

Pensei em algo parecido para aqui .... que cada erro pudesse ser
identificado pela elemento do xml, E retornasse as informações que hoje já
saem escritas no texto em variáveis.

Poderia existir um arquivo de "message" padrão, que nós poderíamos
substituir conforme nossa necessidade.

Espero ter explicado de uma forma melhor rsrs


2016-05-20 8:42 GMT-03:00 Felipe Damiani <notifications@github.com>:

> O que voê está querendo dizer @waldandrade
> <https://github.com/waldandrade> seria uma mensagem de erro mais amigável
> ao usuário? Por que para isso você deveria capturar no seu aplicativo e
> tratar da forma que mais lhe convém, se é que entendi a pergunta.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/wmixvideo/nfe/issues/147#issuecomment-220584424>
>



-- 
*Waldney Souza de Andrade*
*compengi engenharia & sistemas*
*waldney.andrade@gmail.com <waldney.andrade@gmail.com>*

*+55(84)8894-3405*
*+55(84)9447-7354*

**Comment by waldandrade** [comment]
Isso abre caminho para por exemplo ... pegarmos o locale, e buscarmos o
arquivo de "message" utilizando o locale.
pt-BR, US, EN, e assim vai ....

Em 20 de maio de 2016 13:43, Waldney Andrade <waldney.andrade@gmail.com>
escreveu:

> Exatamente Felipe
>
> Só que, como as informações estão vindo em um texto, já "tratadas"
> aparentemente. Eu não consigo tratar elas novamente para mostrar da minha
> forma ao usuário.
>
> Para quem usa Framework, no Grails por exemplo, tem posso definir
>
> minhaClasse.minhaVariavel.invalid = "Aconteceu um erro X"
> e quando o erro acontece eu defino que o erro e "invalid".
>
> No caso, também é possível utilizar valores que são retornados junto com o
> erro, o que me dá uma maior liberdade para trabalhar o erro como melhor
> convém.
>
> Pensei em algo parecido para aqui .... que cada erro pudesse ser
> identificado pela elemento do xml, E retornasse as informações que hoje já
> saem escritas no texto em variáveis.
>
> Poderia existir um arquivo de "message" padrão, que nós poderíamos
> substituir conforme nossa necessidade.
>
> Espero ter explicado de uma forma melhor rsrs
>
>
> 2016-05-20 8:42 GMT-03:00 Felipe Damiani <notifications@github.com>:
>
>> O que voê está querendo dizer @waldandrade
>> <https://github.com/waldandrade> seria uma mensagem de erro mais
>> amigável ao usuário? Por que para isso você deveria capturar no seu
>> aplicativo e tratar da forma que mais lhe convém, se é que entendi a
>> pergunta.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/wmixvideo/nfe/issues/147#issuecomment-220584424>
>>
>
>
>
> --
> *Waldney Souza de Andrade*
> *compengi engenharia & sistemas*
> *waldney.andrade@gmail.com <waldney.andrade@gmail.com>*
>
> *+55(84)8894-3405 <%2B55%2884%298894-3405>*
> *+55(84)9447-7354 <%2B55%2884%299447-7354>*
>



-- 
*Waldney Souza de Andrade*
*compengi engenharia & sistemas*
*waldney.andrade@gmail.com <waldney.andrade@gmail.com>*

*+55(84)8894-3405*
*+55(84)9447-7354*

**Comment by fincatto** [comment]
A idéia é boa, mas carece de validação.
Você consegue postar um código de exemplo?

**Comment by waldandrade** [comment]
Creio que sim, só que precisaria de um tempo para entender como funciona hoje. Como está sendo montado o erro hoje ...

Só mais um exemplo para que todos consigam compreender .... acabei de tentar gerar o XML de uma nota, em um processo que chamei de "validação", utilizando a biblioteca. Meu sistema retorna a mensagem gerada na exceção. O erro retornado foi "Telefone de tamanho invalido (null)". Bem ... vou ter agora, eu desenvolvedor, que verificar qual foi o telefone que falhou. 

Minha ideia é que a Exception da validação, retorne em campos separados "o campo que está errado", "a entidade a quem este campo pertence", dentre outras informações em um array, além da sequência dentro do XML até chegar no elemento que apresentou erro, ou o código que representa o campo no documento do SEFAZ, e também um identificador que representaria o tipo de falha. Por exemplo, "nullable", "pattern".

No meu arquivo de "messages" eu teria por exemplo:

NFe.infNFe.ide.cNF.invalid = O campo ${0} com valor ${1} é inválida. Deve seguir o padrão ${2} ..

**Comment by waldandrade** [comment]
Quando trabalho com arquivos de configuração utilizo esse código abaixo:
```
public static Properties getProp() throws IOException {
    	
        Properties props = new Properties();
        InputStream file = Main.class.getClassLoader().getResourceAsStream("conf/conf");
        props.load(file);
        return props;

    }
```

**Comment by klutzer** [comment]
Acho que a melhor solução nesse caso seria aprimorar a Exception lançada, talvez criando um objeto próprio que informe o erro com mais detalhes. Aí nesse caso cada um trataria essa Exception da forma que quisesse..

**Comment by jefperito** [comment]
Talvez a da exceção seja uma boa idéia...

Porém é bom fazer o tratamento antes de enviar para a biblioteca, como na UI.
