### ISSUE TITLE
Nenhum alias encontrado no certificado

### ISSUE THREAD

**Issue by cnbatalha** [wmixvideo/nfe#152]
Olá pessoal, estou iniciando no projeto e pretendo contribuir também, no entanto estou tendo este problema ao chamar a classe de configurações, 

"Nenhum alias encontrado no certificado"

Estou utilizando a geração automática das cadeias de certificados.

**Comment by jefperito** [comment]
Talvez possa ter acontecido algum problema na geração dos certificados, Verifique se possui os aliases criado para cada certificado na cadeia.

**Comment by henriquebartoski** [comment]
Tive esse mesmo problema semana passada. Se estiver usando Windows instale o certificado e verifique através do IE, na tela de certificados, se o certificado em questão possui alguma coisa no campo "Nome Amigável".

Caso esteja vazio você pode incluir algum texto usando o MMC, segue o passo a passo:  https://technet.microsoft.com/pt-br/library/cc725909(v=ws.11).aspx

**Comment by edivaldoms** [comment]
Isso porque não está encontrando o caminho do certificado.
Troque essa linha:
`try (InputStream certificadoStream = NFeConfigByEmitente.class.getResourceAsStream("/certificado.pfx")) {...}`
Por essa:
`try (InputStream certificadoStream = new FileInputStream("C:/cetificado.pfx")) {...}`

Faça o mesmo em:
`try (InputStream cadeia = NFeConfigByEmitente.class.getResourceAsStream("/homologacao.cacerts")) {..}`
Troque por essa:
`try (InputStream cadeia = new FileInputStream("C:/homologacao.cacerts")) {..}`
