### ISSUE TITLE
Validação do campo nItemPed

### ISSUE THREAD

**Issue by henriquebartoski** [wmixvideo/nfe#158]
Estou fazendo a migração de nosso atual emissor Nfe e me deparei com um erro de validação no campo nItemPed, onde atualmente utilizamos valores a partir de "1", sendo aceito normalmente pelo Sefaz.
Atualmente a biblioteca está com a validação [100.000-999.999], seria possível a alteração para  [1-999.999], visto que o sefaz permite tal formato?

**Comment by fincatto** [comment]
Se a Sefaz permite, sem dúvidas! 
Inclua um teste unitário validando sua alteração e faça o PR.
