### ISSUE TITLE
Hospedar Javadoc no github

### ISSUE THREAD

**Issue by felipewmartins** [wmixvideo/nfe#162]
Bom dia pessoal,
 Estive pensando sobre ter o javadoc da biblioteca nfe, hospedado no github.io
O que vocês acham sobre isso? Para tal, será necessário melhorar a documentação dos métodos e classes existentes nela.

**Comment by jefperito** [comment]
Podia ser, mas seria em que nível tu tem em mente? Eu acho legal ter java doc na parte de comunicação e o facade

**Comment by felipewmartins** [comment]
Concordo!
A minha ideia seria documentar todas as classes. Mas a princípio, poderíamos começar por essa parte de comunicação, onde tem mais detalhes especificos.

**Comment by jefperito** [comment]
Adicionei alguma documentação no WsFacade, a idéia é ir melhorando para sanar as dúvidas da melhor forma possível

**Comment by fincatto** [comment]
Alguém consulta a documentação fora do projeto?
