### ISSUE TITLE
Versão 2.0.0

### ISSUE THREAD

**Issue by fauker** [wmixvideo/nfe#165]
Amigos, tem previsão para que a versão 2.0.0 do projeto seja publicada no Maven?

**Comment by jefperito** [comment]
Oi, ainda sem previsão alguma do milestone

**Comment by fauker** [comment]
Beleza. Já estou utilizando a versão 2.0.0-SNAPSHOT instalada localmente em meu projeto e está funcionando tudo perfeitamente, inclusive a feature que aceita XMLs já assinados. ✌️

**Comment by fincatto** [comment]
É bom saber, Lucas.
Acho que ja podemos liberar essa versão em produção, se não surgir nenhum
bug nos proximos dias.
Att,
Diego

**Comment by williamgueiros** [comment]
estava pensando em embarcar esta solução de NFCE em android, o que vcs acham de trabalharmos para isso na versão 2.0 ??

**Comment by fincatto** [comment]
Interessantíssimo William.
Que tipo de adaptações precisariam ser feitas?
Att,
Diego

**Comment by williamgueiros** [comment]
Andei dando uma olhada no projeto.
recomendo que leia este link:
http://stackoverflow.com/questions/6944367/problem-with-axis2-libarary

Teríamos que ver se todas as dependências são necessárias.
Depois disso analisar se possuem suporte para Android e Java.
Alem de verificar se no código existem acessos a Javax.

**Comment by fincatto** [comment]
Você tem conhecimento técnico para fazer isso?
Se quiser, podemos criar um branch, para facilitar a colaboração da
comunidade.
Att,
Diego

2016-06-16 20:18 GMT-03:00 william de melo gueiros <notifications@github.com

**Comment by williamgueiros** [comment]
Tenho o conhecimento, mas tenho que estudar mais o projeto.
daqui 2 semana acredito que tenha tempo para ver isso como um todo.

**Comment by fincatto** [comment]
Parto do princípio que, se você sugere o suporte a android é porque você o
usará nele, certo?
Se estiver correto, é só você importar a lib no seu projeto e fazer uma
consulta de teste.
Se funcionar, não precisa mexer em nada e não precisa nem conhecer a fundo
o projeto.
Se não funcionar, é só pegar a exceção e verificar o porque.
Att,
Diego

**Comment by waldandrade** [comment]
Android tem suporte a Axys2? Achei massa a idéia. Mas confesso que to tendo
dificuldades de imaginar a arquitetura que isso teria.
Em 17/06/2016 12:11, "Diego Fincatto" <notifications@github.com> escreveu:

> Parto do princípio que, se você sugere o suporte a android é porque você o
> usará nele, certo?
> Se estiver correto, é só você importar a lib no seu projeto e fazer uma
> consulta de teste.
> Se funcionar, não precisa mexer em nada e não precisa nem conhecer a fundo
> o projeto.
> Se não funcionar, é só pegar a exceção e verificar o porque.
> Att,
> Diego
>
> On Fri, Jun 17, 2016 at 12:02 PM, william de melo gueiros <

**Comment by jefperito** [comment]
Foi adicionado tratamento de erros mais amigáveis a versao 2.0.0.

Obrigado @klutzer!

**Comment by waldandrade** [comment]
Show!!!!!
Em 21/06/2016 14:58, "Jeferson Viana Perito" <notifications@github.com>
escreveu:

**Comment by fincatto** [comment]
A versão 2.0.0 foi liberada no Maven. 
Aguardando propagação dos repositórios.
