### ISSUE TITLE
Manifestação do desitinatário

### ISSUE THREAD

**Issue by fincatto** [wmixvideo/nfe#169]
Implementar o serviço de manifestação do destinatário.

**Comment by rafaelTartigrado** [comment]
Bom dia,

Estou precisando utilizar este evento, existe alguma iniciativa de implementação deste evento?

**Comment by fincatto** [comment]
Bom dia @rafaelTartigrado.
Ainda não temos previsão para desenvolver aqui. Você teria condições de desenvolver essa consulta? Se tiveres disposição e tempo, podemos lhe auxiliar, em caso de dúvidas.
DF

**Comment by rafaelTartigrado** [comment]
Muito obrigado @fincatto, vou iniciar o desenvolvimento, tenho uma dúvida inicial sobre a estrutura de pacotes e classes, utilizo a mesma estrutura do cancelar (com as devidas alterações)?

Outra coisa, vou precisar criar um ENUM com os códigos do evento: 
210200 – Confirmação da Operação
210210 – Ciência da Emissão
210220 – Desconhecimento da Operação 
210240 – Operação não Realizada

Crio esse ENUM no pacote com.fincatto.nfe310.classes.evento.manifestacaodestinatario, por exemplo?

**Comment by fincatto** [comment]
Quanto ao pacote, me parece o mais adequado, sim. 
O Enum também, creio que o melhor lugar seria dentro do pacote de manifestação mesmo.
PS: se quiser criar um branche específico no projeto para facilitar a colaboração, é só me avisar!
[]s

**Comment by higomatos** [comment]
Segundo esta notícia: https://www.sefaz.rs.gov.br/Site/MontaDuvidas.aspx?al=l_nfe_aviso

Os serviços de "Registro de Evento", "Consulta NF-e Destinadas" e "Download XML Destinadas"  vinculados à Manifestação do Destinatário agora devem ser consumidos exclusivamente através do Ambiente Nacional (91).

O evento Cancelamento não é citado na notícia, ou seja, temos que tomar uma decisão, iremos colocar URLs de serviço de acordo com o tipo de Evento? Ou iremos migrar todos os eventos para o Ambiente Nacional? Ou outra solução?

Obs: Ambiente Nacional não é a SVAN.

@fincatto @jefperito

**Comment by higomatos** [comment]
Outra notícia explicando a dissociação dos serviços de acordo com o tipo de eventos: http://www.sped.fazenda.pr.gov.br/modules/conteudo/conteudo.php?conteudo=87

"A SEFA/PR disponibiliza Web Service de Registro de Eventos que autoriza os seguintes eventos emitidos por contribuintes paranaenses:

- Carta de Correção Eletrônica - CC-e;
- Cancelamento da NF-e.

O Ambiente Nacional (AN) disponibiliza Web Service genérico de Registro de Eventos que autoriza os seguintes eventos:

- Eventos de Manifestação do Destinatário."

**Comment by higomatos** [comment]
@fincatto 

Separamos o evento de manifestação num novo serviço para podermos apontar a URL para o AN? Ou teria alguma outra sugestão para resolver esta situação?

**Comment by fincatto** [comment]
Não analisei a fundo o funcionamento dos eventos mas, pelo que vc enviou no post anterior, creio que sim.

**Comment by rafaelTartigrado** [comment]
#247

**Comment by fincatto** [comment]
Obrigado @rafaelTartigrado!
Vou lançar a versão 2.1.0 em breve, pra subir pro maven!
