### ISSUE TITLE
Depreciar metodos do facade que nao possuem modelo

### ISSUE THREAD

**Issue by jefperito** [wmixvideo/nfe#171]
Com o advento da NFC-e para o projeto, vários métodos foram alterados do facade para adequar a nova realidade... os novos métodos foram criados com base nos antigos e receberam um novo parâmetro chamado "modelo".
Como no exemplo abaixo:
```java
public NFLoteConsultaRetorno consultaLote(final String numeroRecibo); // antigo
public NFLoteConsultaRetorno consultaLote(final String numeroRecibo, final NFModelo modelo); // novo
```
Como o novo método serve também para a NF-e, sugiro depreciar esses métodos antigos e um futuro próximo apagá-los. O que acham?

**Comment by fincatto** [comment]
Ótima ideia!
Deprecie eles e comente a nova forma, que eu removo ele no release 2.1.0.

**Comment by jefperito** [comment]
feito!
