### ISSUE TITLE
Alterar biblioteca de comunicação com webservices

### ISSUE THREAD

**Issue by fincatto** [wmixvideo/nfe#177]
O Java dispõe de uma biblioteca padrão para consulta de webservices (javax.xml.ws).
Verificar o impacto da troca do Axis pela padrão, a fim de reduzir as dependências externas do projeto.

**Comment by fincatto** [comment]
Teriamos que alterar a versão do java. Ficará para o futuro!

**Comment by higomatos** [comment]
@fincatto, quais seriam as dificuldades ou tarefas que impedem alterar a versão do java?

**Comment by fincatto** [comment]
Dificuldade creio que nao exista, todo o codigo é compativel. Somente que iremos obrigar todos a usarem a ultima versao do java, o que é ruim pra comunicade e pra nós traz pouco ganho.
