### ISSUE TITLE
cvc-pattern-valid: O valor '0.00' não tem um aspecto válido em relação ao padrão

### ISSUE THREAD

**Issue by damascoa** [wmixvideo/nfe#179]
XML Gerado
```
<NFe xmlns="http://www.portalfiscal.inf.br/nfe"><infNFe Id="NFe31160610445097000108550010000000051876543214" versao="3.10"><ide><cUF>31</cUF><cNF>87654321</cNF><natOp>5403</natOp><indPag>2</indPag><mod>55</mod><serie>1</serie><nNF>5</nNF><dhEmi>2016-06-28T16:42:20-03:00</dhEmi><dhSaiEnt>2016-06-28T16:42:20-03:00</dhSaiEnt><tpNF>1</tpNF><idDest>1</idDest><cMunFG>3148004</cMunFG><tpImp>2</tpImp><tpEmis>1</tpEmis><cDV>0</cDV><tpAmb>2</tpAmb><finNFe>1</finNFe><indFinal>0</indFinal><indPres>0</indPres><procEmi>2</procEmi><verProc>3.10</verProc><dhCont>2016-06-28T16:42:20-03:00</dhCont><xJust>EMISSAO DE NOTAS FISCAL DE CONTINGENCIA</xJust></ide><emit><CNPJ>10445097000108</CNPJ><xNome>B2B SISTEMAS LTDA - ME</xNome><xFant>Olivet Sistemas</xFant><enderEmit><xLgr>Dona Luiza</xLgr><nro>521</nro><xCpl>Sala 304</xCpl><xBairro>Centro</xBairro><cMun>3148004</cMun><xMun>Patos de Minas</xMun><UF>MG</UF><CEP>38700164</CEP><cPais>1058</cPais><xPais>Brasil</xPais><fone>3438222250</fone></enderEmit><IE>0010974000051</IE><CRT>1</CRT></emit><dest><CPF>10618296697</CPF><xNome>Renato Gonçalves dos Santos</xNome><enderDest><xLgr>Dona Luiza</xLgr><nro>521</nro><xCpl>Sala 304</xCpl><xBairro>Centro</xBairro><cMun>3148004</cMun><xMun>Patos de Minas</xMun><UF>MG</UF><CEP>38700164</CEP><cPais>1058</cPais><xPais>Brasil</xPais><fone>3438222250</fone></enderDest><indIEDest>9</indIEDest><IE/><email>contato.renatosi@hotmail.com</email></dest><det nItem="1"><prod><cProd>000asd1</cProd><cEAN>7898215151784</cEAN><xProd>PRODUTO DE TESTE</xProd><NCM>04015021</NCM><CFOP>5403</CFOP><uCom>UN</uCom><qCom>1</qCom><vUnCom>100</vUnCom><vProd>100.00</vProd><cEANTrib>7898215151784</cEANTrib><uTrib>UN</uTrib><qTrib>1</qTrib><vUnTrib>100</vUnTrib><vFrete>0.00</vFrete><vSeg>0.00</vSeg><vDesc>0.00</vDesc><vOutro>0.00</vOutro><indTot>1</indTot></prod><imposto><ICMS><ICMSSN500><orig>0</orig><CSOSN>300</CSOSN><vBCSTRet>0.00</vBCSTRet><vICMSSTRet>0.00</vICMSSTRet></ICMSSN500></ICMS><IPI><clEnq>99999</clEnq><cEnq>999</cEnq><IPINT><CST>99</CST></IPINT></IPI><PIS/><COFINS><COFINSOutr><CST>99</CST><vBC>0.00</vBC><pCOFINS>0.00</pCOFINS><qBCProd>0</qBCProd><vAliqProd>0.0000</vAliqProd><vCOFINS>0.00</vCOFINS></COFINSOutr></COFINS></imposto><infAdProd>Yeahhh</infAdProd></det><total><ICMSTot><vBC>100.00</vBC><vICMS>0.00</vICMS><vICMSDeson>0.00</vICMSDeson><vBCST>0.00</vBCST><vST>0.00</vST><vProd>100.00</vProd><vFrete>0.00</vFrete><vSeg>0.00</vSeg><vDesc>0.01</vDesc><vII>0.00</vII><vIPI>0.00</vIPI><vPIS>0.00</vPIS><vCOFINS>0.00</vCOFINS><vOutro>0.00</vOutro><vNF>0.00</vNF><vTotTrib>0.00</vTotTrib></ICMSTot></total><transp><modFrete>9</modFrete><transporta><CNPJ>10445097000108</CNPJ><xNome>TRANSPORTADORA TESTE</xNome><IE/><xEnder>RUA RUI BARBOSA</xEnder><UF>MG</UF></transporta><veicTransp><placa>GKO0000</placa><UF>MG</UF><RNTC>123</RNTC></veicTransp></transp></infNFe><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI="#NFe31160610445097000108550010000000051876543214"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>JUd+432bZXLrH8d8CG1TMLujdoM=</DigestValue></Reference></SignedInfo><SignatureValue>h0EDG/7Lu2K1t45ePZwUbSh+f0EuqWjM4DLtQEioKbEv/AAqVe4ZqQwHahnFQYxh3588oJuvOXkb
VCPMD2a6EDMAaNdCWZProtGQrwJ374+xA2KVZbwp9MQ6jAAzF1Wpwer5p4Iqn1oi16fuhh1lHFxH
PhBib4mONkd6IM//w2g042sd+hJkKspMhuOCs+f6Nn2T5cazfZNCqqmw3LHxAepr8VV32J5lABUf
Pv6ESaICWyhC1JwtYUM/J411gJ6DuXTyZdyneS5pG5urqHwuk0kWzhhYwRoK2Zc/wk5DTPscn6V5
oVU0CcBQj6YCB5HxvKxyQg1iSXedKGyHuFPKjw==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIH+DCCBeCgAwIBAgIIBmcLPIlQdQ4wDQYJKoZIhvcNAQELBQAwdTELMAkGA1UEBhMCQlIxEzAR
BgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFs
IGRvIEJyYXNpbCAtIFJGQjEZMBcGA1UEAxMQQUMgU0VSQVNBIFJGQiB2MjAeFw0xNTA3MDkxMDMx
MDBaFw0xNjA3MDgxMDMxMDBaMIHbMQswCQYDVQQGEwJCUjELMAkGA1UECBMCTUcxFzAVBgNVBAcT
DlBBVE9TIERFIE1JTkFTMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMTYwNAYDVQQLEy1TZWNyZXRhcmlh
IGRhIFJlY2VpdGEgRmVkZXJhbCBkbyBCcmFzaWwgLSBSRkIxFjAUBgNVBAsTDVJGQiBlLUNOUEog
QTExEzARBgNVBAsTCkFSIEtSWVBUT04xLDAqBgNVBAMTI0IyQiBTSVNURU1BUyBMVERBIE1FOjEw
NDQ1MDk3MDAwMTA4MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqQtInWusT2dElpOj
47tkCJVL49eGQa4kpJJ14QrrlnBTRNgkMCic5c94c0Ilf2URUIViErd6MEhK1i/kmpGxeSqNmZRh
gXGulhJraEr1itc03NQxb2PurQsY1shOFZYOFsh762orRj+7HOS7UEYOkst8tn4e/EBrILHypy+c
NkA8cbIRhTW/QblfKN/c31D0MfBAZpf0YwFuicWDleBeCCQjK91rWazy9y3MdQb5DnZWRV/B2/21
lIOSRlAwDJVpYV4FMHnIBIxl32iyFFPPP1V50G/3qyANuvlLlNJzScKnglK1AgflLXeLoggUOG/s
ryk6YNfPx0WszrtpAW+RcQIDAQABo4IDIzCCAx8wgZkGCCsGAQUFBwEBBIGMMIGJMEgGCCsGAQUF
BzAChjxodHRwOi8vd3d3LmNlcnRpZmljYWRvZGlnaXRhbC5jb20uYnIvY2FkZWlhcy9zZXJhc2Fy
ZmJ2Mi5wN2IwPQYIKwYBBQUHMAGGMWh0dHA6Ly9vY3NwLmNlcnRpZmljYWRvZGlnaXRhbC5jb20u
YnIvc2VyYXNhcmZidjIwCQYDVR0TBAIwADAfBgNVHSMEGDAWgBSyoMQ9Rp58yIVsCB4QMpRlRnBB
czBxBgNVHSAEajBoMGYGBmBMAQIBDTBcMFoGCCsGAQUFBwIBFk5odHRwOi8vcHVibGljYWNhby5j
ZXJ0aWZpY2Fkb2RpZ2l0YWwuY29tLmJyL3JlcG9zaXRvcmlvL2RwYy9kZWNsYXJhY2FvLXJmYi5w
ZGYwgfMGA1UdHwSB6zCB6DBKoEigRoZEaHR0cDovL3d3dy5jZXJ0aWZpY2Fkb2RpZ2l0YWwuY29t
LmJyL3JlcG9zaXRvcmlvL2xjci9zZXJhc2FyZmJ2Mi5jcmwwRKBCoECGPmh0dHA6Ly9sY3IuY2Vy
dGlmaWNhZG9zLmNvbS5ici9yZXBvc2l0b3Jpby9sY3Ivc2VyYXNhcmZidjIuY3JsMFSgUqBQhk5o
dHRwOi8vcmVwb3NpdG9yaW8uaWNwYnJhc2lsLmdvdi5ici9sY3IvU2VyYXNhL3JlcG9zaXRvcmlv
L2xjci9zZXJhc2FyZmJ2Mi5jcmwwDgYDVR0PAQH/BAQDAgXgMB0GA1UdJQQWMBQGCCsGAQUFBwMC
BggrBgEFBQcDBDCBvAYDVR0RBIG0MIGxgR1UUklOREFERUZJU0NBTEBORVRTSVRFLkNPTS5CUqAd
BgVgTAEDAqAUExJMVUlTIEFOVE9OSU8gU0lMVkGgGQYFYEwBAwOgEBMOMTA0NDUwOTcwMDAxMDig
PQYFYEwBAwSgNBMyMDgwOTE5NzI4MzE0MDIzOTY1MzAwMDAwMDAwMDAwMDAwMDAwME01NDM3Mjk2
U1NQTUegFwYFYEwBAwegDhMMMDAwMDAwMDAwMDAwMA0GCSqGSIb3DQEBCwUAA4ICAQC41dzLyT3G
H9QBCowC5+KE9GzEr2X8wPmWzNbS98wrd0tC0Pkt5zPixkFJChxZ94hsWM2KB7RTK8s1BycoKBvi
S0L3sC5pfWjg6xkWIJ75WpUS2KKSvKzEJhsM+nMWNaoPzwaCpG3OfLjUGZphiAeg9TwZ5MRDLArB
rcjmGwcCQn5401I/8obC5Av+2kNvrpYujdvyi3z1dCAl+NQ+M9yGcVHVnkdW3GSDbi8KcT4ETbU0
ImopqvkkixnF46tYfWeMPfhmKgrw1t796m3dt+WhJMFUh/4o5VFm3MRvDHhgC1K9O4UsywN4RMlm
Jau+NljLZIzgftmubOk2mLx6FGQyccX1hnLHv/dxeyeLXBLlfcPrMGVpAzWCPadI9IDiQXuVToaF
aW7eH6e9ghePi4IbtFyz+3/dg2zVNK7YuoU3AYM+K3gmuR82ojgb9v9kyHzeP3WjplBE+xYVnFC2
V/ElGFbS/93lgJ0C66oyp6U7kaWmObB+Yg8+bW5tYNeEXsAx+a4+yx32f5gPd3KHV7veN9AGl+0V
m9MWdrm1TJKFqZ2JwjTpomdGJBz3OxoiD4vekNbpG5JRsdShCDxE69eKdOFMtZcHqDESfqoBFVtm
uOLoAL9z9UZRLi5J/YMAXOgHQd/q1Y1EDWGbtZ6TH4aq4O4zZy9DazWZM6mrB8DbJg==</X509Certificate></X509Data></KeyInfo></Signature></NFe>
```

Na coluna1810 que fala sobre o erro tenho a tag <indTot>0</indTot> aparentemente o valor está correto.
Alguem passou por este mesmo problema?
Estou usando a versão 1.2.0

**Comment by waldandrade** [comment]
Não sei se é o caso. Mas tem umas tags que não pode ter valor 0, ou tem
valor ou não tem a tag.

2016-06-28 16:46 GMT-03:00 damascoa <notifications@github.com>:

> XML Gerado
>
> <NFe xmlns="http://www.portalfiscal.inf.br/nfe"><infNFe Id="NFe31160610445097000108550010000000051876543214" versao="3.10"><ide><cUF>31</cUF><cNF>87654321</cNF><natOp>5403</natOp><indPag>2</indPag><mod>55</mod><serie>1</serie><nNF>5</nNF><dhEmi>2016-06-28T16:42:20-03:00</dhEmi><dhSaiEnt>2016-06-28T16:42:20-03:00</dhSaiEnt><tpNF>1</tpNF><idDest>1</idDest><cMunFG>3148004</cMunFG><tpImp>2</tpImp><tpEmis>1</tpEmis><cDV>0</cDV><tpAmb>2</tpAmb><finNFe>1</finNFe><indFinal>0</indFinal><indPres>0</indPres><procEmi>2</procEmi><verProc>3.10</verProc><dhCont>2016-06-28T16:42:20-03:00</dhCont><xJust>EMISSAO DE NOTAS FISCAL DE CONTINGENCIA</xJust></ide><emit><CNPJ>10445097000108</CNPJ><xNome>B2B SISTEMAS LTDA - ME</xNome><xFant>Olivet Sistemas</xFant><enderEmit><xLgr>Dona Luiza</xLgr><nro>521</nro><xCpl>Sala 304</xCpl><xBairro>Centro</xBairro><cMun>3148004</cMun><xMun>Patos de Minas</xMun><UF>MG</UF><CEP>38700164</CEP><cPais>1058</cPais><xPais>Brasil</xPais><fone>3438222250</fone></enderEmit><IE>0010974000051</IE><CRT>1</CRT></emit><dest><CPF>10618296697</CPF><xNome>Renato Gonçalves dos Santos</xNome><enderDest><xLgr>Dona Luiza</xLgr><nro>521</nro><xCpl>Sala 304</xCpl><xBairro>Centro</xBairro><cMun>3148004</cMun><xMun>Patos de Minas</xMun><UF>MG</UF><CEP>38700164</CEP><cPais>1058</cPais><xPais>Brasil</xPais><fone>3438222250</fone></enderDest><indIEDest>9</indIEDest><IE/><email>contato.renatosi@hotmail.com</email></dest><det nItem="1"><prod><cProd>000asd1</cProd><cEAN>7898215151784</cEAN><xProd>PRODUTO DE TESTE</xProd><NCM>04015021</NCM><CFOP>5403</CFOP><uCom>UN</uCom><qCom>1</qCom><vUnCom>100</vUnCom><vProd>100.00</vProd><cEANTrib>7898215151784</cEANTrib><uTrib>UN</uTrib><qTrib>1</qTrib><vUnTrib>100</vUnTrib><vFrete>0.00</vFrete><vSeg>0.00</vSeg><vDesc>0.00</vDesc><vOutro>0.00</vOutro><indTot>1</indTot></prod><imposto><ICMS><ICMSSN500><orig>0</orig><CSOSN>300</CSOSN><vBCSTRet>0.00</vBCSTRet><vICMSSTRet>0.00</vICMSSTRet></ICMSSN500></ICMS><IPI><clEnq>99999</clEnq><cEnq>999</cEnq><IPINT><CST>99</CST></IPINT></IPI><PIS/><COFINS><COFINSOutr><CST>99</CST><vBC>0.00</vBC><pCOFINS>0.00</pCOFINS><qBCProd>0</qBCProd><vAliqProd>0.0000</vAliqProd><vCOFINS>0.00</vCOFINS></COFINSOutr></COFINS></imposto><infAdProd>Yeahhh</infAdProd></det><total><ICMSTot><vBC>100.00</vBC><vICMS>0.00</vICMS><vICMSDeson>0.00</vICMSDeson><vBCST>0.00</vBCST><vST>0.00</vST><vProd>100.00</vProd><vFrete>0.00</vFrete><vSeg>0.00</vSeg><vDesc>0.01</vDesc><vII>0.00</vII><vIPI>0.00</vIPI><vPIS>0.00</vPIS><vCOFINS>0.00</vCOFINS><vOutro>0.00</vOutro><vNF>0.00</vNF><vTotTrib>0.00</vTotTrib></ICMSTot></total><transp><modFrete>9</modFrete><transporta><CNPJ>10445097000108</CNPJ><xNome>TRANSPORTADORA TESTE</xNome><IE/><xEnder>RUA RUI BARBOSA</xEnder><UF>MG</UF></transporta><veicTransp><placa>GKO0000</placa><UF>MG</UF><RNTC>123</RNTC></veicTransp></transp></infNFe><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI="#NFe31160610445097000108550010000000051876543214"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>JUd+432bZXLrH8d8CG1TMLujdoM=</DigestValue></Reference></SignedInfo><SignatureValue>h0EDG/7Lu2K1t45ePZwUbSh+f0EuqWjM4DLtQEioKbEv/AAqVe4ZqQwHahnFQYxh3588oJuvOXkb
> VCPMD2a6EDMAaNdCWZProtGQrwJ374+xA2KVZbwp9MQ6jAAzF1Wpwer5p4Iqn1oi16fuhh1lHFxH
> PhBib4mONkd6IM//w2g042sd+hJkKspMhuOCs+f6Nn2T5cazfZNCqqmw3LHxAepr8VV32J5lABUf
> Pv6ESaICWyhC1JwtYUM/J411gJ6DuXTyZdyneS5pG5urqHwuk0kWzhhYwRoK2Zc/wk5DTPscn6V5
> oVU0CcBQj6YCB5HxvKxyQg1iSXedKGyHuFPKjw==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIH+DCCBeCgAwIBAgIIBmcLPIlQdQ4wDQYJKoZIhvcNAQELBQAwdTELMAkGA1UEBhMCQlIxEzAR
> BgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFs
> IGRvIEJyYXNpbCAtIFJGQjEZMBcGA1UEAxMQQUMgU0VSQVNBIFJGQiB2MjAeFw0xNTA3MDkxMDMx
> MDBaFw0xNjA3MDgxMDMxMDBaMIHbMQswCQYDVQQGEwJCUjELMAkGA1UECBMCTUcxFzAVBgNVBAcT
> DlBBVE9TIERFIE1JTkFTMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMTYwNAYDVQQLEy1TZWNyZXRhcmlh
> IGRhIFJlY2VpdGEgRmVkZXJhbCBkbyBCcmFzaWwgLSBSRkIxFjAUBgNVBAsTDVJGQiBlLUNOUEog
> QTExEzARBgNVBAsTCkFSIEtSWVBUT04xLDAqBgNVBAMTI0IyQiBTSVNURU1BUyBMVERBIE1FOjEw
> NDQ1MDk3MDAwMTA4MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqQtInWusT2dElpOj
> 47tkCJVL49eGQa4kpJJ14QrrlnBTRNgkMCic5c94c0Ilf2URUIViErd6MEhK1i/kmpGxeSqNmZRh
> gXGulhJraEr1itc03NQxb2PurQsY1shOFZYOFsh762orRj+7HOS7UEYOkst8tn4e/EBrILHypy+c
> NkA8cbIRhTW/QblfKN/c31D0MfBAZpf0YwFuicWDleBeCCQjK91rWazy9y3MdQb5DnZWRV/B2/21
> lIOSRlAwDJVpYV4FMHnIBIxl32iyFFPPP1V50G/3qyANuvlLlNJzScKnglK1AgflLXeLoggUOG/s
> ryk6YNfPx0WszrtpAW+RcQIDAQABo4IDIzCCAx8wgZkGCCsGAQUFBwEBBIGMMIGJMEgGCCsGAQUF
> BzAChjxodHRwOi8vd3d3LmNlcnRpZmljYWRvZGlnaXRhbC5jb20uYnIvY2FkZWlhcy9zZXJhc2Fy
> ZmJ2Mi5wN2IwPQYIKwYBBQUHMAGGMWh0dHA6Ly9vY3NwLmNlcnRpZmljYWRvZGlnaXRhbC5jb20u
> YnIvc2VyYXNhcmZidjIwCQYDVR0TBAIwADAfBgNVHSMEGDAWgBSyoMQ9Rp58yIVsCB4QMpRlRnBB
> czBxBgNVHSAEajBoMGYGBmBMAQIBDTBcMFoGCCsGAQUFBwIBFk5odHRwOi8vcHVibGljYWNhby5j
> ZXJ0aWZpY2Fkb2RpZ2l0YWwuY29tLmJyL3JlcG9zaXRvcmlvL2RwYy9kZWNsYXJhY2FvLXJmYi5w
> ZGYwgfMGA1UdHwSB6zCB6DBKoEigRoZEaHR0cDovL3d3dy5jZXJ0aWZpY2Fkb2RpZ2l0YWwuY29t
> LmJyL3JlcG9zaXRvcmlvL2xjci9zZXJhc2FyZmJ2Mi5jcmwwRKBCoECGPmh0dHA6Ly9sY3IuY2Vy
> dGlmaWNhZG9zLmNvbS5ici9yZXBvc2l0b3Jpby9sY3Ivc2VyYXNhcmZidjIuY3JsMFSgUqBQhk5o
> dHRwOi8vcmVwb3NpdG9yaW8uaWNwYnJhc2lsLmdvdi5ici9sY3IvU2VyYXNhL3JlcG9zaXRvcmlv
> L2xjci9zZXJhc2FyZmJ2Mi5jcmwwDgYDVR0PAQH/BAQDAgXgMB0GA1UdJQQWMBQGCCsGAQUFBwMC
> BggrBgEFBQcDBDCBvAYDVR0RBIG0MIGxgR1UUklOREFERUZJU0NBTEBORVRTSVRFLkNPTS5CUqAd
> BgVgTAEDAqAUExJMVUlTIEFOVE9OSU8gU0lMVkGgGQYFYEwBAwOgEBMOMTA0NDUwOTcwMDAxMDig
> PQYFYEwBAwSgNBMyMDgwOTE5NzI4MzE0MDIzOTY1MzAwMDAwMDAwMDAwMDAwMDAwME01NDM3Mjk2
> U1NQTUegFwYFYEwBAwegDhMMMDAwMDAwMDAwMDAwMA0GCSqGSIb3DQEBCwUAA4ICAQC41dzLyT3G
> H9QBCowC5+KE9GzEr2X8wPmWzNbS98wrd0tC0Pkt5zPixkFJChxZ94hsWM2KB7RTK8s1BycoKBvi
> S0L3sC5pfWjg6xkWIJ75WpUS2KKSvKzEJhsM+nMWNaoPzwaCpG3OfLjUGZphiAeg9TwZ5MRDLArB
> rcjmGwcCQn5401I/8obC5Av+2kNvrpYujdvyi3z1dCAl+NQ+M9yGcVHVnkdW3GSDbi8KcT4ETbU0
> ImopqvkkixnF46tYfWeMPfhmKgrw1t796m3dt+WhJMFUh/4o5VFm3MRvDHhgC1K9O4UsywN4RMlm
> Jau+NljLZIzgftmubOk2mLx6FGQyccX1hnLHv/dxeyeLXBLlfcPrMGVpAzWCPadI9IDiQXuVToaF
> aW7eH6e9ghePi4IbtFyz+3/dg2zVNK7YuoU3AYM+K3gmuR82ojgb9v9kyHzeP3WjplBE+xYVnFC2
> V/ElGFbS/93lgJ0C66oyp6U7kaWmObB+Yg8+bW5tYNeEXsAx+a4+yx32f5gPd3KHV7veN9AGl+0V
> m9MWdrm1TJKFqZ2JwjTpomdGJBz3OxoiD4vekNbpG5JRsdShCDxE69eKdOFMtZcHqDESfqoBFVtm
> uOLoAL9z9UZRLi5J/YMAXOgHQd/q1Y1EDWGbtZ6TH4aq4O4zZy9DazWZM6mrB8DbJg==</X509Certificate></X509Data></KeyInfo></Signature></NFe>
>
> Na linha 1810 que fala sobre o erro tenho a tag 0 aparentemente o valor
> está correto.
> Alguem passou por este mesmo problema?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/wmixvideo/nfe/issues/179>, or mute the thread
> <https://github.com/notifications/unsubscribe/ALSmmfC3UoJUKBY6oXV_zw93NWPxmFeSks5qQXoLgaJpZM4JAdpB>
> .
>



-- 
*Waldney Souza de Andrade*
*compengi engenharia & sistemas*
*waldney.andrade@gmail.com <waldney.andrade@gmail.com>*

*+55(84)8894-3405*
*+55(84)9447-7354*

**Comment by damascoa** [comment]
Esta tag é obrigatório, conferi aqui no código e se nao informar ele nem gera o xml

**Comment by waldandrade** [comment]
Qual é a tag?

2016-06-28 17:09 GMT-03:00 damascoa <notifications@github.com>:

> Esta tag é obrigatório, conferi aqui no código e se nao informar ele nem
> gera o xml
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/wmixvideo/nfe/issues/179#issuecomment-229167338>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ALSmmfPzCEBtAMUWCF0y0sZi199C3jqnks5qQX9ogaJpZM4JAdpB>
> .
>



-- 
*Waldney Souza de Andrade*
*compengi engenharia & sistemas*
*waldney.andrade@gmail.com <waldney.andrade@gmail.com>*

*+55(84)8894-3405*
*+55(84)9447-7354*

**Comment by waldandrade** [comment]
Dá uma olhada nesses valores dos itens da nota que estão com valor 0.

2016-06-28 17:10 GMT-03:00 Waldney Andrade <waldney.andrade@gmail.com>:

> Qual é a tag?
>
> 2016-06-28 17:09 GMT-03:00 damascoa <notifications@github.com>:
>
>> Esta tag é obrigatório, conferi aqui no código e se nao informar ele nem
>> gera o xml
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/wmixvideo/nfe/issues/179#issuecomment-229167338>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe/ALSmmfPzCEBtAMUWCF0y0sZi199C3jqnks5qQX9ogaJpZM4JAdpB>
>> .
>>
>
>
>
> --
> *Waldney Souza de Andrade*
> *compengi engenharia & sistemas*
> *waldney.andrade@gmail.com <waldney.andrade@gmail.com>*
>
> *+55(84)8894-3405 <%2B55%2884%298894-3405>*
> *+55(84)9447-7354 <%2B55%2884%299447-7354>*
>



-- 
*Waldney Souza de Andrade*
*compengi engenharia & sistemas*
*waldney.andrade@gmail.com <waldney.andrade@gmail.com>*

*+55(84)8894-3405*
*+55(84)9447-7354*

**Comment by jefperito** [comment]
Talvez o campo não pode ser zero, geralmente existe uma expressão regular que valida o valor que não pode ser zerado, verifique no manual se é um valor válido.

**Comment by waldandrade** [comment]
De acordo!

2016-06-28 17:17 GMT-03:00 Jeferson Viana Perito <notifications@github.com>:

> Talvez o campo não pode ser zero, geralmente existe uma expressão regular
> que valida o valor que não pode ser zerado, verifique no manual se é um
> valor válido.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/wmixvideo/nfe/issues/179#issuecomment-229169660>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ALSmmVV32Tx_3T5AEDdHdUIU8aws2Hzpks5qQYFqgaJpZM4JAdpB>
> .
>



-- 
*Waldney Souza de Andrade*
*compengi engenharia & sistemas*
*waldney.andrade@gmail.com <waldney.andrade@gmail.com>*

*+55(84)8894-3405*
*+55(84)9447-7354*

**Comment by damascoa** [comment]
A tag <indTot>0</indTot>
Este campo deverá ser preenchido com: 
0  o valor do item (vProd) não compõe o valor total da NF-e (vProd) 
1  o valor do item (vProd) compõe o valor total da NF-e (vProd) 

@Element(name = "indTot", required = true)
    private NFProdutoCompoeValorNota compoeValorNota;


Fiz um teste removi a biblioteca do maven e adicionei o projeto direto e o erro nao ocorreu mais, porém encontrei outro erro  

> **Nao foi possivel parsear o xml: Element 'Signature' is already used with @org.simpleframework.xml.Element(name=Signature, type=void, data=false, required=false) on field 'assinatura' private com.fincatto.nfe310.classes.nota.assinatura.NFSignature com.fincatto.nfe310.classes.nota.NFNota.assinatura at line 40**

Estou verificando as modelos para ver o que acontece que ele não está conseguindo converter.

**Comment by waldandrade** [comment]
E por favor, não esquece de colocar aqui sua resolução, para contribuir com
a comunidade. :)

Em 28 de junho de 2016 17:19, Waldney Andrade <waldney.andrade@gmail.com>
escreveu:

> De acordo!
>
> 2016-06-28 17:17 GMT-03:00 Jeferson Viana Perito <notifications@github.com
> >:
>
>> Talvez o campo não pode ser zero, geralmente existe uma expressão regular
>> que valida o valor que não pode ser zerado, verifique no manual se é um
>> valor válido.
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/wmixvideo/nfe/issues/179#issuecomment-229169660>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe/ALSmmVV32Tx_3T5AEDdHdUIU8aws2Hzpks5qQYFqgaJpZM4JAdpB>
>> .
>>
>
>
>
> --
> *Waldney Souza de Andrade*
> *compengi engenharia & sistemas*
> *waldney.andrade@gmail.com <waldney.andrade@gmail.com>*
>
> *+55(84)8894-3405 <%2B55%2884%298894-3405>*
> *+55(84)9447-7354 <%2B55%2884%299447-7354>*
>



-- 
*Waldney Souza de Andrade*
*compengi engenharia & sistemas*
*waldney.andrade@gmail.com <waldney.andrade@gmail.com>*

*+55(84)8894-3405*
*+55(84)9447-7354*

**Comment by waldandrade** [comment]
Desculpa, mas não consigo mais compreender seu problema!

2016-06-28 17:19 GMT-03:00 damascoa <notifications@github.com>:

> A tag 0
> Este campo deverá ser preenchido com:
> 0 � o valor do item (vProd) não compõe o valor total da NF-e (vProd)
> 1 � o valor do item (vProd) compõe o valor total da NF-e (vProd)
>
> @Element <https://github.com/Element>(name = "indTot", required = true)
> private NFProdutoCompoeValorNota compoeValorNota;
>
> Fiz um teste removi a biblioteca do maven e adicionei o projeto direto e o
> erro nao ocorreu mais, porém encontrei outro erro
>
> *Nao foi possivel parsear o xml: Element 'Signature' is already used with
> @org <https://github.com/org>.simpleframework.xml.Element(name=Signature,
> type=void, data=false, required=false) on field 'assinatura' private
> com.fincatto.nfe310.classes.nota.assinatura.NFSignature
> com.fincatto.nfe310.classes.nota.NFNota.assinatura at line 40*
>
> Estou verificando as modelos para ver o que acontece que ele não está
> conseguindo converter.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/wmixvideo/nfe/issues/179#issuecomment-229170239>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ALSmmSt20dJg4sZ4BYd9KlzfhzkAh0y7ks5qQYHrgaJpZM4JAdpB>
> .
>



-- 
*Waldney Souza de Andrade*
*compengi engenharia & sistemas*
*waldney.andrade@gmail.com <waldney.andrade@gmail.com>*

*+55(84)8894-3405*
*+55(84)9447-7354*

**Comment by damascoa** [comment]
Corrigi e postei a solução no meu post anterior.

**Comment by jefperito** [comment]
valor do produto precisa ser acima de zero.

Nao consegui achar na documentacao sobre o valor do produto, mas achei no XSD.

o tipo do valor do produto no XSD é TDec_1302,

```xml
<xs:simpleType name="TDec_1302">
		<xs:annotation>
			<xs:documentation>Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="preserve"/>
			<xs:pattern value="0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,12}(\.[0-9]{2})?"/>
		</xs:restriction>
	</xs:simpleType>
```

Pela expressão regular ele nao permite 0.00 como foi postado antes

**Comment by damascoa** [comment]
O problema que ocorria não era no valor do produto e sim no campo que indica se o valor do produto faz parte do total da nota.

**Comment by jefperito** [comment]
hmmmm, ainda bem, acabei de reler a expressão regular e ele permite 0 ou 0.0! me enganei como é  outros padrões, que bom que achou o seu problema!

**Comment by damascoa** [comment]
Hehehe, mais mesmo assim muito obrigado pela atenção.
