### ISSUE TITLE
Fluxo Emissão de NFE

### ISSUE THREAD

**Issue by damascoa** [wmixvideo/nfe#184]
Bom dia estou começando a desenvolver o módulo NF-e e estou iniciando e estou um pouco perdido com o fluxo que a biblioteca trabalha.
Até o momento montei o seguinte fluxo.

Implementei o `NFeConfig`
Carreguei o `NFNota`
Adicionar a `NFNota `ao `NFLoteEnvio`
Após esta etapa fique um pouco com dúvida pois dei uma olhada a fundo no codigo `WSLoteEnvio.enviaLote` e notei que este método gera a chave de acesso para as notas do lote faz a assinatura dos lotes.
Até aqui tudo bem porém após o retorno do objeto `NFLoteEnvioRetornoDados ` o que deve-se proceder? Quando utilizar o `NFNotaProcessada `? Pois fala para adicionar o protocolo manualmente e este protocolo é gerado pelo Sefaz.
Bom se alguém souber e que me possa esclarecer esta dúvida fico muito grato e me prontifico a dar início da documentação destas etapas para que ninguém perca horas e horas com estas dúvidas banais.

**Comment by mauriliommachado** [comment]
Tenho essa mesma dúvida

**Comment by klutzer** [comment]
Você primeiro faz o envio de lote e depois a consulta, o conjunto das duas "gera" uma NFNotaProcessada..

Dêem uma olhada no #153 que ta bem detalhado lá

**Comment by jefperito** [comment]
Estou pensando em criar um wiki, página algo do tipo (aqui no GitHub) para instruir os mais novos sobre fluxo da biblioteca, dando um apanhado geral sobre como funciona, os principais gotcha's, etc...
O que acham? esse fim de semana daria pra escrever um draft sobre

**Comment by dmitrukbr** [comment]
Jeferson, sou novo no grupo. Estou pesquisando sobre como funciona o SOAP
para um trabalho de faculdade. Baixei o projeto de vocês e estou lendo os
códigos para entender rsrs. Já consegui assinar com o certificado A1 e
validar o XML. Agora estou na procura aonde o sistema faz o POST do XML
junto com o cabeçalho e envelope para poder entender o SOAP. Acho legal sua
idéia. Abraços.

Em 1 de julho de 2016 08:09, Jeferson Viana Perito <notifications@github.com

**Comment by damascoa** [comment]
jefperito, com toda certeza vai agregar muito o projeto e a comunidade irá aumentar, assim facilitando o encontro de novos bugs e até aumentando a quantidade de desenvolvedores envolvido no projeto.

**Comment by jefperito** [comment]
é através do Façade do projeto, ele deixa isso transparente para o usuário, você não manipula o SOAP diretamente, ela abstrai toda a parte da arquitetura de webservice.

a classe do façade é _WsFacade_, é por ela que começa o fluxo, dá uma olhada nela.

**Comment by mauriliommachado** [comment]
Vejo que muitos desenvolvedores acabam por desistir de usar a ferramenta por falta de documentação. Acho que seria muito útil.

**Comment by klutzer** [comment]
Eu acho válida a ideia, com certeza. Porém não acredito que este seja o motivo de alguém desistir de usar a biblioteca, até pq o README da conta de quase tudo o que o cara precisa (pelo menos pra mim, quando comecei). E realmente como o @jefperito falou, o façade do projeto é autoexplicativo.

O projeto como um todo foi muito bem montado, com caras que se preocupam com código decente. Mesmo "caindo de para-quedas", a pouco mais de 1 mês aqui, de todos os projetos de NF-e que já tive contato, este de longe é o mais simples e objetivo.. A wiki poderia inclusive destacar essas facilidades/benefícios que acho que são um grande diferencial..

**Comment by mauriliommachado** [comment]
Sim, eu mesmo me localizei facilmente no projeto, porem já passei esse projeto para uns amigos com menor instrução, e tiveram dificuldades.

**Comment by fincatto** [comment]
Há um manual no site da NFe bem detalhado sobre como deve ser o fluxo da troca de informações.

Mas resumindo, você envia um lote de notas pra lá e eles te retornam um numero de protocolo.
Com esse número, você deve consultar o status do processamento das suas notas, uma vez que o processo na Sefaz é assíncrono.

Sobre a documentação, se o que estão propondo é uma documentação grande e burocrática, acho difícil alguém ler e manter isso vira um inferno. Gosto das coisas mais práticas e objetivas, por isso voto com o @jefperito para a criação de uma wiki, um pouco mais detalhada que o README, que contenha os passos básicos (com código) para cada etapa da nota (emissão, consulta, cancelamento, evento, etc). 

Alguém aí se habilita em escrever?

**Comment by jefperito** [comment]
Eu já estou escrevendo alguma coisa e provável que hoje ainda devo postar

**Comment by jefperito** [comment]
Adicionei alguma informação em https://github.com/wmixvideo/nfe/blob/master/docs/mais_info.md, ainda tem que colocar muito mais informação e polir o texto, pretendo manter no código fonte pois mantem versionamento enquanto não tem ums versao de "release" para a wiki
