### ISSUE TITLE
Rejeicao: Assinatura difere do calculado

### ISSUE THREAD

**Issue by damascoa** [wmixvideo/nfe#185]
Opa pessoal acho que agora está quase.
Estou transmitindo a nota fiscal porém estou tendo: Rejeicao: `Assinatura difere do calculado`
Já verifiquei o meu certificado e a senha e está tudo ok, consultando o cadastro, consultando a situação, porém está dando esta rejeição na nota.

Segue o XML
`<nfeProc versao="3.10" xmlns="http://www.portalfiscal.inf.br/nfe">
    <NFe>
        <infNFe Id="NFe31160610445097000108550010111111181517518844" versao="3.10">
            <ide>
                <cUF>31</cUF>
                <cNF>51751884</cNF>
                <natOp>5403</natOp>
                <indPag>2</indPag>
                <mod>55</mod>
                <serie>1</serie>
                <nNF>11111118</nNF>
                <dhEmi>2016-06-29T12:14:47-03:00</dhEmi>
                <tpNF>1</tpNF>
                <idDest>1</idDest>
                <cMunFG>3148004</cMunFG>
                <tpImp>1</tpImp>
                <tpEmis>1</tpEmis>
                <cDV>4</cDV>
                <tpAmb>2</tpAmb>
                <finNFe>1</finNFe>
                <indFinal>1</indFinal>
                <indPres>2</indPres>
                <procEmi>0</procEmi>
                <verProc>3.10</verProc>
            </ide>
            <emit>
                <CNPJ>10445097000108</CNPJ>
                <xNome>B2B SISTEMAS LTDA ME</xNome>
                <xFant>Olivet Sistemas</xFant>
                <enderEmit>
                    <xLgr>Dona Luiza</xLgr>
                    <nro>521</nro>
                    <xCpl>Sala 304</xCpl>
                    <xBairro>Centro</xBairro>
                    <cMun>3148004</cMun>
                    <xMun>Patos de Minas</xMun>
                    <UF>MG</UF>
                    <CEP>38700164</CEP>
                    <cPais>1058</cPais>
                    <xPais>Brasil</xPais>
                    <fone>3438222250</fone>
                </enderEmit>
                <IE>0010974000051</IE>
                <CRT>1</CRT>
            </emit>
            <dest>
                <CNPJ>99999999000191</CNPJ>
                <xNome>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xNome>
                <enderDest>
                    <xLgr>Dona Luiza</xLgr>
                    <nro>521</nro>
                    <xCpl>Sala 304</xCpl>
                    <xBairro>Centro</xBairro>
                    <cMun>3148004</cMun>
                    <xMun>Patos de Minas</xMun>
                    <UF>MG</UF>
                    <CEP>38700164</CEP>
                    <cPais>1058</cPais>
                    <xPais>Brasil</xPais>
                    <fone>3438222250</fone>
                </enderDest>
                <indIEDest>9</indIEDest>
                <email>contato.renatosi@hotmail.com</email>
            </dest>
            <det nItem="1">
                <prod>
                    <cProd>000asd1</cProd>
                    <cEAN>7898215151784</cEAN>
                    <xProd>PRODUTO DE TESTE</xProd>
                    <NCM>04015021</NCM>
                    <CFOP>5403</CFOP>
                    <uCom>UN</uCom>
                    <qCom>1</qCom>
                    <vUnCom>100</vUnCom>
                    <vProd>100.00</vProd>
                    <cEANTrib>7898215151784</cEANTrib>
                    <uTrib>UN</uTrib>
                    <qTrib>1</qTrib>
                    <vUnTrib>100</vUnTrib>
                    <indTot>1</indTot>
                </prod>
                <imposto>
                    <ICMS>
                        <ICMSSN500>
                            <orig>0</orig>
                            <CSOSN>500</CSOSN>
                            <vBCSTRet>0.00</vBCSTRet>
                            <vICMSSTRet>0.00</vICMSSTRet>
                        </ICMSSN500>
                    </ICMS>
                    <IPI>
                        <clEnq>99999</clEnq>
                        <cEnq>999</cEnq>
                        <IPINT>
                            <CST>51</CST>
                        </IPINT>
                    </IPI>
                    <PIS>
                        <PISOutr>
                            <CST>99</CST>
                            <vBC>0.00</vBC>
                            <pPIS>0.00</pPIS>
                            <vPIS>0.00</vPIS>
                        </PISOutr>
                    </PIS>
                    <COFINS>
                        <COFINSOutr>
                            <CST>49</CST>
                            <vBC>0.00</vBC>
                            <pCOFINS>0.00</pCOFINS>
                            <vCOFINS>0.00</vCOFINS>
                        </COFINSOutr>
                    </COFINS>
                </imposto>
                <infAdProd>Yeahhh</infAdProd>
            </det>
            <total>
                <ICMSTot>
                    <vBC>100.00</vBC>
                    <vICMS>0.00</vICMS>
                    <vICMSDeson>0.00</vICMSDeson>
                    <vBCST>0.00</vBCST>
                    <vST>0.00</vST>
                    <vProd>100.00</vProd>
                    <vFrete>0.00</vFrete>
                    <vSeg>0.00</vSeg>
                    <vDesc>0.01</vDesc>
                    <vII>0.00</vII>
                    <vIPI>0.00</vIPI>
                    <vPIS>0.00</vPIS>
                    <vCOFINS>0.00</vCOFINS>
                    <vOutro>0.00</vOutro>
                    <vNF>0.00</vNF>
                    <vTotTrib>0.00</vTotTrib>
                </ICMSTot>
            </total>
            <transp>
                <modFrete>9</modFrete>
                <transporta>
                    <CNPJ>10445097000108</CNPJ>
                    <xNome>TRANSPORTADORA TESTE</xNome>
                    <xEnder>RUA RUI BARBOSA</xEnder>
                    <UF>MG</UF>
                </transporta>
                <veicTransp>
                    <placa>GKO0000</placa>
                    <UF>MG</UF>
                    <RNTC>123</RNTC>
                </veicTransp>
            </transp>
        </infNFe>
        <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
            <SignedInfo>
                <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
                <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
                <Reference URI="#NFe31160610445097000108550010111111181517518844">
                    <Transforms>
                        <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                        <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
                    </Transforms>
                    <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
                    <DigestValue>5L7KJC5jZAPhEo/ccr2oLMDdhXQ=</DigestValue>
                </Reference>
            </SignedInfo>
            <SignatureValue>kf8DvIFXpok7DU9rLd8yAcxPkDHlPYHzMetXHDMLIRoEs8Wn6gaWcAKX6tTYHivrQrDEFK603D6j
                qApH+5XkOY7Bd7+x3jGu/wtMqSij3gXwFdIWaX4hQNmF3GSJEe+JVvMZLC48HOgFGyDDLFzuOQ68
                ZWBhyVul96ntWnwTFW3Yq3LLGoHfkp2qF76w3lcWqpGjGdzLmyWq3Lvkjfy0B6+hwB5QmxGRNrET
                R/UskbLlp0ijrRHfoMXgMeyrkFpbMGbsM103TpACWwU776D3rKByxRbVFG5bYmRGU2GwFw0VwC9T
                SaxFbY5H7dCpw6U/sTshegrkGdeUC/Y+nBFk5g==</SignatureValue>
            <KeyInfo>
                <X509Data>
                    <X509Certificate>MIIH+DCCBeCgAwIBAgIIBmcLPIlQdQ4wDQYJKoZIhvcNAQELBQAwdTELMAkGA1UEBhMCQlIxEzAR
                        BgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFs
                        IGRvIEJyYXNpbCAtIFJGQjEZMBcGA1UEAxMQQUMgU0VSQVNBIFJGQiB2MjAeFw0xNTA3MDkxMDMx
                        MDBaFw0xNjA3MDgxMDMxMDBaMIHbMQswCQYDVQQGEwJCUjELMAkGA1UECBMCTUcxFzAVBgNVBAcT
                        DlBBVE9TIERFIE1JTkFTMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMTYwNAYDVQQLEy1TZWNyZXRhcmlh
                        IGRhIFJlY2VpdGEgRmVkZXJhbCBkbyBCcmFzaWwgLSBSRkIxFjAUBgNVBAsTDVJGQiBlLUNOUEog
                        QTExEzARBgNVBAsTCkFSIEtSWVBUT04xLDAqBgNVBAMTI0IyQiBTSVNURU1BUyBMVERBIE1FOjEw
                        NDQ1MDk3MDAwMTA4MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqQtInWusT2dElpOj
                        47tkCJVL49eGQa4kpJJ14QrrlnBTRNgkMCic5c94c0Ilf2URUIViErd6MEhK1i/kmpGxeSqNmZRh
                        gXGulhJraEr1itc03NQxb2PurQsY1shOFZYOFsh762orRj+7HOS7UEYOkst8tn4e/EBrILHypy+c
                        NkA8cbIRhTW/QblfKN/c31D0MfBAZpf0YwFuicWDleBeCCQjK91rWazy9y3MdQb5DnZWRV/B2/21
                        lIOSRlAwDJVpYV4FMHnIBIxl32iyFFPPP1V50G/3qyANuvlLlNJzScKnglK1AgflLXeLoggUOG/s
                        ryk6YNfPx0WszrtpAW+RcQIDAQABo4IDIzCCAx8wgZkGCCsGAQUFBwEBBIGMMIGJMEgGCCsGAQUF
                        BzAChjxodHRwOi8vd3d3LmNlcnRpZmljYWRvZGlnaXRhbC5jb20uYnIvY2FkZWlhcy9zZXJhc2Fy
                        ZmJ2Mi5wN2IwPQYIKwYBBQUHMAGGMWh0dHA6Ly9vY3NwLmNlcnRpZmljYWRvZGlnaXRhbC5jb20u
                        YnIvc2VyYXNhcmZidjIwCQYDVR0TBAIwADAfBgNVHSMEGDAWgBSyoMQ9Rp58yIVsCB4QMpRlRnBB
                        czBxBgNVHSAEajBoMGYGBmBMAQIBDTBcMFoGCCsGAQUFBwIBFk5odHRwOi8vcHVibGljYWNhby5j
                        ZXJ0aWZpY2Fkb2RpZ2l0YWwuY29tLmJyL3JlcG9zaXRvcmlvL2RwYy9kZWNsYXJhY2FvLXJmYi5w
                        ZGYwgfMGA1UdHwSB6zCB6DBKoEigRoZEaHR0cDovL3d3dy5jZXJ0aWZpY2Fkb2RpZ2l0YWwuY29t
                        LmJyL3JlcG9zaXRvcmlvL2xjci9zZXJhc2FyZmJ2Mi5jcmwwRKBCoECGPmh0dHA6Ly9sY3IuY2Vy
                        dGlmaWNhZG9zLmNvbS5ici9yZXBvc2l0b3Jpby9sY3Ivc2VyYXNhcmZidjIuY3JsMFSgUqBQhk5o
                        dHRwOi8vcmVwb3NpdG9yaW8uaWNwYnJhc2lsLmdvdi5ici9sY3IvU2VyYXNhL3JlcG9zaXRvcmlv
                        L2xjci9zZXJhc2FyZmJ2Mi5jcmwwDgYDVR0PAQH/BAQDAgXgMB0GA1UdJQQWMBQGCCsGAQUFBwMC
                        BggrBgEFBQcDBDCBvAYDVR0RBIG0MIGxgR1UUklOREFERUZJU0NBTEBORVRTSVRFLkNPTS5CUqAd
                        BgVgTAEDAqAUExJMVUlTIEFOVE9OSU8gU0lMVkGgGQYFYEwBAwOgEBMOMTA0NDUwOTcwMDAxMDig
                        PQYFYEwBAwSgNBMyMDgwOTE5NzI4MzE0MDIzOTY1MzAwMDAwMDAwMDAwMDAwMDAwME01NDM3Mjk2
                        U1NQTUegFwYFYEwBAwegDhMMMDAwMDAwMDAwMDAwMA0GCSqGSIb3DQEBCwUAA4ICAQC41dzLyT3G
                        H9QBCowC5+KE9GzEr2X8wPmWzNbS98wrd0tC0Pkt5zPixkFJChxZ94hsWM2KB7RTK8s1BycoKBvi
                        S0L3sC5pfWjg6xkWIJ75WpUS2KKSvKzEJhsM+nMWNaoPzwaCpG3OfLjUGZphiAeg9TwZ5MRDLArB
                        rcjmGwcCQn5401I/8obC5Av+2kNvrpYujdvyi3z1dCAl+NQ+M9yGcVHVnkdW3GSDbi8KcT4ETbU0
                        ImopqvkkixnF46tYfWeMPfhmKgrw1t796m3dt+WhJMFUh/4o5VFm3MRvDHhgC1K9O4UsywN4RMlm
                        Jau+NljLZIzgftmubOk2mLx6FGQyccX1hnLHv/dxeyeLXBLlfcPrMGVpAzWCPadI9IDiQXuVToaF
                        aW7eH6e9ghePi4IbtFyz+3/dg2zVNK7YuoU3AYM+K3gmuR82ojgb9v9kyHzeP3WjplBE+xYVnFC2
                        V/ElGFbS/93lgJ0C66oyp6U7kaWmObB+Yg8+bW5tYNeEXsAx+a4+yx32f5gPd3KHV7veN9AGl+0V
                        m9MWdrm1TJKFqZ2JwjTpomdGJBz3OxoiD4vekNbpG5JRsdShCDxE69eKdOFMtZcHqDESfqoBFVtm
                        uOLoAL9z9UZRLi5J/YMAXOgHQd/q1Y1EDWGbtZ6TH4aq4O4zZy9DazWZM6mrB8DbJg==</X509Certificate>
                </X509Data>
            </KeyInfo>
        </Signature>
    </NFe>
    <protNFe versao="3.10">
        <infProt>
            <tpAmb>2</tpAmb>
            <verAplic>14.0.2</verAplic>
            <chNFe>31160610445097000108550010111111181517518844</chNFe>
            <dhRecbto>2016-06-29T12:14:51-03:00</dhRecbto>
            <digVal>5L7KJC5jZAPhEo/ccr2oLMDdhXQ=</digVal>
            <cStat>297</cStat>
            <xMotivo>Rejeicao: Assinatura difere do calculado</xMotivo>
        </infProt>
    </protNFe>
</nfeProc>`

Talvez eu esteja passando alguma informação errada, porém nao localizei ela ainda.

**Comment by fauker** [comment]
Cara, isso geralmente acontece quando você assina o XML e depois o modifica. Também pode ser devido a algum caracter especial ou **espaçamento indevido entre tags (menos provável porque senão daria erro pra todo mundo que usa a lib)**.

Já tive esse problema duas vezes. Na primeira foi caracter especial, na segunda foi assinando o XML e depois alterando algo nele.

**Comment by fincatto** [comment]
Boa noite @damascoa.
Basicamente é o que o @fauker colocou.
Verifique por caracteres inválidos. Preferencialmente tratando a construção da nota.
No caso de estar alterando alguma propriedade antes do envio, o que é bastante improvável, mas possível, faça um teste assinando antes de enviar e use o método para enviar uma nota ja assinada.
É interessante informar também qual a versão da biblioteca que você usou para os testes.
