### ISSUE TITLE
Endereço consulta QR-Code de homologação incorreto  - NFC-e Mato Grosso

### ISSUE THREAD

**Issue by leonhardt** [wmixvideo/nfe#186]
Segue o endereço correto do webservice para consulta de QR-Code NFC-e Mato Grosso

````java
https://homologacao.sefaz.mt.gov.br/nfce/consultanfce
````

**Comment by jefperito** [comment]
Oi, tu tem o site que você obteve essa informação?

**Comment by gabrielbo1** [comment]
Verifiquei também que no NFAutorizador31 não consta os serviços do Mato Grosso.

Segue o link com os endereços dos webservices para NFC-e Mato Grosso:

http://www.sefaz.mt.gov.br/portal/nfce/?pg=cGdJbmZvcm1hY2Fv

**Comment by leonhardt** [comment]
Verifiquei também que no NFAutorizador31 não consta os serviços do Mato Grosso

Segue o link com os endereços dos webservices para NFC-e Mato Grosso

http://www.sefaz.mt.gov.br/portal/nfce/?pg=cGdJbmZvcm1hY2Fv

**Comment by klutzer** [comment]
#187

**Comment by jefperito** [comment]
Resolvido no commit do @klutzer
