### ISSUE TITLE
Problema para cancelar NFe na SVAN

### ISSUE THREAD

**Issue by higomatos** [wmixvideo/nfe#189]
O campo idLote do Schema XML: retEnvEventoCancNFe _v9.99.xsd segundo o Manual do Contribuinte é requerido, com tamanho de 1 a 15 e na descrição informa que ele é o "Identificador de controle do Lote de envio do Evento, conforme informado na mensagem de entrada."

Porém especificamente na SVAN (que atende os estados do MA, PA e PI) este campo está vindo vazio do webservice e ao fazer e ao fazer o bind com a classe NFEnviaEventoRetorno o projeto levanta uma exceção (corretamente) pois o campo está marcado como requerido @Element(name = "idLote", required = true):20

Alterando este campo para não requerido conseguimos utilizar o projeto normalmente porém a documentação prevê que ele deveria ser requerido, logo, ficamos na dúvida de como vocês gostariam que fizéssemos para manter a compatibilidade do projeto com a SVAN mesmo sabendo que este ambiente está em desacordo com a documentação?

Segue abaixo retorno obtido da SVAN:

```
<retEnvEvento xmlns="http://www.portalfiscal.inf.br/nfe" versao="1.00">
    <idLote/>
    <tpAmb>1</tpAmb>
    <verAplic>Serpro.Sped.NFe.Sefaz.Evento_1.0.1</verAplic>
    <cOrgao>53</cOrgao>
    <cStat>128</cStat>
    <xMotivo>Lote de evento processado</xMotivo>
    <retEvento versao="1.00">
        <infEvento Id="ID422160008693146">
            <tpAmb>1</tpAmb>
            <verAplic>Serpro.Sped.NFe.Sefaz.Evento_1.0.1</verAplic>
            <cOrgao>22</cOrgao>
            <cStat>135</cStat>
            <xMotivo>Evento registrado e vinculado a NF-e</xMotivo>
            <chNFe>22160773815060000217550010000002881396616175</chNFe>
            <tpEvento>110111</tpEvento>
            <nSeqEvento>1</nSeqEvento>
            <dhRegEvento>2016-07-05T09:25:19-03:00</dhRegEvento>
            <nProt>422160008693146</nProt>
        </infEvento>
    </retEvento>
</retEnvEvento>
```

**Comment by jefperito** [comment]
Não é a primeira vez que isso acontece! Talvez entrar em contato com o Sefaz responsável? o problema que levam mil anos pra responder...

**Comment by fincatto** [comment]
Talvez o ideal seria colocar um converter, e documentar que o caso ocorre em determinada situação.
Usamos um converter chamado StringNullConverter na classe NFNotaInfoItemProduto, como exemplo.
Se testar, posta pra gente se deu certo.
Att,
Diego

**Comment by rafaelTartigrado** [comment]
Fiz um teste localmente com o xml informado anteriormente e funcionou
perfeitamente.

Diego,

Ao alterar a classe NFEnviaEventoRetorno adicionando o converter eu preciso
criar um teste específico ou o fato de passar nos testes atuais já valida a
alteração?


Rafael Ferreira da Costa
Gerente de TI na empresa Tartigrado
http://www.tartigrado.com
http://blog.tartigrado.com

Em 5 de julho de 2016 22:23, Diego Fincatto <notifications@github.com>
escreveu:

**Comment by fincatto** [comment]
Seria interessante criar um caso de teste com o campo nulo para evitar que
alguém que leia a documentação pense que não necessita do conversor e
tire-o. Com o teste, se alguém tirar o conversor estouraria o teste e o
desenvolvedor seria avisado que é um caso excepcional.

**Comment by fincatto** [comment]
Codigo já integrado ao master.
Obrigado @higomatos e @rafaelTartigrado!
