### ISSUE TITLE
Separação em módulos

### ISSUE THREAD

**Issue by diegolovison** [wmixvideo/nfe#196]
Há a intenção de separa esse projeto em módulos?

Vejo pelo menos 3 deles que iriam auxiliar muito a integração com outros projetos bem como diminuir a quantidade de dependências.

1) Separar o domínio ( acredito que seja o pacote "classes" )
2) Separar os webservices e ter uma implementação default com axis.
3) Projeto base. Assinatura digital, validadores, etc
4) Um projeto tenha os projetos 1, 2, 3

**Comment by jefperito** [comment]
Qual seria o objetivo de "externar" a modularização?

**Comment by fincatto** [comment]
A idéia do projeto é justamente fazer a comunicação (envio/retorno) das notas.
Pra isso, precisamos sempre de todos os projetos e, no nosso ponto de vista, quebrar eles em outros diversos projetos para depois ter que juntar tudo novamente traria uma complexidade a mais para quem irá trabalhar nele.
Mas se houver um bom motivo, podemos separar sim.

**Comment by diegolovison** [comment]
Não gostaria de ter o axis2 no meu projeto. Logo a separação do pacote "classes" em outro projeto ajudaria.

Existem classes utilitária que poderiam ser facilmente utilizadas em outros projetos não relacionados ao nfe. Assinatura da request, geração do cacerts, entre outras.

A separação em módulos não muda ou gera complexidade para quem quer fazer a comunicação (envio/retorno) das notas.

Poderíamos ter sub-módulos e um módulo pai com as dependências.

**Comment by jefperito** [comment]
Na minha opinião não sei se muitas pessoas ganhariam com essas alterações, talvez poderia ser avaliado mais para frente, pois tem outras funcionalidades que acho de maior prioridade e beneficio para todos.

**Comment by fincatto** [comment]
@klutzer, acho que, com o advento da danfe no projeto, podemos fazer essa separação com ganhos reais, não? Vamos separar a geração da danfe em um submodulo maven para agilizar a liberação?

**Comment by klutzer** [comment]
Podemos separar, porém tanto a classe que gera a DANF-e (NFDanfeReport) quanto o próprio layout atual da DANF-e NFC-e dependem da NFNotaProcessada e suas demais, portanto, se a gente separar, temos que externalizar as classes de negócio do projeto também
