### ISSUE TITLE
Validação do NCM

### ISSUE THREAD

**Issue by henriquebartoski** [wmixvideo/nfe#197]
Bom dia.
Atualmente nosso sistema permite utilizar o NCM dos produtos com o valor "00000000", o que é aceito pelo sefaz. Estou fazendo a migração para o uso da biblioteca nfe e passei a obter o erro de validação "NCM fora do padrao (00000000)".

É viável a alteração da validação para permitir o uso do "00000000" ou alguém sabe uma forma de contornar a situação?

**Comment by jefperito** [comment]
As validações são feitas de acordo com o padrão da documentação oficial, se é permitido pela doc e não atende é bug.

a expressão regular do NCM no XSD está diferente o que está implementado no java.

XSD:
[0-9]{2}|[0-9]{8}
Java:
[0-9]{2}|[0][1-9][0-9]{6}|[1-9][0-9]{7}

Parece que ficou menos restritivo o valor de NCM.
Deve ser atualizado para o XSD.

**Comment by jefperito** [comment]
Subi essa alteração para o master, se você puder utilizar a versão em snapshot e verificar se isso funciona e dar o feedback, seria de grande ajuda!

**Comment by henriquebartoski** [comment]
Funcionou! Obrigado @jefperito
