### ISSUE TITLE
Mesclar SVAN com SVRS no Piauí

### ISSUE THREAD

**Issue by higomatos** [wmixvideo/nfe#198]
Infelizmente o estado do Piauí além de não desenvolver os webservices fez dois convênios sendo um com a SVAN e outro com a SVRS sendo que para a emissão de NF-e a SEFAZ-PI utiliza a SVAN (http://hom.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=) e para a emissão de NFC-e a SEFAZ-PI utiliza a SVRS (http://www.sefaz.pi.gov.br/index.php/informacoes/imprensa/noticias/noticias-em-destaque/-novos-ambientes-de-autorizacao-de-documentos-na-receita-estadual-do-rs)

Eu entendo que a classe NFAutorizador31 não permite mesclarmos estas duas autorizadoras para uma mesma Unidade Federativa então pergunto como deveremos refatorar a classe para atender esta realidade? A maneira mais simples seria apenas criar no _enum_ a opção PI e mesclar as URL`s mas não sei se isto está de acordo com a organização do projeto.

Aguardo retorno.

**Comment by fincatto** [comment]
Boa noite @higomatos.
A solução de criar um item no enum PI mesclando as URLs de busca me parece a mais apropriada para o caso.
Att,
DF

**Comment by rafaelTartigrado** [comment]
#213

**Comment by fincatto** [comment]
O PR enviado está em conflito com o código atual.
Att,
DF

**Comment by rafaelTartigrado** [comment]
Vou verificar.

**Comment by rafaelTartigrado** [comment]
#214

**Comment by fincatto** [comment]
Bom dia Rafael.
A alteração quebrou um teste, está falhando no travis. Podes dar uma olhada?
Abraços.

**Comment by rafaelTartigrado** [comment]
#217
