### ISSUE TITLE
Consulta Cadastro ES (Espírito Santo)

### ISSUE THREAD

**Issue by edivaldoms** [wmixvideo/nfe#210]
Endereço para consultar cadastro no ES (Espírito Santo)
O endereço abaixo pode ser utilizado em homologação como produção:
https://app.sefaz.es.gov.br/ConsultaCadastroService/CadConsultaCadastro2.asmx

Fonte:
http://internet.sefaz.es.gov.br/informacoes/nfe/ws_consulta_cadastro.php

**Comment by fincatto** [comment]
Favor enviar PR.
