### ISSUE TITLE
Envio de lote - primeiros passos - como obter status do envio

### ISSUE THREAD

**Issue by gestefane** [wmixvideo/nfe#215]
Ambiente: Homologação;

Ao enviar um lote para testes recebo no final dos logs a mensagem "103 - Lote recebido com sucesso".

Entretanto o lote não é registrado, pois ao realizar uma consulta pela chave diretamente no site da sefaz é retornada a informação de que a nota não está na base da sefaz.

Sei que alguma falha no xml enviado está ocorrendo e gerando uma rejeição do lote. Porém pelos logs não consigo identificar o motivo da rejeição.

Implementei um método para consulta de lote que está retornando "null" para a mensagem de retorno e para a chave.

Colocando o breakpoint no código é possível ver o conteúdo do retorno da consulta abaixo
`<retConsReciNFe versao="3.10" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>2</tpAmb><verAplic>NFEPE_H_15.05.02.106</verAplic><nRec>0</nRec><cStat>215</cStat><dhRecbto>2016-08-20T14:43:05-03:00</dhRecbto><xMotivo>Rejeição: Falha no esquema XML</xMotivo><cUF>26</cUF></retConsReciNFe>`

Seguem os códigos de envio e de consulta:

Envio:
`	public void enviarLoteNfe() throws Exception {
		NfeConfigTeste config = new NfeConfigTeste();

			System.out.println("Gerando Nota Fiscal de Homologação"); 
			System.out.println("Gerou Variavel Lote"); 
			NFLoteEnvio lote = new NFLoteEnvio(); 
			System.out.println("Adicionou Nota no Lote");
			List<NFNota> lstNF = new ArrayList<NFNota>();

			NFEndereco emitenteEndereco = new NFEndereco();
		    emitenteEndereco.setLogradouro("RUA ASDBFASDFK KASDF");
		    emitenteEndereco.setNumero("35");
		    emitenteEndereco.setComplemento("LJ 10");
		    emitenteEndereco.setBairro("CENTRO");
		    emitenteEndereco.setCodigoMunicipio("2611606");
		    emitenteEndereco.setDescricaoMunicipio("RECIFE");
		    emitenteEndereco.setUf(NFUnidadeFederativa.valueOfCodigo("PE"));
		    emitenteEndereco.setCep("50070020");
		    emitenteEndereco.setCodigoPais("1058");
		    emitenteEndereco.setDescricaoPais("BRASIL");
		    emitenteEndereco.setTelefone("3134123493");
			
			NFNotaInfoEmitente emitente = new NFNotaInfoEmitente();
		 	emitente.setCnpj("AQUI VEM O CNPJ CORRETO"); // 
		    emitente.setRazaoSocial("NOME EMPRESA LTDA");
		    emitente.setNomeFantasia("EMPRESA");
		    emitente.setEndereco(emitenteEndereco);
		    emitente.setInscricaoEstadual("AQUI VEM A IE");
		    emitente.setRegimeTributario(NFRegimeTributario.valueOfCodigo("1"));			
		    
			
			NFEndereco destinatarioEndereco = new NFEndereco();
			destinatarioEndereco.setLogradouro("RUA BKSJDFH KASDF");
			destinatarioEndereco.setNumero("350");
			destinatarioEndereco.setComplemento("LJ 11");
			destinatarioEndereco.setBairro("CENTRO");
			destinatarioEndereco.setCodigoMunicipio("2611606");
			destinatarioEndereco.setDescricaoMunicipio("RECIFE");
			destinatarioEndereco.setUf(NFUnidadeFederativa.valueOfCodigo("PE"));
			destinatarioEndereco.setCep("32535510");
			destinatarioEndereco.setCodigoPais("1058");
			destinatarioEndereco.setDescricaoPais("BRASIL");
			destinatarioEndereco.setTelefone("2211123344");

			NFNotaInfoDestinatario destinatario = new NFNotaInfoDestinatario();
			destinatario.setCnpj("AQUI VEM O CNPJ CORRETO");
			destinatario.setRazaoSocial("NOME DO DESTINATARIO");
			destinatario.setEndereco(destinatarioEndereco);
			destinatario.setIndicadorIEDestinatario(NFIndicadorIEDestinatario.valueOfCodigo("9")); // nao contribuinte
			destinatario.setEmail("teste@teste.com.br");
			
		    NFNotaInfoIdentificacao identificacao = new NFNotaInfoIdentificacao();
		    identificacao.setUf(NFUnidadeFederativa.valueOfCodigo("PE"));
		    identificacao.setCodigoRandomico(getChave().substring(35, 43)); // aqui
		    identificacao.setNaturezaOperacao("VENDA");
		    identificacao.setFormaPagamento(NFFormaPagamentoPrazo.valueOfCodigo("0"));
		    identificacao.setModelo(NFModelo.valueOfCodigo("55"));
		    identificacao.setSerie("1");
		    identificacao.setNumeroNota(getNumeroNota()); // aqui
		    identificacao.setDataHoraEmissao(new DateTime());
		    identificacao.setDataHoraSaidaOuEntrada(new DateTime());
		    identificacao.setTipo(NFTipo.valueOfCodigo("1"));
		    identificacao.setIdentificadorLocalDestinoOperacao(NFIdentificadorLocalDestinoOperacao.valueOfCodigo("1")); // op. interna
		    identificacao.setCodigoMunicipio("2611606");
		    identificacao.setTipoImpressao(NFTipoImpressao.valueOfCodigo("1")); // retrato
		    identificacao.setTipoEmissao(NFTipoEmissao.valueOfCodigo("1")); // normal
		    identificacao.setDigitoVerificador(1);
		    identificacao.setAmbiente(NFAmbiente.valueOfCodigo("2")); // homologacao
		    identificacao.setFinalidade(NFFinalidade.valueOfCodigo("1")); // normal
		    identificacao.setOperacaoConsumidorFinal(NFOperacaoConsumidorFinal.valueOfCodigo("1")); // 1 -> cosumidor = S
		    identificacao.setIndicadorPresencaComprador(NFIndicadorPresencaComprador.valueOfCodigo("3")); // Teleatendimento
		    identificacao.setProgramaEmissor(NFProcessoEmissor.valueOfCodigo("0")); // Aplicativo do contribuinte
		    identificacao.setVersaoEmissor("1.0");
		    
			NFNotaInfo info = new NFNotaInfo();
			
			info.setIdentificador(getChave()); // aqui
			info.setVersao(new BigDecimal("3.10"));
			info.setIdentificacao(identificacao);
			info.setEmitente(emitente);
			info.setDestinatario(destinatario);
			
			

			NFNotaInfoItem item = new NFNotaInfoItem();
		    item.setNumeroItem(1);

		    NFNotaInfoItemProduto produto = new NFNotaInfoItemProduto();
		    produto.setCodigo("1");
		    produto.setCodigoDeBarras("7896102819014");
		    produto.setDescricao("MARGARINA JR SEM SAL - 10GR/192UN");
		    produto.setNcm("15171000");
		    produto.setCfop("5102");
		    produto.setUnidadeComercial("CX");
		    produto.setQuantidadeComercial(new BigDecimal("1.00"));
		    produto.setValorUnitario(new BigDecimal("1.00"));
		    produto.setValorTotalBruto(new BigDecimal("1.00"));
		    produto.setCodigoDeBarrasTributavel("7896102819014");
		    produto.setUnidadeTributavel("CX");
		    produto.setQuantidadeTributavel(new BigDecimal("1.00"));
		    produto.setValorUnitarioTributavel(new BigDecimal("1.00"));
		    
		    
		    produto.setCampoeValorNota(NFProdutoCompoeValorNota.SIM);
		    
		    
		    
		    NFNotaInfoItemImposto imposto = new NFNotaInfoItemImposto();
		    
		    NFNotaInfoItemImpostoICMS icms = new NFNotaInfoItemImpostoICMS();
		    
		    NFNotaInfoItemImpostoICMSSN500 icmssn500 = new NFNotaInfoItemImpostoICMSSN500();
		    icmssn500.setOrigem(NFOrigem.valueOfCodigo("0")); // nacional
		    icmssn500.setSituacaoOperacaoSN(NFNotaSituacaoOperacionalSimplesNacional.valueOfCodigo("500"));

		    icms.setIcmssn500(icmssn500);
		    		    
		    
		    imposto.setValorTotalTributos(new BigDecimal("0.00"));
		    imposto.setIcms(icms);
		    
		    
		    NFNotaInfoItemImpostoIPI ipi = new NFNotaInfoItemImpostoIPI();
		    ipi.setCodigoEnquadramento("999");

		    NFNotaInfoItemImpostoIPITributado ipiTributado = new NFNotaInfoItemImpostoIPITributado();
		    ipiTributado.setPercentualAliquota(new BigDecimal("0.00"));
		    ipiTributado.setValorBaseCalculo(new BigDecimal("0.00"));
		    ipiTributado.setValorTributo(new BigDecimal("0.00"));
		    ipiTributado.setSituacaoTributaria(NFNotaInfoSituacaoTributariaIPI.valueOfCodigo("99"));
		    ipi.setTributado(ipiTributado);
		    
		    imposto.setIpi(ipi);

		    NFNotaInfoItemImpostoPISNaoTributado pis = new NFNotaInfoItemImpostoPISNaoTributado();
		    pis.setSituacaoTributaria(NFNotaInfoSituacaoTributariaPIS.valueOfCodigo("08"));
		    
		    
		    NFNotaInfoItemImpostoCOFINSNaoTributavel cofins = new NFNotaInfoItemImpostoCOFINSNaoTributavel();
		    cofins.setSituacaoTributaria(NFNotaInfoSituacaoTributariaCOFINS.valueOfCodigo("08"));

		    

		    item.setProduto(produto);
		    item.setImposto(imposto);
		    
		    item.setInformacoesAdicionais("informacoes adicionais");
			
			List<NFNotaInfoItem> itens = new ArrayList<NFNotaInfoItem>();
			
			itens.add(item);
			
			info.setItens(itens);
			
			NFNotaInfoICMSTotal icmsTotal = new NFNotaInfoICMSTotal();
		    icmsTotal.setBaseCalculoICMS(new BigDecimal("0.00"));
		    icmsTotal.setValorTotalICMS(new BigDecimal("0.00"));
		    icmsTotal.setValorICMSDesonerado(new BigDecimal("0.00"));
		    icmsTotal.setValorICMSFundoCombatePobreza(new BigDecimal("0.00"));
		    icmsTotal.setValorICMSPartilhaDestinatario(new BigDecimal("0.00"));
		    icmsTotal.setValorICMSPartilhaRementente(new BigDecimal("0.00"));
		    icmsTotal.setBaseCalculoICMSST(new BigDecimal("0.00"));
		    icmsTotal.setValorTotalICMSST(new BigDecimal("0.00"));
		    icmsTotal.setValorTotalDosProdutosServicos(new BigDecimal("1.00"));
		    icmsTotal.setValorTotalFrete(new BigDecimal("0.00"));
		    icmsTotal.setValorTotalSeguro(new BigDecimal("0.00"));
		    icmsTotal.setValorTotalDesconto(new BigDecimal("0.00"));
		    icmsTotal.setValorTotalII(new BigDecimal("0.00"));
		    icmsTotal.setValorTotalIPI(new BigDecimal("0.00"));
		    icmsTotal.setValorPIS(new BigDecimal("0.00"));
		    icmsTotal.setValorCOFINS(new BigDecimal("0.00"));
		    icmsTotal.setOutrasDespesasAcessorias(new BigDecimal("0.00"));
		    icmsTotal.setValorTotalNFe(new BigDecimal("1.00"));
		    icmsTotal.setValorTotalTributos(new BigDecimal("0.00"));
			
			NFNotaInfoTotal total = new NFNotaInfoTotal();
		    total.setIcmsTotal(icmsTotal);
			
			info.setTotal(total);
			
			NFNotaInfoTransporte transporte = new NFNotaInfoTransporte();

			transporte.setModalidadeFrete(NFModalidadeFrete.valueOfCodigo("0"));

			
			info.setTransporte(transporte);
			
			
			NFNota nota = new NFNota();
			
			nota.setIdentificadorLocal(3106200);
			nota.setInfo(info);

			lstNF.add(nota); 
			lote.setNotas(lstNF); 
			System.out.println("Configura dados Lote, Versao, nrlote");
			lote.setIdLote(getNumeroNota());
			lote.setVersao("3.10");
			lote.setIndicadorProcessamento(NFLoteIndicadorProcessamento.PROCESSAMENTO_ASSINCRONO);

			NFLoteEnvioRetornoDados retorno = new WSFacade(config).enviaLote(lote);

			System.out.println(retorno.getRetorno());
			System.out.println(retorno.getRetorno().getStatus());
			System.out.println(retorno.getRetorno().getMotivo()); 
		
	}
`
Consulta:
`	public void consultarLoteNfe() throws Exception {
		NfeConfigTeste config = new NfeConfigTeste();

		try {

			NFLoteConsultaRetorno retorno;
			retorno = new WSFacade(config).consultaLote(getNumeroNota(), NFModelo.NFE); // aqui uso o numero da nota como numero de lote apenas por comodidade

			System.out.print("Mensagem: "); 
			System.out.println(retorno.getMensagem());

			System.out.print("Chave de Acesso: "); 
			System.out.print(retorno.getProtocolos().get(0).getProtocoloInfo().getChave()); 
			System.out.print("Protocolo: "); 
			System.out.print(retorno.getProtocolos().get(0).getProtocoloInfo().getNumeroProtocolo());
		}
			catch (Exception e){
			System.out.println(e.getMessage());
		}
			
	}
`

**Comment by klutzer** [comment]
Pelo que vi aqui você está consultando o lote pelo número da nota, e não pelo recibo..
```java
NFLoteConsultaRetorno retc = facade.consultaLote(retorno.getInfoRecebimento().getRecibo(), NFModelo.NFE);
for (NFProtocolo prot : retc.getProtocolos()) {
	System.out.println("Chave: "+prot.getProtocoloInfo().getChave());
	System.out.println("Número Protocolo: "+prot.getProtocoloInfo().getNumeroProtocolo());
	System.out.println("Status: "+prot.getProtocoloInfo().getStatus());
	System.out.println("Motivo: "+prot.getProtocoloInfo().getMotivo());
}
```

**Comment by gestefane** [comment]
Implementando o código que o Klutzer sugeriu logo após o envio do lote o problema fica resolvido e os motivos da rejeição são exibidos.

Obrigado Klutzer!
