### ISSUE TITLE
Endereço do site da UF da Consulta via QR-Code - Goiás

### ISSUE THREAD

**Issue by RamonKenedy** [wmixvideo/nfe#225]
Desde ontem (15/09/2016) começou a ocorrer o erro ao emitir NFCe : "Endereço do site da UF da Consulta via QR-Code diverge do previsto".
Verificando no site do sefaz de Goiás, as URLs que devem ser informadas na tag qrcode são as seguintes:
Homologação: http://homolog.sefaz.go.gov.br/nfeweb/sites/nfce/danfeNFCe
Produção: http://nfe.sefaz.go.gov.br/nfeweb/sites/nfce/danfeNFCe​
Através deste link é possível verificar: http://www.nfe.go.gov.br/post/ver/213930/a-sefaz-goias-disponibiliza-a-consulta-da-nota-fiscal-eletronica-do-consumidor---nfc-e-por-qr-code
Se possível, realizar a alteração dessas URLs no projeto.
Obrigado!

**Comment by fincatto** [comment]
Bom dia @RamonKenedy.
Consegue enviar um PR?
Att,
DF

**Comment by RamonKenedy** [comment]
Bom dia @fincatto !
Desculpa a demora para responder!
Eu não tenho experiencia com o github, uso o Assembla.
Pelo que vi para criar uma Pull request é necessário um outro branch para fazer a comparação.
A alteração que fiz foi no enum NFUnidadeFederativa, alterei a linha
de:
GO("GO", "Goi\u00e1s", "52", "http://homolog.sefaz.go.gov.br/nfeweb/sites/nfce/danfeNFCe", "http://nfe.sefaz.go.gov.br/nfeweb/sites/nfce/danfeNFCe"),
para:
GO("GO", "Goi\u00E1s", "52", "http://homolog.sefaz.go.gov.br/nfeweb/jsp/ConsultaDANFENFCe.jsf", "http://nfe.sefaz.go.gov.br/nfeweb/jsp/ConsultaDANFENFCe.jsf"),
Esta funcionando depois que fiz essa alteração, consigo enviar a NFC-e sem receber o erro "Endereço do site da UF da Consulta via QR-Code diverge do previsto".
Obrigado!

**Comment by fincatto** [comment]
Já adicionado ao projeto!

**Comment by RamonKenedy** [comment]
Obrigado!

**Comment by RamonKenedy** [comment]
Bom dia @fincatto !
Verifiquei que nos últimos commits foi ajustado URL de NFCe do RJ, porem a de Goiás não foi alterada!
Como vc informou que foi adicionado ao projeto, estou te informando para que quando possivel possa efetuar essa alteração!
Obrigado!

**Comment by fincatto** [comment]
Olá @RamonKenedy.
Creio que tenha sido alterada sim, veja: https://github.com/wmixvideo/nfe/blob/master/src/main/java/com/fincatto/nfe310/classes/NFUnidadeFederativa.java

**Comment by RamonKenedy** [comment]
Peço desculpas @fincatto , fui verificar e no comentário do dia 5 de outubro eu troquei as URLs, era o contrario, foi falta de atenção minha.
A URLs que devem ser informadas na tag qrcode são as seguintes:
Homologação: http://homolog.sefaz.go.gov.br/nfeweb/sites/nfce/danfeNFCe
Produção: http://nfe.sefaz.go.gov.br/nfeweb/sites/nfce/danfeNFCe​

Link do Sefaz para verificação:
http://www.nfe.go.gov.br/post/ver/213930/a-sefaz-goias-disponibiliza-a-consulta-da-nota-fiscal-eletronica-do-consumidor---nfc-e-por-qr-code

Mais uma vez, obrigado e desculpa pelo transtorno.

**Comment by emersonat** [comment]
Poderiam de tirar desses emails. 

at 

Em 03/12/2016 10:40, Diego Fincatto escreveu: 

> Olá @RamonKenedy [1].
> Creio que tenha sido alterada sim, veja: https://github.com/wmixvideo/nfe/blob/master/src/main/java/com/fincatto/nfe310/classes/NFUnidadeFederativa.java [2] 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [3], or mute the thread [4].
 

Links:
------
[1] https://github.com/RamonKenedy
[2]
https://github.com/wmixvideo/nfe/blob/master/src/main/java/com/fincatto/nfe310/classes/NFUnidadeFederativa.java
[3] https://github.com/wmixvideo/nfe/issues/225#issuecomment-264637027
[4]
