### ISSUE TITLE
Tipo de campo assinatura na classe NFEventoCancelamento 

### ISSUE THREAD

**Issue by edivaldoms** [wmixvideo/nfe#226]
`com.fincatto.nfe310.classes.evento.cancelamento.NFEventoCancelamento

@Element(name = "Signature", required = false)
private String assinatura; //(Como está)

@Element(name = "Signature", required = false)
private NFSignature assinatura; //(Não deveria ser tipo NFSignature? Pois não estou conseguindo parsear.)`

**Comment by edivaldoms** [comment]
Quando tento parsear lança a seguinte Exception: "java.lang.IllegalArgumentException: Nao foi possivel parsear o xml: Element 'SignedInfo' does not have a match in class com.fincatto.nfe310.classes.evento.cancelamento.NFEventoCancelamento at line 1"

**Comment by fincatto** [comment]
Bom dia @edivaldoms.
Em qual dos endpoints você está tendo esse erro?
Att,
DF
