### ISSUE TITLE
Falta campos nProt e xJust nos eventos ao consultar nota cancelada.

### ISSUE THREAD

**Issue by edivaldoms** [wmixvideo/nfe#228]
Ao consultar nota que está cancelada retorna  seguinte:

```
<detEvento versao="1.00">
  <descEvento>Cancelamento</descEvento>
</detEvento>
```

Mas deveria retornar: 

```
<detEvento versao="1.00">
  <descEvento>Cancelamento</descEvento>
  <nProt>999999999999999</nProt>
  <xJust>Motivo do cancelamento</xJust>
</detEvento>
```

Creio que a correção disso seria incluir os campos na classe: com.fincatto.nfe310.classes.evento.NFTipoEvento

```
...
@Element(name = "nProt", required = false)
private String nProt;
@Element(name = "xJust", required = false)
private String justificativa;
```

**Comment by edivaldoms** [comment]
Alterei os seguintes arquivos e funcionou da forma que eu precisava:
`package com.fincatto.nfe310.classes.evento;

import com.fincatto.nfe310.classes.NFBase;
import com.fincatto.nfe310.validadores.BigDecimalParser;
import com.fincatto.nfe310.validadores.StringValidador;
import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;

import java.math.BigDecimal;

@Root(strict = false)
public class NFTipoEvento extends NFBase {

  @Attribute(name = "versao", required = true)
  private String versao;

  @Element(name = "descEvento", required = true)
  private String descricaoEvento;

  // Carta correcao
  @Element(name = "xCorrecao", required = false)
  private String textoCorrecao;

  @Element(name = "xCondUso", required = false)
  private String condicaoUso;

  //::Edivaldo:: Cancelamento: precisa dos campos nProt e xJust para pegar o retorno da consulta da NFe
  @Element(name = "nProt", required = false)
  private String protocoloAutorizacao;

  @Element(name = "xJust", required = false)
  private String justificativa;

  public void setVersao(final BigDecimal versao) {
    this.versao = BigDecimalParser.tamanho5Com2CasasDecimais(versao, "Versao");
  }

  public void setDescricaoEvento(final String descricaoEvento) {
    StringValidador.tamanho5a60(descricaoEvento, "Descricao do Evento");
    this.descricaoEvento = descricaoEvento;
  }

  public String getDescricaoEvento() {
    return this.descricaoEvento;
  }

  public String getVersao() {
    return this.versao;
  }

  public void setCondicaoUso(final String condicaoUso) {
    this.condicaoUso = condicaoUso;
  }

  public void setTextoCorrecao(final String textoCorrecao) {
    this.textoCorrecao = textoCorrecao;
  }

  public String getCondicaoUso() {
    return this.condicaoUso;
  }

  public String getTextoCorrecao() {
    return this.textoCorrecao;
  }

  public void setJustificativa(final String justificativa) {
    StringValidador.tamanho15a256(justificativa, "Justificativa");
    this.justificativa = justificativa;
  }

  public void setProtocoloAutorizacao(final String protocoloAutorizacao) {
    StringValidador.exatamente15N(protocoloAutorizacao, "Protocolo de Autorizacao");
    this.protocoloAutorizacao = protocoloAutorizacao;
  }

  public String getJustificativa() {
    return this.justificativa;
  }

  public String getProtocoloAutorizacao() {
    return this.protocoloAutorizacao;
  }
}
`
`package com.fincatto.nfe310.classes.evento.cancelamento;


import com.fincatto.nfe310.classes.evento.NFTipoEvento;

public class NFInfoCancelamento extends NFTipoEvento {
  /** ::Edivaldo::  Este trecho foi eliminado daqui e passado para  classe: NFTipoEvento
  @Element(name = "nProt", required = true)
    private String protocoloAutorizacao;

    @Element(name = "xJust", required = true)
    private String justificativa;

    public void setJustificativa(final String justificativa) {
        StringValidador.tamanho15a256(justificativa, "Justificativa");
        this.justificativa = justificativa;
    }

    public void setProtocoloAutorizacao(final String protocoloAutorizacao) {
        StringValidador.exatamente15N(protocoloAutorizacao, "Protocolo de Autorizacao");
        this.protocoloAutorizacao = protocoloAutorizacao;
    }

    public String getJustificativa() {
        return this.justificativa;
    }

    public String getProtocoloAutorizacao() {
        return this.protocoloAutorizacao;
    }
    */

    @Override
    public void setCondicaoUso(final String condicaoUso) {
        throw new UnsupportedOperationException("Evento de cancelamento nao possui condicao de uso");
    }

    @Override
    public void setTextoCorrecao(final String textoCorrecao) {
        throw new UnsupportedOperationException("Evento de cancelamento nao possui texto de correcao");
    }
}`

**Comment by fincatto** [comment]
Olá @edivaldoms.
Consegue nos mandar um PR com sua modificação, juntamente com alguns testes unitários com a prova e solução do problema?
Att,
DF

**Comment by edivaldoms** [comment]
Olá @fincatto! Desculpe a demora e por não ter enviado ainda, mas estou mudando de casa e cidade e projetos e está um pouco corrido. Ainda pretendia fazer mais testes e analisar mais o código.

Mas ao tentar enviar o que já fiz aqui o Git retornou o seguinte erro: "not permitted"

**Comment by fincatto** [comment]
Você mandou um PR ou tentou fazer o merge direto?
Att,
DF

2016-09-26 13:59 GMT-03:00 edivaldoms <notifications@github.com>:

**Comment by edivaldoms** [comment]
Eu troquei a versão do meu Netbeans de 7.1 para 8.1 e alterou o menu de opções do Git que estava acostumado que também era em inglês.

Mas o comando que eu dei via Netbeans foi o seguinte:
Selecionei o projeto, no menu de opções Git -> Remoto -> Enviar para Upstream: no console gerou o seguinte:
git push https://github.com/wmixvideo/nfe.git refs/heads/master:refs/heads/master

Sabe se é isso mesmo?

**Comment by edivaldoms** [comment]
Desculpe @fincatto consegui me achar nesse novo Netbeans.

Criei
https://github.com/wmixvideo/nfe/pull/233

**Comment by fincatto** [comment]
Adicionado. Obrigado @edivaldoms!
