### ISSUE TITLE
Sugiro adicionar as anotações Root e Namespace na classe NFProtocoloEvento

### ISSUE THREAD

**Issue by edivaldoms** [wmixvideo/nfe#229]
Quando fui utilizar o XML gerado em outro sistema que utiliza a biblioteca JAXB ao fazer unmarshal do arquivo apresentou um erro.

Antes:

```
public class NFProtocoloEvento extends NFBase {
...
}
```

Depois:

```
@Root(name = "procEventoNFe") /*::Edivaldo:: adicionado o Root*/
@Namespace(reference = "http://www.portalfiscal.inf.br/nfe") /*::Edivaldo:: adicionado o Namespace*/
public class NFProtocoloEvento extends NFBase {
...
}
```

Ainda não testei, mas acredito que deve-se colocar a anotação @Namespace no atributo NFNota nota também, pois ficará igual ao XML que o emissor gratuito gera. 

```
@Root(name = "nfeProc")
@Namespace(reference = "http://www.portalfiscal.inf.br/nfe")
public class NFNotaProcessada extends NFBase {

    @Attribute(name = "versao")
    private String versao;

    @Element(name = "NFe")
    @Namespace(reference = "http://www.portalfiscal.inf.br/nfe") /*::Edivaldo:: testar futuramento este Namespace*/
    private NFNota nota;
...
}
```

**Comment by edivaldoms** [comment]
Com isso ao enviar os XMLs para o cliente/destinatário não haverá problemas de compatibilidade com as bibliotecas JAXB caso ele venha utilizar.

**Comment by fincatto** [comment]
Olá @edivaldoms.
Consegue nos mandar um PR?
Att,
DF
