### ISSUE TITLE
Como funciona a questão do certificado digital na web?

### ISSUE THREAD

**Issue by robertorp** [wmixvideo/nfe#230]
Digo como funciona a questão do certificado digital na web?

Pelo que entendi é, você faz o upload do certificado digital do cliente para o servidor, salva ele em alguma pasta /cnpjCliente/Certificado.pfx
Quando for transmitir, transmite usando o caminho.

É isso mesmo? 
Obg.

**Comment by fauker** [comment]
Você salva o certificado do cliente em algum diretório ou banco de dados, e na hora que precisar dele, basta carrega-lo. 👍

**Comment by fincatto** [comment]
Para deixar da forma mais dinamica possivel, o sistema espera que o certificado venha da classe de configuração: https://github.com/wmixvideo/nfe#como-usar.
Você precisa fazer essa classe retornar seu certificado carregado. 
Você pode armazená-lo da forma que quiser.
Att,
DF
