### ISSUE TITLE
Valor de CEP não é obrigatório para Destinatário

### ISSUE THREAD

**Issue by brunohpg** [wmixvideo/nfe#234]
Olá,

o campo de CEP está como obrigatório na classe NFEndereco.
Entretanto, o CEP é obrigatório para emitente, mas não é obrigatório para destinatário.

Estou recuperando notas fiscais geradas por outro software. No meu caso o destinatário da NF-e não possui o CEP cadastrado no XML, então não consigo gerar o objeto NFNotaProcessada.

Por compatibilidade, acredito que a solução seria fazer validação do CEP apenas ao gerar o XML.
Outra possibilidade é tornar NFEndereco uma interface, e criar um objeto específico para cada endereço (emitente e destinatário), com validações de tipos de objetos no métodos setters.

**Comment by fincatto** [comment]
Boa tarde @brunohpg.
Consegue gerar um PR com a alteração?
Creio que, para simplificar, deixar o a validação na geração do XML funcionaria melhor.
[]s
