### ISSUE TITLE
Passo a Passo

### ISSUE THREAD

**Issue by LeonardoMoraes1989** [wmixvideo/nfe#236]
Oi Pessoal, boa noite,

Tenho um sistema web que alguns clientes usam, dai, surgiu a necessidade de emitir NFe, pesquisei bastante os projetos atuais e gostei bastante desse projeto.
Alguém pode me ajudar com um passo a passo, por onde começar e etc?
Minha aplicação roda num servidor em Linux na amazon, a idéia inicial era poder pegar o certificado instalado na maquina do cliente e usar para assinar e transmitir os XMLs para o SEFAZ.
Outra coisa que tenho dúvida, é como faço para acoplar o projeto ao meu projeto atual, desenvolvi usando maven 3, ja existe alguma solução?

Se possível, gostaría de com esse post, criar um manual pros próximos usuários.
Muito obrigado,

**Comment by fincatto** [comment]
Por favor, antes de perguntar, leia o readme do projeto!
