### ISSUE TITLE
Rejeição 813 (NFC-e)

### ISSUE THREAD

**Issue by klutzer** [wmixvideo/nfe#237]
Bom dia pessoal!

Alguém está passando por este erro ao tentar mandar uma NFC-e (modelo 65) em homologação?

> 813 - Rejeicao: QR-Code com sequencia de escape para o e-comercial. Usar CDATA

Consegui algumas informações sobre este erro aqui:
http://www.oobj.com.br/bc/article/rejei%C3%A7%C3%A3o-813-qr-code-com-sequ%C3%AAncia-de-escape-para-o-e-comercial-usar-cdata-como-resolver-450.html
Porém este erro começou a acontecer hoje, mesmo sem mudança nenhuma na biblioteca. Conferi o XML enviado e ele está de acordo (com CDATA e sem caractere de escape '&amp;')

Obs.: Esta rejeição ocorre apenas em ambiente de homologação.

Alguém que emite NFC-e está passando por este problema também?

**Comment by rafaelTartigrado** [comment]
@klutzer estou passando pelo mesmo erro, você já iniciou alguma solução?

**Comment by rafaelTartigrado** [comment]
Vi que existe uma Nota Técnica 2015/002 que trata deste assunto.
[NT_2015_002_v141 (23-08-2016).pdf](https://github.com/wmixvideo/nfe/files/501628/NT_2015_002_v141.23-08-2016.pdf)

**Comment by higomatos** [comment]
Parece mais um erro no webservice, a regra está sendo cumprida conforme informado na Nota Técnica:

Nota 3: O caractere “&” é um caractere reservado do XML, portanto não pode aparecer no conteúdo da tag. Para viabilizar a informação do QR-Code, o conteúdo deste campo deve ser informado como: <![CDATA[texto]]>
Exemplo:<![CDATA[https://www.sefaz.rs.gov.br/NF CE/NFCE- COM.aspx?chNFe=4315010828769300015765101 0000000971000001251&nVersao=100&tpAmb=2&c Dest=99999999000191&dhEmi=323031352d30312 d32305431373a30303a34392d30323a3030&vNF= 1.00&vICMS=0.00&digVal=2f4a703477714e6d6e4e 646d31776b64743936655a486b65354f513d&cIdTo ken=000001&cHashQRCode=ecc4f0e7e612456f2e 3521768bd572b6f0eae240]]>

**Comment by asandrob** [comment]
Algumas SEFAZ já implementaram essa validação em ambiente de homologação.
Vi que o XML é gerado corretamente mas quando envia o lote passa por esse método:
WSLoteEnvio.java
...
private NFLoteEnvioRetorno comunicaLote(final String loteAssinadoXml, final NFModelo modelo) throws Exception {
		// envia o lote para a sefaz
		final OMElement omElement = this.nfeToOMElement(loteAssinadoXml);
...
}
private OMElement nfeToOMElement(final String documento) throws XMLStreamException {
...
omElement.addAttribute("xmlns", NFeConfig.NFE_NAMESPACE, null);
//aqui o XML fica errado
...
}

Contornei assim:
1) Em WSLoteEnvio.java criei uma variável de instancia:
private String qr;

2) Aqui:
NFLoteEnvioRetornoDados enviaLote(final NFLoteEnvio lote) throws Exception {
...
	case NFCE:
		final NFGeraQRCode geraQRCode = new NFGeraQRCode(nota, this.config);
		nota.setInfoSuplementar(new NFNotaInfoSuplementar());
		nota.getInfoSuplementar().setQrCode(geraQRCode.getQRCode());
//atribuo o qr
		qr = geraQRCode.getQRCode();
//
		qtdNFC++;
		break;

3) Deixei o método nfeToOMElement assim:
	private OMElement nfeToOMElement(final String documento) throws XMLStreamException {
		final OMElement ome = AXIOMUtil.stringToOM(documento);
		final Iterator<?> children = ome.getChildrenWithLocalName(WSLoteEnvio.NFE_ELEMENTO);
		while (children.hasNext()) {
			final OMElement omElement = (OMElement) children.next();
			if ((omElement != null) && (WSLoteEnvio.NFE_ELEMENTO.equals(omElement.getLocalName()))) {
				omElement.addAttribute("xmlns", NFeConfig.NFE_NAMESPACE, null);
			}
		}
		final OMFactory factory = OMAbstractFactory.getOMFactory();
		final OMText omt = factory.createOMText(qr, OMElement.CDATA_SECTION_NODE);
		final Iterator<?> itNfe = ome.getChildrenWithLocalName("NFe");
		while (itNfe.hasNext()) {
			Object elementoNfe = itNfe.next();
			if (elementoNfe instanceof OMElement) {
				OMElement omElementoNfe = (OMElement) elementoNfe;
				Iterator<?> itInfSupl = omElementoNfe.getChildrenWithLocalName("infNFeSupl");
				while (itInfSupl.hasNext()) {
					Object elementoInfSupl = itInfSupl.next();
					if (elementoInfSupl instanceof OMElement) {
						OMElement omElementoInfSupl = (OMElement) elementoInfSupl;
						Iterator<?> itqrCode = omElementoInfSupl.getChildrenWithLocalName("qrCode");
						while (itqrCode.hasNext()) {
							Object elementoQrCode = itqrCode.next();
							if (elementoQrCode instanceof OMElement) {
								((OMElement) elementoQrCode).removeChildren();
								OMElement omElementoQrCode = (OMElement) elementoQrCode;
								omElementoQrCode.addChild(omt);
							}
						}
					}
				}
			}
		}
		return ome;
	}

Agora a NFC-e foi autorizada, segue link:
https://www.sefaz.rs.gov.br/NFCE/NFCE-COM.aspx?chNFe=43161025447992000120650010000000021903616877&nVersao=100&tpAmb=2&dhEmi=323031362d31302d30355432313a32343a35392d30333a3030&vNF=2.00&vICMS=0.00&digVal=44764a325077364833465342414e7657554a74647a6144736c6a4d3d&cIdToken=000001&cHashQRCode=fe80c789db15967d14fad40985daa4989257267a

Talvez não seja a solução mais elegante, mas resolveu o meu caso.

**Comment by andredgusmao** [comment]
Eu acabei verificando o mesmo erro que o @asandrob, o problema é na hora de construir o OMElement, na linha: `final OMElement ome = AXIOMUtil.stringToOM(documento);`
Eu fiz uma solução mudando a forma de construir o OMElement para manter o campo CDATA.

`final XMLInputFactory factory = XMLInputFactory.newInstance();`
`factory.setProperty(XMLInputFactory.IS_COALESCING, false);`
`XMLStreamReader reader = factory.createXMLStreamReader(new StringReader(documento));`
`StAXOMBuilder builder = new StAXOMBuilder(reader);`
`final OMElement ome = builder.getDocumentElement();`

A propriedade IS_COALESCING como false que mantém o CDATA.
Eu fiz um pull request pra vcs analisarem.

**Comment by asandrob** [comment]
@andredgusmao 
Acabei de testar tua solução.
Para NFC-e deu certo, SUCESSO!!!
Como ficou melhor que a minha sugestão, vou trocar aqui.

Segue link com a NFC-e gerada.
https://www.sefaz.rs.gov.br/NFCE/NFCE-COM.aspx?chNFe=43161025447992000120650010000000051127099985&nVersao=100&tpAmb=2&dhEmi=323031362d31302d30365431363a30343a30372d30333a3030&vNF=2.00&vICMS=0.00&digVal=66346b5a746a73506d79567a693177354b7a3130527344747034303d&cIdToken=000001&cHashQRCode=7fbbd073680fbc566682c7b0c1e6e3cb9c5d6e40

**Comment by margelperetto** [comment]
@andredgusmao tua solução funcionou aqui tbm

**Comment by rafaelTartigrado** [comment]
Já estou utilizando em produção.
