### ISSUE TITLE
NFCe para o estado do Pará

### ISSUE THREAD

**Issue by danieldhp** [wmixvideo/nfe#253]
Bom dia, 

estou tentando emitir NFCe para o estado do Pará e vi que as urls estão todas null, verifiquei na  [area do desenvolvedor](http://nfce.sefa.pa.gov.br/index.php/desenvolvedor) e la diz que o Pará usa a Sefaz Virtual do Rio Grande do Sul (SVRS), então alterei as urls para recuperar do SVRS da mesma forma que é feito para os outros estados que utilizam a SVRS (SVRS.getNfceStatusServico(ambiente)) porem quando faço uma consulta utilizando essas urls retorna uma exception "Connection reset".

Alguém poderia me ajudar a identificar o que está errado

**Comment by rafaelTartigrado** [comment]
@danieldhp 

Fiz a pouco tempo esta mesma alteração para o estado do Piauí.
Lembrar de remover o Pará (NFUnidadeFederativa.PA) do método: public NFUnidadeFederativa[] getUFs() do enum SVAN.
Não deixe de fazer os testes correspondentes.

**Comment by danieldhp** [comment]
@rafaelTartigrado 

então, peguei o seu PR e fiz a mesma coisa para o Pará porem o erro continua. Tentei emitir uma NFCe para o Piauí e aconteceu a mesma coisa

**Comment by danieldhp** [comment]
Consegui corrigir o problema adicionando o seguinte código:
```java
final Socket socket = this.sslContext.getSocketFactory().createSocket();
((SSLSocket) socket).setEnabledProtocols(new String[] {"TLSv1"});
```

Encontrei a solução neste link: http://blog.ifollow.com.br/2014/11/26/problema-nfe-reset-connection/

**Comment by fincatto** [comment]
Você tentou sobrescrever o metodo getSSLProtocolo do NFeConfig?
