### ISSUE TITLE
Não consigo enviar contribuição

### ISSUE THREAD

**Issue by estevamdf2** [wmixvideo/nfe#254]
Na branch slack_integracao tentei fazer uma contribuição no arquivo README.MD mais ao fazer o push ele retornou a seguinte mensagem:
ERROR: Permission to wmixvideo/nfe.git denied to estevamdf2.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Como faço para submeter o arquivo. 

Desde já agradeço.

**Comment by danieldhp** [comment]
Acredito que você esteja tentando realizar o push diretamente no repositório original.

Para realizar um push no repositório você precisa criar um fork e desenvolver a alteração nele e então você cria um Pull Request.

Caso você não saiba como fazer, tem esse tutorial que explica bem direitinho o que precisa ser feito: http://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/

**Comment by estevamdf2** [comment]
Ok. Valeu vou ler o tutorial e tentar novamente

**Comment by estevamdf2** [comment]
Segui o tutorial e consegui enviar minha contribuição. Muito obrigado pela ajuda.
