### ISSUE TITLE
Utilização do arquivo .cacerts criado pelo geraCadeiaCertificados.

### ISSUE THREAD

**Issue by estevamdf2** [wmixvideo/nfe#259]
Tenho uma dúvida referente ao seguinte serviço disponibilizado pelo senhores. Na criação do **java key store** é gerado pelo exemplo um arquivo chamado "producao.cacerts" como segue abaixo:

`FileUtils.writeByteArrayToFile(new` File("/tmp/producao.cacerts"), NFGeraCadeiaCertificados.geraCadeiaCertificados(NFAmbiente.PRODUCAO, `"senha"));`

A questão é onde este arquivo é utilizado? Em qual método eu devo utiliza-lo?

@lucas85cunha

**Comment by Raiduster** [comment]
Olá @estevamdf2, esse arquivo é utilizado dentro do NFeConfig, procure pela classe NFeConfigFake que você entenderá.

**Comment by jefperito** [comment]
Acho que o melhor exemplo é o NFeConfigFake mesmo

**Comment by estevamdf2** [comment]
Muito obrigado pelo feedback. Vou ver a classe
