### ISSUE TITLE
Validação de casas decimais em NFNotaInfoItemImpostoICMS51 campo pICMS

### ISSUE THREAD

**Issue by edivaldoms** [wmixvideo/nfe#266]
```
public class NFNotaInfoItemImpostoICMS51 extends NFBase {
//...
@Element(name = "pICMS", required = false)
    private String percentualICMS;
public void setPercentualICMS(final BigDecimal percentualICMS) {
        this.percentualICMS = BigDecimalParser.tamanho5Com2CasasDecimais(percentualICMS, "Percentual ICMS ICMS51 Item");
    }
//...
}
```
O correto seria:
```
public void setPercentualICMS(final BigDecimal percentualICMS) {
        this.percentualICMS = BigDecimalParser.tamanho7ComAte4CasasDecimais(percentualICMS, "Percentual ICMS ICMS51 Item");
    }
```

**Comment by edivaldoms** [comment]
No NFNotaInfoItemImpostoICMS20  também são 4 casas decimais
```
public class NFNotaInfoItemImpostoICMS20 extends NFBase {
//...
public void setPercentualAliquota(final BigDecimal aliquota) {
        this.percentualAliquota = BigDecimalParser.tamanho5Com2CasasDecimais(aliquota, "Aliquota ICMS20 Item");
    }
//...
}
```

`this.percentualAliquota = BigDecimalParser.tamanho7ComAte4CasasDecimais(aliquota, "Aliquota ICMS20 Item");`

**Comment by fincatto** [comment]
Boa noite @edivaldoms!
Consegue gerar um PR com a alteração, com o devido teste unitário?
Obrigado!

**Comment by edivaldoms** [comment]
Esqueci de dizer aqui, mas já está no PR https://github.com/wmixvideo/nfe/pull/272

**Comment by fincatto** [comment]
Excelente @edivaldoms.
Vou fechar esta issue então pois pretendo fazer o merge do PR #272 para o master o quanto antes (fiz só umas observações lá, veja se concordas).
Outro favor que vou lhe pedir é que atualize o seu fork antes de atualizar o PR, pois, do contrário, recebo a seguinte mensagem ao fazer o merge: "This branch is out-of-date with the base branch".
Obrigado!
