### ISSUE TITLE
Usar certificados do Windows com um nomes de ALIAS específico

### ISSUE THREAD

**Issue by jjwroberto** [wmixvideo/nfe#267]
Com o código abaixo é possível obter todos os certificados que estão instalados no Windows e respectivos alias de cada um:

    KeyStore ks = KeyStore.getInstance("Windows-MY", "SunMSCAPI");
    ks.load(null, null);
    for (Enumeration<String> aliases = ks.aliases(); aliases.hasMoreElements();) {
        String alias = aliases.nextElement();
        System.out.println(alias);
    }

No meu caso, possuo vários certificados, o qual preciso de um deles com um **Alias específico**.

Na classe `AssinaturaDigital` o método `assinarDocumento` está pegando sempre o primeiro item do `KeyStore` (linha 77):

    final String certificateAlias = config.getCertificadoKeyStore().aliases().nextElement();

Minha proposta seria a classe `NFeConfig` ter um método `public abstract String getAlias();` para retornar o nome do alias que será utilizado do `KeyStore`, ficando mais ou menos assim:

    final String certificateAlias = config.getAlias();

Como segunda proposta, para garantir compatibilidade, esse `getAlias()` poderia ter uma implementação padrão que retorne `null` e neste caso fazer o mesmo código que antes, ficando assim:

    final String certificateAlias = config.getAlias() == null ? config.getCertificadoKeyStore().aliases().nextElement() : config.getAlias();

Com esta segunda proposta, ninguém que atualize para a próxima versão irá ser impactado e quem precise utilizar um alias específico, basta sobrescrever o método `getAlias()`.

**Comment by fincatto** [comment]
Adicionado ao projeto!
Obrigado, @jjwroberto!

**Comment by AllisonErd** [comment]
Bom dia!
Baixei o repositório usando maven no meu projeto, e olhando a Classe NFeConfig nativa que veio na biblioteca, ela não contém o método getCertificadoAlias(). Como devo proceder?

**Comment by isaiastavares** [comment]
@AllisonErd você baixou o branche master?

Pois no branche master tem o método getCertificadoAlias().
Veja: https://github.com/wmixvideo/nfe/blob/master/src/main/java/com/fincatto/nfe310/NFeConfig.java

Lembrando, que NFeConfig é uma classe abstrata, se você estender ela e utilizar o método getCertificadoAlias() você tem que sobrescrever ele (@Override), pois por padrão esse método retorna null.

**Comment by AllisonErd** [comment]
@isaiastavares sim. Pelo que percebi, quando baixo a biblioteca pelo maven, ela vem desatualizada. Comparando o jar que baixo do maven com o branch master mencionado por vc, realmente, no branch master consta a atualização, porém, quando baixo pelo maven não. E olhando no Maven repository, lá também não consta a atualização que contem o método getCertificadoAlias(). Alguma ideia de como posso proceder para solucionar o problema?

**Comment by fincatto** [comment]
Vamos lançar uma nova versão no maven, contendo as ultimas atualizações de codigo, ainda essa semana.

**Comment by AllisonErd** [comment]
Ok @fincatto, fico aguardando a atualização. Obrigado pela atenção e estou a disposição para contribuição da biblioteca.

**Comment by fincatto** [comment]
Acabou de ser liberada: https://oss.sonatype.org/#nexus-search;quick~nfe
Alguns espelhos ainda não sincronizaram, mas devem fazer até amanhã.

**Comment by RamonKenedy** [comment]
Bom dia!
Sugiro que seja utilizada a logica do @jjwroberto na classe **NFSocketFactory** no método **createKeyManagers** pois na primeira linha desse método esta dessa forma:
` final String alias = getAlias(config.getCertificadoKeyStore());`
sendo que o método getAlias() está pegando sempre o primeiro item do KeyStore.
Dessa forma a primeira linha (linha 61) do método createKeyManagers ficaria assim:
`final String certificateAlias = config.getCertificadoAlias() == null ? getAlias(config.getCertificadoKeyStore()) : config.getCertificadoAlias();`

Obrigado!

**Comment by fincatto** [comment]
@RamonKenedy já foi atualizada. 
Atualize a sua versão aí!
Att

**Comment by granella** [comment]
@fincatto eu tive que efetuar a alteração sugerida pelo @RamonKenedy porque estava com um problema quando uso o certificado A1 e A3 acessado o repositório do Windows.

Da forma que estava o getAlias() percorria o repo e caso o meu certificado A1 estivesse abaixo do A3 ele chamava a dialog de inserir o PIN (caso o cartão estivesse na leitora). Dessa forma fica um pouco estranho pois se o usuário escolhe um certificado A1 que ja esta com a senha no repo do Windows não há a necessidade do usuário entrar com o PIN ja que o alias escolhido não é o A3 

commit https://github.com/granella/nfe/commit/0b5d081d055b904832ffb563992d66d246232409

Obrigado

**Comment by RamonKenedy** [comment]
@granella Obrigado, foi justamente o problema que eu estava tendo!

**Comment by fincatto** [comment]
Vocês conseguem fazer um PR da solução, para facilitar a analise e adicionarmos na base de codigo?

**Comment by granella** [comment]
@fincatto PR submetida

**Comment by fincatto** [comment]
Já incluída no master! Obrigado pessoal!
