### ISSUE TITLE
QrCode de Produção do Rio de Janeiro

### ISSUE THREAD

**Issue by Raiduster** [wmixvideo/nfe#268]
Pessoal, estou implementando a NFCe para o Rio de Janeiro e recebi a Rejeição: Codigo de Hash no QR-Code difere do calculado.

Fiz vários testes e nada, li a documentação e lá está escrito que o Hash precisa estar em caixa alta, a Lib não faz essa verificação, pois bem, fiz a alteração e continuei tomando a rejeição.

Acabei encontrando um erro na url do QrCode de produção, no enum NFUnidadeFederativa, ele tem um sinal de interrogação(?) no final, nenhum outro item do enum possui essa interrogação, a classe NFGeraQRCode já adiciona esse sinal para concatenar com os parâmetros, ai no caso a Url ficam com duas interrogações , gerando tão a Rejeição.
Tirei esse cara e funcionou de primeira, voltei o cara e deu erro, tirei e funcionou, fiz umas 4 vezes e realmente a interrogação está causando o problema.

Alguém pode fazer a correção? 

Um abraço.

A documentação está aqui: http://www.fazenda.rj.gov.br/sefaz/content/conn/UCMServer/path/Contribution%20Folders/site_fazenda/informacao/sistemaseletronicos/nfce/Entendendo%20a%20consulta%20NFC-e.pdf?lve

**Comment by fincatto** [comment]
Ajustado! Obrigado @Raiduster!
