### ISSUE TITLE
Versão do maven desatualizada

### ISSUE THREAD

**Issue by jjwroberto** [wmixvideo/nfe#269]
Os recursos de Manifestação do Destinatário estão liberados/estáveis? 

A versão 2.0.0 do maven não possui o recurso.

		<dependency>
			<groupId>com.github.wmixvideo</groupId>
			<artifactId>nfe</artifactId>
			<version>2.0.0</version>
		</dependency>

**Comment by fincatto** [comment]
@jjwroberto, boa tarde.
Ainda não lançamos pro maven, mas o faremos em breve. 
Att
