### ISSUE TITLE
Em NFEventoCancelamento o atributo está incorreto

### ISSUE THREAD

**Issue by edivaldoms** [wmixvideo/nfe#271]
Na classe o atributo "assinatura" está como tipo String, o correto seria tipo "NFSignature".

```
public class NFEventoCancelamento extends NFBase {
//...
    @Element(name = "Signature", required = false)
    private NFSignature assinatura;
//...
}
```

**Comment by edivaldoms** [comment]
https://github.com/wmixvideo/nfe/pull/272

**Comment by edivaldoms** [comment]
Essa mudança acima resolve o Exception quando tenta parcear o objeto:
java.lang.IllegalArgumentException: Nao foi possivel parsear o xml: Element 'SignedInfo' does not have a match in class com.fincatto.nfe310.classes.evento.cancelamento.NFEnviaEventoCancelamento at line 1

```
public NFEnviaEventoCancelamento loteEventoCancelamentoParaObjeto(final File xml) {
    try {
      return this.persister.read(NFEnviaEventoCancelamento.class, xml);
    } catch (final Exception e) {
      throw new IllegalArgumentException(String.format("Nao foi possivel parsear o xml: %s", e.getMessage()));
    }
  }

  public NFEnviaEventoCancelamento loteEventoCancelamentoParaObjeto(final String xml) {
    try {
      return this.persister.read(NFEnviaEventoCancelamento.class, xml);
    } catch (final Exception e) {
      throw new IllegalArgumentException(String.format("Nao foi possivel parsear o xml: %s", e.getMessage()));
    }
  }
```

**Comment by edivaldoms** [comment]
A classe NFEnviaEventoInutilizacao também está com propriedade "assinatura" como String e acontece o mesmo problema acima quando tenta parsear.

Mudei para "private NFSignature assinatura;" e resolveu.

**Comment by fincatto** [comment]
Obrigado @edivaldoms.
Solicitei no PR que o teste, que foi comentado, fosse implementado adequadamente. É possível?

**Comment by edivaldoms** [comment]
Desculpe @fincatto agora foi um novo PR com mais algumas correções que testei. Agora estão gerando os arquivos XMLs que estão nos padrões que testei em outros sistemas.

**Comment by edivaldoms** [comment]
Analisando o código no Github agora percebi que meu editor está fazendo indentação de 2 casas e o código original com 4. Com isso, parece que são muitas alterações :/ 
Analisando no difenciador do Netbeans ele ignora esses detalhes.

**Comment by fincatto** [comment]
Oi @edivaldoms.
Facilita um monte! 👍 
Obrigado!
