### ISSUE TITLE
Classe de dados de inutilização esta com o nome "NFEventoCancelamentoDados" e não "NFEventoInutilizacaoDados"

### ISSUE THREAD

**Issue by edivaldoms** [wmixvideo/nfe#273]
A classe não deveria se chamar "NFEventoInutilizacaoDados"?

https://github.com/wmixvideo/nfe/blob/master/src/main/java/com/fincatto/nfe310/classes/evento/inutilizacao/NFEventoCancelamentoDados.java

**Comment by fincatto** [comment]
Bom dia @edivaldoms.
Tens razão! Queres fazer o PR?

**Comment by edivaldoms** [comment]
Fiz o PR.

**Comment by fincatto** [comment]
Merge feito!
Obrigado @edivaldoms!
