### ISSUE TITLE
Web Service de Distribuição de DF-e

### ISSUE THREAD

**Issue by edivaldoms** [wmixvideo/nfe#274]
Alguém está trabalhando/desenvolvendo o Web Service de Distribuição de DF-e?

https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=2Z%20kcHOdpHs=

Caso não estejam, pretendo criar em breve para que os citados nos documentos fiscais possam ter ciência dos documentos emitidos e facilitar a manifestação.

**Comment by edivaldoms** [comment]
Não confundir com MDF-e

**Comment by fincatto** [comment]
Olá @edivaldoms. 
Creio que ninguém esteja trabalhando nisso ainda, visto que ninguém se manifestou. 
Se puderes criar, será excelente!

**Comment by higomatos** [comment]
@edivaldoms, início algo?

Este webservice descontinuará outros: Data de desativação dos Web Services NfeConsultaDest e NFeDownloadNF: 02/05/2017

**Comment by edivaldoms** [comment]
@higomatos @fincatto estava pretendendo desenvolver em 2017, pois eu estava precisando de férias depois de 16 anos sem parar. Vida de programador!

Vou tentar desenvolver alguma coisa antes que seja descontinuado.

No momento usamos o Manifestador de NF-e da Sefaz https://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=AxaPNP1BtFk=

**Comment by fincatto** [comment]
Excelente @edivaldoms! 
Aproveite bem suas merecidas férias!
Até 2017!

**Comment by higomatos** [comment]
@edivaldoms, boas férias!!!

@fincatto, pode assinar pra mim? não tenho permissão

**Comment by fincatto** [comment]
També nao consegui assinar. Pelo visto somente consigo assinar pra quem cria o ticket ou pra alguém da equipe wmixvideo. Vou dar uma pesquisada mais a fundo nisso.

**Comment by higomatos** [comment]
@fincatto, cria um branch pra eu fazer um PR da parte que já escrevi.

Eu criei o Stub com Axis (mantendo a compatibilidade java 7) porém também criei os objects automatizados com xjc a partir dos XSDs. Isto traz uma grande agilidade de desenvolvimento mas "foge" ao padrão de criar nomes de campos diferenciados para os atributos dos objetos. Fiquei em dúvida sobre como vocês criaram os objetos (que fazem parse pra XML) anteriores, foi digitando mesmo? Podemos utilizar os nomes dos atributos conforme consta nos XSDs para "aproveitar" as ferramentas de automatização?

**Comment by waldandrade** [comment]
Conte comigo! Pra o MDF

Em 05/01/2017 00:20, "higomatos" <notifications@github.com> escreveu:

**Comment by higomatos** [comment]
@waldandrade, ótimo! Mas esta issue é do DFe, o MDF-e é na issue 211. Você tem interesse em qual delas?

**Comment by fincatto** [comment]
@higomatos no passado, tivemos uma experiencia muito ruim com os geradores de codigo. Eles geravam classes duplicadas e ficava uma bagunça pra manter e evoluir. Isso motivou o uso do Simple e da escrita das classes na mão. Assim, quando uma atualização saia, incluiamos aquele campo e tudo ficava ok. 
Com isso, aproveitamos pra gerar nomes de campos mais amigáveis, para que ficasse fácil para o desenvolvedor ler o codigo e entender, sem ter que estar com o manual na mão. 
Essa foi a premissa básica da criação deste projeto e acho que devemos mantê-la. 
Você está com alguma dificuldade de gerar as classes usando o Simple?
Att

**Comment by higomatos** [comment]
@fincatto, temos dois tipos de classes que podem ser gerados automaticamente:

1 - Stubs;
2 - Objetos que serão "parseados" pra XML;

1 - Os Stubs eu gerei com o plugin do maven axis2-wsdl2code-maven-plugin na versão 1.6.4 e deu certinho.

2 - Já os novos objetos eu gerei com o xjc do JAXB e também deu tudo certinho. Realmente algumas classes são duplicadas pois eu gerei XSD por XSD, mas só exclui as duplicações no final e adicionei o extends em algumas. E a geração já criou JavaDocs muito úteis como exemplo:

O seguinte fragmento do esquema especifica o conteúdo esperado contido dentro desta classe.
 ```
<complexType>
   <complexContent>
     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       <sequence>
         <element name="tpAmb" type="{http://www.portalfiscal.inf.br/nfe}TAmb"/>
         <element name="verAplic" type="{http://www.portalfiscal.inf.br/nfe}TVerAplic"/>
         <element name="cStat" type="{http://www.portalfiscal.inf.br/nfe}TStat"/>
         <element name="xMotivo" type="{http://www.portalfiscal.inf.br/nfe}TMotivo"/>
         <element name="dhResp" type="{http://www.portalfiscal.inf.br/nfe}TDateTimeUTC"/>
         <element name="ultNSU" type="{http://www.portalfiscal.inf.br/nfe}TNSU"/>
         <element name="maxNSU" type="{http://www.portalfiscal.inf.br/nfe}TNSU"/>
         <element name="loteDistDFeInt" minOccurs="0">
           <complexType>
             <complexContent>
               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 <sequence maxOccurs="50">
                   <element name="docZip">
                     <complexType>
                       <simpleContent>
                         <extension base="<http://www.w3.org/2001/XMLSchema>base64Binary">
                           <attribute name="NSU" use="required" type="{http://www.portalfiscal.inf.br/nfe}TNSU" />
                           <attribute name="schema" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                         </extension>
                       </simpleContent>
                     </complexType>
                   </element>
                 </sequence>
               </restriction>
             </complexContent>
           </complexType>
         </element>
       </sequence>
       <attribute name="versao" use="required" type="{http://www.portalfiscal.inf.br/nfe}TVerDistDFe" />
     </restriction>
   </complexContent>
 </complexType>
```

Acho que desenvolver pro ambiente fiscal sem o Manual é meio improvável e particularmente não vejo problema em manter os nomes originais, no meu caso até facilita pois o nosso norte é a documentação oficial.

Neste [commit](https://github.com/higomatos/nfe/commit/c0b88cc033273f51253079244be541ae3c684124) tem o Web Service de Distribuição funcionando (digamos que é uma versão base ainda sem os testes ou melhorias) pra você avaliar os pontos negativos antes de submeter um PR.

Manter um código não automatizado requer uma maior demanda de mão de obra, principalmente em momentos de mudança de layout ou implantação de novos serviços.

**Comment by fincatto** [comment]
Dá trabalho sim, mas apenas na primeira vez. A manutenção fica bem mais simples, uma vez que a cada versao teremos que lembrar de sair apagando classes duplicadas. Passamos por isso desde a primeira versão da NFe e pra nós foi um inferno.
Outra coisa que temos que prezar é a padronização. Mudar para geração automática, além dos problemas reportados acima, ainda implicaria em regerar tudo novamente e criar wrappers para depreciação dos metodos antigos, para nao quebrar a compatibilidade (por padrao, em uma troca de versao marcamos como depreciados e na outra removermos, para facilitar a migração para os desenvolvedores).

**Comment by higomatos** [comment]
@fincatto, eu fiz vários outros testes e as classes duplicadas são geradas quando não configuramos direito o gerador de objetos. Os Stubs também foram gerados automaticamente e nem por isso optou-se por escrever Stubs "na mão".

Mas acho que utilizar o gerador ou escrever na mão não é a questão a ser discutida, a questão é se pretendemos remover ao máximo as dependências. Se este for um princípio do projeto (acho que li isto em algum post, deveria até ir pro README) remover o Simple Framework também tem que estar nos planos (mesmo que com baixa prioridade) e passar a utilizar javax.xml.bind.annotation será o caminho natural.

Consegui implementar aqui sem o Simple e sem o Axis e o projeto fica praticamente sem dependências (o próprio Joda tem que ser removido também...)

Sobre ter nomes amigáveis, embora eu não concorde muito porque "quebra" a compatibilidade com a documentação, acho que é uma questão muito de ponto de vista.

Bom, mas minha dúvida é: remover dependências é um princípio do Projeto? Neste caso o Axis, o Simple e Joda podem ser alvos de substituição por tecnologias nativas da JDK?

**Comment by fincatto** [comment]
Absolutamente @higomatos!
Este projeto foi concebido na troca da primeira para a segunda versão da NFe e muita coisa mudou de lá pra cá. Se conseguirmos usar somente o JDK padrão e funcionar ok, acho que devemos buscar isso! 
Sobre os nomes amigáveis, podemos alterar sim, sem problema algum, se facilitar pra nós desenvolvedores, é absolutamente algo a ser implementado! O princípio da biblioteca é justamente facilitar (e fazer as coisas de forma bem feitas).
O que você acha de implementarmos, para essa nova versão da NFe (4.0), como você sugeriu, sem dependências externas? Você acha viável? Eu não uso geradores de código desde a versão 1.0 da NFe, é um ponto a ser testado. Se você acha viável, acho que poderiamos usar o branch 3.0 (ou até renomeá-lo para 4.0 e seguir junto com a versão da NFe) e iniciarmos os testes, pode ser?

**Comment by higomatos** [comment]
Excelente @fincatto, "sem dependências externas" acredito que não até porque nos testes que eu fiz precisei ainda do apache.commons e algumas outras (mas pouquíssimas), acredito que podemos reduzir quase totalmente o uso de dependências externas sim e já pra estão versão 3.0.

Com relação a alterar para 4.0 eu não concordo e faço é outra sugestão (eita que estou sugerindo d+ já ;) ), acho que deveríamos alterar o nome do projeto de nfe para dfe ou sped pois no momento que incorporar algo do CT-e (já tem um PR) ou do MDF-e (já tem uma issue) nós sairemos totalmente do projeto NF-e para outros projetos do grupo do SPED e o nome perderá o sentido pela abrangência dada.

Com relação a facilitar para o desenvolvedor eu pensei que poderia ser uma estratégia (quando os nomes amigáveis forem retirados) incluirmos no javadoc do atributo a descrição e observação que tem na documentação oficial, seria muito mais útil que o nome amigável e aí não precisaríamos escrever o código olhando para o Manual pois ele já estaria disponível.

Com relação aos geradores de código de objetos eles seriam utilizados somente para o bootstrap do objeto continuaríamos mantendo na mão os javadocs ou especificidades. Numa alteração de versão de layout geraríamos novamente mas só pra pegar os trechos novos / alterados para colar nos objetos já gerados.

**Comment by higomatos** [comment]
Este serviço foi adicionado ao branch 3.0, alguém poderia fazer testes de consumo?

@edivaldoms

**Comment by MarioJunio** [comment]
Realizei os testes aqui utilizando sua Branch, porém não funcionou corretamente:

**Teste:**
```
RetDistDFeInt consultaDocumentoFiscal = new WSFacade(conf).consultaDocumentoFiscal("05405941000200", "", "0", NFUnidadeFederativa.MG);
String motivo = consultaDocumentoFiscal.getXMotivo();
System.out.printf("Motivo: %s\n", motivo); 
```

**Saída:**
`Motivo: Rejeicao: Falha no esquema xml`
