### ISSUE TITLE
Teste que quero fazer mas preciso de ajuda (Config no md diz que é extends.. mas e implements..)

### ISSUE THREAD

**Issue by robertorp** [wmixvideo/nfe#275]
`public class ConfiguracaoWix implements NFeConfig {

    private KeyStore keyStoreCertificado = null;
    private KeyStore keyStoreCadeia = null;

    @Override
    public NFAmbiente getAmbiente() {
        return NFAmbiente.HOMOLOGACAO;
    }

    @Override
    public File getCertificado() throws IOException {
        return null;
    }

    @Override
    public File getCadeiaCertificados() throws IOException {
        return null;
    }

    @Override
    public String getCertificadoSenha() {
        return "123456";
    }

    @Override
    public NFUnidadeFederativa getCUF() {
        return NFUnidadeFederativa.GO;
    }

    @Override
    public NFTipoEmissao getTipoEmissao() {
        return NFTipoEmissao.EMISSAO_NORMAL;
    }
}`

ele retorna file..
como seria a implementação dos métodos que retornam file?

obs: to fazendo somente teste no android.. obs2: é so um teste

**Comment by robertorp** [comment]
Hmm, pelo que vi aqui era uma versão 1.0.22 (algo assim)
agora parece que deu certo o extends

**Comment by fincatto** [comment]
Bom dia @robertorp.
Não é a mesma senha (senão não faria muito sentido colocar um método para tal).
É a senha da cadeia de certificados das Sefaz que vc acessa, mas alguns outros necessários pra nota. Há um teste unitário inclusive baixando essa cadeia e tem algo no readme do projeto tb.
No java, geralmente essa cadeia possui a extensão jks.
