### ISSUE TITLE
Implementação dos validadores da NFe

### ISSUE THREAD

**Issue by estevamdf2** [wmixvideo/nfe#276]
No código fonte e disponibilizado algum método que faça a validação do xslt de envio para a receita?
A Sefaz RS disponibiliza um validador na web (https://www.sefaz.rs.gov.br/NFE/NFE-VAL.aspx) onde inserimos o xml do lote da nota fiscal e ele retorna os erros das regras de negócio.
Estamos enviando algumas notas no ambiente de homologação usando o site da sefaz para validar o conteúdo do xml. 
Ele retorna algumas mensagens de erro como:
539 - [Simulacao] Rejeicao: Duplicidade de NF-e, com diferenca na Chave de Acesso
228 - [Simulacao] Rejeicao: Data de Emissao muito atrasada
505 - [Simulacao] Rejeicao: Data de Entrada/Saida anterior ao permitido

Mas ao utilizarmos o método enviaLote() da WSFacade e retornado para nós o status 103 - Lote recebido com sucesso. Este método por sua vez utiliza o método validaLote() da classe XMLValidador que não retorna nenhum dos erros acima informados.

Os senhores tem estes validadores implementado ?

**Comment by caiocteodoro** [comment]
@estevamdf2 o serviço de envioLote() vai retornar se o lote enviado foi recebido pela SEFAZ, você deve utilizar o serviço de consultaLote() para saber se as notas foram processadas pela SEFAZ recebendo assim o código de Autorização de uso (100) ou o de erro!

**Comment by estevamdf2** [comment]
Certo. 

Fizemos o teste aqui agora. Enviamos a nota usando o método consultaNota() e obtivemos o seguinte retorno:

`<protNFe versao="3.10">
    <infProt Id="ID353160000222473">
    <tpAmb>2</tpAmb>
     <verAplic>SVRS201611281548</verAplic>
     <chNFe>53161209168704000142550020000979081007979080</chNFe>
     <dhRecbto>2016-12-14T14:35:27-02:00</dhRecbto>
     <nProt>353160000222473</nProt>
     <digVal>C4IcZhfNiCGaDjvZCdPrUFp0S7g=</digVal>
     <cStat>100</cStat>
    <xMotivo>Autorizado o uso da NF-e</xMotivo>
    </infProt>
</protNFe>`

Pegando o conteúdo do xml e fazendo a validação pelo site da Sefaz RS obtivemos o seguinte retorno:

- 204 - [Simulacao] Rejeicao: Duplicidade de NF-e

O ambiente de homologação não está fazendo a validação de forma correta?

@ambroiler

**Comment by fincatto** [comment]
Boa tarde.
O sistema faz a validação do esquema do arquivo, com base no modelo fornecido pela Sefaz.
O projeto, em si, não tem como validar notas duplicadas, pois isso só é feito usando a base de dados.

**Comment by estevamdf2** [comment]
Muito obrigado pelos esclarecimentos.
