### ISSUE TITLE
Armazenamento de eventos

### ISSUE THREAD

**Issue by danieldhp** [wmixvideo/nfe#277]
Bom dia,

Estou verificando como armazenar os eventos e aparentemente não é possível armazenar corretamento os eventos com a biblioteca no momento.

Peguei com o contador de um cliente um exemplo de XML de inutilização: [exemplo](http://pastebin.com/8D8afJGm)

Como é possível ver, é basicamente a junção do XML que é enviado (inutNFe assinado) com o retorno (retInutNFe) em um node com nome de ProcInutNFe. A mesma regra se aplica para o cancelamento.

Se alguém souber me informar se esta é a forma correta, posso realizar as alterações e fazer um PR

**Comment by isaiastavares** [comment]
@danieldhp Daniel, é isso mesmo, o procInut é montado a partir do inutNFe + assinatura + retorno da Sefaz (retInutNFe).

A mesma coisa vale para os eventos. (Cancelamento, Carta de Correção e etc...)

[exemplo](http://pastebin.com/LEQRPDBW)
