### ISSUE TITLE
Envio de notas em contigência

### ISSUE THREAD

**Issue by jefperito** [wmixvideo/nfe#28]
Criar mecanismo para envio de notas em contigência

**Comment by henriquebartoski** [comment]
Como tratam atualmente o envio em contingência?  Existe alguma previsão de desenvolvimento?

**Comment by jefperito** [comment]
Até o momento não tivemos problemas com contingência, sem previsão de nossa parte, talvez alguém da comunidade de usuários da lib desenvolva.

**Comment by RickFerreira911** [comment]
Notei que as URL's dos SVC (RS e Nacional) estão no projeto e também a uma estrutura de seleção do tipo de emissão contendo SVCRS e SVCAN. Como está a implementação em relação aos sefaz virtuais de contingencia?

**Comment by jefperito** [comment]
Olá,

Como está no comentário anterior sem previsão nenhuma dos _core members_, mas nada impede que qualquer pessoa desenvolva e apareça um pull request com essa funcionalidade, como foi o caso de diversas funcionalidades desenvolvidas pela comunidade criada em volta da biblioteca.

**Comment by henriquebartoski** [comment]
Boa tarde!
Estou fazendo as alterações para o envio no SVC-RS e SVC-AN.
Notei que quando uma nfe é autorizada no SVC e enviada ao sefaz do estado do emitente o evento de cancelamento, quando submetido pelo SVC, não é replicado ao sefaz do emitente (pelo menos não foi após 6hrs de espera entre meus testes).
Alguém sabe qual o procedimento correto? Cancela no Sefaz do emitente, no SVC utilizado ou em ambos?

**Comment by higomatos** [comment]
Manual de Orientação do Contribuinte, versão 6.0.0, página 155

c) Serviço de Registro de Eventos: Cancelamento

O Serviço de Registro de Eventos (Web Service: RecepcaoEvento), para o
evento de Cancelamento (Tipo Evento=110111), sempre estará disponível
somente para as NF-e autorizadas pela própria SVC, dentro das regras
definidas para a operação normal de cancelamento.

Quando da utilização da SVC pela empresa, uma eventual necessidade de
cancelamento de uma NF-e autorizada no ambiente normal deverá ser
*represada* para comando posterior no ambiente de autorização normal da
SEFAZ de origem da circunscrição do contribuinte.
Nota:
Futuramente, poderá ser analisada a possibilidade de cancelamento na SVC de
uma NF-e emitida no ambiente de autorização normal da SEFAZ e/ou o
cancelamento no ambiente de autorização normal da SEFAZ de uma NF-e
autorizada pela SVC. Neste caso, somente será possível o cancelamento no
outro ambiente, caso o documento autorizado já tenha sido automaticamente
compartilhado entre o ambiente normal de autorização e o ambiente da SVC (e
vice-versa).

Em 1 de julho de 2016 18:02, Henrique Bartoski <notifications@github.com>
escreveu:

> Boa tarde!
> Estou fazendo as alterações para o envio no SVC-RS e SVC-AN.
> Notei que quando uma nfe é autorizada no SVC e enviada ao sefaz do estado
> do emitente o evento de cancelamento, quando submetido pelo SVC, não é
> replicado ao sefaz do emitente (pelo menos não foi após 6hrs de espera
> entre meus testes).
> Alguém sabe qual o procedimento correto? Cancela no Sefaz do emitente, no
> SVC utilizado ou em ambos?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/wmixvideo/nfe/issues/28#issuecomment-230046683>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AG74HfudMPQT5eJk0rmrnTYuEbN_t4rCks5qRYBugaJpZM4D5Mq7>
> .
>



-- 
Higo Soares Matos
+55 86 99934-3237 - TIM
+55 86 98882-3796 - OI

**Comment by gabrielbo1** [comment]
Boa tarde tenho muito interesse em implementar a funcionalidade de contingencia. 
Estou começando um novo projeto em minha organização e gostaria muito de usar o projeto opensouce em minha solucao ERP.  Gostaria de saber se a equipe tem interesse nessa funcionalidade pois e uma necessidade do meu projeto.

**Comment by fincatto** [comment]
Boa tarde @gabrielbo1.
Com certeza muita gente vai se beneficiar da funcionalidade, portanto, será muito bem vinda!

**Comment by nielsonjr** [comment]
Pessoal, estou precisando fazer envio de notas emitidas em contingência FSDA e OFFLINE. Tentei realizar a operação de envio e um erro de "Método de emissão não suportado" foi levantado. Vi que a classe responsável por isso é a NFAutorizador31, pois não suporta os métodos de contingência citados para o retorno de um "Autorizador". Segundo o manual do Contribuinte v. 6.0.0, página 89:

"[...] O envio das NF-e emitidas nesta situação (FS-DA) para SEFAZ de *origem* será realizado quando cessarem os problemas técnicos que impediam a sua transmissão [...]".

Concluo que nesse caso, o "Autorizador" seria o mesmo de uma Emissão Normal ("SEFAZ  de origem"). Feito isso, o envio de notas com esses tipos de contingência é realizado sem problemas. 

Fiz os devidos ajustes no código e posso emitir um pull request pro projeto.
