### ISSUE TITLE
Problema com timezone e padrão de campos Data e Hora

### ISSUE THREAD

**Issue by higomatos** [wmixvideo/nfe#280]
Ao compilar o projeto estando em outro timezone o java utiliza o timezone do desenvolvedor e, por isto, todos os testes de data / hora não são executados corretamente.

Exemplo de erro:
`org.junit.ComparisonFailure: expected:<...016-11-30T02:30:00-0[2]:00</dhRegEvento><nP...> but was:<...016-11-30T02:30:00-0[3]:00</dhRegEvento>`

Testei duas formas de corrigir o problema, a primeira consiste em informar ao maven qual timezone utilizar:

```
     <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <argLine>-Duser.timezone=America/Sao_Paulo</argLine>
                </configuration>
     </plugin>
```

A segunda seria informar o timezone nos testes na hora de criar as datas:

`infoEventoCancelamento.setDataHoraEvento(new DateTime(2014, 1, 1, 10, 10, 10, DateTimeZone.forID("America/Sao_Paulo")));`

porém percebi que temos uma despadronização no código, exemplo:

class NFInfoEventoCancelamento >  private DateTime dataHoraEvento;
class NFInfoEventoRetorno > private LocalDateTime dataHoraRegistro;

Questões:

1 - Qual das formas acima devo utilizar para contornar o erro nos testes para fazer PR?
2 - Existe um motivo pra utilizar LocalDateTime e DateTime ou podemos padronizar isto?

**Comment by higomatos** [comment]
@fincatto, @jefperito, @flppsilva

**Comment by fincatto** [comment]
Olá @higomatos. Acho que podemos padronizar, se não houver nada na
documentação contra. Tenho a impressão que isso entrou num pr de um colega
que estava em outra timezone, mas não tenho certeza agora (estou em viagem,
tá difícil usar no celular). Mas acho que podes padronizar sim, creio que
ficará melhor. Abs.

**Comment by fincatto** [comment]
Bom dia @higomatos. 
Esse problema foi corrigido? Posso fechar a issue?
