### ISSUE TITLE
Alteração Leiaute da NF-e para versão “4.00”

### ISSUE THREAD

**Issue by higomatos** [wmixvideo/nfe#281]
Conforme NT_2016_002_v1.00 preparar novo layout.

O prazo previsto para a implementação das mudanças é:
- Ambiente de Homologação (ambiente de teste das empresas): 01/06/2017;
- Ambiente de Produção: 01/08/17.
- Desativação da versão anterior: 06/11/17.

**Comment by fincatto** [comment]
Olá @higomatos, boa tarde!
Já marquei essa migração como versão 3.0 e o coloquei como responsável técnico.
A partir do dia 20/01 estarei de volta e poderei ajudar com código também.
Vou criar um branch para facilitar a colaboração. 
Qualquer duvida, me adicione no skype (fincatto) ou se você usa outro mensageiro, só me informar.

**Comment by fincatto** [comment]
https://github.com/wmixvideo/nfe/tree/3.0

**Comment by caiocteodoro** [comment]
Poderiam me passar uma posição de como anda o desenvolvimento do novo layout da NF-e, e o que falta implementar para que possa estar ajudando? Pelo que vi no branch 3.0 estão remodelando o projeto, só que continua com a versão antiga da NF-e.

**Comment by rafaelTartigrado** [comment]
Novos prazos (Nota Técnica 2016.002 - v 1.20 (atualizada em 31/05/2017)):

O prazo previsto para a implementação das mudanças é:
- Ambiente de Homologação (ambiente de teste das empresas): 03/07/2017.
- Ambiente de Produção: 02/10/17.
- Desativação da versão anterior: 02/04/18.

**Comment by GiuseppeMP** [comment]
Bom dia pessoal!

Preciso iniciar a evolução da API para versão 4 para um cliente que estou trabalhando, gostaria de fazer isso colaborando com esse projeto.

Não gostaria de iniciar uma versão 4 do 0, mas sim colaborar a evoluir está que utilizei para versão 3.10. Caso alguém já tenha iniciado poderia entrar em contato ou podemos alinhar o que precisa ser feito?


No aguardo, 
Att

**Comment by walterportugal** [comment]
Giuseppe,

Já fiz a implementação de uma versão em um fork -
https://github.com/walterportugal/nfe. Se quiser dar uma olhada.

Walter

Em qua, 8 de nov de 2017 às 09:46, Giuseppe Matheus Bairros Pereira <
notifications@github.com> escreveu:

**Comment by GiuseppeMP** [comment]
Obrigado Walter!

Show vi sim, consigo colaborar com algo? 

Como estão rastreando as atividades? trello?

**Comment by yelken** [comment]
@walterportugal Gostaria de colaborar com algo relacionado, tens alguma TASK sobrando?

**Comment by malikoski** [comment]
@walterportugal Muito bom.. se eu puder colaborar com algo também, pode contar comigo.

**Comment by yelken** [comment]
@fincatto Bom dia amigo, a versão 4.0 já teve alguma evolução?

Fico a disposição para ajudar no que precisar.

Um abraço

**Comment by damascoa** [comment]
Alguma posição de como vai ser feita a evolução da NF para 4.0, se vai ser feita em uma nova branch e se vai manter o atual padrão de dependências utilizados pelo projeto?

**Comment by fincatto** [comment]
Estamos iniciando a implementação da nova versão. Ela vai coexistir com a
versão atual, então será feita no master. Temos um branch em que estamos
testando novos modelos de dependências, mas ele só estará no master quando
estiver pronto e bem testado.

Em qua, 10 de jan de 2018 15:27, Renato G. <notifications@github.com>
escreveu:

**Comment by juliofozz** [comment]
Boa noite a todos, caso estiver em local errado peço que me perdoe, peço uma orientação, estou já finalizando um sistema comercial, ele se encontra rodando em ambiente de produção , preciso fazê-lo emitir  NF-e ou NFC-e, como devo proceder a princípio,  por onde começar?  Estava pensando ué deveria iniciar criando um web Service que receberia s requisições da notas, é por aí? Será td integrado ao mesmo sistema, pode funcionar assim?

**Comment by juliofozz** [comment]
Perdão,  quis dizer em ambiente de desenvolvimento.

**Comment by fincatto** [comment]
Essa é uma decisão técnica, você deve implementar da forma que faz sentido
ao seu negócio.

Em seg, 29 de jan de 2018 21:01, juliofozz <notifications@github.com>
escreveu:

**Comment by juliofozz** [comment]
Obrigado fincatto, a minha aplicação é em java web, utilizando as tecnologias jsf, primefaces e outros Framework. Porém a aplicação estará rodando em servidor local com acesso a internet, a minha pergunta é, o que devo implementar pra emissão da Nf, a aplicação já efetua a venda/compra e imprime comprovante, a ideia seria emitir a NF com os dados da venda, não é essa a logica? Poderia então escolher a venda em questão e solicitar a emissão da NF. O que vc acha, poderia ser usada essa logica?

**Comment by fincatto** [comment]
Pode sim. Você pode fazer isso dentro do seu fluxo de emissão ou ainda
fazer de forma assíncrona, que é o que recomendo.

Em ter, 30 de jan de 2018 16:55, juliofozz <notifications@github.com>
escreveu:

**Comment by juliofozz** [comment]
Só mais umas informações, desculpe minha ignorância, mas este projeto "nfe", não posso incorporar em meu projeto né? Tipo terei sempre que ter dois rodando em paralelo? não há como fundir os dois pra se tornar uma aplicação somente? Se tem como, como fazer?? A respeito desse projeto "nfe", como faço pra rodar ele, a minha ferramenta Netbeans fica avisando que ele não tem nenhuma classe principal, como rodo esta aplicação em minha maquina?
Obrigado pela atenção!

**Comment by yelken** [comment]
@juliofozz Você precisa criar uma classe Main e criar as suas configurações e emissão de nota mas lá nos resources de testes tem alguns exemplos que podes se basear para iniciar.

Sobre integrar o NFE no seu projeto, eu não recomendo por ser um projeto grande e dará um trabalho para juntar.

Recomendo que você transforme a Fachada que irás utilizar em um micro serviço e chamar no outro projeto.

Dessa maneira você tem o emissor independente.

**Comment by juliofozz** [comment]
Obrigadão @yelken , já criei um novo pacote e dentro uma classe principal, agora eu preciso saber quais classes invocar dentro desta classe, qual devo invocar primeiro, sendo que uma contem dependências de outras. lembrando que desejo imprimir o documento fiscal auxiliar do consumidor. Obrigado

**Comment by fincatto** [comment]
O ideal é você utilizar o maven para controle de dependencias. Assim, você
não precisa mexer ou integrar no projeto.
Quanto a impressão, a lib não faz diretamente. Há um trabalho do pessoal
num branch a parte, mas acho que não foi muito pra frente. Nesse caso,
recomendo a utilizacao de um outro serviço.
Att

2018-02-07 20:17 GMT-02:00 juliofozz <notifications@github.com>:

**Comment by eldevanjr** [comment]
Desativação da versão anterior(3.10): 02/07/18.

**Comment by estevamdf2** [comment]
Como fazer para montar o xml conforme o novo layout?
@lucas85cunha

**Comment by fincatto** [comment]
A nova versão foi implementada no master, já está habilitada para testes.
Uma nova versão será enviada ao maven central nos proximos dias.
