### ISSUE TITLE
Consulta Status do Serviço de CT-e.

### ISSUE THREAD

**Issue by isaiastavares** [wmixvideo/nfe#282]
Nesse repositório já é possível consultar o status do serviço de NFe e NFC-e.

Mas eu preciso também do serviço de CT-e. Eu me prontifico a desenvolver.

**Comment by fincatto** [comment]
Ola @isaiastavares.
Sua contribuição será muito bem-vinda!
Procuramos sempre manter alguns padrões no projeto, bem como sempre procuramos adicionar testes unitários. Qualquer dúvida, estou a disposição para ajudá-lo!
Att

**Comment by higomatos** [comment]
O CT-e tem estes serviços:

CteRecepcao
CteRetRecepcao
CteInutilizacao
CteConsultaProtocolo
CteStatusServico
CteRecepcaoEvento

@isaiastavares, vc precisa somente do webservice de status do CT-e?

**Comment by pllets** [comment]
É possivel gerar cte Os?

**Comment by fincatto** [comment]
A geração ainda não foi implementada.
Essa semana, desenvolvemos a consulta e download de CTes emitidas.
Att

**Comment by caiocteodoro** [comment]
@fincatto o projeto se encontra na CT-e 2.00 ou a nova versão 3.00?

**Comment by fincatto** [comment]
No repositorio tem somente a 2.0 por hora.
Att

**Comment by caiocteodoro** [comment]
Ok, vou fazer uma contribuição com os arquivos gerados que tenho da 3.00

2017-09-22 12:15 GMT-03:00 Diego Fincatto <notifications@github.com>:

> No repositorio tem somente a 2.0 por hora.
> Att
>
> On Fri, Sep 22, 2017 at 10:23 AM, Caio Cezar Teodoro <
