### ISSUE TITLE
Valor exclusivo duplicado [1] declarado para a restrição de identidade do elemento "infNFe" Ao validar lote.

### ISSUE THREAD

**Issue by fabianofsantos** [wmixvideo/nfe#283]
já conseguir gerar e autorizar várias notas, mas de um determinado cliente quando tento validar recebo esse erro, alguém já passou por isso? o que poderia ser? Lembrando que estou utilizando Certificado A1

**Comment by fincatto** [comment]
Olá @fabianofsantos. Pela mensagem de erro, parece que há dois elementos infNFe onde poderia ter somente um. Verifique a string gerada para confirmar se é isto mesmo.

**Comment by fabianofsantos** [comment]
Justamente isso já resolvi pode fechar, Obrigado pela ajuda!!
