### ISSUE TITLE
Atualizar a parte de Como Usar do README

### ISSUE THREAD

**Issue by isaiastavares** [wmixvideo/nfe#284]
Houve alterações na interface de NFeConfig, mas a parte de como usar não foi atualizada.

**Comment by EliveltonRepolho** [comment]
Estou tendo dificuldades em relação a geração das cadeias do certificado da SEFAZ

utilizei o código de exemplo para geração que segue, mas no método  getCertificadoKeyStore() ele precisa de um pfx... Em relação a isto que estou tendo dúvidas

```java
public static void main(String args[]){
    try {
        FileUtils.writeByteArrayToFile(new File("/tmp/producao.cacerts"), NFGeraCadeiaCertificados.geraCadeiaCertificados(NFAmbiente.PRODUCAO, "senha"));
        FileUtils.writeByteArrayToFile(new File("/tmp/homologacao.cacerts"), NFGeraCadeiaCertificados.geraCadeiaCertificados(NFAmbiente.HOMOLOGACAO, "senha"));
    } catch (Exception e) {
        e.printStackTrace();
    }
}
`

Seria este tipo de atualizações no README que se refere também?

**Comment by isaiastavares** [comment]
@EliveltonRepolho recebi uma notificação de que você havia feito um comentário aqui, mas deve ter apagado. Sua dúvida foi respondida?

Eu estava me referindo a essa parte aqui

![image](https://cloud.githubusercontent.com/assets/6800108/21767903/c8a9521a-d65d-11e6-8898-e2c705f7d54d.png)

O nome dos métodos mudaram, o retorno dos métodos também mudaram e no README não foi atualizado.

Na minha implementação está assim:

![image](https://cloud.githubusercontent.com/assets/6800108/21767929/ecf5d8fa-d65d-11e6-9701-a8e7aca7fc88.png)

O arquivo pfx que você citou ele realmente é necessário. O arquivo pfx é referente ao Certificado Digital que é uma assinatura com validade jurídica que garante proteção às transações eletrônicas e outros serviços via internet, permitindo que pessoas e empresas se identifiquem e assinem digitalmente de qualquer lugar do mundo com mais segurança e agilidade.

**Comment by fincatto** [comment]
Olá @isaiastavares.
Creio que o seu branch esteja desatualizado, não? Procuramos manter o readme sempre atualizados, embora possa ter passado algo em branco. 
Vi no seu PR anterior que o seu branch não havia sido atualizado a bastante tempo então creio que possa ser isso.
Do contrário, indique onde o readme está fora de sincronia com o código que corrigimos (ou você pode mesmo corrigir e propor um PR, você ja é mestre no projeto!).
Att

**Comment by isaiastavares** [comment]
Nossa @fincatto, foi mal! Pode rejeitar essa issue então.
Eu tinha feito um fork desse projeto há muito tempo atrás, aí eu achei que estava atualizado, mas não estava.

Sou noob no GIT, tenho que aprender como deixar meu fork igual o master desse aqui.
Só estou acostumado no SVN kkkkk

Vou ter que aprender um pouco mais sobre GIT kkkkk

**Comment by fincatto** [comment]
Tranquilo @isaiastavares.
