### ISSUE TITLE
Erro 252 ao enviar nfe em Produção.

### ISSUE THREAD

**Issue by eduardomorgon** [wmixvideo/nfe#288]
Ao enviar lote em produção com a tpAmb = 1 o retorno está vindo como homologação tpAmb=2 com a mensagem - Rejeição: Ambiente informado diverge do Ambiente de recebimento.
Gostaria de saber se alguém já passou por esse erro?

Desculpe se esse não é o lugar correto, mas foi a forma que achei de fazer essa pergunta.

**Comment by caiocteodoro** [comment]
@eduardomorgon verifica se na classe NFAutorizador31 a URL de acesso ao Web Service para o seu estado está correta.

**Comment by eduardomorgon** [comment]
Esta sim, acabei de comparar com as urls do site do sefaz com as urls da classe NFAutorizador31.

NfeAutorizacao:
https://nfe.fazenda.sp.gov.br/ws/nfeautorizacao.asmx
NfeRetAutorizacao:
https://nfe.fazenda.sp.gov.br/ws/nferetautorizacao.asmx
NfeInutilizacao2:
https://nfe.fazenda.sp.gov.br/ws/nfeinutilizacao2.asmx
NfeConsulta2:
https://nfe.fazenda.sp.gov.br/ws/nfeconsulta2.asmx
RecepcaoEvento:
https://nfe.fazenda.sp.gov.br/ws/recepcaoevento.asmx
CadConsultaCadastro2:
https://nfe.fazenda.sp.gov.br/ws/cadconsultacadastro2.asmx
NfeStatusServico2:
https://nfe.fazenda.sp.gov.br/ws/nfestatusservico2.asmx

**Comment by caiocteodoro** [comment]
Estranho, tem como mandar o XML gerado?

2017-01-17 13:04 GMT-02:00 Eduardo Morgon <notifications@github.com>:

**Comment by eduardomorgon** [comment]
Para envio o parametro <tpAmb>1</tpAmb> esta setado certo.
Ai no NFLoteEnvioRetornoDados se der um toString() nele, ja volta assim

<retEnviNFe versao="3.10" xmlns="http://www.portalfiscal.inf.br/nfe">
	<tpAmb>2</tpAmb>
        <verAplic>SP_NFE_PL_008i2</verAplic>
	<cStat>103</cStat>
	<xMotivo>Lote recebido com sucesso</xMotivo>
	<cUF>35</cUF>
         ....
 </retEnviNFe>

Detalhe para o tpAmb no retorno para 2.

**Comment by caiocteodoro** [comment]
Quando consultada a nota está em ambiente de produção na SEFAZ SP?

2017-01-17 13:54 GMT-02:00 Eduardo Morgon <notifications@github.com>:

**Comment by eduardomorgon** [comment]
Pelo log4j eu estou vendo que esta sendo enviado em homologação, mesmo eu colocando a cadeia de certificados de produção. Não sei se é isso que esta ocasionando esse problema.

**Comment by isaiastavares** [comment]
@eduardomorgon coloca o código aqui de como está a implementação da NFeConfig.

**Comment by eduardomorgon** [comment]
`

public class NfeConfig extends NFeConfig {
    
    private KeyStore keyStoreCertificado = null;
    private KeyStore keyStoreCadeia = null;
    
    private final String uf;
    private final String certSenha;
  
    private final BfCertificado bfCertificado;

    public NfeConfig(BfCertificado bfCertificado) {
        this.bfCertificado = bfCertificado;
        this.uf = Integer.toString(bfCertificado.getUfSefaz());
        this.certSenha = bfCertificado.getPassw();
    }
    
    
    @Override
    public NFUnidadeFederativa getCUF() {
        return NFUnidadeFederativa.valueOfCodigo(uf);
    }

    @Override
    public String getCertificadoSenha() {
        return this.certSenha;
    }

    @Override
    public String getCadeiaCertificadosSenha() {
        return "changeit";
    }
    
    @Override
    public KeyStore getCertificadoKeyStore() throws KeyStoreException {
        if (this.keyStoreCertificado == null) {
            this.keyStoreCertificado = KeyStore.getInstance("PKCS12");
            try (InputStream certificadoStream = new ByteArrayInputStream(bfCertificado.getArquivo())) {
                this.keyStoreCertificado.load(certificadoStream, this.getCertificadoSenha().toCharArray());
            } catch (CertificateException | NoSuchAlgorithmException | IOException e) {
                this.keyStoreCadeia = null;
                throw new KeyStoreException("Nao foi possivel montar o KeyStore com a cadeia de certificados", e);
            }
        }
        return this.keyStoreCertificado;
    }

    @Override
    public KeyStore getCadeiaCertificadosKeyStore() throws KeyStoreException{
        if (this.keyStoreCadeia == null) {
            this.keyStoreCadeia = KeyStore.getInstance("JKS");
            try (InputStream certificadoCadeia = new ByteArrayInputStream(this.bfCertificado.getTipoAmbiente().getCertificado())) {
                this.keyStoreCadeia.load(certificadoCadeia, this.getCadeiaCertificadosSenha().toCharArray());
            } catch (CertificateException | NoSuchAlgorithmException | IOException e) {
                this.keyStoreCadeia = null;
                throw new KeyStoreException("Nao foi possivel montar o KeyStore com o certificado(cadeia)", e);
            } catch (NullPointerException e) {
                throw new NullPointerException("Não foi possivel carregar o certificado(cadeia): Certificado nulo.");
            }
        }
        return this.keyStoreCadeia;
    }

    
}
`

**Comment by isaiastavares** [comment]
Tá explicado.

O método getAmbiente() retorna o ambiente de homologação por padrão na NFeConfig. Se você deseja alterar, você tem que sobrescrever esse método.

https://github.com/wmixvideo/nfe/blob/master/src/main/java/com/fincatto/nfe310/NFeConfig.java

Adiciona o seguinte método na sua classe NfeConfig.

```
@Override
public NFAmbiente getAmbiente() {
    return NFAmbiente.PRODUCAO;
}
```

**Comment by eduardomorgon** [comment]
@isaiastavares era isso mesmo, como so tinha feito testes em homologação foi um descuido não ter notado isso. pensava que era so alterar o cacerts para ser usado o de produção que ele pegava o ambiente.

No mais, muito obrigado pela ajuda de todos. Abraços.

**Comment by isaiastavares** [comment]
vlw @eduardomorgon , qualquer dúvida, é só falar...

A API usa esse método para escolher qual a URL ele deve mandar o XML, por isso é necessário alterar.

**Comment by eduardomorgon** [comment]
Entendi @isaiastavares, desde já muito obrigado pelas informações. Abraços.
