### ISSUE TITLE
Envio de nota de forma síncrona

### ISSUE THREAD

**Issue by jefperito** [wmixvideo/nfe#29]
Existe apenas a forma de envio no modo assíncrono, criar mecanismo que possibilite  o envio de nota síncrona

**Comment by renanol** [comment]
@jefperito Como anda o andamento dessa issue?

**Comment by jefperito** [comment]
Oi,

Ninguem assinou essa issue para fazer ainda

**Comment by renanol** [comment]
E o que pensaram sobre a questão do uso da NFC-e?

**Comment by jefperito** [comment]
Oi,

Aqui nós não utilizamos NFC-e, então não tem como verificar a funcionalidade em sua plenitude, teria que ser alguém da comunidade desenvolver a funcionalidade

**Comment by renanol** [comment]
#64 Acabei vendo essa issue @jefperito

**Comment by jefperito** [comment]
Foi por engano. Precisa ter a chave de mudança de urls e outros pequenos ajustes.

**Comment by danilomagrini** [comment]
@jefperito Essa implementação síncrona é prevista no manual oficial da NFe? Até onde sei somente há a possibilidade de fazer o envio de forma assíncrona. É possível, obviamente tentar "simular" uma chamada síncrona, todavia não é o formato mais adequado para envio da nota.

**Comment by danilomagrini** [comment]
@jefperito Já desenvolvi uma solução NFe própria e estou disposto ajudar com esse projeto. Porém sou novato aqui no github. Por onde posso começar a entender o funcionamento como por exemplo: "ninguém assinou essa issue". Queria um link de algum howto para que eu possa participar. Grato.

**Comment by jefperito** [comment]
Não há necessidade de assinar, apenas entrar em contato por aqui.

Isso aqui pode ajudar: https://guides.github.com/

**Comment by danilomagrini** [comment]
OK. Vou dar uma analisada no projeto para entender a estrutura e desenvolvo
o  envio síncrono. Eu só precisaria de um certificado A1 pra testar. Mas
vou ver se consigo um. Obrigado.
Em 17/06/2016 17:12, "Jeferson Viana Perito" <notifications@github.com>
escreveu:
