### ISSUE TITLE
Protocolo de Correção

### ISSUE THREAD

**Issue by renancarvalhoo** [wmixvideo/nfe#291]
Vocês não estão gerando o protocolo de correção ? 

Eu vi que foi criado uma classe somente para cancelamento.. mas as vezes precisa gerar o protocolo de correção para enviar ao cliente.

**Comment by higomatos** [comment]
@renancarvalhoo o que seria um "protocolo de correção"?

é referente ao Web Service – RecepcaoEvento – Carta de Correção? Sendo este evento tem a class WSCartaCorrecao

**Comment by walterportugal** [comment]
O protocolo de correção é semelhante ao protocolo de cancelamento ou protocolo da própria NF-e. É um formato de arquivo especificado para ser enviado ao destinatário da NF-e quando um evento da CC-e é gerado. Pode-se verificar no manual da NF-e em **4.8.10 Armazenamento e Disponibilização da Carta de Correção**. Inclusive, eu fiz uma alteração na master para ser possível a geração e estarei fazendo o pull request hoje.
