### ISSUE TITLE
Incluir os Web Services de NFC-e do MS.

### ISSUE THREAD

**Issue by isaiastavares** [wmixvideo/nfe#295]
Na API atual não tem os Web Services de NFC-e do MS.

Os Web Services de Homologação e Produção de MS estão disponíveis nos seguintes links:

Homologação: http://nfce.encat.org/desenvolvedor/webservices-h/
Produção: http://nfce.encat.org/desenvolvedor/webservices-p/

Aproveitar e atualizar as URLs de Homologação de Amazonas também.

Pode assinar a atividade no meu nome que vou fazer o Pull Request.

**Comment by fincatto** [comment]
Feito!
