### ISSUE TITLE
O projeto atende o modelo de notas 021 SP. 

### ISSUE THREAD

**Issue by EMOSAICO** [wmixvideo/nfe#312]
Bom dia,

Quero saber se o projeto (biblioteca) atende o modelo de nota 021 de São Paulo?

Grato.

**Comment by fincatto** [comment]
Não, somente nacional.

**Comment by EMOSAICO** [comment]
Amigo, como assim? Digo, A1 de São Paulo.

**Comment by EMOSAICO** [comment]
Notas do tipo A1 de Sâo Paulo.
