### ISSUE TITLE
Falha nos webservices de NFC da branch 3.0

### ISSUE THREAD

**Issue by danieldhp** [wmixvideo/nfe#314]
Estou realizando testes na branch 3.0 e ocorreu este erro ao consultar o status do serviço:

> {http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico2}NfeStatusServico2 não é um serviço válido. Os serviços válidos são {http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico3}NfeStatusServico3

e o seguinte erro ao enviar um lote:
> {http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao}NfeAutorizacao não é um serviço válido. Os serviços válidos são {http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao3}NfeAutorizacao3

Os erros ocorrem ao tentar instanciar os clientes 
`WSLoteEnvio#comunicaLote`
`new NfeAutorizacao(new URL(endpoint))`

`WSStatusConsulta#efetuaConsultaStatus`
`new NfeStatusServico2(new URL(endpoint))`

**Comment by fauker** [comment]
Comigo deu o seguinte erro quando chama o método `ws.enviaLote`, no ambiente de homologação

```
javax.xml.ws.WebServiceException: javax.xml.bind.MarshalException
 - with linked exception:
[com.sun.istack.internal.SAXException2: com.sun.istack.internal.SAXException2: xmlns has been already bound to . Rebinding it to http://www.portalfiscal.inf.br/nfe is an error
javax.xml.stream.XMLStreamException: xmlns has been already bound to . Rebinding it to http://www.portalfiscal.inf.br/nfe is an error
javax.xml.transform.TransformerException: com.sun.istack.internal.SAXException2: xmlns has been already bound to . Rebinding it to http://www.portalfiscal.inf.br/nfe is an error
javax.xml.stream.XMLStreamException: xmlns has been already bound to . Rebinding it to http://www.portalfiscal.inf.br/nfe is an error]
```

Obs: na branch **master** consigo enviar NFC-e tranquilamente no ambiente de homologação. Só deu o erro na branch **3.0**.
