### ISSUE TITLE
Validação do campo 'quantidadeVendida' em NFNotaInfoItemImpostoPISST

### ISSUE THREAD

**Issue by danieldhp** [wmixvideo/nfe#317]
Ao setar a quantidadeVendida na classe NFNotaInfoItemImpostoPISST está sendo realizado a mesma validação do campo valorAliquota até com a mesma mensagem de erro. 

Esta validação está correta?

Posso fazer um PR caso esteja errada

**Comment by fincatto** [comment]
Deve!
