### ISSUE TITLE
Problemas com nome amigável de certificado

### ISSUE THREAD

**Issue by gapler** [wmixvideo/nfe#319]
Ao utilizar a biblioteca com certificados que não possuem nomes amigáveis, temos o problema de lançar uma exceção NullPointerException no método assinarDocumento em com.fincatto.nfe310.assinatura.assinaturaDigital.

Porque há a necessidade desse nome amigável? O que fazer quando o certificado digital é fornecido pela entidade certificadora sem o nome amigável? 

É possível tornar o item opcional, evitando a exceção?

**Comment by henriquebartoski** [comment]
É possível resolver facilmente o problema do certificado :
https://github.com/wmixvideo/nfe/issues/151#issuecomment-221667690 

Mas seria interessante pensar na possibilidade de tornar opcional.

**Comment by gapler** [comment]
Sim, saber que há como "manualmente" resolver o problema, eu já sabia. O problema mesmo é resolver de uma forma automática, de forma a evitar que o usuário do sistema tivesse que fazer isso. Se é um sistema que pretende ser usado por n pessoas diferentes, precisaríamos de uma forma de ser automático, ou a criação do nome amigável, ou evitarmos ter que pedir esse nome...

**Comment by gapler** [comment]
Desculpe a ignorância, mas o que significa "fincatto added this to the 3.0 milestone 8 hours ago"? Esse recurso foi desenvolvido? Ou será desenvolvimento, no futuro? Preciso pegar uma versão mais nova do projeto?

**Comment by fincatto** [comment]
Será desenvolvido na versão 3.0, que está em andamento.
Se tiveres urgencia para a funcionalidade, vc pode sempre criar um PR, que
adiciono no master sem problemas.
Att

**Comment by gapler** [comment]
@fincatto - Ok, entendi. Nesse caso, eu já consegui criar um workaround para o problema. 

Mas, estou com um problema com o certificado A3. Abri um issue, a #323. 

Esse #323 realmente é algo que eu precisaria de uma ajuda urgente. Se puder, me adiciona no skype - rafaelnsc, que podemos verificar uma consultoria à parte para nos auxiliar com esse problema, se possível. OU se tiver alguém para indicar que nos dê ajude com o problema, também agradeço.
