### ISSUE TITLE
Problema com geração de id para carta de correção

### ISSUE THREAD

**Issue by cpaqui** [wmixvideo/nfe#320]
O metódo gerarDadosCartaCorrecao da classe com.fincatto.nfe310.webservices.WSCartaCorrecao está gerando um id com mais de 54 caracteres, que o limite desse campo, quando o número sequencial do evento é maior 9. O erro está na máscara de formatação na linha 99 como segue:
infoEvento.setId(String.format(**"ID%s%s0%s"**, WSCartaCorrecao.EVENTO_CODIGO, chaveAcesso, numeroSequencialEvento));
Esse máscara deveria ser "ID%s%s%02d".

Como sou não tenho o habito de usar o github para colaborar com os projetos não sei o procedimento para executar a correção e subir o código.

**Comment by fincatto** [comment]
Obrigado!
