### ISSUE TITLE
Problema com atributo CNPJ/ IdEstrangeiro NFe Exterior

### ISSUE THREAD

**Issue by RamonKenedy** [wmixvideo/nfe#321]
Estou adaptando minha aplicação para emitir NFe para o exterior e estou enfrentando um problema:
Tenho que informar a tag CNPJ (do destinatário) vazia, ou informar o IdEstrangeiro.
Como, quase sempre, não existe IdEstrangeiro, tentei deixar o CNPJ nulo para que fosse gerado a tag vazia ou setar o IdEstrangeiro vazio. Nas duas situações tenho o seguinte erro de retorno:
Foi detectado um conteúdo inválido começando com o elemento 'xNome'. Era esperado um dos '{"http://www.portalfiscal.inf.br/nfe":CNPJ, "http://www.portalfiscal.inf.br/nfe":CPF, "http://www.portalfiscal.inf.br/nfe":idEstrangeiro}'.

**Comment by fincatto** [comment]
Essa é uma validação da Sefaz, indicando que, ao menos um dos 3 deve haver.
Há algo na documentação que vá contra isso?

**Comment by RamonKenedy** [comment]
Não tem nada errado com a documentação, o problema é quando não se tem um IdEstrangeiro, o correto seria informar a tag CNPJ vazia no XML, porem da forma como esta, ao gerar o XML para envio do sefaz, é ignorado o CNPJ nullo ou o IdEstrangeiro vazio, ficando sem uma das tags obrigatórias, gerando esse erro.

**Comment by RamonKenedy** [comment]
`<dest>  
<CNPJ></CNPJ>  
<xNome>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xNome>  
<enderDest>  
(...)  
</enderDest>  
<IE></IE>  
</dest>  `

**Comment by walterportugal** [comment]
As orientações do manual para esse caso são:

"*Informar o CNPJ ou o CPF do destinatário, preenchendo os*
*zeros não significativos. No caso de operação com o exterior,*
*ou para comprador estrangeiro informar a tag "idEstrangeiro",*
*com o número do passaporte ou outro documento legal para*
*identificar pessoa estrangeira (campo aceita valor nulo).*"

Ou seja, sempre que for operação com estrangeiro, o CNPJ OU o CPF devem ser
preenchidos com zeros...

Assim que sempre fizemos no nosso sistema.

Em qui, 23 de mar de 2017 às 12:04, RamonKenedy <notifications@github.com>
escreveu:

**Comment by RamonKenedy** [comment]
Ah sim, vou tentar dessa forma, obrigado pela ajuda!
