### ISSUE TITLE
Capturar certificado A3

### ISSUE THREAD

**Issue by gapler** [wmixvideo/nfe#323]
Senhores:

Já abrir algumas discussões no DISQUS sobre a possibilidade de se utilizar a captura de certificado A3 usando a biblioteca, mas até agora não obtive nenhum retorno satisfatório. Esse recurso está disponível? Se está, qual é a possibilidade de ser feito um registro de um exemplo? Porque os exemplos que existem no DISQUS (e que alguns usuários informando que funcionam, não estão funcionando...). Se não está funcionando, há alguma possibilidade de vir a funcionar no futuro?

**Comment by Heverton** [comment]
Bom dia,

fiz uma breve pesquisa na internet e encontrei [(http://www.javac.com.br/jc/posts/list/222-resolvendo-o-problema-4037-forbidden-para-certificado-a3-protocolsocketfactory.page)].

Vou examinar o código mas tarde e tentar contribuir com a solução do problema.

Parabéns pelo projeto.

**Comment by fincatto** [comment]
Obrigado! ;)
