### ISSUE TITLE
Situação Tributária Inválida

### ISSUE THREAD

**Issue by rafaelbomfim** [wmixvideo/nfe#324]
No caso de empresas optantes do Simples Nacional não há cobrança de PIS e COFINS.
Então utilizei a opção OUTRAS_OPERACOES

`aliq.setSituacaoTributaria(NFNotaInfoSituacaoTributariaPIS.OUTRAS_OPERACOES);`

Mas sempre retorna Situação Tributária Inválida.

Na classe NFNotaInfoItemImpostoPISAliquota tem o seguinte método

`    public void setSituacaoTributaria(final NFNotaInfoSituacaoTributariaPIS situacaoTributaria) {
        if (!NFNotaInfoSituacaoTributariaPIS.OPERACAO_TRIBUTAVEL_CUMULATIVO_NAO_CUMULATIVO.equals(situacaoTributaria) && !NFNotaInfoSituacaoTributariaPIS.OPERACAO_TRIBUTAVEL_ALIQUOTA_DIFERENCIADA.equals(situacaoTributaria)) {
            throw new IllegalStateException("Situacao tributaria invalida");
        }
        this.situacaoTributaria = situacaoTributaria;
    }`

Ou seja, se a opção não for OPERACAO_TRIBUTAVEL_CUMULATIVO_NAO_CUMULATIVO ou OPERACAO_TRIBUTAVEL_ALIQUOTA_DIFERENCIADA sempre vai gerar exceção.

Como fazer no caso de optantes do simples?

**Comment by fincatto** [comment]
Boa tarde @rafaelbomfim.
Você confirmou que a situação é "outras" mesmo?
Se for, confirme aqui que poderemos alterar o metodo.
Você poderia, neste caso, criar um PR com os devidos testes unitários, para que possamos adicionar o código ao projeto?
Att

**Comment by rafaelbomfim** [comment]
Bom dia @fincatto 
A situação é outras mesmo, mas o projeto está correto.
Eu é que não estava sabendo utilizar.

A situação não deveria ser setada diretamente.
O uso correto seria mais ou menos assim:

`    private NFNotaInfoItemImpostoPIS getPis(NotaFE entity) {
        NFNotaInfoItemImpostoPIS pis = new NFNotaInfoItemImpostoPIS();
        NFNotaInfoItemImpostoPISOutrasOperacoes oo = new NFNotaInfoItemImpostoPISOutrasOperacoes();
        oo.setSituacaoTributaria(NFNotaInfoSituacaoTributariaPIS.OUTRAS_OPERACOES);
        oo.setValorBaseCalculo(BigDecimal.ZERO);
        oo.setPercentualAliquota(BigDecimal.ZERO);
        oo.setValorTributo(BigDecimal.ZERO);
        pis.setOutrasOperacoes(oo);
        return pis;
    }

    private NFNotaInfoItemImpostoCOFINS getConfins(NotaFE entity) {
        NFNotaInfoItemImpostoCOFINS cofins = new NFNotaInfoItemImpostoCOFINS();
        NFNotaInfoItemImpostoCOFINSOutrasOperacoes oo = new NFNotaInfoItemImpostoCOFINSOutrasOperacoes();
        oo.setSituacaoTributaria(NFNotaInfoSituacaoTributariaCOFINS.OUTRAS_OPERACOES);
        oo.setQuantidadeVendida(BigDecimal.ZERO);
        oo.setValorAliquota(BigDecimal.ZERO);
        oo.setValorCOFINS(BigDecimal.ZERO);
        cofins.setOutrasOperacoes(oo);
        return cofins;
    }`

Só descobri isso ontem.

O projeto está correto!!

Aproveito o contato para deixar os meus parabéns pela iniciativa.

**Comment by fincatto** [comment]
Obrigado @rafaelbomfim.
Esperamos que lhe seja bastante util!
[]s
