### ISSUE TITLE
Emissao NFCe

### ISSUE THREAD

**Issue by Renatocff** [wmixvideo/nfe#331]
Ola, boa noite!
Estou começando a estudar a API mais devido a mesma ter um nível bem complexo..eu estou um pouco perdido em como fazer algumas operações.

Alguem teria algum exemplo de como gero NFCe?

Consegui testar status do serviço aqui na Bahia..consegui gerar os cacerts..mais não passei disso.

**Comment by brinfoleo** [comment]
Boa tarde!
Poderia me passar a planta de como vc fez pra pegar o status do servidor?
Obrigado!
