### ISSUE TITLE
A lib atende o modelo de notas A1 de São Paulo?

### ISSUE THREAD

**Issue by estevamdf2** [wmixvideo/nfe#333]
Quero saber se consigo utilizar a biblioteca para emitir notas do tipo A1 de São Paulo ? 
Desde já agradeço.

**Comment by EMOSAICO** [comment]
Por favor, peço ajuda neste item.

Quero saber se consigo utilizar a biblioteca para emitir notas do tipo A1 de São Paulo ?

No aguardo.

**Comment by isaiastavares** [comment]
@estevamdf2, @EMOSAICO, não entendi muito bem sua dúvida.

Quando vocês dizem notas do tipo A1, vocês se referem a Nota Fiscal de Papel? Se for, essa biblioteca não atende, inclusive acredito que esse modelo nem seja mais utilizado, pois a Nota Fiscal Eletrônica (NF-e) veio justamente para substituir esse modelo.

Ou vocês quiserem dizer Nota Fiscal de Serviço (NFS-e)? Se for, essa biblioteca também não atende.

Ou vocês estão querendo perguntar se essa biblioteca atende Nota Fiscal Eletrônica (NF-e) com certificado do tipo A1? Se for, isso sim atende.

Essa biblioteca atende Emissão de NF-e e NFC-e somente.

**Comment by estevamdf2** [comment]
@isaiastavares agradeço pelos esclarecimentos. Procuramos aqui o setor de faturamento da empresa para obtermos mais informações. A nota que precisamos emitir e a modelo 021 (nota fiscal de comunicação modelo 21) utilizada para emissão dos serviços de comunicação.
Nós conseguimos enviar este tipo de serviço através da NF-e ou NFC-e?

Link: http://www.anatec.org.br/index.php/opiniao/marcelo-de-sousa/599-nota-fiscal-de-comunicacao-modelo-21

**Comment by isaiastavares** [comment]
@estevamdf2 

Muito interessante, eu realmente não conhecia esse modelo.

Atualmente, essa API não emite nota fiscal nesse modelo 021. Mas talvez seria interesse implementar.
Mas para isso, temos que achar uma documentação que informa como deve ser feito essa integração. Eu procurei rapidamente aqui e não encontrei.

Respondendo a sua pergunta:

> Nós conseguimos enviar este tipo de serviço através da NF-e ou NFC-e?

Não tem como, são modelos bem diferentes.

**Comment by estevamdf2** [comment]
@isaiastavares 
Desde já agradecemos  pelo feedback. Muito obrigado.
