### ISSUE TITLE
URL's para geração de QRCode da PB foram modificadas.

### ISSUE THREAD

**Issue by nielsonjr** [wmixvideo/nfe#335]
As URL's para a geração de QRCode do cupom para a PB foram alteradas. O http/https é obrigatório.

Homologação: https://www.receita.pb.gov.br/nfcehom
Produção: https://www.receita.pb.gov.br/nfce

Fonte: http://nfce.encat.org/desenvolvedor/qrcode/ 

Gostaria de saber como faço para colaborar com o projeto e qual branch devo utilizar para tal propósito. Já fiz a alteração na minha máquina e gostaria de atualizar o projeto.

**Comment by fincatto** [comment]
Boa tarde.
A forma mais simples é fazer um PR para nós!
Att

2017-05-22 16:04 GMT-03:00 nielsonjr <notifications@github.com>:
