### ISSUE TITLE
Submeter serialização de objeto do xml do envio da nota e do protocolo de recebimento da nota.

### ISSUE THREAD

**Issue by estevamdf2** [wmixvideo/nfe#336]
Senhores fizemos uma classe que lê o xml do envio da nota <enviNfe> e do protocolo do envio da nota fiscal <retConsReciNFe>. Esta classe retorna um objeto populado com os respectivos nós/elementos/atributos.
Queremos disponibilizar o código, mas precisamos de dicas para realizar os testes para está funcionalidade e qual a melhor forma de submeter isso?
@lucas85cunha
@ambroiler
@emosaico

**Comment by fincatto** [comment]
Não entendi como isso se encaixa no projeto? Tem como descrever melhor?
