### ISSUE TITLE
297 Assinatura difere do calculado.

### ISSUE THREAD

**Issue by simmifelipe** [wmixvideo/nfe#338]
Olá pessoal, estou com essa rejeição na hora de autorizar o lote.
Alguém sabe qual pode ser a causa. Estou removendo os espaços e os caracteres especiais.
Segue o XML de envio do lote.

`<enviNFe versao="3.10" xmlns="http://www.portalfiscal.inf.br/nfe"><idLote>330100000000001</idLote><indSinc>1</indSinc><NFe><infNFe Id="NFe43170691362590006270550000000394461582538744" versao="3.10"><ide><cUF>43</cUF><cNF>58253874</cNF><natOp>0018-REMESSA P/CONSERTO OU REPARO (NO ESTADO)</natOp><indPag>1</indPag><mod>55</mod><serie>0</serie><nNF>39446</nNF><dhEmi>2017-06-05T09:45:17-03:00</dhEmi><tpNF>1</tpNF><idDest>1</idDest><cMunFG>4316501</cMunFG><tpImp>1</tpImp><tpEmis>1</tpEmis><cDV>4</cDV><tpAmb>2</tpAmb><finNFe>1</finNFe><indFinal>0</indFinal><indPres>1</indPres><procEmi>0</procEmi><verProc>nfe3g</verProc></ide><emit><CNPJ>91362590006270</CNPJ><xNome>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xNome><enderEmit><xLgr>AV. DUQUE DE CAXIAS</xLgr><nro>0359</nro><xBairro>CENTRO</xBairro><cMun>4316501</cMun><xMun>SALVADOR DO SUL</xMun><UF>RS</UF><CEP>95750000</CEP><cPais>1058</cPais><xPais>BRASIL</xPais><fone>00555136385000</fone></enderEmit><IE>2210014632</IE><CRT>3</CRT></emit><dest><CNPJ>02090299000148</CNPJ><xNome>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xNome><enderDest><xLgr>AV. SALDANHA DA GAMA</xLgr><nro>658</nro><xBairro>CENTRO</xBairro><cMun>4318705</cMun><xMun>SAO LEOPOLDO</xMun><UF>RS</UF><CEP>93010230</CEP><cPais>1058</cPais><xPais>BRASIL</xPais><fone>5135921000</fone></enderDest><indIEDest>1</indIEDest><IE>1240169032</IE></dest><det nItem="1"><prod><cProd>0077165</cProd><cEAN></cEAN><xProd>MAQUINA CORTAR CABELO HOMEPRO BASIC-WAHL</xProd><NCM>85102000</NCM><CFOP>5915</CFOP><uCom>PC</uCom><qCom>1</qCom><vUnCom>45.9789</vUnCom><vProd>45.97</vProd><cEANTrib></cEANTrib><uTrib>PC</uTrib><qTrib>1</qTrib><vUnTrib>45.9789</vUnTrib><indTot>1</indTot></prod><imposto><vTotTrib>18.78</vTotTrib><ICMS><ICMS51><orig>0</orig><CST>51</CST><modBC>3</modBC><pRedBC>0.00</pRedBC><vBC>0.00</vBC><pICMS>0.00</pICMS><vICMSOp>0.00</vICMSOp><pDif>100.00</pDif><vICMSDif>0.00</vICMSDif><vICMS>0.00</vICMS></ICMS51></ICMS><IPI><cEnq>999</cEnq><IPINT><CST>03</CST></IPINT></IPI><PIS><PISOutr><CST>49</CST><vBC>0.00</vBC><pPIS>0.00</pPIS><vPIS>0.00</vPIS></PISOutr></PIS><COFINS><COFINSOutr><CST>49</CST><vBC>0.00</vBC><pCOFINS>0.00</pCOFINS><vCOFINS>0.00</vCOFINS></COFINSOutr></COFINS></imposto></det><total><ICMSTot><vBC>0.00</vBC><vICMS>0.00</vICMS><vICMSDeson>0.00</vICMSDeson><vBCST>0.00</vBCST><vST>0.00</vST><vProd>45.97</vProd><vFrete>0.00</vFrete><vSeg>0.00</vSeg><vDesc>0.00</vDesc><vII>0.00</vII><vIPI>0.00</vIPI><vPIS>0.00</vPIS><vCOFINS>0.00</vCOFINS><vOutro>0.00</vOutro><vNF>45.97</vNF><vTotTrib>18.78</vTotTrib></ICMSTot></total><transp><modFrete>1</modFrete><transporta><IE></IE><xEnder></xEnder></transporta><vol><qVol>1</qVol><nVol>0000000001</nVol><pesoL>0.000</pesoL><pesoB>0.000</pesoB></vol></transp><infAdic><infAdFisco>ICMS diferido cfe.Livro III, Art.1 Ap.II,Sec.I,Item I RICMS/RS</infAdFisco><infCpl>TOTAL IMPOSTOS PAGOS R$ 18.78(40.85%)Fonte:IBPT Fat.: OFICINA-AS Ordem Compra:</infCpl></infAdic></infNFe></NFe></enviNFe>`

**Comment by fincatto** [comment]
Como está o problema? Conseguiu resolver?
