### ISSUE TITLE
Caminho relativo para o campo chave na impressão da Nota

### ISSUE THREAD

**Issue by andrewasem** [wmixvideo/nfe#341]
Na impressão da nota o jasper se encontra com o campo chave com o caminho relativo, onde na verdade deveria conter o caminho absoluto.

Estava olhando que a versão 3.0 está com o caminho absoluto para o campo chave da nota.
Será feito algum merge? Posso realizar um commit com esta correção?

**Comment by fincatto** [comment]
Pode!
