### ISSUE TITLE
Erro: 298 - Assinatura difere do padrão do Projeto

### ISSUE THREAD

**Issue by andersonajx** [wmixvideo/nfe#344]
Olá pessoal.

Estou implementando a NF-e no meu sistema e até o momento está tudo certo. Está enviando o lote com sucesso, gerei os CaCerts e tudo mais. Porém, quando eu consulto o lote, pra ver se a nota foi processada, ele me retorna o seguinte erro: **298 - Assinatura difere do padrao do Projeto**

O que será que pode estar faltando? Fiz exatamente igual está na documentação de vocês. 

Meu certificado é da Valid.

Obrigado.
Abraços.

P.S. Projeto espetacular e quero colaborar com uma mudança na geração dos CaCerts, mas fica pra outra conversa hehe.

**Comment by fincatto** [comment]
Ola Anderson.
Esse é um retorno de erro deles. Eu já vi em foruns o pessoal com esse
mesmo erro, mas, em todos os casos, a solução parece ter sido um "passe de
mágica", ou algo alterado pela própria Sefaz.
Por motivo de historico, pra qual UF você está mandando? É homologação ou
produção?
Você chegou a testar um outro serviço além do lote?
Att

2017-06-27 9:24 GMT-03:00 Anderson Clayton <notifications@github.com>:

**Comment by andersonajx** [comment]
Humm, será que pode ser algo com o CNPJ? Precisa liberar o CNPJ na Receita?
Eu estou mandando do PR para PR, em homologação. Não testei em produção ainda.
Eu fiz o cancelamento e carta de correção, mas pela nota não ter sido processada, não deu certo esses dois. Me retorna Chave Inexistente.
