### ISSUE TITLE
Onde está a tag/branch 2.0.3-SNAPSHOT

### ISSUE THREAD

**Issue by betonetotbo** [wmixvideo/nfe#345]
A um tempo atrás atualizei a dependência do meu projeto para usar uma tag/branch chamada `2.0.3-SNAPSHOT`. Via https://jitpack.io configurei para:

```
<dependency>
	<groupId>com.github.wmixvideo</groupId>
	<artifactId>nfe</artifactId>
	<version>2.0.3-SNAPSHOT</version>
</dependency>
```
Hoje ao obter o projeto, ocorreu que o jitpack não encontrou mais essa tag/branch.

Como posso resolver isso? Não me recordo do motivo de ter saído da versão 2.0.2 para essa snapshot.

**Comment by fincatto** [comment]
Estranho, não está mais no mvnrepository tb.
Pra resolver rápido, você pode baixar o fonte para aquela versão e dar um
mvn install.
Ou então atualizar para a snapshot, com install tb.
Assim que conseguir, vou subir a 2.0.4 pro maven.
Att

2017-06-27 11:48 GMT-03:00 betonetotbo <notifications@github.com>:

**Comment by betonetotbo** [comment]
Certo amigo, mas qual tag/branch é referente a 2.0.3-SNAPSHOT ?

**Comment by fincatto** [comment]
O branch ja foi aplicado no master, por ser uma versão passada.
Pelo log dá pra chegar nela (vide log do pom).
Att

**Comment by betonetotbo** [comment]
Então posso usar a `master`.
Tem previsão para vocês liberarem a versão 2.0.4 no maven ?

**Comment by fincatto** [comment]
Ela está pronta.
Vou ver se consigo liberar até o final de semana.
Att

**Comment by betonetotbo** [comment]
Nada ainda colega?

**Comment by fincatto** [comment]
Bom dia.
Acabei de liberar a 2.0.4 em produção:
https://oss.sonatype.org/content/repositories/releases/com/github/wmixvideo/nfe/
As snapshots, incluindo a 2.0.3, você encontra em:
https://oss.sonatype.org/content/repositories/snapshots/com/github/wmixvideo/nfe/
PS: O release vai pro Maven Central, mas pode demorar um pouco pros
repositórios sincronizarem.
Att
Diego Fincatto
