### ISSUE TITLE
NFCe - Rejeição 813

### ISSUE THREAD

**Issue by Raiduster** [wmixvideo/nfe#348]
Bom dia time.

Aconteceu algo curioso aqui comigo e preciso da ajuda de vocês.
Tenho um servidor hoje com Tomcat 7, rodando o projeto de NFCe tranquilamente, ontem montamos um servidor novo e começamos a tomar o erro 813 da sefaz do Rio Grande do Sul

O erro é: 813 - Rejeicao: QR-Code com sequencia de escape para o e-comercial. Usar CDATA

Descobrimos que o problema está nas libs que o servidor antigo tinha e o novo não, no servidor antigo colocamos dentro da pasta lib do Tomcat todos os jars do projeto JAX-WS, o servidor novo não tem esses jars dentro da pasta lib do Tomcat. O projeto funciona normalmente, sem erro de compilação, os xmls são gerados idênticos, porém a Sefaz retorna o erro para todas as notas geradas pelo servidor novo.

Sabem dizer o que pode ser?

**Comment by fincatto** [comment]
Boa tarde Joao Paulo.
Vocês se atentaram para o encoding das Strings?
Att

2017-07-20 12:20 GMT-03:00 João Paulo Cruz <notifications@github.com>:

**Comment by Raiduster** [comment]
Olá @fincatto o pessoal da Sefaz me disse que o XML está sendo enviado sem o CDATA, porém o xml que extraio da Biblioteca está com o CDATA, 

Utilizo o código xxxxx.getLoteAssinado().getNotas().get(0).toString(), ele me retorna o XML com o QrCode já com o CDATA.

Parece que na hora de mandar ele está tirando o CDATA, não entendi o que está acontecendo

![a](https://user-images.githubusercontent.com/23453690/28433812-71a42d3a-6d63-11e7-8175-54d91b56f1af.jpg)

**Comment by fincatto** [comment]
Não parece ser algo que a lib faria.
Tente logar o xml gerado na hora do envio.
Att

2017-07-20 15:55 GMT-03:00 João Paulo Cruz <notifications@github.com>:

**Comment by Raiduster** [comment]
Só funciona depois que adiciono essas libs 
![a](https://user-images.githubusercontent.com/23453690/28462619-5b6c41bc-6df2-11e7-9104-75b609873edf.png)

Deixando somente dependências da biblioteca não funciona

![b](https://user-images.githubusercontent.com/23453690/28462650-7986ae3a-6df2-11e7-9516-680f3ee6d717.png)


Vamos avançar na busca, mas realmente não entendemos o que pode estar rolando.


Obrigado
