### ISSUE TITLE
Configurando NFeConfig para certificado A3

### ISSUE THREAD

**Issue by fauker** [wmixvideo/nfe#349]
Pessoal, tenho uma pergunta para quem está utilizando a lib com certificado A3 na `master`. 

Como vocês configuraram o carregamento da **KeyStore** classe `NFeConfig`? 

Minha aplicação é **web**. Para certificados A3 é necessário instalar um app desktop feito com swing. Até então, minha `NFeConfig` estava configurada com um certificado A1 estático (só pra abrir as conexões SSL) e eu estava assinando o arquivo XML por meio do meu app desktop e devolvendo pra app web enviar já assinado. Sem erros.

Mas, sempre que eu [valido](https://www.sefaz.rs.gov.br/nfe/nfe-val.aspx) o XML autorizado de um cliente, o certificado do titular vem em nome da empresa do meu certificado estático, e não no nome da empresa que assinou o XML.

Aparentemente é necessário utilizar o certificado A3 do cliente também para abrir as conexões SSL.

Exemplo do validador de XML da SEFAZ: 

`
Certificado Digital do Titular: CN=EMPRESA-DO-MEU-CERTIFICADO-A1-LTDA:11111111 [Visualizar]
`

Sendo que deveria ser:

`
Certificado Digital do Titular: CN=EMPRESA-QUE-ASSINOU-O-XML-LTDA:11111111 [Visualizar]
`

**Comment by edigomes** [comment]
Usa o repositório do Windows pra puxar o A3.

Em 26 de jul de 2017 18:47, "Lucas Moreira" <notifications@github.com>
escreveu:

**Comment by fauker** [comment]
Sim. Eu já faço isso, mas pra assinar o XML e devolver pra app web, porque quem faz toda a comunicação com a SEFAZ é a app web, entende?

**Comment by edigomes** [comment]
Você tem de transmitir usando o A3 também, vai ter que transmitir no App
desktop e retornar o XML protocolado para seu app web.

Em 26 de jul de 2017 19:26, "Lucas Moreira" <notifications@github.com>
escreveu:

**Comment by fauker** [comment]
Saquei. É, eu tava pensando nessa possibilidade.

**Comment by betonetotbo** [comment]
@fauker Você sabe dizer se realmente ainda da pra fazer isso que você citou no post acima: assinar o XML de NF-e com um certificado A3 e transmitir com um certificado A1 de propriedade da minha empresa desenvolvedora?
