### ISSUE TITLE
Compilação - error: try-with-resources is not supported in -source 1.6

### ISSUE THREAD

**Issue by gestefane** [wmixvideo/nfe#354]
Olá,
Estou tentando compilar um projeto para testes com o pacote nfe e estou obtendo esse erro.
Abaixo a saída completa do console apos compilacao. 
Estou usando JDK 1.7.
Agradeço a colaboração.

`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building MyApp 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ common14 ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 11 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ common14 ---
[INFO] Compiling 321 source files to myPath\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] <myApppath>\NFeConfigFake.java:[27,16] error: try-with-resources is not supported in -source 1.6
[ERROR] <myAppPath>\NFeConfigFake.java:[29,42] error: multi-catch statement is not supported in -source 1.6
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.180s
[INFO] Finished at: Sun Aug 27 23:38:04 BRT 2017
[INFO] Final Memory: 16M/224M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project common14: Compilation failure: Compilation failure:
[ERROR] <myApppath>\NFeConfigFake.java:[27,16] error: try-with-resources is not supported in -source 1.6
[ERROR] <myApppath>\NFeConfigFake.java:[29,42] error: multi-catch statement is not supported in -source 1.6
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`

As linhas reportadas 27 e 29 seguem abaixo, são do try e do catch (classe NFeConfigFake.java do proprio repositorio)

`
    @Override

    public KeyStore getCertificadoKeyStore() throws KeyStoreException {
        if (this.keyStoreCertificado == null) {
            this.keyStoreCertificado = KeyStore.getInstance("PKCS12");
            try (InputStream certificadoStream = NFeConfigFake.class.getResourceAsStream("homologacao.pfx")) {
                this.keyStoreCertificado.load(certificadoStream, this.getCertificadoSenha().toCharArray());
            } catch (CertificateException | NoSuchAlgorithmException | IOException e) {
                this.keyStoreCadeia = null;
                throw new KeyStoreException("Nao foi possibel montar o KeyStore com a cadeia de certificados", e);
            }
        }
        return this.keyStoreCertificado;
    }
`

**Comment by fincatto** [comment]
Bom dia.
Pela sua saída de erro, você está compilando seu codigo para java 1.6:
[ERROR] \NFeConfigFake.java:[27,16] error: try-with-resources is not
supported in -source 1.6
[ERROR] \NFeConfigFake.java:[29,42] error: multi-catch statement is not
supported in -source 1.6
Você precisa indicar para o seu compilador a versão do codigo que vc quer
gerar.
Você pode usar como exemplo o pom do projeto nfe.
Att

**Comment by gestefane** [comment]
Realmente, como uso dois projetos, um deles estava com a versao 1.6. Bastou alterar o pom.xml como se segue e pronto, resolvido.

`    <properties>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>
    </properties>
`
Obrigado.
