### ISSUE TITLE
Chave, protocolo e data de emissão null na DANFE

### ISSUE THREAD

**Issue by gestefane** [wmixvideo/nfe#357]
Olá,

Estou com o processo de envio para a SEFAZ funcionando perfeitamente, gerando o XML e DANFE, tudo OK.

Só está ocorrendo um pequeno problema. Na DANFE os campos chave, protocolo e data de emissão estão null.

Abaixo o código que estou usando para carregar o XML para o jasper e exibir o relatorio:
`
		String xml = <minhaClasseQueTemaNotaFiscalEletronica>.get(0).getXml();
		
		String jasperFileName = "..\\..\\..\\danfe\\danfeR3.jasper"; // 

		// carrega xml da nota para um InputStream - funcionando ok
		InputStream stream = new ByteArrayInputStream(xml.getBytes(StandardCharsets.UTF_8));
		
		Map params = new HashMap();
		
		// passa o stream com o xml para o jasper - funcionando ok
		params.put(JRXPathQueryExecuterFactory.XML_INPUT_STREAM, stream);

		// prepara e exibe o relatorio - tudo OK
		try (InputStream in = NFeConfig.class.getResourceAsStream(jasperFileName)) {
			JasperPrint print = JasperFillManager.fillReport(in,params);
			
			byte[] bytes = JasperExportManager.exportReportToPdf(print);

	    	FacesContext facesContext = FacesContext.getCurrentInstance();  
	    	HttpServletResponse response = (HttpServletResponse) facesContext.getExternalContext().getResponse();  
			try {
				ServletOutputStream ouputStream = response.getOutputStream();

				response.setHeader("Content-Type", "application/pdf");
				response.setHeader("Content-disposition","inline; filename=nota.pdf'");
				response.setContentLength(bytes.length);  
				ouputStream.write(bytes, 0, bytes.length);
				ouputStream.flush();
				ouputStream.close();
				facesContext.responseComplete();
			} catch (IOException e) {
				throw new RuntimeException(e);
			}  
			
		}

`

Obrigado.

**Comment by fauker** [comment]
Pode nos mostrar o XML que está sendo retornado no seu getXml()? Ele é o xml processado pela sefaz? 

Att.,

Lucas Moreira

**Comment by gestefane** [comment]
Boa noite Lucas,
Primeiramente, obrigado pela resposta.
Segue anexado o XML.
Coloquei dados de cnpj, ie, ficticios no xml, mas da pra ler e ver o que ta ocorrendo.
Obrigado.
Gestefane


[exemploxml.zip](https://github.com/wmixvideo/nfe/files/1272604/exemploxml.zip)

**Comment by fauker** [comment]
O XML aparentemente está ok, @gestefane. Acho que o problema pode ser algo no DANFE então. Eu não gero meu DANFE pela lib, somente o DANFE NFC-e. Vamos aguardar mais pessoas que utilizam essa feature para ver se está tudo ok, ou se passaram pelo mesmo problema que você.

**Comment by gestefane** [comment]
Ok.

Agora será que alguém pode dizer dizer como os dados do xml são mapeados no jasper. Se tivermos como rastrear o mapeamento dos dados no jasper, podemos efetuar a correção,
