### ISSUE TITLE
Danfe - linha detalhe dos itens

### ISSUE THREAD

**Issue by gestefane** [wmixvideo/nfe#358]
Olá,
Testando a Danfe (danfeR3.jrxml), descobri que as colunas unidade e alíquota de icms do item estão sem "stretch type". Com isso se a descrição de um item usa duas linhas essas duas colunas não acompanham o tamanho das demais. 
Isso só é percebido se colocarmos borda inferior nos campos do item.
Para resolver basta setar "stretch type = Relative to Band Height" nas colunas icms e unidade.

**Comment by fincatto** [comment]
Boa noite @gestefane. Consegue nos enviar um PR com a correção?

**Comment by gestefane** [comment]
Boa noite @fincatto. Estou um pouco apertado com umas demandas de trabalho, mas vou fazer um fork do projeto e assim que possivel envio um PR.
ate+
