### ISSUE TITLE
Formato de data no Danfe

### ISSUE THREAD

**Issue by gestefane** [wmixvideo/nfe#359]
Olá,

Estou tentando definir o formato dd/MM/yyyy nos campos data de emissão e data de saída no danfeR3.jrxml mas só é exibida a data no formato como no exemplo "Sun Sep 03".

As propriedades do campo data de emissão e saída na danfe estão originalmente assim:
Text Field Expression = $F{DataEmissao} != null ? new SimpleDateFormat("yyyy-MM-dd").parse($F{DataEmissao}).toString() : null
Expression Class = java.lang.string
Patthern = dd/MM/yyyy

Obrigado.

Gestefane

**Comment by gestefane** [comment]
[RESOLVIDO]
Bastou retirar o ".toString()" do final da expressão do campo data de emissão e saída:

$F{DataEmissao} != null ? new SimpleDateFormat("yyyy-MM-dd").parse($F{DataEmissao}).toString() : null

ficou assim:

$F{DataEmissao} != null ? new SimpleDateFormat("yyyy-MM-dd").parse($F{DataEmissao}) : null

Fica a sugestão para correção no repositório oficial e fechamento dessa issue.

Gestefane

**Comment by fincatto** [comment]
Você consegue gerar um PR?

2017-09-04 13:06 GMT-03:00 gestefane <notifications@github.com>:

**Comment by gestefane** [comment]
Desculpe Fincatto, traduza PR por favor...

**Comment by fauker** [comment]
@gestefane , **PR** é **Pull Request**, ou seja, você fazer um fork do projeto (*clonar para seu GitHub e ter acesso ao código do seu computador*), editar o que você tiver de editar, e enviar o código para o repositório oficial (este) para que seu código seja mesclado através de um **Pull Request**.

Artigo explicando: https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/

**Comment by gestefane** [comment]
Ah, sim, entendi.
Na verdade não fiz o fork ainda. Mas posso fazer perfeitamente e enviar as alterações sim.
Obrigado.
