### ISSUE TITLE
Mensagem de rejeição de situação tributaria não especifica o tributo

### ISSUE THREAD

**Issue by gestefane** [wmixvideo/nfe#369]
Nas classes como NFNotaInfoItemImpostoIPITributado, NFNotaInfoItemImpostoPISNaoTributado e outras similares, existe a mensagem "Situacao tributaria invalida".

Seria bom especificar na mensagem a qual situação tributaria ela se refere. Por exemplo "Situacao tributaria do IPI invalida".

**Comment by fincatto** [comment]
Sim, ficaria melhor mesmo.

2017-09-28 9:52 GMT-03:00 gestefane <notifications@github.com>:
