### ISSUE TITLE
Consulta por nota PI

### ISSUE THREAD

**Issue by kim-ae** [wmixvideo/nfe#407]
Olá tudo bem?
Gostaria de dizer que esse projeto é excepcional! Basicamente salvou muitas horas de desenvolvimento (que não possuia).
Agora a minha dúvida: Tenho recebido status 410, para consulta de situação de NF-e do estado Piaui. Teoricamente essa biblioteca contempla consulta de status para todos os estados, correto? Pode ser que eu esteja com uma versão da biblioteca muito atrasada?
Desde já agradeço pelo trabalho de todos envolvidos, e espero poder contribuir no futuro!

**Comment by fincatto** [comment]
Boa tarde.
A biblioteca deve suportar todos os estados. Porém, em alguns temos mais pessoas testando e em outros, menos. 
Verifique se você está usando a ultima versão do Maven. Se preferir, baixe os fontes e utilize a versão de desenvolvimento, para verificar se houve alguma alteração que possa ter corrigido algum eventual problema.
Att

**Comment by kim-ae** [comment]
Agradeço sua resposta rápido, tentarei baixar o código direto da master e testar.
