### ISSUE TITLE
Consulta Situação NF-e PI

### ISSUE THREAD

**Issue by kim-ae** [wmixvideo/nfe#408]
Olá boa tarde,
Eu verifiquei no código que de acordo com a documentação no site do governo o WS que está sendo usado para consultar situação de nota do PI está incorreto.

> UF que utilizam a SVAN - Sefaz Virtual do Ambiente Nacional: MA, PA 
>UF que utilizam a SVRS - Sefaz Virtual do RS: 
>- Para serviço de Consulta Cadastro: AC, RN, PB, SC 
>- Para demais serviços relacionados com o sistema da NF-e: AC, AL, AP, DF, ES, PB, PI, RJ, RN, RO, RR, SC, SE, TO 

Fonte: [Portal NF-e Fazenda](http://www.nfe.fazenda.gov.br/PORTAL/WebServices.aspx#SVAN)

No código eu verifiquei no Enum `NFAutorizador31` ele faz o seguinte
```
 @Override
        public String getNfeConsultaProtocolo(final DFAmbiente ambiente) {
            return SVAN.getNfeConsultaProtocolo(ambiente);
        }
```
No caso deveria ser `SVRS`.
Eu não sei exatamente quais as politicas para contribuição, por isso não tentei fazer um PR com essa modificação. Caso não tenha problema posso fazer um PR com esta alteração.
Desde já agradeço pela atenção e pelo trabalho excepcional :)

**Comment by kim-ae** [comment]
Eu clonei o repositório e resolvi, já to com uma branch com a resolução, se me derem permissão para push, posso fazer o push e requisitar o PR. Rodei os testes e ta passando 100%.

**Comment by fincatto** [comment]
Bom dia.
Pode enviar o PR sim, a qualquer momento.
Att
