### ISSUE TITLE
Mudança de versão da biblioteca slf4j

### ISSUE THREAD

**Issue by marlosmorbis** [wmixvideo/nfe#409]
Boa tarde,

Pessoal, tivemos um problema para integrar a nova versão da biblioteca da Nfe 4.00 por causa da versão da biblioteca slf4j, hoje essa biblioteca está no pom com a versão <slf4j.version>1.8.0-beta0</slf4j.version>, essa versão não possui compatibilidade com servidor Jetty 9.3 que usamos no app engine do Google, causando o erro:

```
15:25:03.362:WARN:oejw.WebAppContext:Scanner-1: Failed startup of context o.e.j.w.WebAppContext@33cd6002{/,file:///D:/workspace_intellij/ERP/target/gestao-3/,UNAVAILABLE}
java.lang.RuntimeException: Error scanning entry module-info.class from jar file:///D:/workspace_intellij/ERP/target/gestao-3/WEB-INF/lib/slf4j-api-1.8.0-beta0.jar
at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:937)
```

Nos parece que esse erro acontece por o Jetty 9.3 não suportar o JDK9 que faz esse carregamento de module-info.class.
Realizando testes na integração do nosso sistema com a lib wmixvideo/nfe, mudamos a versão do slf4j para <slf4j.version>1.7.25</slf4j.version> e não gerou nenhum erro nos logs e nem no funcionamento para a emissão das notas na versão 4.00.

Seria possível alterar a versão dessa biblioteca slf4j para a 1.7.25 no pom da wmixvideo/nfe ?

Desde já agradeço pela atenção.

**Comment by fincatto** [comment]
Bom dia.
Creio ser possível sim.
Por favor, envio o PR com essa alteração que adicionaremos ao codigo.
Att
