### ISSUE TITLE
Status sobre a versão Atual

### ISSUE THREAD

**Issue by waldandrade** [wmixvideo/nfe#413]
Pessoal, estou precisando de uma atualização sobre a versão atual.

1 - O Master tá emitindo 4.0, ou ainda tá em um Branch? Qual?

2 - Como faço para utilizar a versão mais nova pelo maven, se for possível. Ou tenho mesmo que fazer o clone do projeto.

3 - O Danfe tá gerando pelo Master, ou tem que usar o Branch Danfe? Tem tutorial disso no Blog?

4 - O readme do repositório está atualizado? Posso seguir ele na confiança?

Obrigado desde já! E desculpem mais uma vez. Já fui muito ativo aqui na comunidade, passei um tempo afastado mas agora estou voltando com tudo. Abraço a todos.

**Comment by eldevanjr** [comment]
Olá @waldandrade , não sou o líder do projeto, mas estou usando e fazendo modificações no projeto, 
respondendo suas perguntas do modo como uso o projeto:
1-Utilizo pra emitir notas nas duas versões usando o branch master, ele está dividido em pastas(ou pacote ou como queira chamar) uma é a nfe310(com.fincatto.documentofiscal.nfe310) e a outra é a nfe400(com.fincatto.documentofiscal.nfe400), ou seja, com o mesmo jar conseguirá emitir nas duas versões.
2-Pra utilizar eu fiz um clone do projeto e construí eu mesmo, utilizando  o comando(mvn clean install -Dgpg.skip=true), não testei sem construir, e então utilizo a versão que está no pom que acabei de construir.
3-Na questão da geração eu utilizo uma ferramenta própria .
4-e o readme do repositório está desatualizado.

**Comment by waldandrade** [comment]
Muito obrigado amigo!

Em sex, 23 de mar de 2018 5:05 PM, Eldevan Nery Junior <
notifications@github.com> escreveu:

**Comment by fincatto** [comment]
Bom dia @waldandrade.
Como o colega @eldevanjr colocou (e ele tem contribuido muito com o projeto), a lib está apta a emitir notas nas duas versões. 
Quanto a danfe, alguns colegas se propuseram a desenvolver e foi criado um branch para facilitar a colaboração, mas acho que eles pararam com o desenvolvimento. Vou dar uma checada nisso e, se realmente estiver desatualizado, vou remover do projeto.
Quanto a liberação para o maven, procuramos liberar quando temos uma versão com novas funcionalidades ou correções e a NFe 4 está sim merecendo uma liberação. Vou providenciar isso durante a semana que vem.
No mais, se econtrar algo desatualizado, podes nos passar ou mandar PR que será muito bem vindo!
Att
