### ISSUE TITLE
Erro 252 ao gerar nota

### ISSUE THREAD

**Issue by alairfonseca** [wmixvideo/nfe#426]
Ao enviar a nota, mesmo sobrescrevendo o método getAmbiente do NFeConfig para que ele retorne NFAmbiente.PRODUCAO e utilizando o 'producao.cacerts', no xml que está sendo montado ele envia o tpAmb como 2 (o que seria homologação).
segue trecho do xml
`<ide>
            <cUF>31</cUF>
            <cNF>00000528</cNF>
            <natOp>5907</natOp>
            <indPag>2</indPag>
            <mod>55</mod>
            <serie>1</serie>
            <nNF>528</nNF>
            <dhEmi>2018-04-27T12:23:48-03:00</dhEmi>
            <tpNF>1</tpNF>
            <idDest>1</idDest>
            <cMunFG>3106200</cMunFG>
            <tpImp>0</tpImp>
            <tpEmis>1</tpEmis>
            <cDV>0</cDV>
            <tpAmb>2</tpAmb>
            <finNFe>1</finNFe>
            <indFinal>0</indFinal>
            <indPres>0</indPres>
            <procEmi>0</procEmi>
            <verProc>14.0.28</verProc>
         </ide>`

**Comment by fincatto** [comment]
Olá @alairfonseca.
Tente reproduzir o bug com a classe NFNotaTest e poste o código pra gente ver.

**Comment by alairfonseca** [comment]
Segue os códigos da controller e da classe de configuracao

`public class NfeController extends Controller {

    @Inject
    private Configuration configuration;

    @Inject
    private Environment environment;

    public CompletionStage<Result> gerarNfe() {

        Logger.debug("--- Enviar NFe ---");

        JsonNode json = request().body().asJson();
        if (json == null) {
            Logger.debug("--- JSON NULL ---");
            return CompletableFuture.completedFuture(badRequest("Expecting Json data"));
        }

        Integer emitenteId = json.get("emitente_id").asInt();
        String numeroLote = json.get("numero_lote").asText();

        if(numeroLote.isEmpty())
            return CompletableFuture.completedFuture(notFound("Número do Lote não encontrado!"));


        Credencial credencial = Credencial.find.where().eq("emitente_id", emitenteId).findUnique();

        if(credencial == null)
            return CompletableFuture.completedFuture(notFound("Emitente não encontrado!"));

        String nomeArquivo = configuration.getString("credencial.pasta").concat(credencial.getId().toString()).concat("/").concat(credencial.getArquivo());
        String certificadoPath = environment.getFile("conf/producao.cacerts").getAbsolutePath();
        NFeConfigTeste config = new NFeConfigTeste(nomeArquivo, credencial.getSenha(), "rarolabs", certificadoPath);

        NFLoteEnvio lote = new NFLoteEnvio();

        final NFNota nota = new NotaParser().notaParaObjeto(new File(json.get("nome_arquivo").asText()));
        ArrayList<NFNota> notas = new ArrayList<NFNota>();
        notas.add(nota);
        lote.setNotas(notas);
        lote.setIdLote(numeroLote);
        lote.setIndicadorProcessamento(NFLoteIndicadorProcessamento.PROCESSAMENTO_ASSINCRONO);
        lote.setVersao("3.10");

        try {
            final NFLoteEnvioRetornoDados retorno = new WSFacade(config).enviaLote(lote);
            System.out.println(lote.toString());
            System.out.println("----------------------------");
            return CompletableFuture.completedFuture(ok(retorno.getRetorno().toString()));
        } catch (Exception e) {
            e.printStackTrace();
            return CompletableFuture.completedFuture(status(INTERNAL_SERVER_ERROR, Json.toJson("deu erro")));
        }

    }

    public CompletionStage<Result> consultarNfe() {
        JsonNode json = request().body().asJson();
        if (json == null) {
            Logger.debug("--- JSON NULL ---");
            return CompletableFuture.completedFuture(badRequest("Expecting Json data"));
        }

        Integer emitenteId = json.get("emitente_id").asInt();
        String numeroRecibo = json.get("numero_recibo").asText();

        if(numeroRecibo.isEmpty())
            return CompletableFuture.completedFuture(notFound("Número do Recibo não encontrado!"));

        Credencial credencial = Credencial.find.where().eq("emitente_id", emitenteId).findUnique();

        if(credencial == null)
            return CompletableFuture.completedFuture(notFound("Emitente não encontrado!"));

        String nomeArquivo = configuration.getString("credencial.pasta").concat(credencial.getId().toString()).concat("/").concat(credencial.getArquivo());
        String certificadoPath = environment.getFile("conf/producao.cacerts").getAbsolutePath();
        NFeConfigTeste config = new NFeConfigTeste(nomeArquivo, credencial.getSenha(), "rarolabs", certificadoPath);

        try {
            NFLoteConsultaRetorno retorno = new WSFacade(config).consultaLote(numeroRecibo, NFModelo.NFE);
            return CompletableFuture.completedFuture(ok(retorno.toString()));
        } catch (Exception e) {
            e.printStackTrace();
            return CompletableFuture.completedFuture(status(INTERNAL_SERVER_ERROR, Json.toJson("deu erro")));
        }
    }

    public CompletionStage<Result> cancelarNfe() {
        JsonNode json = request().body().asJson();
        if (json == null) {
            Logger.debug("--- JSON NULL ---");
            return CompletableFuture.completedFuture(badRequest("Expecting Json data"));
        }

        Integer emitenteId = json.get("emitente_id").asInt();
        String chave = json.get("chave").asText();
        String protocolo = json.get("protocolo").asText();
        String motivo = json.get("motivo").asText();

        if(chave.isEmpty())
            return CompletableFuture.completedFuture(notFound("Chave não encontrada!"));
        if(protocolo.isEmpty())
            return CompletableFuture.completedFuture(notFound("Protocolo não encontrado!"));
        if(motivo.isEmpty())
            return CompletableFuture.completedFuture(notFound("Motivo não encontrado!"));

        Credencial credencial = Credencial.find.where().eq("emitente_id", emitenteId).findUnique();

        if(credencial == null)
            return CompletableFuture.completedFuture(notFound("Emitente não encontrado!"));

        String nomeArquivo = configuration.getString("credencial.pasta").concat(credencial.getId().toString()).concat("/").concat(credencial.getArquivo());
        String certificadoPath = environment.getFile("conf/producao.cacerts").getAbsolutePath();
        NFeConfigTeste config = new NFeConfigTeste(nomeArquivo, credencial.getSenha(), "rarolabs", certificadoPath);

        try {
            NFEnviaEventoRetorno retorno = new WSFacade(config).cancelaNota(chave, protocolo, motivo);
            return CompletableFuture.completedFuture(ok(retorno.toString()));
        } catch (Exception e) {
            e.printStackTrace();
            return CompletableFuture.completedFuture(status(INTERNAL_SERVER_ERROR, Json.toJson("deu erro")));
        }
    }

    public CompletionStage<Result> inutilizarNfe() {
        JsonNode json = request().body().asJson();
        if (json == null) {
            Logger.debug("--- JSON NULL ---");
            return CompletableFuture.completedFuture(badRequest("Expecting Json data"));
        }

        Integer emitenteId = json.get("emitente_id").asInt();
        String emitenteCNPJ = json.get("emitente_cnpj").asText();
        Integer ano = json.get("ano").asInt();
        String serie = json.get("serie").asText();
        String numeroInicial = json.get("numero_inicial").asText();
        String numeroFinal = json.get("numero_final").asText();
        String justificativa = json.get("justificativa").asText();

        if(emitenteCNPJ.isEmpty())
            return CompletableFuture.completedFuture(notFound("CNPJ do emitente não encontrado!"));
        if(ano.toString().isEmpty())
            return CompletableFuture.completedFuture(notFound("Ano não encontrado!"));
        if(serie.isEmpty())
            return CompletableFuture.completedFuture(notFound("Série não encontrada!"));
        if(numeroInicial.isEmpty())
            return CompletableFuture.completedFuture(notFound("Número Inicial não encontrado!"));
        if(numeroFinal.isEmpty())
            return CompletableFuture.completedFuture(notFound("Número Final não encontrado!"));
        if(justificativa.isEmpty())
            return CompletableFuture.completedFuture(notFound("Justificativa não encontrada!"));

        Credencial credencial = Credencial.find.where().eq("emitente_id", emitenteId).findUnique();

        if(credencial == null)
            return CompletableFuture.completedFuture(notFound("Emitente não encontrado!"));

        String nomeArquivo = configuration.getString("credencial.pasta").concat(credencial.getId().toString()).concat("/").concat(credencial.getArquivo());
        String certificadoPath = environment.getFile("conf/producao.cacerts").getAbsolutePath();
        NFeConfigTeste config = new NFeConfigTeste(nomeArquivo, credencial.getSenha(), "rarolabs", certificadoPath);

        try {
            NFRetornoEventoInutilizacao retorno = new WSFacade(config).inutilizaNota(ano, emitenteCNPJ, serie, numeroInicial, numeroFinal, justificativa, NFModelo.NFE);
            return CompletableFuture.completedFuture(ok(retorno.toString()));
        } catch (Exception e) {
            e.printStackTrace();
            return CompletableFuture.completedFuture(status(INTERNAL_SERVER_ERROR, Json.toJson("deu erro")));
        }
    }

    public CompletionStage<Result> corrigirNfe() {
        JsonNode json = request().body().asJson();
        if (json == null) {
            Logger.debug("--- JSON NULL ---");
            return CompletableFuture.completedFuture(badRequest("Expecting Json data"));
        }

        Integer emitenteId = json.get("emitente_id").asInt();
        String chave = json.get("chave").asText();
        String correcao = json.get("correcao").asText();
        Integer sequencia = json.get("num_sequencia").asInt();

        if(chave.isEmpty())
            return CompletableFuture.completedFuture(notFound("Chave não encontrada!"));
        if(sequencia.toString().isEmpty())
            return CompletableFuture.completedFuture(notFound("Número sequencial não encontrado!"));
        if(correcao.isEmpty())
            return CompletableFuture.completedFuture(notFound("Texto correção não encontrado!"));

        Credencial credencial = Credencial.find.where().eq("emitente_id", emitenteId).findUnique();

        if(credencial == null)
            return CompletableFuture.completedFuture(notFound("Emitente não encontrado!"));

        String nomeArquivo = configuration.getString("credencial.pasta").concat(credencial.getId().toString()).concat("/").concat(credencial.getArquivo());
        String certificadoPath = environment.getFile("conf/producao.cacerts").getAbsolutePath();
        NFeConfigTeste config = new NFeConfigTeste(nomeArquivo, credencial.getSenha(), "rarolabs", certificadoPath);

        try {
            NFEnviaEventoRetorno retorno = new WSFacade(config).corrigeNota(chave, correcao, sequencia);
            return CompletableFuture.completedFuture(ok(retorno.toString()));
        } catch (Exception e) {
            e.printStackTrace();
            return CompletableFuture.completedFuture(status(INTERNAL_SERVER_ERROR, Json.toJson("deu erro")));
        }
    }

    public CompletionStage<Result> gerarCadeiaCertificado(){
        try {
            Logger.debug("--- Vai GERAR CADEIA SEFAZ ...");
            FileUtils.writeByteArrayToFile(new File(environment.getFile("conf/producao.cacerts").getAbsolutePath()), NFGeraCadeiaCertificados.geraCadeiaCertificados(NFAmbiente.PRODUCAO, "rarolabs"));
            FileUtils.writeByteArrayToFile(new File(environment.getFile("conf/homologacao.cacerts").getAbsolutePath()), NFGeraCadeiaCertificados.geraCadeiaCertificados(NFAmbiente.HOMOLOGACAO, "rarolabs"));
            Logger.debug("--- CADEIA SEFAZ GERADA COM SUCESSO...");
            return CompletableFuture.completedFuture(ok());
        } catch (Exception e) {
            Logger.error("___[ERRO AO GERAR CADEIA CERTIFICADO SEFAZ]___", e);
            e.printStackTrace();
            return CompletableFuture.completedFuture(status(INTERNAL_SERVER_ERROR, Json.toJson("deu erro")));
        }
    }

}
`

`public class NFeConfigTeste extends NFeConfig {

    private KeyStore keyStoreCertificado = null;
    private KeyStore keyStoreCadeia = null;
    private String certPath;
    private String certPass;
    private String cadeiaPass;
    private String cadeiaPath;

    public NFeConfigTeste(){
    }

    public NFeConfigTeste(String certPath, String certPass, String cadeiaPass, String cadeiaPath){
        this.certPath = certPath;
        this.certPass = certPass;
        this.cadeiaPass = cadeiaPass;
        this.cadeiaPath = cadeiaPath;
    }

    @Override
    public NFAmbiente getAmbiente() {
        System.out.println("chamou getambiente PRODUCAO");
        return NFAmbiente.PRODUCAO;
    }

    @Override
    public NFUnidadeFederativa getCUF() {
        return NFUnidadeFederativa.MG;
    }

    @Override
    public String getCertificadoSenha() {
        return this.certPass;
    }

    @Override
    public String getCadeiaCertificadosSenha() {
        return this.cadeiaPass;
    }

    @Override
    public KeyStore getCertificadoKeyStore() throws KeyStoreException {
        if (this.keyStoreCertificado == null) {
            this.keyStoreCertificado = KeyStore.getInstance("PKCS12");
            try (InputStream certificadoStream = new FileInputStream(this.certPath)) {
                this.keyStoreCertificado.load(certificadoStream, this.getCertificadoSenha().toCharArray());
            } catch (CertificateException | NoSuchAlgorithmException | IOException e) {
                this.keyStoreCadeia = null;
                throw new KeyStoreException("Nao foi possivel montar o KeyStore com a cadeia de certificados", e);
            }
        }
        return this.keyStoreCertificado;
    }

    @Override
    public KeyStore getCadeiaCertificadosKeyStore() throws KeyStoreException {
        if (this.keyStoreCadeia == null) {
            this.keyStoreCadeia = KeyStore.getInstance("JKS");
            try (InputStream cadeia = new FileInputStream(this.cadeiaPath)) {
                this.keyStoreCadeia.load(cadeia, this.getCadeiaCertificadosSenha().toCharArray());
            } catch (CertificateException | NoSuchAlgorithmException | IOException e) {
                this.keyStoreCadeia = null;
                throw new KeyStoreException("Nao foi possivel montar o KeyStore com o certificado", e);
            }
        }
        return this.keyStoreCadeia;
    }
}`

**Comment by mussinato** [comment]
@alairfonseca como você está gerando o xml? O quê você está passando no ambiente da NFNotaInfoIdentificacao?
Assim como o @fincatto disse, se conseguir reproduzir o erro com os testes seria mais fácil para analisar.

**Comment by fincatto** [comment]
Outra informação importante é a versão que está utilizando.
