### ISSUE TITLE
NFC-e 4.0 em ambiente de homologação

### ISSUE THREAD

**Issue by sammubr** [wmixvideo/nfe#428]
Alguém está conseguindo emitir NFC-e 4.0 em ambiente de homologação?
Para mim está ocorrendo a seguinte exceção:

org.apache.axis2.AxisFault: Unable to handle request. The action 'http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4/nfeAutorizacaoLote' was not recognized.

**Comment by fincatto** [comment]
Bom dia @sammubr.
Qual versão você está utilizando?
Outros serviços para a mesma UF estão funcionais?
Caso não esteja, consegue nos fazer um exemplo para melhor analise?

**Comment by fincatto** [comment]
@sammubr Verifique a correção recém postada pelo @claudiobsi.

**Comment by sammubr** [comment]
@fincatto Desculpa pela demora.
É necessário corrigir as URL's do RS também, o que eu já fiz no meu fork.
Só que eu não sei usar muito bem o Github e acabei fazendo um fork para mim para colocar algumas alterações que eu preciso (danfe por exemplo).
Gostaria de contribuir para o projeto original, só que não posso perder minhas alterações e não consigo fazer outro fork.
Posso fazer um pull request, mas vai ir tudo que eu coloquei e não sei se todos aprovariam.
Aceito sugestões.

**Comment by fincatto** [comment]
Com certeza tem, mas eu também não sei de cabeça, teria que pesquisar.
Mas talvez uma forma facil seria fazer o checkout do projeto limpo, fazer as alterações e ja fazer o PR em seguida. Acho que da menos trabalho.
Att

**Comment by sammubr** [comment]
Tentei fazer um branch e fiz um pull request agora há pouco.
