### ISSUE TITLE
ICMS60 - Faltando vBCSTRet para ICMS60

### ISSUE THREAD

**Issue by adelcioportonfe** [wmixvideo/nfe#434]
Tentei parsear o XML de uma NFe que utiliza a classe: NFNotaInfoItemImpostoICMS60.java informando apenas a TAG origem e CST já que as outras TAGs são opcionais, mas retorna XML inválido.
Verifiquei que na classe, esses campos estão com: required = true.
Acredito que se for alterado para false, resolve o problema.
Este é o trecho do código da classe: NFNotaInfoItemImpostoICMS60.java:
Obs: Os 3 campos abaixo deveriam ser: false
-----------------------------------
    @Element(name = "vBCSTRet", required = true)
    private String valorBCICMSSTRetido;

    @Element(name = "pST", required = true)
    private String percentualAliquotaICMSST;

    @Element(name = "vICMSSTRet", required = true)
    private String valorICMSSTRetido;

**Comment by adelcioportonfe** [comment]
Por favor, poderia me orientar como fazer para baixar o projeto, alterar e criar um pull request?

**Comment by fincatto** [comment]
https://tableless.com.br/tudo-que-voce-queria-saber-sobre-git-e-github-mas-tinha-vergonha-de-perguntar/
https://help.github.com/
