### ISSUE TITLE
Enum NFAutorizador400 - MG

### ISSUE THREAD

**Issue by marcoslombardi** [wmixvideo/nfe#441]
A URL do Web Service getNfeConsultaProtocolo do estada de MG esta incorreta tanto em Homologação quanto em Produção.

As corretas seriam

Homologação "https://hnfe.fazenda.mg.gov.br/nfe2/services/NFeConsultaProtocolo4" Produção "https://nfe.fazenda.mg.gov.br/nfe2/services/NFeConsultaProtocolo4"

**Comment by fincatto** [comment]
Boa noite @marcoslombardi.
Você consegue fazer um PR com essa alteração?
Grato!
