### ISSUE TITLE
Geração da DANFE NFCe 4.0

### ISSUE THREAD

**Issue by Raiduster** [wmixvideo/nfe#445]
Bom dia pessoal.
O código abaixo não funciona mais. Eu o usava para gerar a Danfe, como devo proceder para gerar a DANFE nesse novo código? 

byte[] danfe = new NFDanfeReport(notaProcessada).gerarDanfeNFCe(notaProcessada.getNota().getInfo().getInformacoesAdicionais().getInformacoesAdicionaisInteresseFisco(), true, pagamentos.toArray(new NFCePagamento[pagamentos.size()]));

Obrigado

**Comment by fincatto** [comment]
Bom dia.
A geração de danfe estava sendo desenvolvida em um branch a parte, mas os responsaveis por ele pararam de dar manutenção, antes mesmo de o código estar apto para a produção.
Tenho sugerido para os que dependiam daquele código para que o implementem em um projeto a parte, mesmo que dependa deste.
Se fores fazer, pode me avisar que eu coloco o link dele no readme deste, para que outros usuários possam colaborar também.
Att
