### ISSUE TITLE
Problemas ao ultilizar WS de Pernambuco

### ISSUE THREAD

**Issue by AllisonErd** [wmixvideo/nfe#450]
Bom dia a todos!
Estou desenvolvendo meu emissor de Notas na versão 4.00 e quando tento efetuar operações como status do serviço, ou enviar nota recebo os seguintes erros: 
Status do Serviço PE e Envio de Nota em lote pra SEFAZ de Pernambuco: 
`org.apache.axis2.AxisFault: org.xml.sax.SAXException: SimpleDeserializer encountered a child element, which is NOT expected, in something it was trying to deserialize.`

Quando mudo para RS recebo as seguintes menssagens: 
Status do Serviço RS:
`239 - Rejeicao: Versao do arquivo XML nao suportada` (estou passando versão 4.00)

Retorno do envio em lote para WS RS:
`Rejeicao: UF informada no campo cUF nao e atendida pelo Web Service`

Ao que percebi, pode ser algo com as urls, pois olhando os status dos webservices, estão todos ok (segue imagem)
![image](https://user-images.githubusercontent.com/5253151/41042505-34a275ba-6978-11e8-92a1-331139e945af.png)

Agradeço desde já a ajuda, e atenção de todos!
Obrigado.
Att.

**Comment by AllisonErd** [comment]
Pessoa, olhando atentamente a biblioteca, verifiquei as urls da biblioteca, e as urls da Secretaria da Fazenda de Pernambuco, e percebi que as urls estão diferentes: (segue imagem)
![image](https://user-images.githubusercontent.com/5253151/41056560-eb7a8134-699a-11e8-8248-e637aa7594c3.png)
Sendo assim, necessário (acredito) a alteração das mesmas para o funcionamento correto.
Att.

**Comment by henriqueneves** [comment]
Tenta colocar no seu arquivo config:

@Override
    public String getVersao() {
        return "4.00";
    }

**Comment by AllisonErd** [comment]
Segue imagem das urls contidas na biblioteca. Diferem das divulgadas no site da SEFAZ.

![image](https://user-images.githubusercontent.com/5253151/41060586-6847b3a2-69a6-11e8-8064-8f29f3b67229.png)

**Comment by danielbohnrs** [comment]
Fiz a correção das Urls e um pull request (https://github.com/wmixvideo/nfe/pull/451)

**Comment by AllisonErd** [comment]
Obrigado @danielbohnrs. Quanto tempo até chegar no Maven?

**Comment by danielbohnrs** [comment]
Depende da aprovação do Pull request e merge pelos admins

**Comment by AllisonErd** [comment]
Ok @danielbohnrs Muito obrigado pela ajuda!

**Comment by fincatto** [comment]
Haviam dois PR cujos testes estavam quebrados.
Os testes são parte importante da nossa lib, então solicitei a correção dos mesmos.
Assim que o PR estiver saudavel, o codigo sera adicionado na base.
Está agendado uma liberacao para esta semana.
Att

**Comment by AllisonErd** [comment]
Ok @fincatto . Obrigado pela ajuda e atenção, e espero ter ajudado em algo! :)

**Comment by fincatto** [comment]
@danielbohnrs, se conseguires corrigir os testes e reenviar o PR até o inicio da semana, libero uma nova versão no maven já com ela.
No aguardo.

**Comment by danielbohnrs** [comment]
@fincatto não sei exatamente como funciona a parte de testes do projeto. Se puder me esclarecer, aí posso fazer os ajustes necessários para não quebrar nenhum teste.
As alterações que fiz foram nos arquivos NFAutorizador400.java e NFAutorizador400Test.java
O que mais precisa ser feito?

**Comment by fincatto** [comment]
Olá Daniel.
No projeto não tem nada de mais. Você só precisa, ao fazer uma modificação
no sistema, criar um teste que prove que sua solução funcione.
No caso de já haver testes, como no caso das URLs, é só você corrigir os
testes que quebraram e fazer o PR com tudo junto.
Pra saber que está tudo bem, como em qualquer outro projeto com testes,
rode todos os testes da aplicação antes de fazer o PR e, após o PR feito,
acompanhe na página do github se o seu PR não quebrou algo mais, como a
cobertura de testes.
Estando tudo ok nessa página, consigo fazer o merge sem problemas.
No seu caso, se não me engano, você fez dois PR diferentes, um pra classe e
um pro teste, o que fez com que os dois estivessem quebrados.
Se você rodar os testes da aplicação e tiver tudo ok, tente fazer um novo
PR com tudo junto, e acompanhe na pagina o resultado dos testes, que
rodarão em seguida.
Att

2018-06-10 19:57 GMT-03:00 Daniel José Bohn <notifications@github.com>:

**Comment by fincatto** [comment]
Aceito PR! Será liberado no maven essa semana, sob a versão 3.0.1.
