### ISSUE TITLE
"Erro" ao ultilizar ambiente de produção.

### ISSUE THREAD

**Issue by AllisonErd** [wmixvideo/nfe#458]
Bom dia a todos!
Pessoal pode ser algo que eu não esteja sabendo fazer, por isso não afirmo que seja um erro. Estava usando o ambiente de Homologação tranquilamente e sem problemas. Estou enviando, cancelando, consultando o status do serviço, gerando a cadeia de certificados tudo certo. Daí, cheguei no momento de testar algumas coisas no ambiente de produção, e quando mudei de Homologação para produção, para qualquer função que eu venha a executar eu recebo esse erro: 

`Connection has been shutdown: javax.net.ssl.SSLHandshakeException: Server chose TLSv1, but that protocol version is not enabled or not supported by the client.`

Quando altero novamente para Homologação funciona tudo normal. Daí eu não sei se a unica coisa que tem que ser feita é só alterar o metodo 
`@Override
     public DFAmbiente getAmbiente() {
        return DFAmbiente.PRODUCAO;
    }`

na classe NfeConfig, ou se tem mais alguma configuração a fazer. Agradeço a ajuda desde já.
Obrigado.

**Comment by fincatto** [comment]
Na configuração você pode forçar o protocolo de criptografia. Qual você
está usando? Você entendeu a mensagem de erro?

2018-06-14 9:17 GMT-03:00 José Allison <notifications@github.com>:

**Comment by AllisonErd** [comment]
Obrigado por responder. 
Não sabia que existia essa configuração. Estou usando o padrão, que é esse 

` public String[] getSSLProtocolos() {
        return new String[] { "TLSv1.2" };
    }`
No caso, tenho que colocar uma versão desse protocolo na qual o webservice aceite? Qual seria e onde descubro isso?

**Comment by fincatto** [comment]
A propria mensagem de erro lhe indica que é este o problema e qual a versão
que você deve utilizar.

2018-06-14 11:13 GMT-03:00 José Allison <notifications@github.com>:

**Comment by AllisonErd** [comment]
Obrigado @fincatto. Resolvido o problema! :)
