### ISSUE TITLE
cStat 866: xMotivo não preenchido pela SEFAZ

### ISSUE THREAD

**Issue by rnicolletti** [wmixvideo/nfe#459]
Tive uma rejeição em **produção** de código **866**. O XML do retorno do WS veio com a tag xMotivo vazia. <xMotivo />
Gerou o seguinte erro: org.simpleframework.xml.core.ValueRequiredException: Empty value for @org.simpleframework.xml.Element(name=xMotivo, type=void, data=false, required=true) on field 'motivo' private java.lang.String com.fincatto.documentofiscal.nfe400.classes.NFProtocoloInfo.motivo in class 

Como o código de erro está mapeado no enum NFRetornoStatus e neste enum já tem a descrição, poderia fazer uma manutenção para que não dessem erro caso a tag xMotivo retornasse vazia. Retornando o código cStat, já seria possível descobrir a mensagem.
É possível?

O cStat = 866 é a seguinte mensagem: _Ausencia de troco quando o valor dos pagamentos informados for maior que o total da nota_

Olha o retorno:

```
<version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<soap:Body>
<nfeResultMsg xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRetAutorizacao4">
<retConsReciNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe">
<tpAmb>2</tpAmb>
<verAplic>SVRS201806131626</verAplic>
<nRec>533002180362671</nRec>
<cStat>104</cStat>
<xMotivo>Lote processado</xMotivo>
<cUF>53</cUF>
<dhRecbto>2018-06-14T09:34:50-03:00</dhRecbto>
<protNFe versao="4.00">
<infProt>
<tpAmb>2</tpAmb>
<verAplic>SVRS201806131626</verAplic><chNFe>53180626893330000147550010000227881233836591</chNFe>
<dhRecbto>2018-06-14T09:34:50-03:00</dhRecbto>
<digVal>5CrWOb77V3SU4sLocmVVnm3tO6E=</digVal>
<cStat>866</cStat><xMotivo />
</infProt>
</protNFe>
</retConsReciNFe>
</nfeResultMsg>
</soap:Body>
</soap:Envelope>
```

Valeu.

**Comment by rnicolletti** [comment]
Pessoal, o mesmo erro ocorrem em homogação, ok? Motivo não preenchido.

**Comment by fincatto** [comment]
Boa tarde Ricardo.
Como você já consegue provocar o erro, creio que fique mais facil para você
fazer a correção e um PR pra gente.
É possível?
Att

**Comment by rnicolletti** [comment]
Ok, Diego. Estou bem atarefado, mas vou dar um jeito fazer, blz? Valeu.

**Comment by rnicolletti** [comment]
O erro é simples de reproduzir. Basta informar um pagamento maior que o valor total da nota e não informar o troco. ;)

**Comment by fincatto** [comment]
É, todos estamos. Mas nessa crise que o país atravessa, nem podemos
reclamar né? :)
Blz, aguardo seu PR.

**Comment by danielbohnrs** [comment]
Boa tarde,
@rnicolletti tentei reprisar a situação comentada por você.
Retorno do envio:
<retEnviNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>2</tpAmb><verAplic>RS201806141159</verAplic><cStat>103</cStat><xMotivo>Lote recebido com sucesso</xMotivo><cUF>43</cUF><dhRecbto>2018-06-19T16:16:43-03:00</dhRecbto><infRec><nRec>431002194805343</nRec><tMed>1</tMed></infRec></retEnviNFe>

Retorno da consulta do lote:
<retConsReciNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>2</tpAmb><verAplic>RS201710241656</verAplic><cStat>239</cStat><dhRecbto>2018-06-19T16:19:58-03:00</dhRecbto><xMotivo>Rejeicao: Versao do arquivo XML nao suportada</xMotivo><cUF>43</cUF></retConsReciNFe>

Informando o valor de pagamento correto, a nota é autorizada sem problemas. Só não consegui identificar o porque não consigo obter o mesmo erro que comentastes.

Em que UF você fez o teste?

**Comment by rnicolletti** [comment]
Boa tarde. O problema ocorre somente quando der a rejeição 886.
Basta informar um pagamento **maior que o valor total da nota e não informar o troco**.

**Comment by danielbohnrs** [comment]
Foi o que eu fiz. Nota: 199. Valor pago: 200
Sem tag de troco.
![sem troco](https://user-images.githubusercontent.com/9351538/41619997-afc78fa8-73de-11e8-8065-e95a4937ac3f.png)


Tinha visto essa Issue aberta e não tinha reparado que o teu ajuste foi feito Merge ontem.
Se me permitirem, sugiro adicionar o teste de null no getMotivo, para já retornar a descrição mapeada pelo cStat, dessa forma não é necessário ficar testando quando é diferente de null...

`public String getMotivo() {
    	if (this.motivo==null)//quando nao tiver um retorno, usa o motivo padrao identificado pelo cStat
    		return NFRetornoStatus.valueOfCodigo(this.status).getMotivo();
        return this.motivo;
    }`

**Comment by danielbohnrs** [comment]
Desculpe pelo incomodo, consegui reprisar o erro agora.

**Comment by rnicolletti** [comment]
Não precisa validar se o motivo é nulo. A alteração que fiz SEMPRE vai pegar a descrição em NFRetornoStatus. Só importa o retorno de cStat.

**Comment by danielbohnrs** [comment]
Desculpe a ignorância, mas o seu ajuste apenas tirou a obrigatoriedade do xMotivo (https://github.com/wmixvideo/nfe/pull/465/files).  
Se por acaso eu quiser na minha aplicação exibir o motivo retornado da Sefaz para o cliente, terei que testar quando o xMotivo é nulo ou então SEMRPE exibir o que está mapeado no NFRetornoStatus. 
(A minha sugestão é só para poder usar por padrão o xMotivo que retornou da Sefaz, visto que se eles alterarem a mensagem que é exibida para determinado cStat, se não for alterado o código-fonte, continuará sendo apresentado a mensagem antiga para o cliente).

**Comment by rnicolletti** [comment]
Entendi. O motivo continuará sendo retornado pelo WS da SEFAZ. Na minha opinião, deveria usar somente o enum. Mas faça a alteração e o PR.

**Comment by rnicolletti** [comment]
Boa noite, @fincatto . Tem previsão para disponibilizar uma nova versão com o meu merge ou com o merge do colega @danielbohnrs ?

**Comment by fincatto** [comment]
Merge feito. Vamos testar e subo pro maven no inicio da semana.
