### ISSUE TITLE
Problema com tag dhRecbto no xml retConsReciNFe

### ISSUE THREAD

**Issue by cpaqui** [wmixvideo/nfe#463]
Realizando testes no ambiente de homologação da Sefaz para o estado do Rio de Janeiro, quado o retorno é uma rejeição a tag dhRecbto do xml retConsReciNFe não está vindo. Porém no manual e na na classe com.fincatto.documentofiscal.nfe400.classes.lote.consulta.NFLoteConsultaRetorno está como obrigatório.
Alguém mais está passando por esse problema?

**Comment by mussinato** [comment]
Estou com o projeto atualizado e está normal o retorno para o estado do Paraná.
