### ISSUE TITLE
Disponibilizar resultado do processamento do evento de cancelamento.

### ISSUE THREAD

**Issue by rafagsam** [wmixvideo/nfe#464]
Prezados, inicialmente, parabéns pelo excelente trabalho.
Gostaria de sugerir que se fizesse uma alteração na chamada do WS de cancelamento, para que fosse possível criar o xml de processamento do evento (procEventoNFe ou NFProtocoloEventoCancelamento), sem que seja necessário gerar o xml e assinar antes de enviar. Isto acontece pois no evento assinado há um "carimbo de tempo" não permitindo assim geração e assinatura posterior. Como sugestão, e já utilizando a uma forma tratada para a o envio do lote NFe (NFLoteEnvioRetornoDados.java), criar uma classe tipo NFCancelamentoEnvioRetornoDados para encapsular o evento que foi enviado e o retorno do mesmo.

Desde já agradeço a atenção.

**Comment by fincatto** [comment]
A idéia pode ser interessante @rafagsam.
Você consegue fazer um PR com a proposta?

**Comment by fincatto** [comment]
Fechado por nao haver um PR.

**Comment by rafagsam** [comment]
Opa Diego. Desculpe mas não tinha visto seu comentário... Caiu no Spam... Vou preparar uma sugestão envio sim. Obrigado

**Comment by fincatto** [comment]
Ok @rafagsam. Reabri o ticket e vou aguardar o codigo. Obrigado.

**Comment by fincatto** [comment]
Fechando por falta de retorno.
