### ISSUE TITLE
[DUVIDA] Nota Referenciada

### ISSUE THREAD

**Issue by AllisonErd** [wmixvideo/nfe#467]
Boa tarde.
Não sei bem se deveria está abrindo essa issue, mas procurei no canal do Discus e aqui nas issues que já foram abertas e não encontrei nada relacionado. 
Estou precisando gerar uma nota referenciada, porén não estou sabendo como. Vasculhando a biblioteca, encontrei essa classe `NFInfoReferenciada` , porém não estou sabendo onde encaixar e fazer funcionar. Desde já agradeço a ajuda.

**Comment by danielbohnrs** [comment]
Boa tarde, 
segue trecho para se basear
`NFNotaInfoIdentificacao identificacao = new NFNotaInfoIdentificacao();
//
List<NFInfoReferenciada> referenciadas = new ArrayList<NFInfoReferenciada>();
//for(){ //para cada nota que precisar referenciar
NFInfoReferenciada ref = new NFInfoReferenciada();
ref.setChaveAcesso(nfe.getChaveReferenciada());
referenciadas.add(ref);
//}
identificacao.setReferenciadas(referenciadas);`

**Comment by AllisonErd** [comment]
@danielbohnrs Desculpa ademora em responder. Funcionou perfeitamente. Obrigado pela ajuda mais uma vez!
