### ISSUE TITLE
resNFe_v1.01.xsd

### ISSUE THREAD

**Issue by henriquelssantiago** [wmixvideo/nfe#468]
Já fiz uma busca na lib toda e não achei, mas vale a pergunta.
Não existe a possibilidade ou a classe que represente o schema `resNFe_v1.01.xsd`?
Esse é o schema de nfe resumido.

"`<resNFe versao="1.01" xmlns="http://www.portalfiscal.inf.br/nfe">
    <chNFe...`"

assim como para Nota processada  que utilizo a classe `DFParser` e o método `notaProcessadaParaObjeto`.

**Comment by fincatto** [comment]
Não sei se entendi bem a questão. Você pode melhorá-la?

**Comment by henriquelssantiago** [comment]
ao usar o ws de consulta:
```
public NFDistribuicaoIntRetorno consultarDistribuicaoDFe(final String cnpj, final DFUnidadeFederativa uf, final String chaveAcesso, final String nsu, final String ultNsu) throws Exception {
        return this.wSDistribuicaoNFe.consultar(cnpj, uf, chaveAcesso, nsu, ultNsu);
    }
```
e passando um nsu pra receber um lote de 50 notas, recebemos um List<DocZip> ok? minha intenção é salvar os xmls e extrair algumas informações desse xml pra guardar no banco, ou seja, preciso transformar o xml pra um objeto java, assim consigo extrair informação desse xml.
esse WS retorna alguns schemas, como o `procNfe_v3.10.xsd` ou o `4.00`, esses eu consigo utilizar o método `notaProcessadaParaObjeto` da classe `DFParser`. Mas pro xml cujo schema for `resNFe_v1.01.xsd` o que eu devo fazer, não achei uma classe que representasse esse schema, nem um método pra fazer esse parse.

**Comment by marlosmorbis** [comment]
Bom dia Senhores, @henriquelssantiago e @fincatto 
Realmente não existe o objeto para se fazer o parse para o xml do schema resNFe_v1.01, acredito eu que não foi implementado porque ninguém precisou utilizar ainda.
@henriquelssantiago, pra criar a classe é só seguir os tipos certos definidos no documento que a SEFAZ disponibiliza e usar uma classe do projeto Nfe como exemplo, dai depois você faz uma pull request para contribuir com o projeto.
Espero ter ajudado.
Att,

**Comment by henriquelssantiago** [comment]
@marcoslombardi imaginei exatamente isso. 
Obrigado pela atenção!
