### ISSUE TITLE
Erro ao retirar forma de pagamento Duplicata Mercantil

### ISSUE THREAD

**Issue by eldevanjr** [wmixvideo/nfe#471]
Olá, alguém ao fazer um _commit_ e um _pull request_ no projeto renomeou as classes de formas pagamento e além disso excluíram a forma de pagamento Duplicata Mercantil, mas no esquema XML não foi removido esta forma de pagamento, conforme pode ser atestado pelo arquivo: [PL_009_V4_2016_002_v160/leiauteNFe_v4.00.xsd](https://github.com/wmixvideo/nfe/raw/master/src/main/resources/schemas/PL_009_V4_2016_002_v160/leiauteNFe_v4.00.xsd) no elemento 
```xml
<xs:element name="tPag">
```
, fiz um _pull request_( #470)  que corrige isso. 
Atenciosamente. @fincatto

**Comment by cbockorny** [comment]
Foi excluída na versão 1.50. No manual da versao 1.60 possui uma validação: Rejeição: Informado Duplicata Mercantil como Forma de Pagamento

**Comment by eldevanjr** [comment]
Além @cbockorny  disso na validação(YA02-10) que foi referida no manual da versão 1.60 é para o modelo 65 , e mesmo assim ela ainda não está ativa, como pode se perceber pelo penúltimo item da lista de mudanças da versão citada, como segue:

- Reativada RV YA02-10, tendo em vista que ainda não foi retirado do schema a opção de duplicata mercantil
