### ISSUE TITLE
[DUVIDA] Gerar DANFE Nf-e 4.0

### ISSUE THREAD

**Issue by AllisonErd** [wmixvideo/nfe#477]
Bom dia a todos.
Mais uma vez, procurei no canal do Discus e não encontrei nada relacionado e que me desse uma luz de como resolver, por isso estou perguntando aqui, e mais uma vez peço desculpas se estou errando em fazer isso aqui.

Bom, estou finalizando o meu gerenciador de NF-e e cheguei na parte de imprimir o DANFE. Estou buscando entender como fazer. Olhando issues anteriores, vi que existia uma classe chamada `NFDanfeReport`, porem procurei e não achei na biblioteca. A versão que estou usando é a 3.0.1, que é a ultima que está no repositório do maven, e acredito ser a mais atualizada. Se alguém puder, me dá uma ajuda, e me mostrar a ponta do iceberg, será de grande ajuda!

Desde já agradeço a atenção e ajuda de todos, obrigado!

**Comment by fincatto** [comment]
Bom dia @AllisonErd.
Existia um branch na versão anterior que estava sendo desenvolvida essa funcionalidade, mas ele não andou muito, e acabou que não foi para o master. 
No master, nunca houve um gerador de danfe mas seria muito bacana se houvesse, como disse em outros momentos. Se você tiver o conhecimento para desenvolver, será muito bem vindo.
Att

**Comment by AllisonErd** [comment]
Obrigado por responder @fincatto . 
Sempre quis ajudar no desenvolvimento da biblioteca, só não sabia como, talves seja essa a oportunidade. Prometo da uma pesquisada em como fazer, se eu conseguir, e for interessante para todos, eu ajudo sim.

Mas só pra eu entender, no caso, pra gerar o DANFE eu terei que recorrer a um fonte externa fora da biblioteca, certo?

**Comment by fincatto** [comment]
Não entendi a sua pergunta.
O que você quer dizer com recorrer a fonte externa?

2018-07-14 10:57 GMT-03:00 José Allison <notifications@github.com>:

**Comment by AllisonErd** [comment]
Vc disse que na versão anterior estava sendo desenvolvida a funcionalidade de gerar o danfe nf-e, e que foi descontinuada. Aí nessa versão, pelo que entendi não existe a função de gerar o danfe nf-e. Minha pergunta é se a alguma coisa que eu possa fazer pra gerar o danfe usando a biblioteca, ou terei que fazer algum desenvolvimento do zero, ou por fora, ou algo do tipo pra conseguir gerar.
Pq nós aqui na empresa usamos a biblioteca pra gerar o cupom fiscal da nfc-e, e funcionou perfeitamente, aí por esse motivo perguntei se teria a mesma coisa pra o danfe da nf-e, deu pra entender?

**Comment by danielbohnrs** [comment]
@AllisonErd Aqui no meu projeto uso uma versão da lib Danfe que me foi passada pelo programador que trabalhava antes de mim para esta empresa que trabalho (pelo que vi é uma cópia desde branch que existia neste projeto de nf-e). Upei o projeto no github para se quiser dar uma olhada: https://github.com/danielbohnrs/danfe
