### ISSUE TITLE
NFeConfig para mais de um certificado A3 instalado

### ISSUE THREAD

**Issue by AllisonErd** [wmixvideo/nfe#490]
Bom dia a todos.
Alguém teve a necessidade de configurar a biblioteca para funcionar com mais de um certificado a 3 instalado, pegando claro, pelo repositório do windows?

**Comment by AllisonErd** [comment]
O maximo que eu consegui uma vez foi listar, e seleciono o certificado, passando o alias para o metodo 
`getCertificadoKeyStore()` só que o problema era que ficava pedindo a senha duas vezes. Vc teria como me dá uma força nisso @eldevanjr ? A listar e escolher qual certificado usar?

**Comment by eldevanjr** [comment]
No nosso caso, fazemos assim: 
 ```java
ConfigJkaw.KEY_STORE_CERTIFICADO = KeyStore.getInstance("Windows-MY", "SunMSCAPI"); 
ConfigJkaw.KEY_STORE_CERTIFICADO.load(null, null);
 Enumeration<String> aliasEnum = ConfigJkaw.KEY_STORE_CERTIFICADO.aliases();
```
e então escolhemos o certificado a partir deste Enumeration de Alias, e então carregamos o certificado passando a senha gravada na configuração.

**Comment by fincatto** [comment]
Bom dia @eldevanjr.
Isso pode ser uma boa informação para o readme, não?
Se tiver a fim, pode colocar lá. Acho que pode ajudar o pessoal que usa esse tipo de certificado.

**Comment by fincatto** [comment]
Obrigado @eldevanjr!
