### ISSUE TITLE
Duvida ao acessar repositório windows

### ISSUE THREAD

**Issue by AllisonErd** [wmixvideo/nfe#492]
Bom dia a todos!
Estou tentando fazer minha aplicação funcionar com mais de um certificado A3, acessando o repositório de certificados do windows. Criei uma telinha com um Combobox, onde carrego os aliases contidos no repositório, quando possuo 1 certificado funciona perfeitamente, seleciono e logo em seguida aparece a caixa de diálogo do próprio certificado para informar a senha. Até aqui tudo ótimo!  Meu problema encontrase quando tenho mais de um certificado, que mesmo eu selecionando o alias que eu quero, ele sempre abre a caixa de diálogo de senha referente ao primeiro alias na lista. Estou batendo nisso desde segunda, se alguém já passou por isso e puder dar um help, desde já agradeço.

**Comment by eldevanjr** [comment]
Olá @AllisonErd , no caso do A3 senão me engano é preciso ter um arquivo que diz onde está a DLL no Windows correspondente ao certificado desejado, por exemplo:
`name = eToken ` 
`library = c:\windows\system32\eTpkcs11.dll
`
e carregar este arquivo pelo SunPKCS11, algo assim:
```java
try (InputStream certificadoStream = new FileInputStream(file)) {
 this.provider = new SunPKCS11(certificadoStream);
 Security.addProvider(this.provider);
 this.keyStore = KeyStore.getInstance("pkcs11", this.provider);
 keyStore.load(null, this.getCertificadoSenha().toCharArray());
} catch (CertificateException | NoSuchAlgorithmException | IOException e) {
  e.printStackTrace();                   
  throw new KeyStoreException("Nao foi possivel montar o KeyStore com a cadeia de certificados", e);
}

```

**Comment by AllisonErd** [comment]
Olá @eldevanjr , obrigado por responder.
Entendi. Mas no caso, no teste que estou fazendo aqui, tenho 2 certificados A3, um Token Alladin, e um SmartCard, aí teria que ser dois arquivos pra cada, ou essa dll é genérica pra qualquer certificado?

**Comment by eldevanjr** [comment]
@AllisonErd , é preciso saber certinho a dll de cada certificado, pois Token e SmartCard é diferente, e precisa de um arquivo pra cada. att.

**Comment by AllisonErd** [comment]
@eldevanjr acho que encontrei uma forma de selecionar o certificado A3 sem o uso de dll. Estou começando a alterar o código pra testar. Se der certo, posto aqui o resultado.
