### ISSUE TITLE
Erros de compilação

### ISSUE THREAD

**Issue by rubensdwo** [wmixvideo/nfe#496]
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/httpclient/protocol/ProtocolSocketFactory

Quando vou rodar o IntelliJ me da esse erro.

No caso tbm tenho um proxy aq. Teria algum problema?

**Comment by fincatto** [comment]
Sem problema algum.
Cheque seu pom.xml e verifique se as dependencias estão todas baixadas.

**Comment by fincatto** [comment]
Qual o comando vc está rodando?
