### ISSUE TITLE
Como verifico se as urls do estado do PI estão certas?

### ISSUE THREAD

**Issue by marciobrst** [wmixvideo/nfe#520]
Estou fazendo uns testes no consulta status do serviço e estou pegando o código de erro 410.

`<retEnviNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>1</tpAmb><verAplic>SVAN.NFeAut4_1.0.2</verAplic><cStat>410</cStat><xMotivo>Rejeicao: UF informada no campo cUF nao e atendida pelo Web Service</xMotivo><cUF>22</cUF><dhRecbto></dhRecbto></retEnviNFe>`

**Comment by fincatto** [comment]
Você pode buscar as URLs no site da SeFaz do estado e comparar com a que
temos na API.
Se estiverem diferentes, você altera no sistema, faz os teste e,
funcionando, faz um PR que incorporamos elas a biblioteca.
Att
