### ISSUE TITLE
Erro na mensagem do IntegerValidador

### ISSUE THREAD

**Issue by suchasoftware** [wmixvideo/nfe#530]
A mensagem de erro esta sendo formatada incorretamente no metodo abaixo:

```
	private static void intervalo(final Integer valor, final int minimo, final int maximo, final String info) {
		if (valor < minimo || valor > maximo) {
			throw new NumberFormatException(MessageFormat.format("Valor {0} tem tamanho fora do intervalo de [{1} até {2}]", info, minimo, maximo));
		}
	}
```

**Comment by petersonschmitt** [comment]
@suchasoftware poderia ser mais claro em qual a sua duvida?

**Comment by suchasoftware** [comment]
@petersonschmitt , na verdade não é uma dúvida. É que a formatação da mensagem não estava correta. Era exibida uma mensagem incorreta para o usuário. Eu precisei reescrever o método para que as variávies fossem substituídas corretamente.

O método que enviei acima é o método que eu escrevi. O de você stá assim:

`
    private static void intervalo(final Integer valor, final int minimo, final int maximo, final String info) {
        if (valor < minimo || valor > maximo) {
            throw new NumberFormatException(MessageFormat.format("Valor %s tem tamanho fora do intervalo de [{0}-{1}]", info, minimo, maximo));
        }
    }
`

**Comment by fincatto** [comment]
Agora que entendi. Acabei de corrigir, obrigado!
