### ISSUE TITLE
Certificado digital A1 de homologação

### ISSUE THREAD

**Issue by Greelings** [wmixvideo/nfe#546]
Bom dia, como posso gerar um certificado digital A1 de homologação para testes (emissão de notas fiscais NFC-e)? Obrigado.

**Comment by plinioleitecosta** [comment]
Dentro de utils, tem a classe GeraCadeiaCertificados. Ela é quem vc deve chamar para gerar os certificados carcets.

**Comment by mateushideaki** [comment]
Bom dia, alguém saberia informar se é necessário gerar uma cadeia de certificado para cada empresa? Ou posso gerar a de homologação e produção uma vez, usando as mesmas para todas as empresas?

**Comment by plinioleitecosta** [comment]
Para cada empresa, deve-se gerar uma cadeia certificado diferente. Afinal, cada empresa terá seu certificado digital individual, certo?

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by fincatto** [comment]
@Greelings creio que não será possivel usar um certificado auto-gerado para uso com os servidores da Sefaz, mesmo em homologação.

@mateushideaki Pode usar a mesma cadeia sim. A cadeia de certificados serve para informar que você confia nos certificados da outra parte. Uma vez que a outra parte seja sempre a mesma, a cadeia pode ser a mesma sim.
