### ISSUE TITLE
Erro nas notas geradas em timezone UTC Z

### ISSUE THREAD

**Issue by tatomarchioli** [wmixvideo/nfe#547]
Boa tarde.

Quando se gera um xml em uma máquina na timezone zulu, o xml apresenta os campos de data formatados com o 'Z' no final, porém a SEFAZ não aceita esse tipo de formato.
Um workaround momentâneo foi mudar a timezone da máquina onde a nota é gerada, mas acredito que seja interessante garantir a geração do xml válido independente disso.

**Comment by fincatto** [comment]
Olá @tatomarchioli.
Você consegue gerar um teste forçando o bug?
Eu acredito que o problema ocorra na classe DFLocalDateTimeTransformer, que foi adaptada pelo nosso colega @eldevanjr justamente para permitir que o sistema usasse a data e hora local da maquina.
