### ISSUE TITLE
Atualizar para os Schemas PL_009_V4_00_NT_2018_005_v1.10

### ISSUE THREAD

**Issue by AllisonErd** [wmixvideo/nfe#548]
Bom dia a todos!

Estou recendendo a seguinte rejeição: 

> 215 - Rejeição: Falha no esquema XML

Olhando o [Portal da Nfe](http://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=/fwLvLUSmU8=), verifiquei que existem novos schemas. Seria esse o problema? Como que eu faço pra atualizar-los?

OBS: Uso o maven.

Desde já agradeço a ajuda de todos.

**Comment by decarli** [comment]
Schemas atualizados nesse PR https://github.com/wmixvideo/nfe/pull/550

**Comment by fincatto** [comment]
PR combinado no master.
