### ISSUE TITLE
Emissão de NFe e NFCe

### ISSUE THREAD

**Issue by RobertoTesteDeSoftware** [wmixvideo/nfe#549]
Comecei a implementar emissão de nota fiscal e estou usando o jar wmixvideo. Gostaria de tirar uma dúvida que pode parecer obvia, mas o projeto do wmixvideo/nfe serve para emissão de nfe e nfce?

**Comment by eldevanjr** [comment]
@RobertoTesteDeSoftware ele não é o emissor, mas você usará a biblioteca wmixvideo/nfe para preencher as "tags" do xml que será gerado e enviado para receita.até.

**Comment by RobertoTesteDeSoftware** [comment]
Valeu eldevanjr.
