### ISSUE TITLE
Como faço para emitir uma nota em contingência ?

### ISSUE THREAD

**Issue by rodrigocode4** [wmixvideo/nfe#551]
Gostaria dos passos para gerar uma nota em contingência e saber como enviá-la para a sefaz. =)
Alguém poderia me ajudar ?

**Comment by mateushideaki** [comment]
Olá Rodrigo,

Vou te dizer como emitir uma nota em contingência da maneira que entendi, então, caso alguém veja algo errado nos passos a seguir, por favor, me corrija.

**Obs: Só estou utilizando SVC-AN e SVC-RS, pois são os mais simples até onde entendi, já que não é necessário retransmitir as notas posteriormente em ambiente Normal.**

1. Sobrescreva o método getTipoEmissao da classe NFeConfig, você provavelmente já tem uma classe que sobrescreve a NFeConfig, faça de forma que ela retorne o tipo de emissão desejado.
2. Ao preencher o seu objeto da classe NFNotaInfoIdentificacao, preencha o tipo de emissão utilizado, a justificativa da entrada em contingencia (entre 15 e 256 caracteres) e a Data/Hora da entrada em contingência

O que estou fazendo é apenas isso.

**Comment by rodrigocode4** [comment]
Olá, Mateus. Eu fiz esses passos que você descreveu, só que a o tipo de emissão de estou utilizando é a Contingência Offline (tpEmis = 9). 
Pelo que vi, o sefaz que assina a nota, depois ele retorna como este exemplo:

````
NFLoteEnvioRetornoDados restornoLote = WSFacede.loteEnvio(loteExemploNormal);
````
daí é só salvar o xml
````
salvaXML(restornoLote.getLoteAssinado());
````
o problema é que quando está sem internet, a gente tem que assinar a nota, certo ?
Pq não dá pra gerar o qrCode/link sem a assinatura. Me corrija se eu estiver errado, pfv.

Eu estou fazendo da seguinte forma:
Preencho todos os campos e justificativas em contingência e uso getLoteAssinado() do WSFacede.  
````
NFLoteEnvioRetornoDados restornoLote = WSFacede.getLoteAssinado(loteExemploContingencia);
````
Esse método assina o lote pra mim e assina o lote pra mim, e dessa foma eu consigo gerar xml. 
Depois, quando a internet volta, eu tendo enviar esse lote para a SEFAZ da mesma forma que se enviaria normalmente, **só que com a nota já assinada**:

````
NFLoteEnvioRetornoDados restornoLote = WSFacede.enviaLote(loteExemploContingencia);
````
E isso retorna uma Exception de parseamento do XML, dizendo que um campo está preenchido.

**Comment by DanielChrome** [comment]
Eu faço um processo bem parecido, porém, para a transmissão do XML de contingência (Já assinado previamente), eu estou utilizando outro método .

`NFLoteEnvioRetorno retornoEnvio = new WSFacade(config).enviaLoteAssinado(xmlContingencia, DFModelo.NFCE);`

**Comment by rodrigocode4** [comment]
O que você faz com o retornoEnvio, salva em um novo XML ou junta com esse xml em contingência ?
Caso salve o retorno em um xml separado, envia ele para o contador também ?
caso integre com o xml já salvo, existe um método que faça esse parse de xml ASSINADO ?

**Comment by DanielChrome** [comment]
O XML de retorno envio é salvo também na base de dados
Para envio para contabilidade, normalmente enviamos o <NFeProc>, que contem o XML da nota + XML do protocolo ao qual montamos na mão mesmo, seguindo Layout da Sefaz:
www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=TIiR6jY8fsM=

**Comment by rodrigocode4** [comment]
@DanielChrome teria com você mandar um exemplo de xml desses pronto ? gostaria de ver a estrutura das sessas tags. :smiley:

**Comment by DanielChrome** [comment]
Segue anexo @rodrigocode4 
Exemplos de Inutilizacao, Cancelamento (Evento) e Autorização.


[XMLS Distribuicao.zip](https://github.com/wmixvideo/nfe/files/3039935/XMLS.Distribuicao.zip)

**Comment by rodrigocode4** [comment]
> Segue anexo @rodrigocode4
> Exemplos de Inutilizacao, Cancelamento (Evento) e Autorização.
> 
> [XMLS Distribuicao.zip](https://github.com/wmixvideo/nfe/files/3039935/XMLS.Distribuicao.zip)

**Comment by rodrigocode4** [comment]
Muito obrigado, @DanielChrome :)
