### ISSUE TITLE
Implementação do grupo ZD. Informações do Responsável Técnico

### ISSUE THREAD

**Issue by ivandalvesco** [wmixvideo/nfe#555]
Estou implementado as alterações que a receita disponibilizou na NT 2018.005, versão 1.20 e estou começando a implementar as alterações do grupo de responsável técnico, estou com dificuldade para encontrar a implementação dos campos de idCSRT e hashCSRT, os outros campos relacionados ao grupo, encontrei na classe CTeNotaInfoResponsavelTecnico.
Att.

**Comment by PauloAzevedo** [comment]
Olá! Veja se essa Pull Request já não atende essa alteração que você está implementando, só está faltando o merge com o repositório:
https://github.com/wmixvideo/nfe/pull/550

**Comment by ivandalvesco** [comment]
Opa, atende sim, valeu pela ajuda e vou aguardar o merge no repo
