### ISSUE TITLE
Erro ao consultar distribuição DFe com CPF.

### ISSUE THREAD

**Issue by jpweit** [wmixvideo/nfe#560]
Tentei executar o método `consultarDistribuicaoDFe` e percebi que o mesmo não funciona para CPFs (independente de eu ter executado ele com 11 ou 14 dígitos).

Dei uma analisada no código e aparentemente o método `gerarNFDistribuicaoInt` não leva em consideração o uso de CPFs, populando somente o CNPJ da classe `NFDistribuicaoInt`.

**Comment by fincatto** [comment]
Olá @jpweit.
Implementei a alteração aqui, mas não consegui testar propriamente.
Você consegue fazer um teste aí e me avisar se funcionou ok pra você?
Abs

**Comment by jpweit** [comment]
Testei aqui e funcionou ok. Obrigado.
