### ISSUE TITLE
Log de response da sefaz

### ISSUE THREAD

**Issue by rogersouz** [wmixvideo/nfe#568]
Olá, gostaria de saber se existe algum mecanismo de logging no projeto. Estou tendo um problema que se manifesta de tempos em tempos e gostaria de verificar qual o response que a sefaz está dando quando esse erro acontece.

Bom, o erro é o seguinte:

```
org.simpleframework.xml.core.ValueRequiredException: Empty value for @org.simpleframework.xml.Element(name=cUF, data=false, type=void, required=true) on field 'uf' private com.fincatto.documentofiscal.DFUnidadeFederativa com.fincatto.documentofiscal.nfe400.classes.lote.envio.NFLoteEnvioRetorno.uf in class com.fincatto.documentofiscal.nfe400.classes.lote.envio.NFLoteEnvioRetorno at line 1
```

Acontece durante a execução dessa linha:

`NFLoteEnvioRetornoDados result = wsFacade.enviaLote(lote);`

Desde já, agradeço :)

**Comment by fincatto** [comment]
Existe a fachado do SLF4J, que você pode configurar como quiser, embora, no seu caso, pareça mais um caso de debug do que logging.
