### ISSUE TITLE
Sugestão: strict=false na classe NFNotaProcessada

### ISSUE THREAD

**Issue by danielbohnrs** [wmixvideo/nfe#569]
Boa tarde,
utilizo a lib para ler o xml de notas processadas que os fornecedores mandam pro cliente.
Hoje apresentou alguns erros devido a ter campos no xml que ainda não tinha na classe (eu não tinha atualizado a lib ainda).
O que gostaria de ver é se não podemos colocar `strict=false` na classe `NFNotaProcessada `para quando for lido um xml que tem campos adicionais, simplesmente ignorar as tags que ele não conhece, ao invés de dar erro.

**Comment by eldevanjr** [comment]
Olá @danielbohnrs , acontece sempre comigo este erro, preciso sempre estar atualizando a biblioteca, acho muito interessante se pudermos fazer esta modificação, o que acha @fincatto ?

**Comment by danielbohnrs** [comment]
Olá @eldevanjr , acabei fazendo da seguinte forma, apenas onde uso na minha aplicação:
troquei:
`notaProcessada2 = new com.fincatto.documentofiscal.nfe400.parsers.DFParser().notaProcessadaParaObjeto(sxml);`

por 

```
Persister persister = new DFPersister();
notaProcessada2 = persister.read(NFNotaProcessada.class, sxml, false);
```

(o terceiro parâmetro indica `strict=false` )

**Comment by eldevanjr** [comment]
@danielbohnrs obrigado pela dica, vou fazer isso também.

**Comment by fincatto** [comment]
Bom dia pessoal.
Quando isso acontece comigo, indica que tem campo novo pra implementar, então vou lá e implemento. Mas idéia de poder "pular" essa validação é interessante, embora eu ache que não devia ser a padrão (para evitar erros). 
Implementei no parser um modo estrito, e atualizei a documentação: 
final NFNotaProcessada notaProcessada = new DFParser().setStrict(false).notaProcessadaParaObjeto(xmlNota);
Abs.
