### ISSUE TITLE
Classe DFParser removida?

### ISSUE THREAD

**Issue by prbrios** [wmixvideo/nfe#577]
Baixei a ultima versão e tive problemas com ausência da classe DFParser. Ela foi renomeada ou há outra classe que converta o objeto em String?

**Comment by marcoslombardi** [comment]
Dá uma olhada no tópico abaixo retirado da documentação: 

Convertendo nota XML em Java
Existe uma classe que pode receber um File/String e converter para um objeto NFNota, faça da seguinte forma:

final NFNota nota = new DFPersister().read(NFNota.class, xmlNota);
final NFNotaProcessada notaProcessada = new DFPersister().read(NFNotaProcessada.class, xmlNotaProcessada);

Ou desabilitando o modo estrito (habilitado por padrão):

final NFNota nota = new DFPersister(false).read(NFNota.class, xmlNota);


Outra referencia: https://github.com/wmixvideo/nfe/issues/569
