### ISSUE TITLE
Separar projeto em módulos maven

### ISSUE THREAD

**Issue by leandrodelsole** [wmixvideo/nfe#580]
Implementando código para utilização das NFCe Versão 4.0.0, em todo import, tive que ficar escolhendo qual a versão que gostaria. Se tivesse só a versão 4.0.0 no classpath, que era a única que interessava, além de agilizar o desenvolvimento, não abriria margens para erros.

No mais, o tamanho da dependência no meu Jar final se reduziria. Ponto importante quando estamos pensando em microserviços.

Pelo que vi da estrutura do projeto, daria para dividir em módulos como:
core - onde teria toda a lógica de comunicação com dos WebServices. Dependeria do módulo util e dos módulos contendo os modelos das classes com escopo provided.
util - não teria dependência de nenhum outro módulo do projeto, todos os outros dependeriam dele. Teria basicamente validadores e códigos isolados.
cte, cte200, cte300, mdfe3, nfe, nfe310, nfe400 - módulos de funcionalidades específicas de integração com a receita, que não dependem entre si, ou no máximo tem uma hierarquia entre eles. O usuário da lib incluiria no classpath somente os que precisasse.

Se feito com git mv, acredito que não perderia pull requests pendentes e códigos em desenvolvimento, pois o git conseguiria mapear que a classe só foi movida de pasta e levaria as alterações.

Se aceitarem a proposta eu posso tentar implementar, apesar de não conhecer tão bem a estrutura do projeto ainda.

**Comment by fincatto** [comment]
Bom dia @leandrodelsole.
A idéia parece boa sim, embora eu ache que core e util possam ser integrados (nao temos muitas classes utilitarias no projeto, temos que tentar manter o mais facil possivel de usar).
Você consegue fazer uma PR com a proposta? Talvez eu precise de ajuda com a publicação disso no maven central. Você tem conhecimento nesta área?
Qualquer dúvida, estou à disposição para ajudar.

**Comment by leandrodelsole** [comment]
Farei o PR sim, vou tentar trabalhar nisso este fim de semana.
A separação do core e util talvez seja necessária para evitar dependência cíclica. Por exemplo, se o módulo core depende do nfe400 para fazer a emissão, o nfe400 não pode depender do core para uma validação/conversão, por exemplo de quantidade de dígitos de um número. Daí essa validação/conversão seria extraída para o módulo útil, para a árvore de dependências ficar:
core depende do nfe400 e do util (se necessário)
nfe400 depende do util
util não depende de nenhum outro do projeto.

Sobre a publicação no maven central, não fiz, mas acredito que não deva mudar nada no processo que você já executa hoje, só é necessário configurar direitinho os poms dos módulos. Vou validar em outros projetos que tenho aqui e/ou monto um projeto de exemplo para validarmos.

**Comment by leandrodelsole** [comment]
O trabalho em progresso está em:
https://github.com/leandrodelsole/nfe/tree/580-separar-em-modulos

Está aparecendo muito mais pontos de interdependência entre os módulos do que eu esperava. Visualizando a árvore de diretórios do projeto eu achava que as ramificações eram totalmente desacopladas.

**Comment by fincatto** [comment]
Tá ficando muito bacana!
Se tiver algo em que eu puder ajudar durante a migração, me avisa.
Abs

**Comment by leandrodelsole** [comment]
Ficou complicada a agenda aqui, só vou conseguir voltar a trabalhar nisso daqui umas 2-3 semanas 😞 
Para caso alguém queira continuar o trabalho, eu estava fazendo dessa maneira:
Tentava compilar o projeto pela IDE, mas pode ser via `mvn clean compile`. 
Via o problema que dava. Os problemas ainda são basicamente classes de módulos específicos, por exemplo mdfe3, que utilizam classes de outros módulos, por exemplo nfe400.
Então, há de se avaliar:
- se extrai a classe pro core - tipicamente apenas classes que são utilizadas em todos os módulos
- se duplica a classe nos dois módulos
- Ou então, se coloca em um módulo comum aos dois. 

Ao mover uma classe de pacote é necessário utilizar o `git mv`, para não perder o histórico de commits da classe.

Depois de resolvido todos problemas de compilação, é necessário executar o `mvn clean verify` para garantirmos que todos os testes estão de acordo.

O próximo passo então seria garantir que a publicação no maven central está ocorrendo, ou avaliar se precisa de mais alguma configuração.

O ultimo passo, atualizar o README, para a nova forma de importar e um racional de cada módulo do projeto.
