### ISSUE TITLE
Manifestação do destinatário pessoa física

### ISSUE THREAD

**Issue by isadoramsouza** [wmixvideo/nfe#582]
Boa noite. Hoje tenho a seguinte situação: consigo realizar a distribuiçao nfe para pessoa física e obtenho os xmls de resumo para esse destinatário PF. Para obter o xml completo é necessário manifestação do destinatário. É possível realizar esse evento hoje sendo o destinatário pessoa fisica ou somente se for pessoa juridica?

**Comment by fincatto** [comment]
Olá @isadoramsouza.
O que dizem os manuais da receita, nesse caso?
Att

**Comment by fincatto** [comment]
Fechando issue. Sem resposta.
