### ISSUE TITLE
Rejeicao 878

### ISSUE THREAD

**Issue by gabrielgeraldo** [wmixvideo/nfe#586]
Boa tarde,

Alguém pode ajudar?

Estou tentando emitir uma NFC-e aqui no Rio de janeiro e só recebo a rejeição 878. Veja abaixo a URL utilizada.

tag qrCode:
![CDATA[http://www4.fazenda.rj.gov.br/consultaNFCe/QRCode?p=33190501393317000106650010000000661765503205|2|2|1|5A2F09894AB76C287C042F7A99D6F08E2CEA6CE8]]

tag urlChave:
www.nfce.fazenda.rj.gov.br/consulta

QRCode geraQRCode20 = new QRCode(nota, config);
NFNotaInfoSuplementar nfs = new NFNotaInfoSuplementar();
nfs.setUrlConsultaChaveAcesso(geraQRCode20.urlConsultaChaveAcesso());
nfs.setQrCode(geraQRCode20.getQRCode());
nota.setInfoSuplementar(nfs);

**Comment by eldevanjr** [comment]
Teria que mudar a url do RJ , ela mudou conforme o site : [http://nfce.encat.org/consulte-sua-nota-qr-code-versao-2-0/](http://nfce.encat.org/consulte-sua-nota-qr-code-versao-2-0/) para [www.fazenda.rj.gov.br/nfce/consulta](www.fazenda.rj.gov.br/nfce/consulta)

**Comment by eldevanjr** [comment]
Olá @gabrielgeraldo , fiz a modificação conforme [este](https://github.com/eldevanjr/nfe/commit/006c5b5f5a32caf202a420e78f2b6ebbb925abe1)  [commit](https://github.com/eldevanjr/nfe/commit/006c5b5f5a32caf202a420e78f2b6ebbb925abe1) no meu fork. att.

**Comment by fincatto** [comment]
Boa tarde @eldevanjr.
Você não chegou a fazer o PR deste codigo, certo?

**Comment by gabrielgeraldo** [comment]
@eldevanjr Obrigado pela ajuda.

Como faço para atualizar meu projeto com essa alteração? Basta atualizar o Maven?

**Comment by eldevanjr** [comment]
olá @fincatto , acabei de fazer o PR #587.

**Comment by eldevanjr** [comment]
@gabrielgeraldo , você teria que modificar o código pelo clone que fizeste, e então construí-lo, ou senão teria que esperar o master do projeto aceitar o PR #587   e aí construir o projeto e colocar no POM a versão mais recente do projeto.

**Comment by gabrielgeraldo** [comment]
@eldevanjr 

Uma observação:
Coloquei o URL correta direto no meu método e continue recebendo a rejeição em questão. Veja abaixo.
Será que neste caso somente a alteração da URL vai resolver? 

                QRCode geraQRCode20 = new QRCode(nota, config);
		NFNotaInfoSuplementar nfs = new NFNotaInfoSuplementar();
		nfs.setUrlConsultaChaveAcesso("http://www.fazenda.rj.gov.br/nfce/consulta");
		nfs.setQrCode(geraQRCode20.getQRCode());
		nota.setInfoSuplementar(nfs);

**Comment by eldevanjr** [comment]
@gabrielgeraldo , teria que atualizar toda a biblioteca, pois ele gera pela URL do código, ou tenta setar pra agilizar depois se setar o QrCode.

**Comment by gabrielgeraldo** [comment]
Continuo recebendo a rejeição mesmo setando a URL manualmente. Veja as URLs setadas no XML:
qrCode:
http://www4.fazenda.rj.gov.br/consultaNFCe/QRCode
urlChave:
http://www.fazenda.rj.gov.br/nfce/consulta</urlChave>

Vou aguardar o master do projeto aceitar o PR. Enquanto isso vou deixar o cliente sem emitir NFC-e.
Obrigado pela ajudar.

**Comment by eldevanjr** [comment]
esta url [http://www4.fazenda.rj.gov.br/consultaNFCe/QRCode](http://www4.fazenda.rj.gov.br/consultaNFCe/QRCode) não é mais válida, já atualizei no meu fork.conforme #587

**Comment by fincatto** [comment]
PR aceito! Obrigado @eldevanjr!

**Comment by gabrielgeraldo** [comment]
@eldevanjr de acordo com o site http://nfce.encat.org/desenvolvedor/qrcode/ a ULR http://www4.fazenda.rj.gov.br/consultaNFCe/QRCode? está correta.

Qual é a URL correta? Não entendi.

**Comment by danielbohnrs** [comment]
@gabrielgeraldo essa aí são as URLs do QRCode 1.0.
Do QRCode 2.0 estão aqui: http://nfce.encat.org/consulte-sua-nota-qr-code-versao-2-0/

**Comment by gabrielgeraldo** [comment]
@danielbohnrs essas urls que estão no site http://nfce.encat.org/consulte-sua-nota-qr-code-versao-2-0/ são as urls de consulta, tag <urlChave>.

Eu estou setando ela manualmente e mesmo assim recebo a rejeição. veja abaixo.
Acredito que o problema não seja somente as URLs.

Veja também o meu XML

Alguma ideia do que possa ser?

QRCode geraQRCode20 = new QRCode(nota, config);
NFNotaInfoSuplementar nfs = new NFNotaInfoSuplementar();
nfs.setUrlConsultaChaveAcesso("http://www.fazenda.rj.gov.br/nfce/consulta");
nfs.setQrCode(geraQRCode20.getQRCode());
nota.setInfoSuplementar(nfs);

XML:
tag qrCode:
http://www4.fazenda.rj.gov.br/consultaNFCe/QRCode
tag urlChave:
http://www.fazenda.rj.gov.br/nfce/consulta</urlChave>

**Comment by danielbohnrs** [comment]
Você seta manualmente em que momento estes dados?
Porque a lib gera essa info dentro da classe `WSLoteEnvio`, no `getLoteAssinado`, então pode estar sobrescrevendo o que tu colocou manualmente.

**Comment by gabrielgeraldo** [comment]
@danielbohnrs No momento da geração do QRCode:

QRCode geraQRCode20 = new QRCode(nota, config);
NFNotaInfoSuplementar nfs = new NFNotaInfoSuplementar();
nfs.setUrlConsultaChaveAcesso("http://www.fazenda.rj.gov.br/nfce/consulta");
nfs.setQrCode(geraQRCode20.getQRCode());
nota.setInfoSuplementar(nfs);

**Comment by gabrielgeraldo** [comment]
@danielbohnrs Eu vejo a URL setada no XML processado pelo SEFAZ. Veja o código.

                        NFNotaProcessada notaProcessada = new NFNotaProcessada();
			notaProcessada.setVersao(new java.math.BigDecimal(config.getVersao()));
			notaProcessada.setProtocolo(prot);
			notaProcessada.setNota(nota);

			String xmlNotaProcessadaPeloSefaz = notaProcessada.toString();
			System.out.println("xml: " + xmlNotaProcessadaPeloSefaz);

**Comment by gabrielgeraldo** [comment]
Bom dia Pessoal,

Acho que a URL ainda está errada:

URL por UF utilizada QR code: http://www4.fazenda.rj.gov.br/consultaNFCe/QRCode?
Veja no link: http://nfce.encat.org/desenvolvedor/qrcode/

URL por UF utilizada para consulta chave – Qr Code versão 2.0: www.fazenda.rj.gov.br/nfce/consulta
Veja no link: http://nfce.encat.org/desenvolvedor/httpnfce-encat-orgconsulte-sua-nota-qr-code-versao-2-0/

Da forma que está hoje dá rejeição: 395 Rejeicao: Endereco do site da UF da consulta via QR-Code diverge do previsto
