### ISSUE TITLE
Consulta Cadastro por CPF

### ISSUE THREAD

**Issue by dorcilio** [wmixvideo/nfe#588]
Olá boa tarde!

Gostaria de saber se tem como criar um método para consultar cadastro por CPF, já que o governo disponibiliza um layout de XML com essa opção também nos WebServices.
Atualmente já existe o consulta cadastro com CNPJ, só faltaria essa opção mesmo.

Atenciosamente,
Dorcílio Neto.

**Comment by fincatto** [comment]
Você consegue desenvolver e mandar um PR?
