### ISSUE TITLE
campo vICMSSubstituto nao esta no maven

### ISSUE THREAD

**Issue by acomnet** [wmixvideo/nfe#589]
Bom dia!
Pessoal, náo estou encontrando na classe NFNotaInfoItemImpostoICMS60 o seguinte campo:

`@Element(name = "vICMSSubstituto", required = false)
    private String valorICMSSubstituto;`

Olhando aqui no repositorio o campo existe. Porem a que se encontra no maven nao esta la. 
A minha versao esta atualizada de acordo com a que esta no maven, 3.0.5.
Fico no aguardo.

**Comment by fincatto** [comment]
Versao 3.0.6 liberada no maven!
