### ISSUE TITLE
Campo de validação EX-TIPI

### ISSUE THREAD

**Issue by mkraulich** [wmixvideo/nfe#59]
Boa tarde, 
pude verificar que ao fazer a validação no campo EX-TIPI (referente a um ncm de um produto), o validador se utiliza do parametro ".tamanho2ou3", sendo assim a faixa aceitavel do campo inteiro fica entre 10 e 999. Acho que deveria ser outra faixa, quando na verdade o campo de exceção do NCM começa no numero 01.
Mudei manualmente em meu projeto e está funcionando com o parser da SEFAZ. Gostaria que me dessem uma opinião quanto à questão.
Desde já fico muito grato e os parabenizo pelo projeto, muito bem montado.

**Comment by fincatto** [comment]
Boa tarde mkraulich.
Vamos alterar o projeto sim. 
Você consegue fazer a alteração junto com um teste unitário e fazer um pull request?
