### ISSUE TITLE
395 Rejeicao. URL Incorreta.

### ISSUE THREAD

**Issue by gabrielgeraldo** [wmixvideo/nfe#590]
Boa tarde,

Acho que a URL do Rio de Janeiro ainda está errada:

URL por UF utilizada QR code: http://www4.fazenda.rj.gov.br/consultaNFCe/QRCode?
Veja no link: http://nfce.encat.org/desenvolvedor/qrcode/

URL por UF utilizada para consulta chave – Qr Code versão 2.0: www.fazenda.rj.gov.br/nfce/consulta
Veja no link: http://nfce.encat.org/desenvolvedor/httpnfce-encat-orgconsulte-sua-nota-qr-code-versao-2-0/

Da forma que está hoje dá rejeição: 395 Rejeicao: Endereco do site da UF da consulta via QR-Code diverge do previsto

Acho que o correto é:
RJ("RJ", "Rio de Janeiro", "33", "http://www4.fazenda.rj.gov.br/consultaNFCe/QRCode?", "http://www4.fazenda.rj.gov.br/consultaNFCe/QRCode?", "www.fazenda.rj.gov.br/nfce/consulta", "www.fazenda.rj.gov.br/nfce/consulta"),

**Comment by fincatto** [comment]
Você consegue confirmar isso? Se sim, consegues fazer um PR?

**Comment by gabrielgeraldo** [comment]
Bom dia, 

Teste e PR realizado. Foram dois commit.

**Comment by fincatto** [comment]
Bom dia.
Eu comentei la no PR que existem testes falhando. 
Vou fechar a issue aqui e aguardo a correção lá, ok?
