### ISSUE TITLE
Pis/Cofins NãoTributável Falta CST 5 na verificação

### ISSUE THREAD

**Issue by RobertoTesteDeSoftware** [wmixvideo/nfe#598]
Olá, 

Notei que na classe NFNotaInfoItemImpostoCOFINSNaoTributavel e NFNotaInfoItemImpostoPISNaoTributavel falta adicionar o CST 5 na validação dos tipos de situação tributária. Caso deseje conferir no link: http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=URCYvjVMIzI= tem o manual basta dar uma olhada na pg. 213

Vlw.

**Comment by fincatto** [comment]
Ola @RobertoTesteDeSoftware.
Você consegue fazer um PR com essa alteração?
No aguardo.

**Comment by danielbohnrs** [comment]
Olá @RobertoTesteDeSoftware, já tem esta opção na validação, deste este [commit ](https://github.com/wmixvideo/nfe/commit/434b52eaeeaf2da9fa4eb5786add73d6f2178ef2#diff-906dd4049ab09595c91e2e62840b401f).
