### ISSUE TITLE
QRCode MDF-e

### ISSUE THREAD

**Issue by diegocossa** [wmixvideo/nfe#603]
Alguma previsão ou solução para o caso do QRCode estar contigo no XML do MDF-e que passou a valor na homologação ontem dia 15/07/2019?

Abraço

**Comment by isadoramsouza** [comment]
também gostaria de saber..

**Comment by simmifelipe** [comment]
Tbm tenho interesse...

**Comment by isadoramsouza** [comment]
alguma novidade?

**Comment by edivaldoms** [comment]
A Receita não está mais aceitando validar o XML sem o QRCode. Tem alguma coisa já feita? Vou começar a desenvolver algo aqui, mas gostaria de saber se já tem algo iniciado.

**Comment by eldevanjr** [comment]
Olá @edivaldoms , estou terminando de implementar

**Comment by eldevanjr** [comment]
já já vou postar as modificações.

**Comment by eldevanjr** [comment]
Preenchimento do QRCode no MDF-e: 
```java
MDFInfoSuplementar mdfInfoSuplementar = new MDFInfoSuplementar();
mdfInfoSuplementar.setQrCodMDFe(new MDFGeraQRCode(mdfe, config).getQRCode());
mdfe.setMdfInfoSuplementar(mdfInfoSuplementar);
```

**Comment by edivaldoms** [comment]
Não esquecer de colocar entre `<![CDATA[ ]]>`, pois o aparece erro ao ser lido pelo Jasperreports.
`<infMDFeSupl>
        <qrCodMDFe>
            <![CDATA[https://dfe-portal.svrs.rs.gov.br/mdfe/qrCode?chMDFe=999999999999999999999999999999999999999999&tpAmb=1]]>
        </qrCodMDFe>`

**Comment by eldevanjr** [comment]
Olá @edivaldoms , nós fizemos a implementação sem o CDATA e também usamos o jasperreport, mas ao invés de colocar a tag no projeto adicionamos no arquivo de relatório, ficando independente a forma de relatório usada.

**Comment by edivaldoms** [comment]
Olá @eldevanjr , ignore essa informação do CDATA que postei. Estava desenvolvendo o novo leiaute do DAMDFE e durante o desenvolvimento se eu não colocar no XML de modelo entre CDATA o Jasper não compila, mas quando eu implantei tive que tirar, pois o leitor de QR-Code lê o CDATA como string, já no Jasper Studio 6.10, não. Pode ser versões de dependências que utilizei na implantação que corrigiu isso.
