### ISSUE TITLE
DANFE

### ISSUE THREAD

**Issue by JefersonOC** [wmixvideo/nfe#620]
Existe a possibilidade de adicionar uma pasta "danfe" que contenham as informações de impressão a partir dos arquivos do jasper?

Tenho alguns e gostaria de contribuir para que a comunidade evolua.

**Comment by fincatto** [comment]
Olá @JefersonOC.
Já tentamos incluir as danfes no projeto e não funcionou muito bem, tivemos que remover. 
Sugiro que crie um projeto que dependa deste (no maven mesmo) e que faça somente as danfes. Assim, quem precisa das danfes poderia importar também este projeto.
Existe um outro problema relacionado a dependencia dos jars do jasper tambem, que causa muita dor de cabeça, que podemos evitar.
