### ISSUE TITLE
Erro Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown

### ISSUE THREAD

**Issue by eldevanjr** [wmixvideo/nfe#621]
Olá estou tentando enviar/ consultar um CTe e acontece este erro:
```
 Unable to sendViaPost to url[https://homologacao.cte.fazenda.pr.gov.br/cte/CteConsulta?wsdl]
org.apache.axis2.AxisFault: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
```
, o detalhe é que outros certificados funcionam, esse mesmo certificado que estamos usando envia NFe normalmente, mas no CTe dá este problema, além disso, testei outro certificado pra enviar o CTe e está normal também, se alguém souber alguma coisa, por favor deixe um comentário, estamos a 3 dias tentando resolver este problema e nada! agradecido desde já...

[Stack Trace do Erro](https://docs.google.com/document/d/1Mu651bQYfpm4dUQ7Ddccxh9XvNjo2TpyayfpzhHvOrg/edit?usp=sharing)

**Comment by JefersonOC** [comment]
Olá, 
Nas ultimas vezes que recebi erros de:
`Connection has been shutdown: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown`
Os casos eram:
1. Certificado Vencido
2. Certificado Corrompido
3. Certificado Inválido (por alguma questão da certificadora que fez o mesmo)
4. Cacerts

Confira se o seu é alguns desses.

**Comment by eldevanjr** [comment]
Olá, consegui resolver este problema, a questão é que tinha algum problema em como estava sendo configurado o Socket SSL, após pesquisar bastante, encontrei a solução em outro projeto que utiliza a mesma lógica, e implementei aqui e funcionou já fiz um commit dele aqui : [https://github.com/eldevanjr/nfe/commit/355bfaae3e3db70c697aec5b69d089ae1d1c0802](https://github.com/eldevanjr/nfe/commit/355bfaae3e3db70c697aec5b69d089ae1d1c0802), obrigado.
