### ISSUE TITLE
Usar o certificado instalado no windows A1 / A3

### ISSUE THREAD

**Issue by zuza07** [wmixvideo/nfe#623]
Boa noite pessoal, tenho uma dúvida.
Tenho a aplicação Desktop funcionando corretamente mas surgiu a necessidade de carregar o certificado da instalação do Windows, na configuração eu peço o CNPJ e o mesmo consta no aliás do certificado. Não sei como devo prosseguir para ter no meu KeyStore somente o certificado localizado, mais ou menos como segue abaixo.

KeyStore ks = KeyStore.getInstance("Windows-MY", "SunMSCAPI");
ks.load(null, null);
for (Enumeration<String> aliases = ks.aliases(); aliases.hasMoreElements();) {
    String alias = aliases.nextElement();
    System.out.println(alias);
}

Não sei como continuar esse código, já tentei de tudo mas algo faço de errado.
Aqui exemplo de como carrego o certificado do arquivo, mas não sei o que fazer no caso de referenciar com o certificado no windows.

this.keyStoreCertificado = KeyStore.getInstance("PKCS12");
            try (InputStream certificadoStream = new FileInputStream("/tmp/certificado.pfx")) {
                this.keyStoreCertificado.load(certificadoStream, this.getCertificadoSenha().toCharArray());
            } catch (CertificateException | NoSuchAlgorithmException | IOException e) {
                this.keyStoreCadeia = null;
                throw new KeyStoreException("Nao foi possibel montar o KeyStore com a cadeia de certificados", e);
            }

Desde já agradecido

**Comment by zuza07** [comment]
Entendi como funciona, talvez isso esclareça dúvida de outra pessoa.

***** para o arquivo DFConfig 
informe o aliás escolhido para a
public String getCertificadoAlias() { return null; }

porém a busca do STATUS para mim não estava funicionando, então fiz as seguintes alterações, que penso que seja benéfico colocar para o fincatto NFE.

DFSocketFactory.java

    private KeyManager[] createKeyManagers(final DFConfig config) throws UnrecoverableKeyException, KeyStoreException, NoSuchAlgorithmException {
        final String alias = DFSocketFactory.getAlias(config.getCertificadoKeyStore(),config.getCertificadoAlias()); **//zuza alterado aqui**



    private static String getAlias(final KeyStore ks, final String _alias) throws KeyStoreException {
        if (_alias != null) { **//zuza incluido aqui**
            if (ks.isKeyEntry(_alias)) {
                return _alias;
            }
        } else {
            final Enumeration<String> aliasesEnum = ks.aliases();
            while (aliasesEnum.hasMoreElements()) {
                final String alias = aliasesEnum.nextElement();
                if (ks.isKeyEntry(alias)) {
                    return alias;
                }
            }
        }
        throw new KeyStoreException("Nenhum alias encontrado no certificado");
    }

**Comment by fincatto** [comment]
Olá @zuza07.
Poderia mandar esse codigo como um PR para poder ser melhor avaliado?
No aguardo.
