### ISSUE TITLE
Dúvida sobre A1 e A3

### ISSUE THREAD

**Issue by clayderson** [wmixvideo/nfe#635]
Olá, bom dia!

Gostaria de saber se eu posso assinar um XML localmente usando um A3 de uma empresa X e depois enviar esse XML pra um sistema web que faria a comunicação com a SEFAZ usando um A1 estático da empresa Y.

Se funcionar, no caso de uma emissão de nota por exemplo, ela seria emitida no nome da empresa X que assinou o XML com o A3 ou da empresa Y que fez a requisição usando um A1?

Desculpe se não fui claro. Meu objetivo é construir uma API web que emita notas fiscais com suporte a certificados A3 por meio de um plugin instalado localmente no cliente.

Obrigado!

**Comment by claytonaalves** [comment]
Funciona sim... a SEFAZ não leva em consideração o certificado de quem está transmitindo o documento fiscal, desde que seja um certificado válido.

Ou seja, pode assinar o documento fiscal com o certificado A e transmitir com o certificado B sem problemas.
