### ISSUE TITLE
Processo de CI/CD

### ISSUE THREAD

**Issue by RafaelSTelles** [wmixvideo/nfe#643]
Estou trabalhando em um projeto novo de emissão fiscal, e comecei a utilizar essa lib, porém notei que o código que está na master, não se refere a ultima versão publicada no maven central. Gostaria de propor a criação de um processo de release que assim que chegue o código na master, a ferramenta de ci/cd (no caso o Travis CI), automaticamente execute todos os testes, e após concluído com sucesso, ele rotacione e publique a versão nova no maven central. Para fazer esse processo, basta utilizar [esse plugin ](https://maven.apache.org/maven-release/maven-release-plugin/)que ele faz isso de forma "automática".

Caso tenhas dúvidas de como fazer esse processo, eu posso ajudar, e até mesmo realizar a implementação.

Caso não queira desenvolver esse processo de CI/CD, seria possível gerar uma release da master ? Estou precisando de um fix de consulta o status de uma determinada nota.

**Comment by fincatto** [comment]
Olá @RafaelSTelles! 
A funcionalidade de gerar e publicar no maven central é uma ótima idéia. 
Se puder implementar e criar um PR com a funcionalidade, será muito bem vinda!

**Comment by fincatto** [comment]
Estava vendo agora que o proprio github tem registros de pacotes. Poderia ser uma alternativa também manter o codigo gerar o build e publicar tudo dentro do github. 
Se souber como implementar, pode ir em frente que será adicionado ao projeto, com certeza. 
Se precisar de algo referente a configuração e souber como fazer, passe diretamente pra mim que eu farei, sem problemas.

**Comment by RafaelSTelles** [comment]
Eu acredito que seja melhor começar com o travis ci, que já está implementado. Eu devo fazer uma implementação inicial nesse final de semana, ai te aciono caso precise de algo.

**Comment by fincatto** [comment]
Combinado!

**Comment by RafaelSTelles** [comment]
Opaa, eu abri o PR, vc chegou a ver ?

**Comment by fincatto** [comment]
Olá Rafael. 
Não tinha visto, não. Mas pelo que vi agora por cima, ficou muito bom. 
Eu vou dedicar um tempo a fazer essas configurações neste final de semana e, se tiver com algum problema eu lhe retorno, ok?
Abs

**Comment by RafaelSTelles** [comment]
Opa, blz. Aguardo o seu retorno.

Em ter, 26 de mai de 2020 09:36, Diego Fincatto <notifications@github.com>
escreveu:
