### ISSUE TITLE
Erro ao dar Ciência em uma NFe

### ISSUE THREAD

**Issue by marcelo-cnm** [wmixvideo/nfe#654]
Olá, quando tentamos fazer uma manifestação de destinatário ocorre o seguinte problema:
org.apache.axis2.AxisFault: Connection or outbound has closed
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
	at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:78)
	at org.apache.axis2.transport.http.AxisRequestEntity.writeRequest(AxisRequestEntity.java:84)

Estava funcionando e do nada parou. 
Alguém passou por este problema?

**Comment by danielbohnrs** [comment]
Bom dia.
Não sei se é exatamente o mesmo problema, mas um problema que eu tive com a ciência e download do xml foi por conta da rotina `DFCadeiaCertificados.geraCadeiaCertificados` não gerar os cacerts para os endpoints: www.fazenda.gov.br e www1.fazenda.gov.br .
Depois que adicionei estes dois endpoints na geração dos cacerts, voltou a funcionar (também havia parado de funcionar do nada).

**Comment by marcelo-cnm** [comment]
Valeu, vou testar aqui e digo se deu boa.

**Comment by fincatto** [comment]
Boa dia.
Seria interessante talvez colocar essas URLs la no exemplo de gerador de cacerts, para facilitar para o pessoal que o usa? Se sim, conseguem fazer um PR?

**Comment by megaterrarc** [comment]
Este Problema acima é na ciência da nota ou na consulta da Distribuição? Pois estou com um problema na consulta referente a certificado e creio que seja o mesmo motivo.

**Comment by marlosmorbis** [comment]
Boa tarde,

Só para reafirmar ai, vi que o @danielbohnrs já fez uma PR com a solução na hora de gerar a cadeia de certificados.

Realmente faltava a URL do AN na hora de gerar a cadeia.

```
            final String urlCienciaNota = NFAutorizador400.AN.getRecepcaoEventoAN(ambiente);
            if (StringUtils.isNotBlank(urlCienciaNota)) {
                final String host = new URI(urlCienciaNota).getHost();
                DFCadeiaCertificados.get(keyStore, host);
            }
```

Inserindo esse código na nossa aqui funcionou a Manifestação do Destinatário.

@megaterrarc acredito que com a PR #656 funcione para ti também.

Valeu.

**Comment by megaterrarc** [comment]
Já fizemos o merge com o pull dessa solução testamos e solucionou o problema. Porem o titulo do problema fala da ciência e esta dando erro já na consulta, que é antes da ciência.

deixar isso observado caso alguém tenha esse mesmo problema na distribuição.

**Comment by marlosmorbis** [comment]
Para nós o erro somente acontecia ao dar ciência da nota, já o consultarDistribuicaoDFe estava funcionando normalmente.

Mas que bom que resolveu geral.

Valeu.

**Comment by fincatto** [comment]
Bom dia pessoal. 
Acabei de fazer o merge do #656.
Abs
