### ISSUE TITLE
Problemas com Geração de Arquivo cacert

### ISSUE THREAD

**Issue by rnovochadlo** [wmixvideo/nfe#658]
Bom dia. 

Gostaria de inicialmente agradecer pela biblioteca, estou utilizando ela em um projeto meu desde o ano passado e foi de grande ajuda. Em um momento futuro gostaria de poder também contribuir com este projeto.

A última versão disponibilizada da biblioteca via Maven foi 3.0.6. Nesta versão, a classe DFCadeiaCertificados está desatualizada em relação ao que está disponível aqui no Git. Esta versão desatualizada não está gerando o KeyStore completo e neste caso algumas funcionalidades do biblioteca ficam apresentando erros "javax.net.ssl.SSLHandshakeException".

Provisoriamente, criei uma biblioteca auxiliar para resolver o problema me baseando no DFCadeiaCertificados atualizado recentemente aqui no Git.

Gostaria de verificar a possibilidade de disponibilizar no Maven as correções efetuadas na classe DFCadeiaCertificados aqui no Git.

Att,
Rhodolfo Novochadlo.

**Comment by leandrodelsole** [comment]
Bom dia,

Também estou precisando de outras correções que estão na master mas não estão no maven.

Obrigado

**Comment by fincatto** [comment]
Caros, bom dia.
Liberei hoje uma nova versão no maven central 3,0,8 e, com uma contribuição muito bacana do @RafaelSTelles, cada merge pro master agora vai gerar automaticamente uma nova versão liberada no maven.
Abs
