### ISSUE TITLE
Pagamento da NFCe 4.00 com classes diferente do XSD

### ISSUE THREAD

**Issue by leandrodelsole** [wmixvideo/nfe#670]
Percebi que o Leiaute sendo usado para a nota 4.00 (schemas/PL_009_V4_00_NT_2019_001_v1.20a/leiauteNFe_v4.00.xsd) e todos os outros leiautes passados de notas 4.00 permitem apenas uma tag "pag". 

Hoje, este campo aceita uma lista, mas se tentar gerar o XML com mais de um elemento, ele falha a validação do XSD. Segue o trecho relevante do XSD:
```
						<xs:element name="cobr" minOccurs="0">...</xs:element>
						<xs:element name="pag">
							<xs:annotation>
								<xs:documentation>Dados de Pagamento. Obrigatório apenas para (NFC-e) NT 2012/004</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:element name="detPag" maxOccurs="100">...</xs:element>
									<xs:element name="vTroco" type="TDec_1302" minOccurs="0">...</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="infAdic" minOccurs="0">...</xs:element>
```

Portanto, para evitar erro de utilização a `NFNotaInfo` deve aceitar apenas um elemento de `NFNotaInfoPagamento`, e não uma lista.

**Comment by danielbohnrs** [comment]
Se tu olhar o manual da NF-e, diz que a tag pag tem 0-100 ocorrências, então o que está errado é o XSD de validação.

**Comment by leandrodelsole** [comment]
No caso estou falando de NFC-e, o manual é o mesmo que o de NF-e?
Vc pode compartilhar o link para este manual?

O XSD não é fornecido pelos orgãos competentes, eles não são a fonte da verdade?

**Comment by danielbohnrs** [comment]
É o mesmo manual sim, [este](http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=URCYvjVMIzI=), depois foram lançadas Notas Técnicas com ajustes, mas nada referente a isso.
Pois é, o XSD DEVERIA ser compatível com o manual, mas, às vezes tem erros.
Mas neste caso, como programador, tu pode fazer  teu sistema não preencher mais do que um `NFNotaInfoPagamento`, já que a lib está de acordo com o manual. Então quando lançarem uma nova versão do XSD, a lib continuará ok para este caso.

**Comment by leandrodelsole** [comment]
Obrigado pelos esclarecimentos.
Dei uma olhada no manual, e parece que ele se refere a versão 3.10. Nessa versão o XSD aceita 0..100 pagamentos mesmo. 

Não encontrei nenhum manual que cite a versão 4.00, nem nota técnica. Queria entender como essa evolução de versão se deu, sem atualização do manual.

Sobre conseguimos programar corretamente, sim, é possível, mas a lib é uma forma de ajudar a nos guiar pro correto desenvolvimento. Não vejo sentido em deixar ela fazer algo que o XSD não vai validar. Se depois corrigirem o XSD, voltamos o código para aceitar lista.

**Comment by danielbohnrs** [comment]
São muitas Notas Técnicas, mas encontrei aquela que fala sobre a modificação feita. [Aqui](http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=zfWxcJtOf98=).
Realmente foi modificado para aceitar apenas 1 tag `pag` e também nessa NT foi removido o meio de pagamento `14=Duplicata Mercantil`.
Desculpa qualquer coisa.

**Comment by leandrodelsole** [comment]
Muito bom! Aprendi bastante, obrigado.

**Comment by leandrodelsole** [comment]
Sobre a Duplicada, ia remover ela do Enum `NFMeioPagamento`, no entanto, vi que ela ainda está ativa no XSD. 
Fiquei confuso se ela não pode ter sido reincluída em outra NotaTécnica posterior.
Vou fazer um teste se o Sefaz aceita esse valor preenchido e depois retorno. Dependendo do andar deste PR, isso pode ser uma issue/PR separado.

**Comment by leandrodelsole** [comment]
Realmente a Duplicata foi removida também. O Sefaz do MS rejeitou:
Rejeicao: Informado Duplicata Mercantil como Forma de Pagamento

O curioso é que o XSD ainda possui este tipo, não deveria. Mas o sefaz rejeita. Então estou adicionando ao PR a remoção desse valor.

**Comment by fincatto** [comment]
Boa tarde pessoal.
Está ok agora? Posso fechar o PR?

**Comment by leandrodelsole** [comment]
Pode fechar sim, está ok agora. Obrigado

Em dom., 9 de ago. de 2020 às 13:37, Diego Fincatto <
notifications@github.com> escreveu:

**Comment by rcostaconsultoria** [comment]
Retirar esse cara `14=Duplicata Mercantil` do enum, quebra a baixa de notas do web service de Distribuição de DFe.

**Comment by fincatto** [comment]
Já voltei o enum pra lá!
