### ISSUE TITLE
A PrivateKey nem sempre é a primeira entry do KeyStore

### ISSUE THREAD

**Issue by betonetotbo** [wmixvideo/nfe#673]
Issue referente ao pull request #672 .

https://github.com/wmixvideo/nfe/blob/4eff6b57d15a5a499a5d4f3b711ef2a4afc4be3d/src/main/java/com/fincatto/documentofiscal/utils/DFAssinaturaDigital.java#L109

Peguei um certificado A1, no qual a primeira entry do KeyStore não era a chave privada. Para resolver foi feita a alteração do método `getPrivateKeyEntry` do pull request citado acima.

**Comment by fincatto** [comment]
Boa tarde @betonetotbo. 
O PR acima foi rejeitado pois alterava o arquivo de configuracao do projeto.
Um novo foi submetido e já incorporado ao projeto hoje.
Por favor, veja se resolveu o problema e reabra o chamado, caso ainda esteja com problemas.
Att
