### ISSUE TITLE
Objeto do lote não mantém atributos populados após serializar e desserializar

### ISSUE THREAD

**Issue by danielbohnrs** [wmixvideo/nfe#676]
Estava fazendo um teste de envio de NF-e para destinatário estrangeiro. Segundo o manual da nota, a tag `idEstrangeiro` permite 0 caracteres ou 5-20.
Preenchendo o campo com "", na rotina que assina o lote, esta informação é perdida. Pelo que vi, na linha abaixo, quando a tag está presente, mas sem conteúdo, ela é ignorada e com isso não gera o xml como deveria.

`final NFLoteEnvio loteAssinado = this.config.getPersister().read(NFLoteEnvio.class, documentoAssinado);`

ou seja, mesmo sem assinar, o retorno de `lote.toString()` é diferente de `this.config.getPersister().read(NFLoteEnvio.class, lote.toString()).toString()`;

Alguém já passou por algo semelhante que saberia como poderíamos contornar este problema? Já que teoricamente deveríamos manter o conteúdo da classe igual mesmo após serializar e desserializar.

**Comment by fincatto** [comment]
Bom dia @danielbohnrs.
Existe alguma solução que podemos implementar a nivel de biblioteca para este caso?

**Comment by danielbohnrs** [comment]
Boa tarde @fincatto.
Acredito que dê pra usar essa sugestão que dei no comentário anterior (que é dentro da rotina `getLoteAssinado` do `WSLoteEnvio`), pois não afeta a assinatura já gerada.
Com isso, se tiver sido setado "" antes de assinar, vai manter o xml assinado com a tag preenchida com "".

Se quiser posso preparar um PR com este ajuste.
