### ISSUE TITLE
Exemplo básico

### ISSUE THREAD

**Issue by mrbacamarte** [wmixvideo/nfe#681]
Consegui implementar até a visualização do status:
107
Servico em operacao
Mas, não consegui ir além disso...
Onde eu poderia encontrar um exemplo inicial, com os atributos mais básicos possíveis, para gerar uma NFe?
Valeu!!

**Comment by marcoslombardi** [comment]
Resumidamente,

Você preenche o objeto NFLoteEnvio com ao menos uma NFNota incluída.
E faz a chamada ao WebService conforme abaixo:
NFLoteEnvioRetornoDados loteEnvioRetornoDados = new WSFacade(new NfeConfig()).enviaLote(NFLoteEnvio);

**Comment by mrbacamarte** [comment]
Obrigado irmão, vou dar uma olhada!
