### ISSUE TITLE
LEITURA EM LOTE, CAMPOS REQUERIDOS

### ISSUE THREAD

**Issue by megaterrarc** [wmixvideo/nfe#684]
Boa Noite

   Estou fazendo uma leitura em lote de notas de fornecedores que possuem varias notas que estão omitindo certas tags como:

nfConf.getPersister(false).read(NFNotaProcessada.class, line);

```java
public class NFNotaInfoItemImpostoICMS20 extends DFBase {
    
    @Element(name = "modBC")
    private NFNotaInfoItemModalidadeBCICMS modalidadeBCICMS;

}
```

```java
public class NFNotaInfoFormaPagamento extends DFBase {
    
    @Element(name = "tPag")
    private NFMeioPagamento meioPagamento;

}
```

assim recebo a exceção

```
Empty value for @org.simpleframework.xml.Element(name="tPag", type=void.class, data=false, required=true) on field 'meioPagamento' private com.fincatto.documentofiscal.nfe400.classes.nota.NFMeioPagamento com.fincatto.documentofiscal.nfe400.classes.nota.NFNotaInfoFormaPagamento.meioPagamento in class com.fincatto.documentofiscal.nfe400.classes.nota.NFNotaInfoFormaPagamento at line 1

``` 

Alguma ideia de como podemos resolver isso?

**Comment by marcoslombardi** [comment]
Começou ocorrer este erro comigo também nesta última versão. 
Notas emitidas anteriormente podem vim com "14 - Duplicata mercantil" preenchidas.

Você pode sobrescrever a classe NFMeioPagamento no mesmo pacote com.fincatto.documentofiscal.nfe400.classes.nota adicionando o Enum DUPLICATA_MERCANTIL("14", "Duplicata mercantil")

**Comment by fincatto** [comment]
Acabei de liberar uma nova versao voltando o meio duplicata mercantil, para manter compatibilidade.
Quanto aos campos mencionados assim que estao vindo nulos nas notas, veja se existe em alguma nota tecnica que eles podem ser nulos. Se puderem, podemos colocar eles como nao requeridos na lib.
