### ISSUE TITLE
Erro de leitura de parsing de xml para objeto Java - Colocar novamente o valor 14 de duplicata mercantil no enum

### ISSUE THREAD

**Issue by rcostaconsultoria** [wmixvideo/nfe#685]
Retirar essa linha do enum quebra a leitura de alguns xmls de NFes que já foram emitidas com o valor **14**.

link do commit que retira o valor do enum: https://github.com/wmixvideo/nfe/commit/7e471e20a38347f6bddd78838ef2588c3539f110

Todos os cnpjs que testei aqui, baixou xmls que tinham `<tpag>14</tpag>`, e ao tentar fazer o parser de xml pra objeto Java, dá erro de leitura.

**Comment by fincatto** [comment]
Já foi colocado!
