### ISSUE TITLE
Erro 587 - Usar somente o namespace padrao da NF-e - consultaNota - SEFAZ MS

### ISSUE THREAD

**Issue by danielbohnrs** [wmixvideo/nfe#689]
Bom dia,
na rotina `consultaNota(chave)`, para emitente do MS, está dando o erro `587 - Usar somente o namespace padrao da NF-e`.

Mas pelo visto é apenas nessa UF, pois os clientes de outros estados estão conseguindo usar normalmente essa funcionalidade.

Alguém mais passou por esta situação?

xml gerado:
`<consSitNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00"><tpAmb>1</tpAmb><xServ>CONSULTAR</xServ><chNFe>50200930587916000150550010000002591836661953</chNFe></consSitNFe>`

xml retorno:
`<retConsSitNFe xmlns="http://www.portalfiscal.inf.br/nfe" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" versao="4.00"><tpAmb>1</tpAmb><verAplic>MS_1.0.4</verAplic><cStat>587</cStat><xMotivo>Rejeicao: Usar somente o namespace padrao da NF-e</xMotivo><cUF>50</cUF><dhRecbto>2020-09-16T11:17:59-04:00</dhRecbto></retConsSitNFe>`

**Comment by leandrodelsole** [comment]
Também tivemos esse problema, inclusive debugguei pra ver se o xmlns estava diferente ou algo assim. Parece que é algo do Sefaz MS mesmo. Ele deu tanto em produção quanto em homologação.

Inclusive, esse sefaz está bem lento em homologação também.

**Comment by marlosmorbis** [comment]
Boa tarde, 

Aqui na empresa estávamos com o mesmo problema, somente para o MS. Só que percebi que o problema só acontece no método consultaStatus, o que fizemos foi identificar se o retorno do consultaStatus vinha com o código 587 e deixar passar como OK, ao chamar os métodos para envio e consulta do lote emitido esse erro não acontece e a nota emite normalmente.
Por hora contornou o erro que aparenta ser da SEFAZ.

**Comment by marcelosantanadev** [comment]
Boa tarde, 

Estou com mesmo problema aqui, somente para o MS mesmo. Os outros métodos estão funcionando normalmente, somente de consulta está retornando este erro. Entrei em contato com pessoal da SGI do estado e estou aguardando retorno. Por hora estou utilizando a mesma solução do colega acima, tratando o erro 587 como OK, enquanto aguardo retorno.

**Comment by AntonioCaibro** [comment]
Solução . 

O que MS esta alegando é o prefixo do xml do metodo que é uma regra geral pela documentação. Mas não sei por que outros estados não cobra isso. O xml do parametro é que vai no envolope e não ele por completo . 

--> Com Prrefixo 
`// public static final javax.xml.namespace.QName MY_QNAME = new javax.xml.namespace.QName("http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", "nfeResultMsg", "ns1");`

--> Sem prefixo 
` public static final javax.xml.namespace.QName MY_QNAME = new javax.xml.namespace.QName("http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", "nfeResultMsg", "");`

Não sei vale apena parametrizar por estado já que todos funcionam sem o prefixo ns1 .

**Comment by fincatto** [comment]
Ótimo!
Consegue mandar um PR?
Att

Em ter., 8 de dez. de 2020 às 21:59, AntonioCaibro <notifications@github.com>
escreveu:

**Comment by leandrodelsole** [comment]
Bom dia, abri o PR que corrige o que consegui verificar o problema e testar a solução. Não consigo validar outros Sefaz fora o MS.

**Comment by fincatto** [comment]
Merge feito!

**Comment by Insertsoft** [comment]
Olá Pessoal !

A Sefaz de MS tem formato do XML de protocolo diferente das demais Sefaz ? Pois todas funcionam perfeitamente, mas na MS, eu envio o mesmo XML que as demais e ela me retorna o erro de Mal formatado, alguem já passou por isto?
