### ISSUE TITLE
[enhancement] Maven Central

### ISSUE THREAD

**Issue by eliocapelati** [wmixvideo/nfe#69]
Boa tarde,

* Gostaria de saber se vocês tem planos de publicar o projeto no repositório [central do maven](https://maven.apache.org/guides/mini/guide-central-repository-upload.html). 

Att,
-Elio

**Comment by jefperito** [comment]
Temos sim,

Não paramos ainda para verificar como se faz, se você souber os caminhos das pedras e poder dar uma ajuda, agradeço!

**Comment by jefperito** [comment]
Criado repositorio no maven central para distribuição de artefatos.

**Comment by fauker** [comment]
:+1:
