### ISSUE TITLE
Impressão NFE xml

### ISSUE THREAD

**Issue by P0l1c3na** [wmixvideo/nfe#693]
Olá,

Queria saber se há algum método na API para transformar a NF-e em XML para o DANFE pdf e se si, como usa-lo.

**Comment by danielbohnrs** [comment]
Tem um projeto separado, que usa as classes deste projeto para gerar a danfe a partir do XML.
https://github.com/danielbohnrs/danfe

**Comment by P0l1c3na** [comment]
Valeu mano, deu certo demais!
Muito Obrigado ae, salvou meu dia!
