### ISSUE TITLE
modalidadeBCICMS não requerido SEFAZ BAHIA

### ISSUE THREAD

**Issue by megaterrarc** [wmixvideo/nfe#695]
Estou com um problema ao ler um xml da Sefaz Bahia. Onde me retorna erro de campo requerido modalidadeBCICMS quando cst é 00 ou 20, respectivos NFNotaInfoItemImpostoICMS00 e NFNotaInfoItemImpostoICMS20.

- Forma de leitura.

![image](https://user-images.githubusercontent.com/9610355/95478913-8783bc00-0960-11eb-911d-862aaf904408.png)

- XML EXEMPLO
[29200940499907000161550510012191481018000058-procNFe.zip](https://github.com/wmixvideo/nfe/files/5348902/29200940499907000161550510012191481018000058-procNFe.zip)

- ERRO

```java
org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.Element(name="modBC", type=void.class, data=false, required=true) on field 'modalidadeBCICMS' private com.fincatto.documentofiscal.nfe400.classes.NFNotaInfoItemModalidadeBCICMS com.fincatto.documentofiscal.nfe400.classes.nota.NFNotaInfoItemImpostoICMS00.modalidadeBCICMS for class com.fincatto.documentofiscal.nfe400.classes.nota.NFNotaInfoItemImpostoICMS00 at line 1
```

*SOLUÇÃO*

  Inclui não requerido no campo, porem ao fazer o package do projeto me deparo com uma validação.

![image](https://user-images.githubusercontent.com/9610355/95479081-bc900e80-0960-11eb-9d97-de6091485630.png)

![image](https://user-images.githubusercontent.com/9610355/95479287-fb25c900-0960-11eb-8c1d-f243052cff07.png)

    Gostaria de uma sugestão para solução.

**Comment by fincatto** [comment]
Cria-se um teste unitario com o respectivo XML, altera-se o sistema para que ele funcione com o seu teste e depois, se quebrou algum outro teste, corrija-os para que reflitam a funcionalidade implementada. 
Se for um bug ou algo específico de uma unica sefaz, mas que nao reflete a documentação, sugiro que seja feita uma boa documentação, com comentarios nos codigos, para que outros usuarios entendam claramente o porque da alteração.

**Comment by megaterrarc** [comment]
Entendido! Eu criei um fork e fiz algumas particularidades. O ponto do meu projeto é importar arquivos independente das NTs e ou validações. Creio que não tenha motivo para que seja realizada alterações para esse tipo de procedimento, já que o foco da api é emitir a nfe.
