### ISSUE TITLE
Erro na leitura do retorno do cancelamento da NF-e

### ISSUE THREAD

**Issue by danielbohnrs** [wmixvideo/nfe#698]
Bom dia,
um cliente meu estava tentando cancelar uma nota que já havia CT-e e MDF-e. 
Na primeira tentativa, a Sefaz retornou a mensagem de erro corretamente: 690 - Pedido de Cancelamento para NF-e com MDF-e ou CT-e.

Na segunda tentativa, o xml retornado não estava no padrão previsto (não tenho o xml completo, mas pela mensagem de erro faltava o campo 'idLote'):
`org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.Element(name=idLote, data=false, type=void, required=true) on field 'idLote' private java.lang.String com.fincatto.documentofiscal.nfe400.classes.evento.NFEnviaEventoRetorno.idLote for class com.fincatto.documentofiscal.nfe400.classes.evento.NFEnviaEventoRetorno at line 1`

A minha pergunta é: não seria uma possibilidade de considerarmos colocar todos os atributos como opcionais, pelo menos nas classes usadas para ler os retornos? Dessa forma, mesmo que o webservice deixe de retornar algum dado, pelo menos não teríamos estes erros do Simple para deserializar o XML e poderíamos tratar e mostrar de forma 'amigável' ao usuário.

**Comment by fincatto** [comment]
Poderiamos fazer algo nesse sentido sim.
Quando projetamos a lib, confiamos muito na documentação, mas, com o tempo,
muitas sefaz provaram não seguir a documentação corretamente.
Neste caso, acho que colocar os retornos como não-obrigatorios poderiam
ajudar sim.
Se quierem implementar dessa forma, só mandar o PR e colocar uma boa
descrição e vamos em frente!
Abs

Em ter., 27 de out. de 2020 às 10:10, Daniel José Bohn <
notifications@github.com> escreveu:
