### ISSUE TITLE
[enhancement] Configuração externa

### ISSUE THREAD

**Issue by eliocapelati** [wmixvideo/nfe#70]
Boa tarde,

* Gostaria de saber se vocês tem planos uma maneira de configurar a aplicação de forma dinâmica com um "properties" (xml, yaml, json) externo, algo similar ao *log4j.properties*.

Att,
-Elio

**Comment by jefperito** [comment]
No momento não. A classe de config acho que atende bem o problema

**Comment by fincatto** [comment]
Faz pouco sentido uma feature dessas, uma vez que a biblioteca depende de integração com os sistemas das empresas pra funcionar. Uma vez que se tenha que fazer essa integração, cada um pode fazer a leitura de configurações como melhor lhe atender.
