### ISSUE TITLE
Erro introduzido pela PR #680

### ISSUE THREAD

**Issue by eldevanjr** [wmixvideo/nfe#701]
Olá @fincatto  , na PR #680 foi modificado a maneira de como a chave privada é carregada, quando uso  o KeyStore do Windows(
`KeyStore.getInstance("Windows-MY", "SunMSCAPI");`
) e contém mais de uma certificado, na maneira que foi feita a modificação, ele desconsidera o ALIAS que eu mando na configuração em DFConfig, e retorna o primeiro certificado encontrado, resultando na seguinte rejeição na receita:
Rejeição 213: CNPJ-Base do Autor difere do CNPJ-Base do Certificado Digital;
no meu caso eu escolho o certificado pelo alias do  CNPJ , e mando o ALIAS correto na configuração, no caso do PR ele faz a comparação dos aliases que estão no próprio KeyStore, resultando em sempre retornar o primeiro certificado instalado.

**Comment by eldevanjr** [comment]
talvez o erro #683 ocorreu por este motivo.

**Comment by danielbohnrs** [comment]
> talvez o erro #683 ocorreu por este motivo.

Boa tarde @eldevanjr, Só pra comentar: o erro da issue #683 já ocorria mesmo antes da PR #680 (tenho nos logs, erros desse tipo do ano passado).

**Comment by eldevanjr** [comment]
@danielbohnrs entendi, eu não fiz uma verificação deste erro mais profundamente, só que foi introduzido o código da #680 , e como ele é anterior a #683 achei que poderia estar relacionado... aqui começou a quebrar o código em nosso clientes, mas corrigindo e voltando o código anterior à PR #680 voltou a funcionar....
