### ISSUE TITLE
CSOSN 103

### ISSUE THREAD

**Issue by RobertoFloro** [wmixvideo/nfe#704]
Olá, pessoal! 
Utilizo o projeto da wmixvideos de nf-e/nfc-e faz algum tempo e o contador de um cliente solicitou a missão com CSOSN 103, mas não achei um classe para esse CSOSN.  Alguém poderia me esclarecer pq não tem uma classe de ICMS para o CSOSN 103 tipo NFNotaInfoItemImpostoICMS103?

**Comment by danielbohnrs** [comment]
Boa noite @RobertoFloro.
Conforme o [Manual](http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=URCYvjVMIzI=), (pg 205, para ser exato), os CSOSN 102, 103, 300 ou 400 são todos preenchidos na tag ICMSSN102, correspondente à classe NFNotaInfoItemImpostoICMSSN102 da lib.

**Comment by RobertoFloro** [comment]
Muito obrigado! Vlw
