### ISSUE TITLE
NFC-e SC

### ISSUE THREAD

**Issue by marconric** [wmixvideo/nfe#706]
Previsão para implementação NFC-e SC 

Para envio está faltando URL para geração QR na class DFUnidadeFederativa
Homologação: http://hom.sat.sef.sc.gov.br/nfce/consulta?p=
Produção: http://sat.sef.sc.gov.br/nfce/consulta?p= 

Consulta chave acesso

Homologação: http://hom.sat.sef.sc.gov.br/nfce/consulta
Produção: http://sat.sef.sc.gov.br/nfce/consulta

SC("SC", "Santa Catarina", "42","http://hom.sat.sef.sc.gov.br/nfce/consulta ","http://sat.sef.sc.gov.br/nfce/consulta","http://hom.sat.sef.sc.gov.br/nfce/consulta","http://sat.sef.sc.gov.br/nfce/consulta"),

**Comment by marlosmorbis** [comment]
Feito a PR #727 com a inclusão das URLs

**Comment by fincatto** [comment]
Obrigado @marlosmorbis!
Merge feito e subindo para o Maven Central!
