### ISSUE TITLE
Nota Técnica 2020.006

### ISSUE THREAD

**Issue by walterportugal** [wmixvideo/nfe#715]
Alguém já iniciou o desenvolvimentos das alterações conforme essa NT?

**Comment by plinioleitecosta** [comment]
Boa noite. Implementei o "Indicador Intermediador" da norma técnica citada.

**Comment by joseph-alexandre** [comment]
Boa noite. Alguma previsão de quando essa implementação irá para a master?

**Comment by fincatto** [comment]
Alguém já implementou e fez o PR?

**Comment by nielsonjr** [comment]
Oi, pessoal, eu terminei a implementação. Vou subir o PR

**Comment by fincatto** [comment]
Merge feito. Muito obrigado @nielsonjr, excelente implementação!
