### ISSUE TITLE
Dúvida sobre o lançamento do release 3.0.38 no repositório Maven

### ISSUE THREAD

**Issue by joseph-alexandre** [wmixvideo/nfe#718]
Boa tarde, pessoal, tudo bem?
Estou precisando das alterações que constam na release 3.0.38, utilizo o repositório do Maven para baixar e atualizar o projeto, porém essa release não foi colocada ainda no repositório do Maven. 
Alguém saberia me informar qual seria a previsão em que  a mesma seria postada no repositório do Maven?

Desculpem o incômodo qualquer coisa, agradeço desde já pela informação.

**Comment by fincatto** [comment]
Já está: https://search.maven.org/artifact/com.github.wmixvideo/nfe
