### ISSUE TITLE
Adequações Nota Técnica 2020.006 - v.1.20

### ISSUE THREAD

**Issue by joaoweit** [wmixvideo/nfe#723]
Acredito que sejam necessárias atualizações referentes à esta norma técnica.

**Comment by edivaldoms** [comment]
* Os campos B25c (indIntermed) e o grupo de intermediador (infIntermed) YB01 estarão disponíveis a partir 05/04/2021 em produção, porém, a validação ocorrerá somente a partir do dia 01/09/2021.

Creio que required deva ser false:
br/com/swconsultoria/nfe/schema_4/enviNFe/TNFe.java:29175
`protected String indIntermed;
@XmlElement(namespace = "http://www.portalfiscal.inf.br/nfe", required = true)`

Quando o valor da tag indIntermed é nula, dá erro de validação, pois está presente assim "<indIntermed/>" no XML:

A validação https://www.sefaz.rs.gov.br/NFE/NFE-VAL.aspx
Schema XML: The 'http://www.portalfiscal.inf.br/nfe:indIntermed' element is invalid - The value '' is invalid according to its datatype 'String' - The Enumeration constraint failed.
Caminho: NFe[1]/infNFe/ide/indIntermed

Quando retiro a tag "<indIntermed/>", valida normalmente.

**Comment by bpsanti** [comment]
Olá, agora que me parece que a versão referente a Nota Técnica está no ar em homologação, eu tentei fazer o seguinte teste de emissão utilizando:

- meioPagamento (tPag): 99 - Outros;
- descricaoMeioPagmento(xPag): "Teste".

E recebi a seguinte exception:
cvc-complex-type.2.4.a: Invalid content was found starting with element 'xPag'. One of '{"http://www.portalfiscal.inf.br/nfe":card}' is expected.

Pelo que eu vi, os schemas não estão atualizados, visto que já saíram os schemas dessa Nota Técnica para a v1.20, (a versão atual parece estar usando a v1.00): https://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=/fwLvLUSmU8=

**Comment by joseph-alexandre** [comment]
Estou com o mesmo caso acima. Existe alguma previsão de release com os schemas atualizados? D:

**Comment by fincatto** [comment]
PR integrado ao sistema! Obrigado @eldevanjr!
