### ISSUE TITLE
Erro chamada  NFStatusServicoConsultaRetorno para SP quando utilizado e-CPF

### ISSUE THREAD

**Issue by edudoda** [wmixvideo/nfe#734]
Ao chamar o serviço **NFStatusServicoConsultaRetorno** com os parâmetros abaixo:
 `NFStatusServicoConsultaRetorno retornoConsulta = configNota.consultaStatus( DFUnidadeFederativa.SP, DFModelo.NFE   );`

utilizando um e-CPF (Produtor Rural) o estado de SP retorna: **Rejeição: Certificado Transmissor sem CNPJ (Cód.: 282). [Versão: SP_NFE_PL009_V4]** tanto para ambiente de produção quanto homologação. 

Esse erro não ocorre com nenhum outro estado, ou quando utilizado um e-CNPJ. 

Sugestão: Avaliar se os demais serviços (enviaLote( ), etc.) não precisam desse ajuste para o estado de SP.

**Comment by fincatto** [comment]
Foram feitos trabalhos nessa area. Checar nas novas versoes se o erro persiste. Em caso positivo, mandar um codigo que permita checagem.
