### ISSUE TITLE
Ausência do campo <xPag> na classe NFNotaInfoFormaPagamento dentro de <detPag>

### ISSUE THREAD

**Issue by edudoda** [wmixvideo/nfe#739]
Ausência do campo   **xPag**  na classe **NFNotaInfoFormaPagamento** dentro de  **detPag** 

De acordo com a  [**NT 2020.006 - Criação e Atualização de Regras de Validação** ](https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=olkYgvQ3E7o=) publicada em 16/03/2021  
Se a forma de pagamento for 99 é necessário informar a TAG **Xpag**: Rejeição pelo motivo - 441: Descrição do pagamento obrigatória para meio de pagamento 99- outros .

Entretanto não localizei esse campo na classe **NFNotaInfoFormaPagamento**.

Além disso essa NT indica a necessidade de criar um novo  **Grupo YB. Informações do Intermediador da Transação** <infIntermed>  dentro de **NFNotaInfoPagamento**  . E também do campo <**indIntermed**> (Indicador de intermediador/marketplace) em  I**nformações de identificação da NF-e**

Relacionado a #723

**Comment by fincatto** [comment]
Campo adicionado em um PR anterior.
