### ISSUE TITLE
Dúvida - Porque os métodos get/set não são sempre declarados de forma padrão?

### ISSUE THREAD

**Issue by edudoda** [wmixvideo/nfe#745]
Pessoal, 

gostaria de entender o **motivo pelo qual os métodos get/set nem sempre são declarados de maneira padrão na biblioteca**?  

Deixe-me explicar, utilizo JSF visando integrar essa biblioteca diretamente ao meu front-end, entretanto, pela documentação do JSF: `JavaBeans spec says: If we discover a matching pair of “get<PropertyName>” and “set<PropertyName>” methods that take and return the same type, then we regard these methods as defining a read-write property whose name will be “<propertyName>”
`

E acontece que muitas classes tem métodos declarados de maneira "Não padrão", com isso tenho que ficar (re)fazendo todos os métodos em novas classes padrão para então chamar os métodos originais diretamente via Bean/Service, sendo que facilitaria bastante se pudesse chamá-los diretamente pela view. 

Isso resulta em um erros de **PropertyNotWritableException**, como por exemplo: 
`GRAVE: javax.faces.component.UpdateModelException: javax.el.PropertyNotWritableException: /.../detalharNotaInfoAddRespTec.xhtml @133,78 value="#{fiscalBean.nfeCorrente.nf.info.informacaoResposavelTecnico.cnpj}": Property [cnpj] not writable on type [com.fincatto.documentofiscal.nfe400.classes.nota.NFNotaInfoResponsavelTecnico]`

Exemplo, a clase **NFNotaInfoResponsavelTecnico**,  tem o campo :
 ```
@Element(name = "CNPJ")
 private String cnpj;
 
public String getCnpj() {
        return cnpj;
    }    

 //o erro acontece aqui pois  o  RETORNO não está como void
public NFNotaInfoResponsavelTecnico setCnpj(String cnpj) {
        DFStringValidador.cnpj(cnpj);
        this.cnpj = cnpj;
        return this;
    }
```
O mesmo problema ocorre com muitos outros métodos, em especial para as propriedades que usam alguma validação, como por exemplo  na classe **NFNotaInfoItemProduto** :

  ```
 @Element(name = "qCom")
    private String quantidadeComercial;

    public String getQuantidadeComercial() {
        return this.quantidadeComercial;
    }

 //o erro também acontece aqui pois  embora o retorno seja VOID o parâmetro passado (BigDecimal) é diferente do declarado (String) 
  public void setQuantidadeComercial(final BigDecimal quantidadeComercial) {
             this.quantidadeComercial = DFBigDecimalValidador.tamanho15comAte4CasasDecimais(
                                 quantidadeComercial, "Qtde Comercial Produto");
    }
```

Há um motivo para isso? Seria possível re-fatorar os métodos para a "forma padrão"? Caso contrário alguém tem alguma sugestão menos "onerosa" do que reescrever todos esses métodos em uma nova classe ?

**Comment by eldevanjr** [comment]
Olá, isto é chamado de _"method chaining"_, sendo um padrão de projeto, não está sendo seguido a especificação JavaBean neste caso, não é um erro, mas uma escolha de quem projetou esta classe em particular.

**Comment by edudoda** [comment]
@eldevanjr sim entendo que não é um erro até porque o código compila. Digo que é não padrão pois até mesmo o Eclipse e demais IDEs quando pede-se para gerar o método get/set vem com o mesmo tipo nos parâmetros e retornos.  

Vou ler mais obre o tema  no link que me enviou. Obrigado pela resposta!

**Comment by eldevanjr** [comment]
@edudoda, é isso mesmo, é outro padrão de projeto, o problema é que se algum framework usa o JavaBean, pode ocasionar estes problemas mesmo, já passei por isso. att.

**Comment by eldevanjr** [comment]
> @eldevanjr sim entendo que não é um erro até porque o código compila. Digo que é não padrão pois até mesmo o Eclipse e demais IDEs quando pede-se para gerar o método get/set vem com o mesmo tipo nos parâmetros e retornos.
> 
> Vou ler mais obre o tema no link que me enviou. Obrigado pela resposta!

uma solução seria sobrecarregar o método, para não quebrar os testes e quem usa o esquema de _"method chaining"_

**Comment by fincatto** [comment]
Boa noite pessoal. 
São realmente dois casos distintos. O setter que retorna a propria classe realmente é um padrão de projeto (e um dos bons, diga-se de passagem, pois facilita muito o uso no dia a dia). Quanto a setters com tipo diferente da variavel, isso realmente não deveria ocorrer, estando passível de refatoração (PR são muito bem-vindos!). 
Entrando um pouco no assunto do JSF, também dou manutenção em um sistema legado que usa JSF e o melhor conselho que posso dar é para deixar de usarem!  Nos casos onde não é possível, eu sugiro fortemente que não sejam usados os campos de uma lib externa diretamente na sua view, pois o risco de uma atualização na lib quebrar o seu sistema é muito grande e, sendo o JSF um sistema declarativo, muitas vezes a gente só pega esse tipo de erro em produção. Para tudo que preciso usar JSF, crio uma classe que faz a interface entre a pagina e minhas classes de negócio (sendo elas internas ou externas). Com isso, se algum codigo externo à view "quebra", eu recebo um erro de compilação e resolvo facilmente somente roteando o metodo chamado na minha interface para o novo método. Esse método é mais trabalhoso no início, mas se paga em pouco tempo, principalmente para quem cuida de sistemas grandes. 
Abraços!

**Comment by edudoda** [comment]
Obrigado pelas informações @fincatto! Vou seguir sua idéia e ir criando as classes intermediárias que ainda faltam para evitar chamar a lib direto na view (vai ser um grande trabalho fazer isso mas entendi seu ponto).

Quanto a setters com tipo diferente da variável, quando sobrar algum tempo espero poder contribuir com seu projeto com alguns PRs (desde já aproveito para parabenizá-lo por ele!). 

Se ajudar, posso te passar alguns pares GET/SET que já mapeei e não estão no padrão, basicamente a maioria dos campos que usam BigDecimal (ou BigInteger). Basicamente o que fiz foi mudar o método get() para retornar um BigDecimal ou BigInteger (ao invés de String) por meio de um método local: stringToBD() 
```
public BigDecimal getImpostoDevolvidoValorIPIDevolvido() {
 	 return  stringToBD(itemFull.getImpostoDevolvido().getInformacaoIPIDevolvido().getValorIPIDevolvido(),  2,  false);
 	}  

          //UTIL
	    public BigDecimal stringToBD(String nro, Integer nroCasasDecimais, boolean permitirNulo) { 
			BigDecimal bd =  null;
			if(nro != null) {
			     bd = 	new BigDecimal(nro);			  
			      if(nroCasasDecimais != null) {
					bd.setScale(nroCasasDecimais, RoundingMode.HALF_UP   );
				}			   
			}else {
				if(!permitirNulo) { 	 bd = 	  BigDecimal.ZERO; 	} 
			}		 
			return bd;
        } 
```

**NFNotaInfoTransporte** 
notaInfo.getTransporte().getVeiculo().setUf(DFUnidadeFederativa.valueOf(uf));  

**NFNotaInfoRetencaoICMSTransporte** 
notaInfo.getTransporte().getIcmsTransporte().setValorServico(valorServico); 
notaInfo.getTransporte().getIcmsTransporte().setBcRetencaoICMS(bcRetencaoICMS);
notaInfo.getTransporte().getIcmsTransporte().setAliquotaRetencao(valaliquotaRetencao);
notaInfo.getTransporte().getIcmsTransporte().setValorICMSRetido(valorICMSRetido);

**NFNotaInfoTransporte**
notaInfo.getTransporte().getVolumes().get(indice).setPesoLiquido(val);
notaInfo.getTransporte().getVolumes().get(indice).setPesoBruto(val);

**NFNotaInfoPagamento**
notaInfo.getPagamento().getDetalhamentoFormasPagamento().get(indice).setValorPagamento(valor);
notaInfo.getPagamento().setValorTroco(valor);

**NFNotaInfoResponsavelTecnico**
notaInfo.getInformacaoResposavelTecnico().setCnpj(cnpj);

**NFNotaInfoItemProduto**
itemFull.getProduto().setQuantidadeComercial(valor); 
itemFull.getProduto().setValorUnitario(valor); 
itemFull.getProduto().setValorTotalBruto(valor); 
itemFull.getProduto().setQuantidadeTributavel(valor); 
itemFull.getProduto().setValorUnitarioTributavel(valor); 
itemFull.getProduto().setValorFrete(valor); 
itemFull.getProduto().setValorSeguro(valor); 
itemFull.getProduto().setValorDesconto(valor); 
itemFull.getProduto().setValorOutrasDespesasAcessorias(valor); 

**NFNotaInfoItemImposto**
itemFull.getImposto().setValorTotalTributos(valor); 

**NFNotaInfoItemImpostoISSQN**
itemFull.getImposto().getIssqn().setValor(valor);

**NFNotaInfoItemImpostoImportacao**
itemFull.getImposto().getImpostoImportacao().setValorImpostoImportacao(valor);
itemFull.getImposto().getImpostoImportacao().setValorIOF(valor);
itemFull.getImposto().getImpostoImportacao().setValorDespesaAduaneira(valor);
itemFull.getImposto().getImpostoImportacao().setValorBaseCalculo(valor);

**NFNotaInfoSituacaoTributariaPIS**
itemFull.getImposto().getPis().getAliquota().setValorBaseCalculo(valor); 
itemFull.getImposto().getPis().getOutrasOperacoes().setValorBaseCalculo(valor); 
itemFull.getImposto().getPis().getAliquota().setPercentualAliquota(valor);
itemFull.getImposto().getPis().getOutrasOperacoes().setPercentualAliquota(valor); 
itemFull.getImposto().getPis().getAliquota().setValorTributo(valor);.
itemFull.getImposto().getPis().getOutrasOperacoes().setValorTributo(valor);
itemFull.getImposto().getPis().getQuantidade().setValorTributo(valor);
itemFull.getImposto().getPis().getQuantidade().setValorAliquota(valor);
itemFull.getImposto().getPis().getOutrasOperacoes().setValorAliquota(valor); 
itemFull.getImposto().getPis().getQuantidade().setQuantidadeVendida(valor);
itemFull.getImposto().getPis().getOutrasOperacoes().setQuantidadeVendida(valor);

**ImpostoPISSTPercentualAliquota**
itemFull.getImposto().getPisst().setQuantidadeVendida(valor); 
itemFull.getImposto().getPisst().setPercentualAliquota(valor);
itemFull.getImposto().getPisst().setValorAliquota( valor);
itemFull.getImposto().getPisst().setValorBaseCalculo(valor)
itemFull.getImposto().getPisst().setValorTributo(valor);

**NFNotaInfoSituacaoTributariaCOFINS**
itemFull.getImposto().getCofins().getAliquota().setValorBaseCalculo(valor); 
itemFull.getImposto().getCofins().getOutrasOperacoes().setValorBaseCalculo(valor); 
itemFull.getImposto().getCofins().getAliquota().setPercentualAliquota(valor); 
itemFull.getImposto().getCofins().getOutrasOperacoes().setPercentualCOFINS(valor); 
itemFull.getImposto().getCofins().getAliquota().setValor(valor);
itemFull.getImposto().getCofins().getOutrasOperacoes().setValorCOFINS(valor);
itemFull.getImposto().getCofins().getQuantidade().setValorTributo(valor);
itemFull.getImposto().getCofins().getQuantidade().setValorAliquota(valor);
itemFull.getImposto().getCofins().getOutrasOperacoes().setValorAliquota(valor); 
itemFull.getImposto().getCofins().getQuantidade().setQuantidadeVendida(valor);
itemFull.getImposto().getCofins().getOutrasOperacoes().setQuantidadeVendida(valor);

**ImpostoCOFINSST**
itemFull.getImposto().getCofinsst().setPercentualAliquota(valor);
itemFull.getImposto().getCofinsst().setQuantidadeVendida(valor);
itemFull.getImposto().getCofinsst().setValorAliquotaCOFINS( valor);
itemFull.getImposto().getCofinsst().setValorBaseCalculo(valor);
itemFull.getImposto().getCofinsst().setValorCOFINS(valor);

**ImpostoIPI**
itemFull.getImposto().getIpi().getTributado().setPercentualAliquota(valor);
itemFull.getImposto().getIpi().getTributado().setQuantidade(valor);
itemFull.getImposto().getIpi().getTributado().setValorBaseCalculo(valor);
itemFull.getImposto().getIpi().getTributado().setValorTributo(valor);
itemFull.getImposto().getIpi().getTributado().setValorUnidadeTributavel(valor);

**NFImpostoDevolvido**
itemFull.getImpostoDevolvido().getInformacaoIPIDevolvido().setValorIPIDevolvido(valor);
itemFull.getImpostoDevolvido().setPercentualDevolucao(valor);

**ICMS**
[Inúmeras...]

**Comment by fincatto** [comment]
Realmente este ponto é bastante válido. Eu concordo em usar os tipos corretos, mas acho que essa conversao nao deveria ser no get, mas sim na camada que faz a transição entre o objeto e o xml (ou vice versa). 
Idealmente, os objetos devem conter seus tipos certos para a "lógica" do negócio, e não obedecer a um tipo para o uso final dele. 
Neste caso, os PR serão muito bem vindos (trocando os tipos dentro dos objetos e convertedo no momento de carregar dos xml). Inclusive pode ser uma mudança incremental, você pode ir fazendo objeto a objeto e mandando os PR. Procure sempre adicionar testes unitários que validem sua alteração e garantam a funcionalidade da bibllioteca. Se precisar quebrar compatibilidade, daí sim é melhor fazer tudo de uma vez mandando um unico PR e solicitando a troca da versão, para não quebrarmos a implementação dos colegas que já usam desta maneira em produção.
