### ISSUE TITLE
Erro na validação do Schema XML NF-e: cvc-complex-type.2.4.a: Invalid content was found starting with element 'xPag'

### ISSUE THREAD

**Issue by joseph-alexandre** [wmixvideo/nfe#750]
Estou preenchendo o objeto da nota corretamente, porém quando o meio de pagamento é Outros, recebo o seguinte exception:
cvc-complex-type.2.4.a: Invalid content was found starting with element 'xPag'. One of '{"http://www.portalfiscal.inf.br/nfe":card}' is expected.

Vi que outra pessoa estava tendo o mesmo problema e a razão era que os Schemas estavam desatualizados, cujo foram atualizados em um PR recente. 
Issue: https://github.com/wmixvideo/nfe/issues/723

Contudo, o erro continua persistindo pra mim.

A lib está na versão 3.0.57 no meu projeto.

Forma de preenchimento:
meioPagamento (tPag): 99 - Outros;
descricaoMeioPagmento(xPag): "Teste outros pagamento".

Alguém ainda está passando por isso ou tem alguma ideia do que pode ser ou como proceder?

Agradeço desde já.

**Comment by fincatto** [comment]
Olá @joseph-alexandre.
Veja se a versão dos xsds estão corretas no projeto e depois veja se nelas tem a opção que você está preenchendo.

**Comment by edudoda** [comment]
Esse erro acontece está acontecendo por aqui também, acabei de atualizar para v3.0.59 e persiste...

**Comment by bpsanti** [comment]
Boa noite, eu havia comentado na issue que tu colou anteriormente.

Só vim relatar que eu não sei exatamente qual o problema. Achei que podesse ser alguma coisa nos schemas e verifiquei que existem schemas novos liberados pela Sefaz, mas mesmo atualizando os schemas o problema continua acontecendo, e pelo que vi do meu XML gerado, parece estar correto.

Além disso apenas como teste, testei remover a validação que a lib faz e enviar direto para a Sefaz (RS, homologação), e continuou ocorrendo o problema pra mim.

Os outros meios de pagamento (incluindo os novos), parecem estar normais.

Abaixo trecho do XML gerado, referente ao xPag.

```
<pag>
        <detPag>
          <indPag>0</indPag>
          <tPag>99</tPag>
          <vPag>1.00</vPag>
          <xPag>1231231123232</xPag>
        </detPag>
      </pag>
```

Não sei ainda como resolver o problema, alguém conseguiu já emitir uma nota com tPag 99 e xPag? Abraços :)

**Comment by bpsanti** [comment]
Bom dia, atualizando sobre a questão.

Aparentemente a tag <xPag> deveria vir antes da tag <vPag>
Eu vou ver se consigo essas modificações e abro o PR para cá :)
