### ISSUE TITLE
Erro ao realizar leitura de evento recebido da Sefaz

### ISSUE THREAD

**Issue by jpweit** [wmixvideo/nfe#757]
Estou realizando a leitura de eventos da sefaz, através do método consultarDistribuicaoDFe. 

Quando o evento é do tipo "procEventoNFe_v1.00.xsd", estou tentando realizar a leitura da seguinte forma

`new DFPersister().read(NFProtocoloEvento.class, xml)`

Mas estou recebendo o seguinte erro

`Element 'chCTe' does not have a match in class com.fincatto.documentofiscal.nfe400.classes.evento.NFInfoEventoRetorno at line 1`

Gostaria de uma orientação de como deveria realizar a leitura deste evento, segue o evento recebido abaixo

`<procEventoNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="1.00"><evento versao="1.00" xmlns="http://www.portalfiscal.inf.br/nfe"><infEvento Id="ID6101305120101020906300096355001000005068110028518101"><cOrgao>91</cOrgao><tpAmb>1</tpAmb><CNPJ>33683111000107</CNPJ><chNFe>51201010209063000963550010000050681100285181</chNFe><dhEvento>2020-10-22T02:13:52-03:00</dhEvento><tpEvento>610130</tpEvento><nSeqEvento>1</nSeqEvento><verEvento>1.00</verEvento><detEvento versao="1.00"><descEvento>Comprovante de Entrega do CT-e</descEvento><cOrgaoAutor>51</cOrgaoAutor><tpAutor>5</tpAutor><verAplic>1.3.6</verAplic><CTe><chCTe>51201004017029000137570010013307601008389851</chCTe><nProtCTe>151200420240056</nProtCTe><dhEntrega>2020-10-13T15:25:25-04:00</dhEntrega><nDoc>168100223</nDoc><xNome>DAVID DE A LIMA</xNome><hashEntregaCTe>Z7hRRHke/YmuIEvQNqV7Ly5eTQ8=</hashEntregaCTe><dhHashEntregaCTe>2020-10-21T18:50:09-03:00</dhHashEntregaCTe></CTe></detEvento></infEvento><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" /><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" /><Reference URI="#ID6101305120101020906300096355001000005068110028518101"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" /></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" /><DigestValue>3/LWqYkP9N4XEtDSL20Onl8V05s=</DigestValue></Reference></SignedInfo><SignatureValue>v1D32JqWA5so9yDn6MR/vS3KdQVFI66uzvbF1br249YbX7G9vdG27dSnoxZVvVjUPoJ+uNPYSeF7YJw1NR5SntPbOflpJGCKS6fRi2Z78HSZhi9rabUKbDBbecUiRoOPUiIZGVANM4gEpToLCtJ1Wn+9MndLPw6sFFWzhOa3H/RQ+skGlQVwFoFMzVDT/TSmE7IiLMBHqFMBH4TS6gNcbjF/FTlK3nVPDxwuQMOldoA/YaZIDSRqXnFA1YFKf9IiLzOsudH9IcvPpjzUmxyAjUvDTBiBjlui/YqpxQtPSWpsVKMZDvpLYg0oBWw5GUdIxjTSxGa1on9sMfhV85YWlQ==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIJJzCCBw+gAwIBAgIMKBhy+3q5VmK7F5jiMA0GCSqGSIb3DQEBCwUAMIGOMQswCQYDVQQGEwJCUjETMBEGA1UECgwKSUNQLUJyYXNpbDE2MDQGA1UECwwtU2VjcmV0YXJpYSBkYSBSZWNlaXRhIEZlZGVyYWwgZG8gQnJhc2lsIC0gUkZCMTIwMAYDVQQDDClBdXRvcmlkYWRlIENlcnRpZmljYWRvcmEgZG8gU0VSUFJPUkZCIFNTTDAeFw0yMDA4MDUxMjE3MDRaFw0yMTA4MDUxMjE3MDRaMIIBMDEYMBYGA1UEDwwPQnVzaW5lc3MgRW50aXR5MRMwEQYLKwYBBAGCNzwCAQMMAkJSMRcwFQYDVQQFEw4zMzY4MzExMTAwMDEwNzELMAkGA1UEBhMCQlIxCzAJBgNVBAgMAlNQMRgwFgYDVQQHDA9NT0dJIERBUyBDUlVaRVMxEzARBgNVBAoMCklDUC1CcmFzaWwxFzAVBgNVBAsMDjMzNjgzMTExMDAwMTA3MTYwNAYDVQQLDC1TZWNyZXRhcmlhIGRhIFJlY2VpdGEgRmVkZXJhbCBkbyBCcmFzaWwgLSBSRkIxETAPBgNVBAsMCEFSU0VSUFJPMRowGAYDVQQLDBFSRkIgZS1TZXJ2aWRvciBBMTEdMBsGA1UEAwwUc3BlZC5yZWNlaXRhLmZhemVuZGEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDP5XI63lcKRGT5WaFKOl1OMkjfINRFkQQGvkoVOyjj1UBumkySIdXfH9Nd8MVZ5f8DAgc5OEIPwF6Bu2HOUH27F5TTIsbclZ0u2PU8Bcq5E3GAChRIXwiCBxNU9BJOPKre55weCfiHfOWOQ9EYaGvVchpMU/HvxeaAFUYDdEDwxJSXYF14kaMK5W+Y5bHdjdlRRs6gyYCC/AbNx3wGY55elvgn/y9K0+ru0cVAnRYxOzXLCMWsMF0+9c8fYb03JF29yk1m62PVjjLpFoz4lbiD2PtMFXgBsm+y/9XMqbrD/KFZQB7nwGg+gfzCpb6bQiBIuCvPAYJni+1m6nZp9ObfAgMBAAGjggPeMIID2jAfBgNVHSMEGDAWgBQgjRFcVcMBb6tW8YPMaKmrwtq1YzBoBgNVHSAEYTBfMAgGBmeBDAECAjBTBgZgTAECAVswSTBHBggrBgEFBQcCARY7aHR0cDovL3JlcG9zaXRvcmlvLnNlcnByby5nb3YuYnIvZG9jcy9kcGNhY3NlcnByb3JmYnNzbC5wZGYwgYsGA1UdHwSBgzCBgDA9oDugOYY3aHR0cDovL3JlcG9zaXRvcmlvLnNlcnByby5nb3YuYnIvbGNyL2Fjc2VycHJvcmZic3NsLmNybDA/oD2gO4Y5aHR0cDovL2NlcnRpZmljYWRvczIuc2VycHJvLmdvdi5ici9sY3IvYWNzZXJwcm9yZmJzc2wuY3JsMIIBBAYKKwYBBAHWeQIEAgSB9QSB8gDwAHYAXNxDkv7mq0VEsV6a1FbmEDf71fpH3KFzlLJe5vbHDsoAAAFzvo214QAABAMARzBFAiBRgUSZE9xIAPzg96YX9FdGYZd/M9w8hSKkGYWVX3fe1wIhAOJUdJ9IvPNQpLR0uc4NxTkZ2PdlYG/Welfpxe8tgntLAHYA9lyUL9F3MCIUVBgIMJRWjuNNExkzv98MLyALzE7xZOMAAAFzvo3E/AAABAMARzBFAiEAmRHIeU8aM9aWcBbsTZ5gi5m7CNWMYaDsbW46neE7nAICIGItIP0ww5is/WODwwaDdlnovCnlD9PbG+1Gi6XwY36WMIGOBggrBgEFBQcBAQSBgTB/MEcGCCsGAQUFBzAChjtodHRwOi8vcmVwb3NpdG9yaW8uc2VycHJvLmdvdi5ici9jYWRlaWFzL2Fjc2VycHJvcmZic3NsLnA3YjA0BggrBgEFBQcwAYYoaHR0cDovL29jc3Auc2VycHJvLmdvdi5ici9BQ1NFUlBST1JGQlNTTDCB9gYDVR0RBIHuMIHroDsGBWBMAQMIoDIEMFNFUlZJQ08gRkVERVJBTCBERSBQUk9DRVNTQU1FTlRPIERFIERBRE9TIFNFUlBST4IUc3BlZC5yZWNlaXRhLmZhemVuZGGgOAYFYEwBAwSgLwQtMTgwMzE5ODAyODU2MDE2ODgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwoCIGBWBMAQMCoBkEF0VEVUFSRE8gWU9TSElEQSBTQUxPTUFPoBkGBWBMAQMDoBAEDjMzNjgzMTExMDAwMTA3gR1lZHVhcmRvLnlvc2hpZGFAc2VycHJvLmdvdi5icjAOBgNVHQ8BAf8EBAMCBeAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA0GCSqGSIb3DQEBCwUAA4ICAQCcFDVpr1I3MFCqIkkjbNed8+FV91rtK9gjnwvwa7hmnzHOUXJERDHa7PwmSi4Xrg5mQqmgiPyjyhs0TNU2YBC1EbO02YHMA+a3frrkgRYm0w7gb2LU0mcnGSfbXST1odu6tztzaiDF+GfLg6uAcSRKyc+czXNI3tnZPQ1xqASnkZ6jc1KqCIA9hEIrzQx4LFCaAXrqZqyYEZs02eXzgvgRCPg0NqptGqI+Ir0Qg3cmTxIONMPiIohP4EN4XisPUWCEA5RiTiRFWOSgJnRTB8Fbe6DjEZnlCARpaKEExikIacxMcPEURVUgSXAP492uITyNZw8h6v3rb5F0E6Z4fiqgsW8O6aCDNZ2tr2gXTZ0+ZGOoNFKxa34r4V/ZW48wz9x8ix24jJo2Dt4iz/KfQh3UucTf6sgt/C5BN3/WY6zXzmaMNhzQeKDyrz/SNEF4nJaqHS6j1a1YjrNr/fTgc3gBzRU+YLx06+WVDj8Hzf70Yhx5kC9VM7iMLlD0GuvGcIWV/irhXtw2wwZW0uaUAjJ2xozrmwkK8YZ1FQzOX7QQgxLYr0GTa39Bm/qVNGNvLRXrhIH5T3pnssJLdpGzYrf1THIY3AQe8z/r47PtGwviZJoFTXpYI8UUyAcb7tcARU9tYLkbQphkcXbEhf8b7Wt7EztM/FhoucomdYvQqTlwGg==</X509Certificate></X509Data></KeyInfo></Signature></evento><retEvento versao="1.00" xmlns="http://www.portalfiscal.inf.br/nfe"><infEvento Id="ID891203880261978"><tpAmb>1</tpAmb><verAplic>AN_1.1.3</verAplic><cOrgao>91</cOrgao><cStat>135</cStat><xMotivo>Evento registrado e vinculado a NF-e</xMotivo><chNFe>51201010209063000963550010000050681100285181</chNFe><tpEvento>610130</tpEvento><nSeqEvento>1</nSeqEvento><cOrgaoAutor>51</cOrgaoAutor><chCTe>51201004017029000137570010013307601008389851</chCTe><dhRegEvento>2020-10-22T02:13:52-03:00</dhRegEvento><nProt>891203880261978</nProt></infEvento></retEvento></procEventoNFe>`

**Comment by pedrovitore** [comment]
Me parece que o problema está sendo causado pelo tipo de evento 610130 especificamente, que segue um schema diferente do procEventoNFe descrito no manual da SEFAZ. Será que o schema do procEventoNFe foi alterado mas o documento não foi atualizado?
Não encontrei nenhuma documentação referente a esse tipo de evento. Alguém encontrou?

Mas ao que me parece a classe com.fincatto.documentofiscal.nfe400.classes.evento.NFInfoEventoRetorno não tem o campo chCTe.
Além disso também a classe com.fincatto.documentofiscal.nfe400.classes.evento.NFTipoEvento não têm os campos do CTe: cOrgaoAutor, tpAutor, verAplic e o grupo CTe inteiro.
Adicionar esse campos nas classes deve resolver o seu problema.
