### ISSUE TITLE
Assinatura digital ao gerar especificação de requisitos PAF-NFC-e/Santa Catarina

### ISSUE THREAD

**Issue by FelipeGutjahr** [wmixvideo/nfe#759]
Estou gerando o arquivo .txt requerido pela sefaz de Santa Catarina em sistemas que fazem a emissão de NFC-e, porém o registro tipo EAD - Assinatura digital se mostrou um pouco complexo.

Alguém que já implementou a geração desse arquivo pode disponibilizar a forma em que é gerado o registro EAD?

[http://legislacao.sef.sc.gov.br/html/atos_diat/2020/atodiat_20_038_anexo_iii.pdf](url)

**Comment by fincatto** [comment]
Ola Felipe. 
Isso está relacionado a NFe?
