### ISSUE TITLE
Consulta NFCe em MT retorna erro

### ISSUE THREAD

**Issue by Roberto-Slv** [wmixvideo/nfe#761]
Olá pessoal.
Gostaria de uma ajuda, ao realizar uma consulta de NFC-e para o estado de MT utilizando o Método: "**new WSFacade(config).consultaNota(numeroChave)**", recebo o erro "**Attribute 'id' does not have a match in class com.fincatto.documentofiscal.nfe400.classes.NFProtocoloInfo at line 1**", não consegui uma solução para esse erro, não sei se tem precedente aqui desse caso ou se estou fazendo alguma coisa erra na hora de consulta. Alguém tem uma luz para ajudar?

**Comment by fincatto** [comment]
Boa noite Roberto.
Você chegou a debugar o retorno?
Consegue compartilhar o seu codigo para checagem?

**Comment by Roberto-Slv** [comment]
Olá, cheguei a debugar sim. 
O erro ocorre no momento de converter o XML em String para a classe NFNotaConsultaRetorno.class.
É exatamente na linha 27 da classe WSNotaConsulta.class.

**Comment by eldevanjr** [comment]
Olá @Roberto-Slv e @fincatto , tive um erro semelhante , o retorno XML da receita retornava alguns caracteres estranhos, como pode ser verificado neste PR: [https://github.com/wmixvideo/nfe/pull/638](https://github.com/wmixvideo/nfe/pull/638), eu precisei remover estes caracteres estranhos, para depois converter p/ para a classe NFNotaConsultaRetorno.class.

**Comment by eldevanjr** [comment]
Não sei se pode ser o mesmo erro...

**Comment by Roberto-Slv** [comment]
Vlw, @eldevanjr!
Dei uma olhada no caso, mas o problema no caso ocorre no campo **id**  da classe **NFProtocoloInfo.class**. Ela fala que não combina. No meu caso fiz uma emissão **Sincrona** e na hora de consultar pelo método" **new WSFacade(config).consultaNota(numeroChave)**" .

**Comment by eldevanjr** [comment]
Então @Roberto-Slv ,  No meu caso eu primeira realizo a consulta como String e depois faço a Serialização do Objeto, talvez tente verificar o retorno String e localizar o erro, assim que consegui resolver o problema no PR #638 , segue a baixo o código que uso :
``` java
 String s = new WSFacade(config).consultaNotaAsString(chave);                  
 NFNotaConsultaRetorno consultaNFe = new DFPersister(false).read(NFNotaConsultaRetorno.class, s.replaceAll("&null;", ""));
```

**Comment by eldevanjr** [comment]
No meu caso coloco o _strict_  da classe _DFPersister_ como falso p/ ignorar os campos não encontrados... talvez funcione pra este caso.

**Comment by fincatto** [comment]
Esse campo está na documentação oficial da Sefaz? Se estiver, é só colocar. 
Se for uma "aberração" da Sefaz estadual, sugiro a solução do @eldevanjr, setando o strict para false.

**Comment by Roberto-Slv** [comment]
@fincatto e @eldevanjr muito obrigado pela ajuda.
