### ISSUE TITLE
Como validar data de expiração do certificado?

### ISSUE THREAD

**Issue by secodigo** [wmixvideo/nfe#767]
How to validate certificate expiration date?

**Comment by marcoslombardi** [comment]
Segue um trecho de código para recuperar a data de expiração de certificados do tipo A1


      `
      Date dataExpiracaoCertificado = null;
      
      // Certificado A1
      InputStream certificadoStream = NfeConfig.class.getResourceAsStream("/pasta/certificado.pfx");
      
      Security.addProvider(new BouncyCastleProvider());
      
      KeyStore keyStoreCertificado = KeyStore.getInstance("PKCS12", BouncyCastleProvider.PROVIDER_NAME);
      keyStoreCertificado.load(certificadoStream, getCertificadoSenha().toCharArray());
      
      KeyStore.PrivateKeyEntry privateKeyEntry = getPrivateKey();
      String alias = getAliasPrivateKey();
      
      if(keyStoreCertificado != null && StringUtils.isNotBlank(alias)) {
	      
	      Certificate certificado = keyStoreCertificado.getCertificate(alias);
	      
	      if (certificado.getType().equals("X.509")) {
      
		      X509Certificate x509Certificate = ((X509Certificate) privateKeyEntry.getCertificate());
      
		      dataExpiracaoCertificado = x509Certificate.getNotAfter();
	      }
      }
      `

**Comment by secodigo** [comment]
Obrigado Marcos
