### ISSUE TITLE
Novas tags não mapeadas FCPDif, vFCPEfet e pFCPDif

### ISSUE THREAD

**Issue by rcostaconsultoria** [wmixvideo/nfe#773]
As tags a seguir não estão mapeadas e acaba dando erro ao tentar fazer a desserialização de xml para Objeto:
FCPDif, vFCPEfet e pFCPDif

**Comment by fincatto** [comment]
Olá @rcostaconsultoria.
Em qual dos objetos você está tendo esso erro?
Consegue fazer um PR com a correção e o teste?
