### ISSUE TITLE
Error ao consultar Distribuição DFe, 403 - Forbidden

### ISSUE THREAD

**Issue by hugosantos22** [wmixvideo/nfe#797]
Estou com o error abaixo ao consultar a distribuição de DFe em homologação para o estado de minas gerais.

Caused by: java.lang.Exception: Transport error: 403 Error: Forbidden
	at com.fincatto.documentofiscal.nfe.webservices.distribuicao.WSDistribuicaoNFe.consultar(WSDistribuicaoNFe.java:59)

Alguém está passando por isso também ?

**Comment by pedrovitore** [comment]
Vc está usando um certificado digital válido e dentro do prazo de validade?

Quando eu tomei erro 403 era porque o certificado digital da empresa estava expirado.

**Comment by hugosantos22** [comment]
Sim, utilizei mais de um para realizar testes e todos são validos.

**Comment by marcoslombardi** [comment]
Esse erro acontece tem bastante tempo (anos) no ambiente de homologação. Já no ambiente de produção acontece a rejeição 109 - Servico paralisado sem previsao

Creio que foi descontinuado esse WS.

**Comment by fincatto** [comment]
Pela documentação da Sefaz, estavam ocorrendo abusos neste serviço, então eles travaram o uso até eles melhorarem a implementação deles. Deve voltar daqui a um tempo.
