### ISSUE TITLE
CDATA na URL do QrCode NFCe

### ISSUE THREAD

**Issue by Ommegadata** [wmixvideo/nfe#805]
Na versão 1.0 do QrCode era necessário utilizar a tag CDATA para escapar o '&', mas na versão 2.0 não é mais necessário pois foi substituído pelo '|'.

Exemplo 1.0:
```
<infNFeSupl>
    <qrCode>
        <![CDATA[
https://www.sefaz.rs.gov.br/NFCE/NFCE-COM.aspx?chNFe=43180907385111000102655010306202701131447746&nVersao=100&tpAmb=2&cDest=07385111000102&dhEmi=323031352d30392d30345430393a30303a30302d30333a3030&vNF=474.00&vICMS=0.00&digVal=7438702f2b4761695353556a41345054777a5563574e756b5153553d&cIdToken=000001&cHashQRCode=0F2ACF628AC384DCCDAF5B42FF382CA6936D3529]]>
    </qrCode>
</infNFeSupl>
```

Exemplo 2.0:
```
<infNFeSupl>
    <qrCode>https://www.sefaz.rs.gov.br/NFCE/NFCE-COM.aspx?p=43180907385111000102655010306202701131447746|2|2|2|D181FB0770A496C5B70B1804E26B2112628A0FC1</qrCode>
    <urlChave>http://www.sefaz.rs.gov.br/nfce/consulta</urlChave>
</infNFeSupl>
```

Ao gerar o XML de uma NFCe com QrCode 2.0 ainda está aparecendo o CDATA:

```
<infNFeSupl>
	<qrCode><![CDATA[https://hom.sat.sef.sc.gov.br/nfce/consulta?p=42220434150405000128650010000158301734940283|2|2|1|59BB8E76987DB046FC587C67A2AAA3E4B3DE9BE3]]></qrCode>
	<urlChave>https://hom.sat.sef.sc.gov.br/nfce/consulta</urlChave>
</infNFeSupl>
```

Isso está comprometendo a leitura da URL em sistemas que importam o XML gerado pela biblioteca. A nossa equipe sugere a seguinte alteração na classe [NFNotaInfoSuplementar](https://github.com/wmixvideo/nfe/blob/ff172643a2df1854a8c07bcb57c4c6ea9941e7d8/src/main/java/com/fincatto/documentofiscal/nfe400/classes/nota/NFNotaInfoSuplementar.java).

De:
```
    @Element(data = true, name = "qrCode")
    private String qrCode;
```

Para:
```
    @Element(name = "qrCode")
    private String qrCode;
```

[]'s

**Comment by fincatto** [comment]
Olá @Ommegadata.
Essa sugestão irá quebrar a versão antiga? Se sim, existe uma alterativa para manter a retrocompatibilidade?
