### ISSUE TITLE
Sugestão de Adaptação/Melhoria

### ISSUE THREAD

**Issue by LimaLucas96** [wmixvideo/nfe#812]
Voce poderia adaptar o código para ser possível o envio do BP-e

**Comment by fincatto** [comment]
Olá @LimaLucas96. 
É bem dificil testar a funcionalidade sem que nosso CNPJ esteja apto a enviar de fato esses documentos.
Se você tem acesso a um certificado com isso, estaria apto a implementar esse envio e nos mandar um PR?
