### ISSUE TITLE
Mudança de endereços dos serviços NFeDistribuicaoDFe e RecepcaoEvento para ambiente de Homologação 

### ISSUE THREAD

**Issue by edudoda** [wmixvideo/nfe#815]
Pessoal estou tendo problemas ao testar o serviço `consultarDistribuicaoDFe()` em ambiente de Homologação (Em produção está ok).  Estou usando o protocolo padrão "TLSv1.2".

```
Erro: Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
	at com.fincatto.documentofiscal.nfe.webservices.distribuicao.WSDistribuicaoNFe.consultar(WSDistribuicaoNFe.java:59)
	at com.fincatto.documentofiscal.nfe400.webservices.WSFacade.consultarDistribuicaoDFe(WSFacade.java:365)
```

Pelo que pude verificar, aparentemente os endereços dos serviços **NFeDistribuicaoDFe**  e **RecepcaoEvento**  do  Ambiente Nacional (AN) de [HOMOLOGAÇÃO](https://hom.nfe.fazenda.gov.br/portal/webServices.aspx) mudaram e agora os métodos abaixo precisam incluir o número '1' (**https://hom1...**) na classe **NFAutorizador400.java** :

```
   @Override
     public String getNFeDistribuicaoDFe(final DFAmbiente ambiente) {
         return DFAmbiente.HOMOLOGACAO.equals(ambiente) ? "https://hom1.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx" :         	 "https://www1.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx";
     }
 
     @Override
     public String getRecepcaoEventoAN(final DFAmbiente ambiente) {
         return DFAmbiente.HOMOLOGACAO.equals(ambiente) ? "https://hom1.nfe.fazenda.gov.br/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx" : 
        	 "https://www.nfe.fazenda.gov.br/NFeRecepcaoEvento4/NFeRecepcaoEvento4.asmx";
     }
```

**Comment by capkverna** [comment]
Devido aos caminhos errados também está retornando erro 404 Not Found.
Como dito anteriormente, o problema é apenas em ambiente de homologação.
Preciso fazer alguns testes na rotina em ambiente de homologação, mas devido ao erro não tenho como fazê-los.

**Comment by giovaneboeing** [comment]
estou com o mesmo problema do citado na issue, no aguardo do pr

**Comment by fincatto** [comment]
Os releases pendentes foram feitos! Havia um problema com a chave pgp, mas tudo normalizado agora!
