### ISSUE TITLE
Monitorar nota emitida para meu CNPJ

### ISSUE THREAD

**Issue by hermesalvesbr** [wmixvideo/nfe#828]
Boa tarde pessoal,

Poderiam me indicar alguma lib/sdk que permita via meu certificado digital que eu monitore as notas fiscais emitidas para o meu CNPJ?

Gostaria de saber quando alguém emitir uma nota fiscal de venda para o meu cnpj. 

Pode ser em outra linguagem, não tem problemas. 

Agradeço desde já qualquer contribuição,

**Comment by arthurrib** [comment]
Essa aqui permite, mano. Você vai implementar o método "consultarDistribuicaoDFe" aqui da lib e fazer a consulta por chave, NSU ou ultNSU.
A implementação não é muito amigável mas a culpa é da SEFAZ heheh.

Você precisa guardar esse valor do ultNSU e consultar de tempos em tempos para recuperar os arquivos novos. A parte chata é que tem um limite muito baixo de consultas na sefaz.
Se você consultar um mesmo nsu 3 vezes toma ban de 1h, e o limite é de 20 consultas por hora. Se a consulta em lote (por ultNSU) não te servir você precisa fazer consulta sequencial por NSU, limitado a 20 por hora mesmo.
