### ISSUE TITLE
Mais de um certificado pfx

### ISSUE THREAD

**Issue by henriquelssantiagorcosta** [wmixvideo/nfe#832]
Como fazer a utilização de mais de um certificado digital do tipo pfx?
Por exemplo, no caso de o sistema emitir NFes ou até mesmo outras comunicações com a sefaz ao mesmo tempo.
Empresa A emitindo NFe com um certificado digital e Empresa B emitiindo NFe com outro certificado digital ao mesmo tempo, ou até mesmo uma empresa C emitindo uma NFCe.
E também o caso de baixa de NFe pelo WS de Distribuição de DFe.

**Comment by fincatto** [comment]
Nós utilizamos configurações diferentes (objeto de configuração que contem o arquivo). 
Funciona bem e é prático.
