### ISSUE TITLE
Xml com nova informação tpAto no ramo procRef

### ISSUE THREAD

**Issue by guigssilva** [wmixvideo/nfe#849]
Boa Tarde o Xml que tento ler pela biblioteca está com esse novo atributo <tpAto> e o objeto referente NFNotaInfoProcessoReferenciado ainda não possui ele, alguma previsão

**Comment by fincatto** [comment]
Bom dia @guigssilva.
Você consegue implementar, com um caso de teste, e mandar um PR?

**Comment by fincatto** [comment]
Fechando issue por falta de PR com a implementacao.
