### ISSUE TITLE
CSOSN 202 não deveria obrigar o percentual de FCP para o mesmo estado

### ISSUE THREAD

**Issue by karinejung6** [wmixvideo/nfe#854]
CSOSN 202 não deveria obrigar o percentual de FCP para alguns estados.

**Comment by karinejung6** [comment]
Para SC, por exemplo, não deveria ser obrigatório o percentual de FCP.

**Comment by fincatto** [comment]
Recebemos um PR com conflitos, que não pode ser mergeado. Aguardando novo PR corrigido.
