### ISSUE TITLE
Gerando dhEmi com data errada

### ISSUE THREAD

**Issue by andregui7** [wmixvideo/nfe#89]
Olá, estou com problemas ao gerar o XML. está gerando a tag dhEmi no formato errado. 

Exemplo: <dhEmi>2015-10-11T11:13:16Z</dhEmi>

Acho que o "Z" está errado, deveria ser assim:

<dhEmi>2015-10-11T11:13:16-03:00</dhEmi>

No código estou fazendo como nas classes testes:

setDataHoraEmissao(new LocalDateTime(2015, 11, 11, 9, 0, 0));

Interessante que isso acontece somente em computadores Windows.

Alguma sugestão?

Obrigado.

**Comment by jefperito** [comment]
Eu não utilizo S.O. Windows, porém não acho que seja problema com relação ao sistema operacional, pois vários usuários da lib usa Windows.
Talvez a lib JodaTime deve ta pegando alguma configuração da tua maquina virtual. Tenta dar uma olhada nisso

**Comment by andregui7** [comment]
To achando que pode ser questão de versão do Java. Compilei na versão 8. Vou testar na 7 ou 6.

**Comment by fauker** [comment]
Faz esse teste e posta aqui pra gente o resultado, @andregui7. Deve ser algo local desse tipo, mesmo.

Não uso Windows, mas não tem muito sentido ser S.O.

**Comment by andregui7** [comment]
Para gerar NFC-e ele está pedindo que informe QRCode no campo infNFeSupl. Pelo visto esta biblioteca não tem essa tag infNFeSupl para ser informada. Acredito que não consiga usar pra NFC-e.

**Comment by andregui7** [comment]
Bom, não vejo outra alternativa se não fazer uma biblioteca do zero. Será que consigo reaproveitar esta para NFC-e?

**Comment by jefperito** [comment]
Creio que sim, não tenho idéia como seja NFC-e, mas creio que seja muito parecida, talvez daria para deixar intercambiável, porém não utilizamos NFC-e aqui e não teria como testar com a Sefaz, para dar suporte, teria que esperar alguém se prontificasse em implementar isso.

**Comment by andregui7** [comment]
Perito, talvez já tenha perguntado isso, mas o que teria que fazer basicamente? Baixar algum arquivo do governo e gerar as classes stubs? Refazer talvez as classes do pacote classes?

**Comment by jefperito** [comment]
Eu não sei o que exatamente teria q ser feito, acho que possui a informação no site da sefaz:
http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=9hd38oni4Nc=

Se eu nao me engano, na versao 3.10, a NF-e e NFC-e sao o mesmo modelo, portanto daria para ser aproveitado.

Acho criar do zero o projeto é um pouco complexo, pois a geracao dos stubs é coisa de 5% do projeto, nesse aqui possui mais de 2000 testes de unidade e 5480 linhas de código implementado por + de 1 ano.

**Comment by andregui7** [comment]
Infelizmente não são mesmo modelo. Talvez antes era assim, mas hoje não é mais. No forum do javac http://www.javac.com.br/jc/posts/list/0/2312.page#10864 o GGarcia fala de algumas tags de diferença entre os layouts.

**Comment by jefperito** [comment]
Ok, vou fechar o ticket pois considero que a lib no momento não suporta NFC-e.
