### ISSUE TITLE
Adequação SOAP 1.2 - SEFAZ MG

### ISSUE THREAD

**Issue by matheuscardosocontrolenamao** [wmixvideo/nfe#916]
Olá, desde o início da semana passada na página de webservices da SEFAZ-MG existe um comunicado sobre:

"A partir de 03/07, seguindo o manual do contribuinte, não será mais aceito outro padrão diferente do SOAP Versão 1.2" (conforme imagem abaixo):

![1](https://github.com/wmixvideo/nfe/assets/111610602/b9ee8f3d-66f2-40cf-841a-71db16537b33)

No nosso sistema, tentamos emitir uma NF-e via SEFAZ-MG e nos retornou o seguinte erro:

`<retConsStatServ xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00"><tpAmb>1</tpAmb><verAplic>W-3.0.70</verAplic><cStat>215</cStat><xMotivo>Rejeicao: Falha no esquema XML</xMotivo><cUF>31</cUF><dhRecbto>2023-07-05T13:30:52-03:00</dhRecbto><dhRetorno>2023-07-05T13:30:52-03:00</dhRetorno></retConsStatServ>`

Alguém saberia me informar qual a versão SOAP utilizada atualmente? Se já é utilizada, a partir de qual release deste repositório começou tal utilização?

**Comment by jrkaibro** [comment]
Dá uma validada no xsd do consultar status veja se está diferente do xsd
utilizado hoje com o que o endpoint de Minas envia.


Em qua., 5 de jul. de 2023 às 13:49, matheuscardosocontrolenamao <
***@***.***> escreveu:

**Comment by matheuscardosocontrolenamao** [comment]
Seria este xsd "leiauteConsStatServ_v3.10.xsd"?

**Comment by jrkaibro** [comment]
Não é 4.00 agora veja a estrutura do xml que o endpoint devolve eles estão
em manutenção. Testei aqui é único método que está diferente o resto
funciona normal até o momento. Mais tarde válido tbm a estrutura

Em qua., 5 de jul. de 2023 às 14:37, matheuscardosocontrolenamao <
***@***.***> escreveu:

**Comment by matheuscardosocontrolenamao** [comment]
Quando tento consultar o status é retornado este XML:

`<retConsStatServ xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00"><tpAmb>1</tpAmb><verAplic>W-3.0.70</verAplic><cStat>215</cStat><xMotivo>Rejeicao: Falha no esquema XML</xMotivo><cUF>31</cUF><dhRecbto>2023-07-05T13:30:52-03:00</dhRecbto><dhRetorno>2023-07-05T13:30:52-03:00</dhRetorno></retConsStatServ>`

**Comment by jrkaibro** [comment]
Válida pelo navegador o retorno agora se está igual.

Em qua., 5 de jul. de 2023 às 14:41, matheuscardosocontrolenamao <
***@***.***> escreveu:

**Comment by matheuscardosocontrolenamao** [comment]
Pelo o que eu vi sim, mas ainda ocorre a Falha no esquema XML
