### ISSUE TITLE
Atualização axis2 de 1.6.4 para 1.7.9

### ISSUE THREAD

**Issue by rafaelstelles** [wmixvideo/nfe#922]
Eu fiz a atualização dessa biblioteca para a versão mencionada, e fiz os testes em meu projeto e funcionou perfeitamente. 

Será que tem mais pessoas que poderia nos ajudar nessa atualização testando em seus projeto ? Eu queria ver se tem mais pessoas que poderiam ajudar nos testes antes de abrir o PR.

https://github.com/rafaelstelles/nfe

**Comment by fincatto** [comment]
Bom dia Rafael.
Essa atualização será ótima mesmo! 
Eu já pensei varias vezes em até matar essa lib de vez (fazer as chamadas diretamente). Cada camada que se tira, é um ganho que se tem. 
Vou tentar testar aqui também!
Abs

**Comment by rafaelstelles** [comment]
@fincatto Um outro ponto, eu fui migrar para a última versão (1.8.x), e alguns arquivos gerados quebraram, pois alguns arquivos foram removidos. Você tem o histórico de como foi gerado essas classes ?

**Comment by fincatto** [comment]
@rafaelstelles coloquei na epoca o passo a passo no diretorio docs na raiz do projeto.
Faz um tempinho, e o axis costuma quebrar com frequencia, então não tenho muito esperança de que os passos funcionarão para as novas versões, mas vale a pena dar uma espiada.

**Comment by mauriciodantas** [comment]
@rafaelstelles fizemos alguns testes internos utilizando a versão do seu projeto. Nossa comunicação funcionou normalmente.  Pode seguir com abertura do PR

**Comment by rafaelstelles** [comment]
Segue o PR

https://github.com/wmixvideo/nfe/pull/923

**Comment by fincatto** [comment]
Feito o merge. Vou deixar a issue aberta por mais uns dias para caso alguem tenha um problema relatar aqui.
