### ISSUE TITLE
Emissão de NFC-e com Certificado A3

### ISSUE THREAD

**Issue by Vitor-Antunes** [wmixvideo/nfe#943]
Gostaria de confirmar se a única maneira de emissão da NFC-e com o certificado A3, é assinar o XML com uma aplicação Desktop utilizando o A3, e depois realizar a transmissão com um certificado A1, ou se há alguma outra maneira de utilizar o certificado A3 sem a utilização do certificado A1?

**Comment by jrkaibro** [comment]
é não eu utilizo na web, desktop e mobile.

Em ter., 2 de jan. de 2024 às 16:18, Vitor Antunes Sarmento <
***@***.***> escreveu:

**Comment by jrkaibro** [comment]
Respondendo sua pergunta funciona nos ambientes


Em ter., 2 de jan. de 2024 às 16:23, Junior Kaibro ***@***.***>
escreveu:

**Comment by Vitor-Antunes** [comment]
Então não preciso do A1 pra nada, somente com o certificado A3 consigo realizar todo o processo, desde a assinatura do XML até a transmissão para SEFAZ?

**Comment by jrkaibro** [comment]
Sim! Sendo um certificado valido

**Comment by Vitor-Antunes** [comment]
Obrigado, sabe me dizer se existe alguma documentação com as orientações de como utilizar o A3?
