### ISSUE TITLE
Alterações para NT 2023.004 e 2019.001 

### ISSUE THREAD

**Issue by Ommegadata** [wmixvideo/nfe#953]
Tendo em vista que as NT 2023.004 e 2019.001 tem data de Homologação em 11/03/2024 e Produção 01/04/2024
o layout foi disponibilizado em 06/02/2024 pela SEFAZ  em Schemas da [NT 2023.004 v1.01 e NT 2019.001 v1.60](https://dfe-portal.svrs.rs.gov.br/Nfe/Documentos).

Onde haverá mudanças nos grupos de ICMS com a mais campos de Beneficio Fiscal, Desoneração e Grupo de Pagamentos.

Alguém já começou a implementar essas alterações do layout?

**Comment by fincatto** [comment]
Ainda não. Consegue implementar e mandar um PR?
