### ISSUE TITLE
Valor "perdido"no xml do protocolo de entrega

### ISSUE THREAD

**Issue by marcondesmacaneiro** [wmixvideo/nfe#954]
Recebemos a assinatura de uma NFe e o protocolo de entrega foi gerado com um valor perdido no xml, sem estar dentro de tag inclusive.....

![CleanShot 2024-03-11 at 16 00 32@2x](https://github.com/wmixvideo/nfe/assets/113733/1c6b60c4-c54f-4618-888f-b1c106632e20)

**Comment by fincatto** [comment]
Boa tarde @marcondesmacaneiro.
Esse valor foi gerado pela lib? Se sim, consegue gerar um codigo demonstrando como reproduzir o problema?

**Comment by marcondesmacaneiro** [comment]
Sim, foi gerado pela lib, mas eu ainda não consegui identificar de onde vem o valor. Mas a NFe foi autorizada.

**Comment by marcondesmacaneiro** [comment]
vou deixar fechado para verificar mais.
