### ISSUE TITLE
Correção na geração do XML da NFNotaInfoItem conforme NT 2021.004 v1.32

### ISSUE THREAD

**Issue by ViniciusG1403** [wmixvideo/nfe#959]
Identifiquei uma inconformidade na implementação da classe NFNotaInfoItem com a [NT 2021.004 v1.32](https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=JeLYMujeNcU=) onde o arquivo XML deveria estar sendo gerado desta maneira:

               <imposto>
			<obsItem>
				<obsFisco xCampo="cBenef">
					<xTexto>PR830001</xTexto>
				</obsFisco>
			</obsItem>
               </imposto>

Porém, esta gerando dessa forma:

               <imposto>
			<obsFisco xCampo="cBenef">
				<xTexto>PR830001</xTexto>
			</obsFisco>
               </imposto>

Visando corrigir o problema, criei o [Pull Request 958](https://github.com/wmixvideo/nfe/pull/958) corrigindo a implementação da classe.

**Comment by fincatto** [comment]
Bom dia @ViniciusG1403.
Obrigado pela correção. O PR já foi mesclado!
Um ótimo final de semana pra ti!
