### ISSUE TITLE
Desativação do Serviço Assíncrono do MDFe

### ISSUE THREAD

**Issue by edivaldoms** [wmixvideo/nfe#961]
Conforme Aviso de Desativação do Serviço Assíncrono do MDFe https://dfe-portal.svrs.rs.gov.br/Mdfe/Avisos/2926
Serviços Assincronos serão desativados na data de 30 de Junho de 2024 conforme versa a NT 2024.001.
Essa desativação não será prorrogada, alertamos que todos migrem para o serviço de recepção síncrono do MDFe (MDFeRecepcaoSinc).

Iniciel o desenvolvimento do processo síncrono, no entanto no site do projeto não é possivel fazer o download dos Schemas nem das Notas Técnicas. Os Link não apontam para os destino, pois tem apenas ancoras (#) nos links.

https://dfe-portal.svrs.rs.gov.br/Mdfe/Documentos

Tentei falar com suporte, mas a página de  contato também não funciona.
https://atendimento.receita.rs.gov.br/faleconosco

Pesquisei na Internet e nao encontrei a NT 2024.001 nem os Schemas.

Alguém teria ou sabe onde encontrar?

**Comment by edivaldoms** [comment]
Entrei em contato com o fale conosco da Sefaz de MS e me enviaram as notas técnicas e schemas XMLs.

**Comment by rafaelstelles** [comment]
@edivaldoms vc conseguiu todos os xmls ? Eu começei a fazer [essa](https://github.com/wmixvideo/nfe/issues/929) migração, porém eu não concluí porque eu não achei todos os arquivos.

Você topa ajudar nessa migração também ?

**Comment by edivaldoms** [comment]
Seguem os LINKS que a equipe de desenvolvimento MDF-E/MS me enviou após
consulta no http://www.faleconosco.ms.gov.br/faleconosco/

MOC MDF-e Visão Geral v3.00b
https://www.mdfe.ms.gov.br/wp-content/uploads/2024/05/MOC_MDFe_VisaoGeral_v3.00b.pdf

MOC MDF-e Anexo II – DAMDFE v3.00b
https://www.mdfe.ms.gov.br/wp-content/uploads/2024/05/MOC_MDFe_Anexo-II_DAMDFE_v3.00b.pdf


MOC MDF=e Anexo I - Leiaute e Regras Validação
https://www.mdfe.ms.gov.br/wp-content/uploads/2024/05/MOC_MDFe_Anexo-I_Leiaute-e-Regras-Validacao_v3.00b.pdf


Schemas MOC MDF-e v 3.00b

https://www.mdfe.ms.gov.br/wp-content/uploads/2024/05/PL_MDFe_300b.zip


MDF-e Nota Técnica 2024.001 v1.02

https://www.mdfe.ms.gov.br/wp-content/uploads/2024/05/MDFe_Nota_Tecnica_2024_001_v1.02-1.pdf

Schemas NT 2024.001 v1.02
https://www.mdfe.ms.gov.br/wp-content/uploads/2024/05/PL_MDFe_300b_NT012024_v1.02.zip


MDF-e Nota Técnica 2024.002
https://www.mdfe.ms.gov.br/wp-content/uploads/2024/05/MDFe_Nota_Tecnica_2024_002_CTeSimplificado_v1.00-1.pdf


Schemas Nota Técnica 2024.002

https://www.mdfe.ms.gov.br/wp-content/uploads/2024/05/PL_MDFe_300b_NT022024-4.zip


Em sáb., 1 de jun. de 2024, 09:15, Rafael Sanches Telles <
***@***.***> escreveu:

**Comment by edivaldoms** [comment]
Esqueci de avisar, já desenvolvi o método síncrono e enviei PR e aguardando
aprovação https://github.com/edivaldoms/nfe

Em sáb., 1 de jun. de 2024, 09:15, Rafael Sanches Telles <
***@***.***> escreveu:
