### ISSUE TITLE
Importar no Android Studio

### ISSUE THREAD

**Issue by arthur1901** [wmixvideo/nfe#98]
Estou iniciando projeto de NFC-e e tentei importar essa biblioteca para o android studio porem não obtive exito, como poderei realizar essa importação?

**Comment by fincatto** [comment]
Bom dia Arthur.
No Readme do projeto existem as instruções. De uma lida antes de iniciar a implementação.
Basicamente você deve adicionar sua dependencia via maven ou gradle e iniciar o uso.
Mais informações na página do mavencentral: http://search.maven.org/#artifactdetails%7Ccom.github.wmixvideo%7Cnfe%7C1.0.23%7C

**Comment by arthur1901** [comment]
Bom dia fincatto,
Seguindo seu tutorial, eu adicionei a dependencia via gradle, porem esta me retornando este erro.
Error:Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: org/apache/axis2/transport/http/ApplicationXMLFormatter.class

Poderia me ajudar?

**Comment by fincatto** [comment]
Não conheço este erro, então não posso te ajudar.
Sugiro que você poste esta solicitação lá no forum para que mais pessoas
possam se habilitar em ajudar com seu problema.
Att,
Diego
