### ISSUE TITLE
Erro no ConsultaCadastro

### ISSUE THREAD

**Issue by dcassiano** [wmixvideo/nfe#99]
Anteriormente ao chamar o ConsultaCadastro da forma abaixo funcionava corretamente:
NFRetornoConsultaCadastro cadastro = new WSFacade(config).consultaCadastro(cnpj, uf);

Após o commit https://github.com/wmixvideo/nfe/commit/e3b8a34bd26bb4ac9b2d0305135267f4e69bb29f onde foi alterado o elemento IE para = true, comecei a receber o seguinte erro:

Value for @org.simpleframework.xml.Element(data=false, required=true, type=void, name=IE) on field 'inscricaoEstadual' private java.lang.String com.fincatto.nfe310.classes.cadastro.NFInfoConsultaCadastro.inscricaoEstadual is None in class com.fincatto.nfe310.classes.cadastro.NFInfoConsultaCadastro

Para testar alterei os métodos necessários passando a receber a IE e passando no consultaCadastro porém recebia um erro de XML mal formado.

Voltei para required=false e funcionou corretamente.

Podem verificar por favor?

Obrigado

**Comment by higomatos** [comment]
Identifiquei o mesmo problema.

**Comment by fincatto** [comment]
Resolvido. Versão: 1.1.5-SNAPSHOT
