### ISSUE TITLE
Conflito de dependências causando erro em runtime

### ISSUE THREAD

**Issue by jpwerka** [wmixvideo/nfe#999]
Bom dia. Estamos utilizando a biblioteca em um projeto nosso e estamos tendo erros ao importar um XML em função de não encontrar um método:
![image](https://github.com/user-attachments/assets/aea0c117-2440-4e0d-abc7-75999f9bd3c8)
Analisando a arvore de dependências chegamos na seguinte análise de conflito:
![image](https://github.com/user-attachments/assets/f1ef2cbd-2331-496e-9f94-3f82fb711df5)

Após fazer a atualização da LIB *axis2-** (forçando meu pom.xml) para a ultima versão liberada 
`<axis2.version>1.8.2</axis2.version>`

Passou a funcionar corretamente a importação de XML.

É possível avaliar o impacto para fazer o UPGRADE de versão das libs do *axis2* no seu projeto por padrão?

Atenciosamente
Jackson Patrick Werka

**Comment by fincatto** [comment]
Oi, boa tarde. Sim, podemos fazer. Manda o PR que avaliamos aqui.
